@ HumilauCity do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_HumilauCity_MapScripts::
	.byte 0

Unova_HumilauCity_EventScript_Placa0::
	msgbox Unova_HumilauCity_Text_HumilauCitySignText, MSGBOX_SIGN
	end

Unova_HumilauCity_EventScript_Placa1::
	msgbox Unova_HumilauCity_Text_HumilauMarlonSignText, MSGBOX_SIGN
	end

Unova_HumilauCity_EventScript_Placa2::
	msgbox Unova_HumilauCity_Text_HumilauMarineTubeSignText, MSGBOX_SIGN
	end

Unova_HumilauCity_EventScript_Npc0::
	msgbox Unova_HumilauCity_Text_HumilauCityCooltrainerFText, MSGBOX_NPC
	end

Unova_HumilauCity_EventScript_Npc1::
	msgbox Unova_HumilauCity_Text_HumilauCityCooltrainerMText, MSGBOX_NPC
	end

Unova_HumilauCity_EventScript_Npc2::
	msgbox Unova_HumilauCity_Text_HumilauCityFisherText, MSGBOX_NPC
	end

Unova_HumilauCity_EventScript_Npc3::
	msgbox Unova_HumilauCity_Text_HumilauCityLassText, MSGBOX_NPC
	end

Unova_HumilauCity_EventScript_Npc4::
	msgbox Unova_HumilauCity_Text_HumilauCityYoungsterText, MSGBOX_NPC
	end

Unova_HumilauCity_EventScript_Npc5::
	msgbox Unova_HumilauCity_Text_HumilauCityTeacherText, MSGBOX_NPC
	end

Unova_HumilauCity_EventScript_Npc6::
	msgbox Unova_HumilauCity_Text_NeighborText_Dangerous, MSGBOX_NPC
	end

Unova_HumilauCity_EventScript_Npc7::
	msgbox Unova_HumilauCity_Text_HumilauCityTubeBlockerText, MSGBOX_NPC
	end

Unova_HumilauCity_EventScript_Npc8::
	msgbox Unova_HumilauCity_Text_HumilauCityRoamingBlockerText, MSGBOX_NPC
	end

Unova_HumilauCity_EventScript_Npc9::
	msgbox Unova_HumilauCity_Text_HumilauCityGymBlockerText, MSGBOX_NPC
	end

Unova_HumilauCity_EventScript_Npc10::
	msgbox Unova_HumilauCity_Text_HumilauCityPCBlockerText, MSGBOX_NPC
	end


Unova_HumilauCity_Text_HumilauCitySignText::
	.string "HUMILAU CITY"
	.string "\pA resort with"
	.string "\ncalm and"
	.string "\lsparkling seas!$"

Unova_HumilauCity_Text_HumilauMarlonSignText::
	.string "MARLON's house.$"

Unova_HumilauCity_Text_HumilauMarineTubeSignText::
	.string "MARINE TUBE"
	.string "\pUndersea passage"
	.string "\nto UNDELLA TOWN.$"

Unova_HumilauCity_Text_HumilauCityCooltrainerFText::
	.string "Wow, the ocean"
	.string "\nview is so"
	.string "\lbeautiful!$"

Unova_HumilauCity_Text_HumilauCityCooltrainerMText::
	.string "I took my girl-"
	.string "\nfriend on vacation"
	.string "\lhere."
	.string "\pIt sure must be"
	.string "\nnice living out"
	.string "\lhere!$"

Unova_HumilauCity_Text_HumilauCityFisherText::
	.string "Technology is"
	.string "\nincredible!"
	.string "\pPeople can now"
	.string "\nmodify games and"
	.string "\pshare them on"
	.string "\nthe internet!$"

Unova_HumilauCity_Text_HumilauCityLassText::
	.string "Isn't it peaceful"
	.string "\nliving out here"
	.string "\lon the waves?$"

Unova_HumilauCity_Text_HumilauCityYoungsterText::
	.string "I want to go play"
	.string "\nin the grass, but"
	.string "\pmy mom says it's"
	.string "\ndangerous."
	.string "\pI sure wish I had"
	.string "\na POKéMON to take"
	.string "\lwith me!$"

Unova_HumilauCity_Text_HumilauCityTeacherText::
	.string "Hi, {PLAYER}."
	.string "\pIf you're planning"
	.string "\non leaving town,"
	.string "\pIt's a good idea"
	.string "\nto stop by the"
	.string "\lPOKé MART."
	.string "\pThey have all"
	.string "\nkinds of things"
	.string "\pthat will help"
	.string "\nyou out!$"

Unova_HumilauCity_Text_NeighborText_Dangerous::
	.string "Oh, hi, {PLAYER}."
	.string "\pThis is the way"
	.string "\nto ROUTE 22."
	.string "\pYou'd better not"
	.string "\nkeep going."
	.string "\pIt's dangerous"
	.string "\noutside of town."
	.string "\pYou could get"
	.string "\nattacked by a"
	.string "\lwild POKéMON!$"

Unova_HumilauCity_Text_HumilauCityTubeBlockerText::
	.string "I was trying to"
	.string "\nget into the"
	.string "\pMARINE TUBE to"
	.string "\nreach UNDELLA"
	.string "\lTOWN…"
	.string "\pBut it's crowded"
	.string "\nwith tourists!$"

Unova_HumilauCity_Text_HumilauCityRoamingBlockerText::
	.string "Whew! The tourists"
	.string "\nhave finally gone"
	.string "\lhome…$"

Unova_HumilauCity_Text_HumilauCityGymBlockerText::
	.string "It looks like the"
	.string "\nGYM LEADER is"
	.string "\laway…"
	.string "\pDarn! I wanted to"
	.string "\nchallenge the gym!$"

Unova_HumilauCity_Text_HumilauCityPCBlockerText::
	.string "Hmm…"
	.string "\pWhich POKéMON"
	.string "\nshould I take"
	.string "\lwith me today…?$"
