EternaCityPokecenter2F_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

EternaCityPokecenter2F_EventScript_Npc1::
	msgbox EternaCityPokecenter2F_Text_Npc1, MSGBOX_NPC
	end

EternaCityPokecenter2F_Text_Npc1:
	.string "Multi Battles are the ultimate in\npulse-pounding action!\pYou won't know how exciting they are\nuntil you've actually experienced one!$"
