Route228SouthHouse_MapScripts::
	.byte 0

Route228SouthHouse_EventScript_Npc1::
	msgbox Route228SouthHouse_Text_Npc1, MSGBOX_NPC
	end

Route228SouthHouse_Text_Npc1:
	.string "That Badge...\nIt's from Sunyshore's Gym?\pYou've been to that port town, then...\pWould... Would you lend an ear to this\nold man's tale?$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

Route228SouthHouse_EventScript_Placa1::
	msgbox Route228SouthHouse_Text_Placa1, MSGBOX_SIGN
	end

Route228SouthHouse_Text_Placa1:
	.string "There are many old and difficult-looking\nbooks here.\p'Mind and Matter'\n'The Presence of Spirit'...$"

Route228SouthHouse_EventScript_Placa2::
	msgbox Route228SouthHouse_Text_Placa2, MSGBOX_SIGN
	end

Route228SouthHouse_Text_Placa2:
	.string "There are many old and difficult-looking\nbooks here.\p'Machines and Their Construction'\n'The Mechanism of Perfection'...$"

Route228SouthHouse_EventScript_Placa3::
	msgbox Route228SouthHouse_Text_Placa3, MSGBOX_SIGN
	end

Route228SouthHouse_Text_Placa3:
	.string "There are many old and difficult-looking\nbooks here.\p'Beyond Time and Space'\n'What Is the Space-Time Continuum?'...$"

Route228SouthHouse_EventScript_Placa4::
	msgbox Route228SouthHouse_Text_Placa4, MSGBOX_SIGN
	end

Route228SouthHouse_Text_Placa4:
	.string "There are many old and difficult-looking\nbooks here.\p'Space and the Galaxies'\n'The Beginning of Space'...$"
