OreburghCity_Flat3_F2_MapScripts::
	.byte 0

OreburghCity_Flat3_F2_EventScript_Worker::
	msgbox OreburghCity_Flat3_F2_Text_Worker, MSGBOX_NPC
	end

OreburghCity_Flat3_F2_EventScript_SchoolKid::
	msgbox OreburghCity_Flat3_F2_Text_SchoolKid, MSGBOX_NPC
	end

OreburghCity_Flat3_F2_EventScript_Lass::
	msgbox OreburghCity_Flat3_F2_Text_Lass, MSGBOX_NPC
	end

OreburghCity_Flat3_F2_Text_Worker:
	.string "Long shift down in the MINE today.\n"
	.string "Nothing beats coming home to rest.$"

OreburghCity_Flat3_F2_Text_SchoolKid:
	.string "I can see the whole town from my\n"
	.string "window up here!$"

OreburghCity_Flat3_F2_Text_Lass:
	.string "A DUSK BALL works best if you use\n"
	.string "it at night or inside a cave.$"
