EternaCityCondominiums3F_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

EternaCityCondominiums3F_EventScript_Npc1::
	msgbox EternaCityCondominiums3F_Text_Npc1, MSGBOX_NPC
	end

EternaCityCondominiums3F_Text_Npc1:
	.string "Badges from Gyms, or Contest wins...\nThere's more than just one way to\pbe a winner, it seems.\nHere's hoping you'll find something\pin which you can be the victor.$"

EternaCityCondominiums3F_EventScript_Npc2::
	msgbox EternaCityCondominiums3F_Text_Npc2, MSGBOX_NPC
	end

EternaCityCondominiums3F_Text_Npc2:
	.string "Hahaha! I've got you now!\nI'm gonna take your Flag!$"

EternaCityCondominiums3F_EventScript_Npc3::
	msgbox EternaCityCondominiums3F_Text_Npc3, MSGBOX_NPC
	end

EternaCityCondominiums3F_Text_Npc3:
	.string "I gathered up a lot of Berries, so\nI'm trading them in for Accessories.\pNext stop, Hearthome City!\nI'm taking the Contest challenge!$"

EternaCityCondominiums3F_EventScript_Npc4::
	msgbox EternaCityCondominiums3F_Text_Npc4, MSGBOX_NPC
	end

EternaCityCondominiums3F_Text_Npc4:
	.string "You can't catch me!\nI set some Traps!$"
