JubilifeCity_PoketchCompany_F3_MapScripts::
	.byte 0

JubilifeCity_PoketchCompany_F3_EventScript_AppSign1::
	msgbox JubilifeCity_PoketchCompany_F3_Text_AppSign, MSGBOX_SIGN
	end

JubilifeCity_PoketchCompany_F3_EventScript_AppSign2::
	msgbox JubilifeCity_PoketchCompany_F3_Text_AppSign, MSGBOX_SIGN
	end

JubilifeCity_PoketchCompany_F3_EventScript_AppSign3::
	msgbox JubilifeCity_PoketchCompany_F3_Text_AppSign, MSGBOX_SIGN
	end

JubilifeCity_PoketchCompany_F3_EventScript_AppSign4::
	msgbox JubilifeCity_PoketchCompany_F3_Text_AppSign, MSGBOX_SIGN
	end

JubilifeCity_PoketchCompany_F3_Text_AppSign:
	.string "There are descriptions of\n"
	.string "Pokétch apps.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

JubilifeCity_PoketchCompany_F3_EventScript_Npc1::
	msgbox JubilifeCity_PoketchCompany_F3_Text_Npc1, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F3_Text_Npc1:
	.string "Do you have a Pokétch?\pThere's a girl's model and a boy's\nmodel, each in different colors.$"

JubilifeCity_PoketchCompany_F3_EventScript_Npc2::
	msgbox JubilifeCity_PoketchCompany_F3_Text_Npc2, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F3_Text_Npc2:
	.string "My husband's the president.\pWe started out in a small workshop\nwhere he made what he liked.\pNow we're making something that makes\nthe world happy. Imagine that!$"

JubilifeCity_PoketchCompany_F3_EventScript_Npc3::
	msgbox JubilifeCity_PoketchCompany_F3_Text_Npc3, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F3_Text_Npc3:
	.string "People everywhere make Pokétch apps.\pYou'll be able to get new apps from\nsurprising sources.\pThe PCs here have guides on the\nvarious Pokétch apps.$"

JubilifeCity_PoketchCompany_F3_EventScript_Placa4::
	msgbox JubilifeCity_PoketchCompany_F3_Text_Placa4, MSGBOX_SIGN
	end

JubilifeCity_PoketchCompany_F3_Text_Placa4:
	.string "There are descriptions of Pokétch\napps.$"

JubilifeCity_PoketchCompany_F3_EventScript_Placa5::
	msgbox JubilifeCity_PoketchCompany_F3_Text_Placa5, MSGBOX_SIGN
	end

JubilifeCity_PoketchCompany_F3_Text_Placa5:
	.string "There are descriptions of Pokétch\napps.$"

JubilifeCity_PoketchCompany_F3_EventScript_Placa6::
	msgbox JubilifeCity_PoketchCompany_F3_Text_Placa6, MSGBOX_SIGN
	end

JubilifeCity_PoketchCompany_F3_Text_Placa6:
	.string "There are descriptions of Pokétch\napps.$"

JubilifeCity_PoketchCompany_F3_EventScript_Placa7::
	msgbox JubilifeCity_PoketchCompany_F3_Text_Placa7, MSGBOX_SIGN
	end

JubilifeCity_PoketchCompany_F3_Text_Placa7:
	.string "There are descriptions of Pokétch\napps.$"
