JubilifeCity_PoketchCompany_F3_MapScripts::
	.byte 0

JubilifeCity_PoketchCompany_F3_EventScript_NinjaBoy::
	msgbox JubilifeCity_PoketchCompany_F3_Text_NinjaBoy, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F3_EventScript_PokefanF::
	msgbox JubilifeCity_PoketchCompany_F3_Text_PokefanF, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F3_EventScript_ExpertF::
	msgbox JubilifeCity_PoketchCompany_F3_Text_ExpertF, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F3_EventScript_AppSign1::
	msgbox JubilifeCity_PoketchCompany_F3_Text_AppSign, MSGBOX_SIGN
	end

JubilifeCity_PoketchCompany_F3_EventScript_AppSign2::
	msgbox JubilifeCity_PoketchCompany_F3_Text_AppSign, MSGBOX_SIGN
	end

JubilifeCity_PoketchCompany_F3_EventScript_AppSign3::
	msgbox JubilifeCity_PoketchCompany_F3_Text_AppSign, MSGBOX_SIGN
	end

JubilifeCity_PoketchCompany_F3_EventScript_AppSign4::
	msgbox JubilifeCity_PoketchCompany_F3_Text_AppSign, MSGBOX_SIGN
	end

JubilifeCity_PoketchCompany_F3_Text_NinjaBoy:
	.string "I'm testing how fast I can cross\n"
	.string "this floor.\p"
	.string "Don't mind me!$"

JubilifeCity_PoketchCompany_F3_Text_PokefanF:
	.string "These displays explain every\n"
	.string "Pokétch app ever made.\p"
	.string "I could read them all day.$"

JubilifeCity_PoketchCompany_F3_Text_ExpertF:
	.string "I used to work on the Pokétch\n"
	.string "prototypes.\p"
	.string "Best job I ever had.$"

JubilifeCity_PoketchCompany_F3_Text_AppSign:
	.string "There are descriptions of\n"
	.string "Pokétch apps.$"
