@ LentimasCoinHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_LentimasCoinHouse_MapScripts::
	.byte 0

Unova_LentimasCoinHouse_EventScript_Npc0::
	msgbox Unova_LentimasCoinHouse_Text_LentimasCoinHouseAskText, MSGBOX_NPC
	end


Unova_LentimasCoinHouse_Text_LentimasCoinHouseAskText::
	.string "Please, young"
	.string "\ntrainer, could you"
	.string "\pspare ¥1000 for an"
	.string "\nold man?$"
