@ Rt18 do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt18_MapScripts::
	.byte 0

Unova_Rt18_EventScript_Npc6::
	msgbox Unova_Rt18_Text_HikerR18SeenText, MSGBOX_NPC
	end

Unova_Rt18_EventScript_Npc7::
	msgbox Unova_Rt18_Text_BlackbeltR18SeenText, MSGBOX_NPC
	end

Unova_Rt18_EventScript_Npc8::
	msgbox Unova_Rt18_Text_BattleGirlR18SeenText, MSGBOX_NPC
	end

Unova_Rt18_EventScript_Npc9::
	msgbox Unova_Rt18_Text_BackpackerMR18SeenText, MSGBOX_NPC
	end

Unova_Rt18_EventScript_Npc10::
	msgbox Unova_Rt18_Text_BackpackerFR18SeenText, MSGBOX_NPC
	end


Unova_Rt18_Text_HikerR18SeenText::
	.string "When I look down"
	.string "\nfrom a high place,"
	.string "\lI feel very good!"
	.string "\pPOKéMON battles"
	.string "\nare the same!$"

Unova_Rt18_Text_BlackbeltR18SeenText::
	.string "I just won a"
	.string "\nbattle back there,"
	.string "\pso I'm feeling"
	.string "\ngood!$"

Unova_Rt18_Text_BattleGirlR18SeenText::
	.string "Number! Eight!"
	.string "\nTeen!$"

Unova_Rt18_Text_BackpackerMR18SeenText::
	.string "BACKPACKERs are"
	.string "\nexactly what they"
	.string "\lsound like."
	.string "\pThey set out on"
	.string "\nthe road with only"
	.string "\pthe packs on their"
	.string "\nbacks and the"
	.string "\pPOKéMON in their"
	.string "\nPOKéBALLs!$"

Unova_Rt18_Text_BackpackerFR18SeenText::
	.string "Your POKéMON and"
	.string "\nyour strategy!"
	.string "\pI'll be taking"
	.string "\nnotes on both!$"
