SandgemTown_RivalHouse_F1_MapScripts::
	.byte 0

SandgemTown_RivalHouse_F1_EventScript_Expert::
	msgbox SandgemTown_RivalHouse_F1_Text_Expert, MSGBOX_NPC
	end

SandgemTown_RivalHouse_F1_EventScript_Twin::
	msgbox SandgemTown_RivalHouse_F1_Text_Twin, MSGBOX_NPC
	end

SandgemTown_RivalHouse_F1_Text_Expert:
	.string "Ah, so that ROWAN fellow is back?\n"
	.string "He's quite the remarkable man.\p"
	.string "He's been studying POKéMON since\n"
	.string "way, way back.$"

SandgemTown_RivalHouse_F1_Text_Twin:
	.string "Oh, hi! There was news on TV saying\n"
	.string "there's a massive outbreak of\l"
	.string "POKéMON! That'd be great for filling\n"
	.string "up your POKéDEX!$"
