@ FoothillTown_PokemonCenter_2F: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 17.2) por dev_scripts/copia_planta_ex.py.

FoothillTown_PokemonCenter_2F_MapScripts::
	map_script MAP_SCRIPT_ON_FRAME_TABLE, CableClub_OnFrame
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, CableClub_OnWarp
	map_script MAP_SCRIPT_ON_LOAD, CableClub_OnLoad
	map_script MAP_SCRIPT_ON_TRANSITION, CableClub_OnTransition
	.byte 0
