@ RelicCastleB1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_RelicCastleB1F_MapScripts::
	.byte 0

Unova_RelicCastleB1F_EventScript_Npc1::
	msgbox Unova_RelicCastleB1F_Text_PsychicFRelicCastleB1FSeenText, MSGBOX_NPC
	end


Unova_RelicCastleB1F_Text_PsychicFRelicCastleB1FSeenText::
	.string "My psychic type"
	.string "\nPOKéMON just"
	.string "\pstarted making"
	.string "\nnoises. Is that"
	.string "\pbecause we're in"
	.string "\nthe ruins… or is"
	.string "\lit because of you?$"
