@ MembersRoom do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_MembersRoom_MapScripts::
	.byte 0

Unova_MembersRoom_EventScript_Placa0::
	msgbox Unova_MembersRoom_Text_MembersRoomVendingText, MSGBOX_SIGN
	end

Unova_MembersRoom_EventScript_Placa1::
	msgbox Unova_MembersRoom_Text_MembersRoomVendingText, MSGBOX_SIGN
	end

Unova_MembersRoom_EventScript_Npc2::
	msgbox Unova_MembersRoom_Text_MembersRoomCherenText, MSGBOX_NPC
	end

Unova_MembersRoom_EventScript_Npc3::
	msgbox Unova_MembersRoom_Text_MembersRoomMarlonText, MSGBOX_NPC
	end

Unova_MembersRoom_EventScript_Npc4::
	msgbox Unova_MembersRoom_Text_MembersRoomRoodInitialText, MSGBOX_NPC
	end

Unova_MembersRoom_EventScript_Npc5::
	msgbox Unova_MembersRoom_Text_MembersRoomAlderInitialText, MSGBOX_NPC
	end

Unova_MembersRoom_EventScript_Npc6::
	msgbox Unova_MembersRoom_Text_MembersRoomIrisText, MSGBOX_NPC
	end

Unova_MembersRoom_EventScript_Npc7::
	msgbox Unova_MembersRoom_Text_MembersRoomCaitlinText, MSGBOX_NPC
	end

Unova_MembersRoom_EventScript_Npc8::
	msgbox Unova_MembersRoom_Text_MembersRoomCynthiaText, MSGBOX_NPC
	end

Unova_MembersRoom_EventScript_Npc9::
	msgbox Unova_MembersRoom_Text_MembersRoomHughText, MSGBOX_NPC
	end

Unova_MembersRoom_EventScript_Npc10::
	msgbox Unova_MembersRoom_Text_MembersRoomElesaText, MSGBOX_NPC
	end

Unova_MembersRoom_EventScript_Npc11::
	msgbox Unova_MembersRoom_Text_MembersRoomBiancaText, MSGBOX_NPC
	end


Unova_MembersRoom_Text_MembersRoomVendingText::
	.string "A vending machine!"
	.string "\nHere's the menu.$"

Unova_MembersRoom_Text_MembersRoomCherenText::
	.string "Oh, {PLAYER}!"
	.string "\pI heard about what"
	.string "\nhappened at the"
	.string "\lPOKéMON LEAGUE."
	.string "\pCongratulations on"
	.string "\nbecoming the"
	.string "\lChampion!"
	.string "\pThis area is an"
	.string "\nexclusive spot"
	.string "\pwhere Champions"
	.string "\nand members of the"
	.string "\pPOKéMON LEAGUE"
	.string "\nmeet with each"
	.string "\lother."
	.string "\pHang around, and"
	.string "\nyou may just meet"
	.string "\psome incredible"
	.string "\nPOKéMON trainers!"
	.string "\pBy the way, I"
	.string "\nheard a rumor that"
	.string "\pa strange POKéMON"
	.string "\nwas spotted at a"
	.string "\pcave inside of"
	.string "\nVICTORY ROAD."
	.string "\pPerhaps you may"
	.string "\nwant to check it"
	.string "\lout."
	.string "\pAnyway, I'd better"
	.string "\nget back to my"
	.string "\pGYM. It was nice"
	.string "\nseeing you,"
	.string "\l{PLAYER}.$"

Unova_MembersRoom_Text_MembersRoomMarlonText::
	.string "Yo, {PLAYER},"
	.string "\nhow's it hangin'?"
	.string "\pA trainer like you"
	.string "\nmust always be"
	.string "\pseekin' out a new"
	.string "\nchallenge, huh?"
	.string "\pWell, I heard some"
	.string "\nnews that a"
	.string "\ptotally radical"
	.string "\ntrainer's been"
	.string "\pstayin' in one of"
	.string "\nthe villas over in"
	.string "\lUNDELLA TOWN!"
	.string "\pWho knows? Maybe"
	.string "\nyou're in for a"
	.string "\lrockin' battle!$"

Unova_MembersRoom_Text_MembersRoomRoodInitialText::
	.string "Ah, {PLAYER}!"
	.string "\nIt's me, ROOD, from"
	.string "\pthe shelter in"
	.string "\nDRIFTVEIL CITY."
	.string "\pI want to thank"
	.string "\nyou for your help."
	.string "\pINFER came back"
	.string "\nhome the other"
	.string "\pday. We may not"
	.string "\nhave reconciled"
	.string "\pall of our differ-"
	.string "\nences yet, but at"
	.string "\pleast I know she"
	.string "\nis safe."
	.string "\pFor that, I owe"
	.string "\nyou my deepest"
	.string "\lgratitude."
	.string "\pYou should come by"
	.string "\nthe shelter and"
	.string "\lvisit sometime.$"

Unova_MembersRoom_Text_MembersRoomAlderInitialText::
	.string "Hm? I haven't seen"
	.string "\nyou around here"
	.string "\lbefore."
	.string "\pThe name's ALDER."
	.string "\nI was the Champion"
	.string "\pof the POKéMON"
	.string "\nLEAGUE once,"
	.string "\pthough that was a"
	.string "\nwhile ago now."
	.string "\pI mostly keep to"
	.string "\nmy home in"
	.string "\pFLOCCESY TOWN now,"
	.string "\nand teach the"
	.string "\llocal kids."
	.string "\pYou should come by"
	.string "\nsometime! Maybe I"
	.string "\pcould even teach"
	.string "\nyou something!$"

Unova_MembersRoom_Text_MembersRoomIrisText::
	.string "Hi, {PLAYER}!"
	.string "\pI really want to"
	.string "\nsee how strong you"
	.string "\pare, now that you"
	.string "\nbeat the POKéMON"
	.string "\lLEAGUE!"
	.string "\pI'll be waiting"
	.string "\nfor you at my"
	.string "\phouse in OPELUCID"
	.string "\nCITY, if you want"
	.string "\lto battle!$"

Unova_MembersRoom_Text_MembersRoomCaitlinText::
	.string "Hmf…"
	.string "\pYou've interrupted"
	.string "\nmy nap…"
	.string "\pOh, it's you. That"
	.string "\ntrainer from"
	.string "\lbefore."
	.string "\pYou were a satis-"
	.string "\nfying challenge"
	.string "\pthe last time we"
	.string "\nbattled. If you'd"
	.string "\plike another"
	.string "\nmatch, you can"
	.string "\pfind me at my"
	.string "\nvilla in UNDELLA"
	.string "\lTOWN."
	.string "\pJust don't make it"
	.string "\na bore.$"

Unova_MembersRoom_Text_MembersRoomCynthiaText::
	.string "Oh, {PLAYER}, it's"
	.string "\nyou! I've been"
	.string "\ptraveling UNOVA,"
	.string "\nlooking for strong"
	.string "\pPOKéMON trainers"
	.string "\nto challenge."
	.string "\pHow good to have"
	.string "\nrun into you here!"
	.string "\pIf you'd like to"
	.string "\nchallenge me"
	.string "\pagain, you can"
	.string "\ncome visit me at"
	.string "\pCAITLIN's villa in"
	.string "\nUNDELLA TOWN,"
	.string "\pwhere I've been"
	.string "\nstaying."
	.string "\pI look forward to"
	.string "\nbattling you!$"

Unova_MembersRoom_Text_MembersRoomHughText::
	.string "Hey, {PLAYER}!"
	.string "\pI've been thinking"
	.string "\non what I need to"
	.string "\pbecome stronger,"
	.string "\nand I'm ready to"
	.string "\ptest out what I've"
	.string "\ncome up with. You"
	.string "\pshould come meet"
	.string "\nme at the shelter"
	.string "\pin DRIFTVEIL CITY,"
	.string "\nand I'll show you"
	.string "\lwhat I've learned.$"

Unova_MembersRoom_Text_MembersRoomElesaText::
	.string "Oh, {PLAYER}, is"
	.string "\nit? You're the"
	.string "\pnew champion,"
	.string "\nright?"
	.string "\pI'm ELESA, of the"
	.string "\nELITE FOUR."
	.string "\pListen, I was"
	.string "\npaying a visit to"
	.string "\pmy hometown in"
	.string "\nNIMBASA CITY, when"
	.string "\pI ran into a"
	.string "\ntrainer I remember"
	.string "\pchallenging back"
	.string "\nwhen I was a GYM"
	.string "\lLEADER there."
	.string "\pThey were young,"
	.string "\nbut they certainly"
	.string "\pleft an impression"
	.string "\non me!"
	.string "\pYou may be able to"
	.string "\nfind them hanging"
	.string "\paround at the old"
	.string "\nPARK, where my GYM"
	.string "\lused to be.$"

Unova_MembersRoom_Text_MembersRoomBiancaText::
	.string "Oh, {PLAYER}, it's"
	.string "\ngood to see you!"
	.string "\pYou've certainly"
	.string "\ngotten much"
	.string "\pstronger as a"
	.string "\nPOKéMON trainer"
	.string "\pthan when we first"
	.string "\nmet!"
	.string "\pspeaking of which…"
	.string "\pAn old friend of"
	.string "\nmine stopped by to"
	.string "\lvisit today!"
	.string "\pThey're staying in"
	.string "\nNUVEMA TOWN for a"
	.string "\pwhile, if you want"
	.string "\nto go and say hi!"
	.string "\pTell them the"
	.string "\nPROF. sent you!"
	.string "\lHee hee!$"
