@ CasteliaCitySouth do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_CasteliaCitySouth_MapScripts::
	.byte 0

Unova_CasteliaCitySouth_EventScript_Placa0::
	msgbox Unova_CasteliaCitySouth_Text_CasteliaBattleCompanySignText, MSGBOX_SIGN
	end

Unova_CasteliaCitySouth_EventScript_Placa1::
	msgbox Unova_CasteliaCitySouth_Text_CasteliaBridgeSignText, MSGBOX_SIGN
	end

Unova_CasteliaCitySouth_EventScript_Placa2::
	msgbox Unova_CasteliaCitySouth_Text_CasteliaFerrySignText, MSGBOX_SIGN
	end

Unova_CasteliaCitySouth_EventScript_Placa3::
	msgbox Unova_CasteliaCitySouth_Text_CasteliaPlazaSignText, MSGBOX_SIGN
	end

Unova_CasteliaCitySouth_EventScript_Npc0::
	msgbox Unova_CasteliaCitySouth_Text_CasteliaFerryManClosedText, MSGBOX_NPC
	end

Unova_CasteliaCitySouth_EventScript_Npc3::
	msgbox Unova_CasteliaCitySouth_Text_CasteliaSouthGentlemanText, MSGBOX_NPC
	end

Unova_CasteliaCitySouth_EventScript_Npc4::
	msgbox Unova_CasteliaCitySouth_Text_CasteliaSouthSneaselText, MSGBOX_NPC
	end

Unova_CasteliaCitySouth_EventScript_Npc5::
	msgbox Unova_CasteliaCitySouth_Text_CasteliaSouthSailorText, MSGBOX_NPC
	end

Unova_CasteliaCitySouth_EventScript_Npc6::
	msgbox Unova_CasteliaCitySouth_Text_CasteliaSouthTeacherText, MSGBOX_NPC
	end

Unova_CasteliaCitySouth_EventScript_Npc7::
	msgbox Unova_CasteliaCitySouth_Text_CasteliaSouthSailor2Text, MSGBOX_NPC
	end

Unova_CasteliaCitySouth_EventScript_Npc8::
	msgbox Unova_CasteliaCitySouth_Text_CasteliaSouthSailor3Text, MSGBOX_NPC
	end

Unova_CasteliaCitySouth_EventScript_Npc9::
	msgbox Unova_CasteliaCitySouth_Text_CasteliaSouthMysticWaterGiver_AskScaleText, MSGBOX_NPC
	end


Unova_CasteliaCitySouth_Text_CasteliaBattleCompanySignText::
	.string "BATTLE COMPANY.$"

Unova_CasteliaCitySouth_Text_CasteliaBridgeSignText::
	.string "SKYARROW BRIDGE."
	.string "\pPassage to"
	.string "\nNACRENE CITY.$"

Unova_CasteliaCitySouth_Text_CasteliaFerrySignText::
	.string "FERRY service to"
	.string "\nVIRBANK CITY."
	.string "\pInquire inside.$"

Unova_CasteliaCitySouth_Text_CasteliaPlazaSignText::
	.string "CASTELIA GAME"
	.string "\nPLAZA."
	.string "\pCome play with us!$"

Unova_CasteliaCitySouth_Text_CasteliaFerryManClosedText::
	.string "Ahoy! This be the"
	.string "\nFERRY to VIRBANK"
	.string "\lCITY."
	.string "\pIf ye've got a"
	.string "\nticket, go show it"
	.string "\pto the fellow"
	.string "\ninside!$"

Unova_CasteliaCitySouth_Text_CasteliaSouthGentlemanText::
	.string "This SNEASEL is"
	.string "\nmy partner."
	.string "\pI wonder if it'll"
	.string "\never evolve?"
	.string "\pMaybe if it's"
	.string "\nholding a certain"
	.string "\litem…$"

Unova_CasteliaCitySouth_Text_CasteliaSouthSneaselText::
	.string "SNEASEL: Snaah!$"

Unova_CasteliaCitySouth_Text_CasteliaSouthSailorText::
	.string "The sewers have"
	.string "\nflooded recently."
	.string "\pIt's just as well,"
	.string "\ndangerous POKéMON"
	.string "\lhad begun to come"
	.string "\lout of there.$"

Unova_CasteliaCitySouth_Text_CasteliaSouthTeacherText::
	.string "CASTELIA's GAME"
	.string "\nPLAZA has a great"
	.string "\pselection of"
	.string "\nprizes! I'm just"
	.string "\pno good at the"
	.string "\ngames, so I never"
	.string "\lwin anything…$"

Unova_CasteliaCitySouth_Text_CasteliaSouthSailor2Text::
	.string "Everyone's faces"
	.string "\nblend together!"
	.string "\pIs that because"
	.string "\nI'm tired?$"

Unova_CasteliaCitySouth_Text_CasteliaSouthSailor3Text::
	.string "When you just"
	.string "\ncan't stand it"
	.string "\panymore, try"
	.string "\nshouting at the"
	.string "\lopen ocean!$"

Unova_CasteliaCitySouth_Text_CasteliaSouthMysticWaterGiver_AskScaleText::
	.string "Ahoy there, young-"
	.string "\nun! I've been"
	.string "\plookin' for a"
	.string "\nshiny type of"
	.string "\ptrinket they call"
	.string "\na HEART SCALE."
	.string "\pThey say you can"
	.string "\nfish 'em up, but"
	.string "\pI've been havin'"
	.string "\nno luck!"
	.string "\pYou wouldn't have"
	.string "\none you could"
	.string "\lspare, would ya?$"
