@ FallarborTown_Ex5_11: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 5.11) por dev_scripts/copia_planta_ex.py.

FallarborTown_Ex5_11_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 5.11), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
FallarborTown_Ex5_11_EventScript_ExNpc0::
	msgbox FallarborTown_Ex5_11_Text_ExNpc0, MSGBOX_NPC
	end

FallarborTown_Ex5_11_Text_ExNpc0:
	.string "Why does all the ash fall on this side of\n"
	.string "the mountain?$"

