@ Rt4 do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt4_MapScripts::
	.byte 0

Unova_Rt4_EventScript_Placa0::
	msgbox Unova_Rt4_Text_R4DesertSignText, MSGBOX_SIGN
	end

Unova_Rt4_EventScript_Placa1::
	msgbox Unova_Rt4_Text_R4CasteliaSignText, MSGBOX_SIGN
	end

Unova_Rt4_EventScript_Npc4::
	msgbox Unova_Rt4_Text_RichBoyR4SeenText, MSGBOX_NPC
	end

Unova_Rt4_EventScript_Npc5::
	msgbox Unova_Rt4_Text_RoughneckR4SeenText, MSGBOX_NPC
	end

Unova_Rt4_EventScript_Npc6::
	msgbox Unova_Rt4_Text_Fisher1R4SeenText, MSGBOX_NPC
	end

Unova_Rt4_EventScript_Npc7::
	msgbox Unova_Rt4_Text_Fisher2R4SeenText, MSGBOX_NPC
	end

Unova_Rt4_EventScript_Npc8::
	msgbox Unova_Rt4_Text_LadyR4SeenText, MSGBOX_NPC
	end

Unova_Rt4_EventScript_Npc9::
	msgbox Unova_Rt4_Text_Policeman1R4SeenText, MSGBOX_NPC
	end

Unova_Rt4_EventScript_Npc10::
	msgbox Unova_Rt4_Text_Policeman2R4SeenText, MSGBOX_NPC
	end

Unova_Rt4_EventScript_Npc11::
	msgbox Unova_Rt4_Text_PokefanMR4SeenText, MSGBOX_NPC
	end

Unova_Rt4_EventScript_Npc12::
	msgbox Unova_Rt4_Text_PokefanFR4SeenText, MSGBOX_NPC
	end

Unova_Rt4_EventScript_Npc13::
	msgbox Unova_Rt4_Text_BikerR4SeenText, MSGBOX_NPC
	end


Unova_Rt4_Text_R4DesertSignText::
	.string "DESERT RESORT"
	.string "\nahead.$"

Unova_Rt4_Text_R4CasteliaSignText::
	.string "Access to"
	.string "\nCASTELIA CITY.$"

Unova_Rt4_Text_RichBoyR4SeenText::
	.string "I'll see if you're"
	.string "\nworthy to stand on"
	.string "\pthe same stage as"
	.string "\nme!$"

Unova_Rt4_Text_RoughneckR4SeenText::
	.string "This ain't no"
	.string "\nplace for kids"
	.string "\llike you!$"

Unova_Rt4_Text_Fisher1R4SeenText::
	.string "You've been caught"
	.string "\nby a powerful"
	.string "\lhook, which is me!$"

Unova_Rt4_Text_Fisher2R4SeenText::
	.string "Check out my"
	.string "\nlively POKéMON,"
	.string "\pwhich I've"
	.string "\ngathered from all"
	.string "\laround UNOVA!$"

Unova_Rt4_Text_LadyR4SeenText::
	.string "A stylish POKéMON"
	.string "\nbattle is starting"
	.string "\lnow!$"

Unova_Rt4_Text_Policeman1R4SeenText::
	.string "What's a kid like"
	.string "\nyou doing around"
	.string "\lthese parts?$"

Unova_Rt4_Text_Policeman2R4SeenText::
	.string "Ah, that smell?"
	.string "\pMy POKéMON here"
	.string "\nseems to say that"
	.string "\pyou've got a"
	.string "\ndangerous smell"
	.string "\labout you!$"

Unova_Rt4_Text_PokefanMR4SeenText::
	.string "What? You're a"
	.string "\ntrainer? Awesome!$"

Unova_Rt4_Text_PokefanFR4SeenText::
	.string "Now dance grace-"
	.string "\nfully! Bring forth"
	.string "\pyour beautiful"
	.string "\nmoves! Let us"
	.string "\pperform, my lovely"
	.string "\nPOKéMON!$"

Unova_Rt4_Text_BikerR4SeenText::
	.string "A motorcycle in"
	.string "\nthe desert! It"
	.string "\pdoesn't get much"
	.string "\nmore wild than"
	.string "\lthis, eh?$"
