@ MarshalsRoom do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_MarshalsRoom_MapScripts::
	.byte 0

Unova_MarshalsRoom_EventScript_Lider0::
	trainerbattle_single TRAINER_UNOVA_E4_MARSHAL, Unova_MarshalsRoom_Text_EliteFourMarshalIntroText, Unova_MarshalsRoom_Text_EliteFourMarshalWinText
	end


Unova_MarshalsRoom_Text_EliteFourMarshalIntroText::
	.string "Greetings,"
	.string "\nchallenger. My"
	.string "\lname is MARSHAL."
	.string "\pI am the No. 1"
	.string "\npupil of the great"
	.string "\lALDER."
	.string "\pIn order to master"
	.string "\nthe art of"
	.string "\pfighting, I've"
	.string "\nkept training."
	.string "\pYou're also"
	.string "\nwalking a similar"
	.string "\ppath with your"
	.string "\nPOKéMON. It is my"
	.string "\pintention to test"
	.string "\nyou- to take you"
	.string "\pto the limits of"
	.string "\nyour strength."
	.string "\lKiai!$"

Unova_MarshalsRoom_Text_EliteFourMarshalWinText::
	.string "Whew! Well done!"
	.string "\nAs your battles"
	.string "\pcontinue, aim for"
	.string "\neven greater"
	.string "\lheights!$"
