@ FortreeCity_Ex12_11: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 12.11) por dev_scripts/copia_planta_ex.py.

FortreeCity_Ex12_11_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 12.11), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
FortreeCity_Ex12_11_EventScript_ExNpc0::
	msgbox FortreeCity_Ex12_11_Text_ExNpc0, MSGBOX_NPC
	end

FortreeCity_Ex12_11_Text_ExNpc0:
	.string "Me and my friends are experts in the\n"
	.string "shadows.$"

FortreeCity_Ex12_11_EventScript_ExNpc1::
	msgbox FortreeCity_Ex12_11_Text_ExNpc1, MSGBOX_NPC
	end

FortreeCity_Ex12_11_Text_ExNpc1:
	.string "My boy is in time out for jumping out of\n"
	.string "trees scaring people.\p"
	.string "Please leave him alone.$"

