EternaCityUndergroundManHouse_MapScripts::
	.byte 0

EternaCityUndergroundManHouse_EventScript_Npc1::
	msgbox EternaCityUndergroundManHouse_Text_Npc1, MSGBOX_NPC
	end

EternaCityUndergroundManHouse_Text_Npc1:
	.string "Let's dig up some Treasure!\pI'm from Oreburgh.\nI work at the mining museum there.\pI got advice from the Underground\nMan on digging up Treasure and Spheres.\pBefore I get digging, let me share\nhis advice with you.\pWhile you're digging, you may uncover\ndark rocks.\pThey are very hard! If you keep\nhitting them, the wall will collapse.\pDon't forget that, and you'll be\ndigging up Treasure in no time!$"

EternaCityUndergroundManHouse_EventScript_Npc2::
	msgbox EternaCityUndergroundManHouse_Text_Npc2, MSGBOX_NPC
	end

EternaCityUndergroundManHouse_Text_Npc2:
	.string "I am! I am the first to have gone\nunderground and dug some tunnels.\pYou can call me the Underground Man.\nEveryone else does.\pI'll make a gift of this to you.\nYou hold up your end of the deal\pand put it to good use!$"

EternaCityUndergroundManHouse_EventScript_Placa1::
	msgbox EternaCityUndergroundManHouse_Text_Placa1, MSGBOX_SIGN
	end

EternaCityUndergroundManHouse_Text_Placa1:
	.string "'Shortcut to the Underground' is on\nthe screen.$"
