EternaCityUndergroundManHouse_MapScripts::
	.byte 0

EternaCityUndergroundManHouse_EventScript_Npc1::
	msgbox EternaCityUndergroundManHouse_Text_Npc1, MSGBOX_NPC
	end

EternaCityUndergroundManHouse_Text_Npc1:
	.string "Let's dig up some Treasure!\pI'm from Oreburgh.\nI work at the mining museum there.\pI got advice from the Underground\nMan on digging up Treasure and Spheres.\pBefore I get digging, let me share\nhis advice with you.\pWhile you're digging, you may uncover\ndark rocks.\pThey are very hard! If you keep\nhitting them, the wall will collapse.\pDon't forget that, and you'll be\ndigging up Treasure in no time!$"

EternaCityUndergroundManHouse_EventScript_Npc2::
	msgbox EternaCityUndergroundManHouse_Text_Npc2, MSGBOX_NPC
	end

EternaCityUndergroundManHouse_Text_Npc2:
	.string "I am! I am the first to have gone\nunderground and dug some tunnels.\pYou can call me the Underground Man.\nEveryone else does.\pI'll make a gift of this to you.\nYou hold up your end of the deal\pand put it to good use!$"

EternaCityUndergroundManHouse_EventScript_Placa1::
	msgbox EternaCityUndergroundManHouse_Text_Placa1, MSGBOX_SIGN
	end

EternaCityUndergroundManHouse_Text_Placa1:
	.string "'Shortcut to the Underground' is on\nthe screen.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

EternaCityUndergroundManHouse_EventScript_Npc1::
	msgbox EternaCityUndergroundManHouse_Text_Npc1, MSGBOX_NPC
	end

EternaCityUndergroundManHouse_Text_Npc1:
	.string "The underground tunnels go\neverywhere!\pGrab your friends and let's play\ntogether using DS Wireless\pCommunications!$"

EternaCityUndergroundManHouse_EventScript_Npc2::
	msgbox EternaCityUndergroundManHouse_Text_Npc2, MSGBOX_NPC
	end

EternaCityUndergroundManHouse_Text_Npc2:
	.string "All I ever unearth are Armor Fossils.\nMy buddy only digs up Skull Fossils.\pI wonder why that happens?\pIt doesn't matter though. I can just\nswap them with my buddy.\pI simply let a Pokémon hold an Armor\nFossil and trade it to him.$"

EternaCityUndergroundManHouse_EventScript_Placa3::
	msgbox EternaCityUndergroundManHouse_Text_Placa3, MSGBOX_SIGN
	end

EternaCityUndergroundManHouse_Text_Placa3:
	.string "New and on sale!\nUnderground Radar!\pThe upper radar screen indicates\npossible Treasure locations.\pThe lower Touch Radar indicates\nprecise locations!$"
