@ OpelucidCuriosityShop do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_OpelucidCuriosityShop_MapScripts::
	.byte 0

Unova_OpelucidCuriosityShop_EventScript_Npc0::
	msgbox Unova_OpelucidCuriosityShop_Text_CuriosityShopIntroText, MSGBOX_NPC
	end


Unova_OpelucidCuriosityShop_Text_CuriosityShopIntroText::
	.string "Hey, welcome to"
	.string "\nthe OPELUCID CITY"
	.string "\lCURIOSITY SHOP."
	.string "\pWe got all kinds"
	.string "\nof rare bargains!$"
