@ Rt11OpelucidGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt11OpelucidGate_MapScripts::
	.byte 0

Unova_Rt11OpelucidGate_EventScript_Npc0::
	msgbox Unova_Rt11OpelucidGate_Text_R11OpelucidGateOfficerText, MSGBOX_NPC
	end


Unova_Rt11OpelucidGate_Text_R11OpelucidGateOfficerText::
	.string "Hello, trainer who"
	.string "\nhas come to"
	.string "\lOPELUCID CITY!"
	.string "\pOr, if you're"
	.string "\ngoing to ROUTE 11,"
	.string "\lplease come again!$"
