TwinleafTown_Haouse1_MapScripts::
	.byte 0

TwinleafTown_Haouse1_EventScript_Expert::
	msgbox TwinleafTown_Haouse1_Text_Expert, MSGBOX_NPC
	end

TwinleafTown_Haouse1_EventScript_Twin::
	msgbox TwinleafTown_Haouse1_Text_Twin, MSGBOX_NPC
	end

TwinleafTown_Haouse1_Text_Expert:
	.string "Did you hear? The POKéMON Professor\n"
	.string "returned to the next town over.\p"
	.string "They say he was gone for four long\n"
	.string "years. I wonder what he found?$"

TwinleafTown_Haouse1_Text_Twin:
	.string "Listen, listen! I want a cute\n"
	.string "POKéMON!$"
