JubilifeCity_PoketchCompany_F1_MapScripts::
	.byte 0

JubilifeCity_PoketchCompany_F1_EventScript_Scientist::
	msgbox JubilifeCity_PoketchCompany_F1_Text_Scientist, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F1_EventScript_Receptionist::
	msgbox JubilifeCity_PoketchCompany_F1_Text_Receptionist, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F1_EventScript_Lass::
	msgbox JubilifeCity_PoketchCompany_F1_Text_Lass, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F1_Text_Scientist:
	.string "Every Pokétch app starts as a\n"
	.string "scribble on a napkin.\p"
	.string "This one just needed more\n"
	.string "napkins.$"

JubilifeCity_PoketchCompany_F1_Text_Receptionist:
	.string "Welcome to the Pokétch Company!\n"
	.string "Please wait here if you have an\l"
	.string "appointment.$"

JubilifeCity_PoketchCompany_F1_Text_Lass:
	.string "I come here just to watch the\n"
	.string "machines work.\p"
	.string "It's oddly relaxing.$"
