JubilifeCity_PoketchCompany_F1_MapScripts::
	.byte 0

JubilifeCity_PoketchCompany_F1_EventScript_Scientist::
	msgbox JubilifeCity_PoketchCompany_F1_Text_Scientist, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F1_EventScript_Receptionist::
	msgbox JubilifeCity_PoketchCompany_F1_Text_Receptionist, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F1_EventScript_Lass::
	msgbox JubilifeCity_PoketchCompany_F1_Text_Lass, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F1_Text_Scientist:
	.string "Every Pokétch app starts as a\n"
	.string "scribble on a napkin.\p"
	.string "This one just needed more\n"
	.string "napkins.$"

JubilifeCity_PoketchCompany_F1_Text_Receptionist:
	.string "Welcome to the Pokétch Company!\n"
	.string "Please wait here if you have an\l"
	.string "appointment.$"

JubilifeCity_PoketchCompany_F1_Text_Lass:
	.string "I come here just to watch the\n"
	.string "machines work.\p"
	.string "It's oddly relaxing.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

JubilifeCity_PoketchCompany_F1_EventScript_Npc1::
	msgbox JubilifeCity_PoketchCompany_F1_Text_Npc1, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F1_Text_Npc1:
	.string "Oh, you can be sure I will keep\ndeveloping Pokétch apps.\pJust like Pokémon, my Pokétch is\nsomething that evolves!$"

JubilifeCity_PoketchCompany_F1_EventScript_Npc2::
	msgbox JubilifeCity_PoketchCompany_F1_Text_Npc2, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F1_Text_Npc2:
	.string "Welcome to the Pokétch Company.\pWe're actually a family-run business,\nso we're not very impressive.$"

JubilifeCity_PoketchCompany_F1_EventScript_Npc3::
	msgbox JubilifeCity_PoketchCompany_F1_Text_Npc3, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F1_Text_Npc3:
	.string "Hey, do you watch TV?\n'Pokétch Detective' is a great show.\pSeeing that program compels me to use\nmy Pokétch more!$"
