JubilifeCity_PoketchCompany_F1_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

JubilifeCity_PoketchCompany_F1_EventScript_Npc1::
	msgbox JubilifeCity_PoketchCompany_F1_Text_Npc1, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F1_Text_Npc1:
	.string "Oh, you can be sure I will keep\ndeveloping Pokétch apps.\pJust like Pokémon, my Pokétch is\nsomething that evolves!$"

JubilifeCity_PoketchCompany_F1_EventScript_Npc2::
	msgbox JubilifeCity_PoketchCompany_F1_Text_Npc2, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F1_Text_Npc2:
	.string "Welcome to the Pokétch Company.\pWe're actually a family-run business,\nso we're not very impressive.$"

JubilifeCity_PoketchCompany_F1_EventScript_Npc3::
	msgbox JubilifeCity_PoketchCompany_F1_Text_Npc3, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F1_Text_Npc3:
	.string "Hey, do you watch TV?\n'Pokétch Detective' is a great show.\pSeeing that program compels me to use\nmy Pokétch more!$"
