@ VerdanturfTown_Ex6_11: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 6.11) por dev_scripts/copia_planta_ex.py.

VerdanturfTown_Ex6_11_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 6.11), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
VerdanturfTown_Ex6_11_EventScript_ExNpc0::
	msgbox VerdanturfTown_Ex6_11_Text_ExNpc0, MSGBOX_NPC
	end

VerdanturfTown_Ex6_11_Text_ExNpc0:
	.string "If you go through RUSTURF TUNNEL you\n"
	.string "can reach the FROZEN HEIGHTS.\p"
	.string "It’s the only part of HOENN that gets\n"
	.string "snow year round.$"

VerdanturfTown_Ex6_11_EventScript_ExNpc1::
	msgbox VerdanturfTown_Ex6_11_Text_ExNpc1, MSGBOX_NPC
	end

VerdanturfTown_Ex6_11_Text_ExNpc1:
	.string "They let the grass grow long here.\p"
	.string "It feels great on my toes!$"

