@ CasteliaMassage do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_CasteliaMassage_MapScripts::
	.byte 0

Unova_CasteliaMassage_EventScript_Npc0::
	msgbox Unova_CasteliaMassage_Text_MassageAskText, MSGBOX_NPC
	end


Unova_CasteliaMassage_Text_MassageAskText::
	.string "Welcome to the"
	.string "\nCASTELIA massage"
	.string "\lparlor!"
	.string "\pWe can give one"
	.string "\nof your POKéMON a"
	.string "\lrelaxing massage"
	.string "\lfor just ¥500."
	.string "\pWould you like me"
	.string "\nto do that?$"
