@ PWTBackRoom do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_PWTBackRoom_MapScripts::
	.byte 0

Unova_PWTBackRoom_EventScript_Npc0::
	msgbox Unova_PWTBackRoom_Text_PwtBackRoomClayText, MSGBOX_NPC
	end

Unova_PWTBackRoom_EventScript_Npc1::
	msgbox Unova_PWTBackRoom_Text_PwtBackRoomCherenText, MSGBOX_NPC
	end

Unova_PWTBackRoom_EventScript_Npc3::
	msgbox Unova_PWTBackRoom_Text_PwtBackRoomJuniper1Text, MSGBOX_NPC
	end

Unova_PWTBackRoom_EventScript_Npc4::
	msgbox Unova_PWTBackRoom_Text_PwtBackRoomIrisText, MSGBOX_NPC
	end

Unova_PWTBackRoom_EventScript_Npc6::
	msgbox Unova_PWTBackRoom_Text_PwtBackRoomInferText, MSGBOX_NPC
	end

Unova_PWTBackRoom_EventScript_Npc7::
	msgbox Unova_PWTBackRoom_Text_PwtBackRoomVioText, MSGBOX_NPC
	end


Unova_PWTBackRoom_Text_PwtBackRoomClayText::
	.string "CLAY: Alrighty"
	.string "\nnow, head on back"
	.string "\pfer yer match"
	.string "\nwhen yer ready.$"

Unova_PWTBackRoom_Text_PwtBackRoomCherenText::
	.string "CHEREN: So, you've"
	.string "\ndrawn BIANCA in"
	.string "\lthe first round…"
	.string "\pGood luck, you'll"
	.string "\nneed it.$"

Unova_PWTBackRoom_Text_PwtBackRoomJuniper1Text::
	.string "JUNIPER: Don't let"
	.string "\nher personality"
	.string "\pfool you, the"
	.string "\nPROF. is a"
	.string "\ptalented POKéMON"
	.string "\ntrainer too.$"

Unova_PWTBackRoom_Text_PwtBackRoomIrisText::
	.string "IRIS: I gave up"
	.string "\nbeing CHAMPION"
	.string "\pto go back to live"
	.string "\nwith my Grandpa,"
	.string "\pbut I still like"
	.string "\nto come battle"
	.string "\levery now and"
	.string "\lthen!$"

Unova_PWTBackRoom_Text_PwtBackRoomInferText::
	.string "INFER: You'd"
	.string "\nbetter win your"
	.string "\pmatch, and when"
	.string "\nyou do, I'll be"
	.string "\pwaiting for you"
	.string "\nin the next round!$"

Unova_PWTBackRoom_Text_PwtBackRoomVioText::
	.string "VIO: … … … …$"
