CanalaveCitySailorEldritchHouse_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

CanalaveCitySailorEldritchHouse_EventScript_Npc1::
	msgbox CanalaveCitySailorEldritchHouse_Text_Npc1, MSGBOX_NPC
	end

CanalaveCitySailorEldritchHouse_Text_Npc1:
	.string "I'm going to be a Sailor like my\ndaddy!\pHe's a real man among men!\nEven the sea doesn't scare him!\pOh, but a Gym Leader'd be cool, too!\nByron is so awesome!$"

CanalaveCitySailorEldritchHouse_EventScript_Npc2::
	msgbox CanalaveCitySailorEldritchHouse_Text_Npc2, MSGBOX_NPC
	end

CanalaveCitySailorEldritchHouse_Text_Npc2:
	.string "Our boy has too much energy!\n...That's the best way to be!$"
