@ SeasideCaveB2F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_SeasideCaveB2F_MapScripts::
	.byte 0

Unova_SeasideCaveB2F_EventScript_Lider3::
	trainerbattle_single TRAINER_UNOVA_GRUNTM_SEASIDE_CAVE_1, Unova_SeasideCaveB2F_Text_GruntM1SeasideCaveSeenText, Unova_SeasideCaveB2F_Text_GruntM1SeasideCaveBeatenText
	end

Unova_SeasideCaveB2F_EventScript_Lider4::
	trainerbattle_single TRAINER_UNOVA_GRUNTM_SEASIDE_CAVE_2, Unova_SeasideCaveB2F_Text_GruntM2SeasideCaveSeenText, Unova_SeasideCaveB2F_Text_GruntM2SeasideCaveBeatenText
	end

Unova_SeasideCaveB2F_EventScript_Lider5::
	trainerbattle_single TRAINER_UNOVA_GRUNTM_SEASIDE_CAVE_3, Unova_SeasideCaveB2F_Text_GruntM3SeasideCaveSeenText, Unova_SeasideCaveB2F_Text_GruntM3SeasideCaveBeatenText
	end

Unova_SeasideCaveB2F_EventScript_Lider6::
	trainerbattle_single TRAINER_UNOVA_GRUNTF_SEASIDE_CAVE_1, Unova_SeasideCaveB2F_Text_GruntF1SeasideCaveSeenText, Unova_SeasideCaveB2F_Text_GruntF1SeasideCaveBeatenText
	end

Unova_SeasideCaveB2F_EventScript_Lider7::
	trainerbattle_single TRAINER_UNOVA_GRUNTF_SEASIDE_CAVE_2, Unova_SeasideCaveB2F_Text_GruntF2SeasideCaveSeenText, Unova_SeasideCaveB2F_Text_GruntF2SeasideCaveBeatenText
	end

Unova_SeasideCaveB2F_EventScript_Lider8::
	trainerbattle_single TRAINER_UNOVA_GRUNTF_SEASIDE_CAVE_3, Unova_SeasideCaveB2F_Text_GruntF3SeasideCaveSeenText, Unova_SeasideCaveB2F_Text_GruntF3SeasideCaveBeatenText
	end


Unova_SeasideCaveB2F_Text_GruntM1SeasideCaveSeenText::
	.string "Target acquired!"
	.string "\nTermination will"
	.string "\lnow begin!$"

Unova_SeasideCaveB2F_Text_GruntM1SeasideCaveBeatenText::
	.string "I was terminated…?"
	.string "\nWhat a trainer!$"

Unova_SeasideCaveB2F_Text_GruntM2SeasideCaveSeenText::
	.string "Aren't you pretty"
	.string "\nconfident, just"
	.string "\pwaltzing right"
	.string "\ninto the enemy!$"

Unova_SeasideCaveB2F_Text_GruntM2SeasideCaveBeatenText::
	.string "Argh… No wonder"
	.string "\nyou're confident"
	.string "\pwith that kind of"
	.string "\nstrength.$"

Unova_SeasideCaveB2F_Text_GruntM3SeasideCaveSeenText::
	.string "Knave! I do ambush"
	.string "\nthee!$"

Unova_SeasideCaveB2F_Text_GruntM3SeasideCaveBeatenText::
	.string "Woe is me!$"

Unova_SeasideCaveB2F_Text_GruntF1SeasideCaveSeenText::
	.string "How about we see"
	.string "\nhow well I can use"
	.string "\pthis POKéMON I"
	.string "\njust got!$"

Unova_SeasideCaveB2F_Text_GruntF1SeasideCaveBeatenText::
	.string "Hmph… No good,"
	.string "\nhuh?$"

Unova_SeasideCaveB2F_Text_GruntF2SeasideCaveSeenText::
	.string "Even if we don't"
	.string "\nhave our king any-"
	.string "\pmore, we still"
	.string "\nwon't lose!$"

Unova_SeasideCaveB2F_Text_GruntF2SeasideCaveBeatenText::
	.string "Plasmaaa! Glory to"
	.string "\nTEAM PLASMA!$"

Unova_SeasideCaveB2F_Text_GruntF3SeasideCaveSeenText::
	.string "Oh-ho-ho! You've"
	.string "\nbeen ambushed!$"

Unova_SeasideCaveB2F_Text_GruntF3SeasideCaveBeatenText::
	.string "I lost! No!"
	.string "\nPlasmaaa!!$"
