@ SeasideCaveB2F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_SeasideCaveB2F_MapScripts::
	.byte 0

Unova_SeasideCaveB2F_EventScript_Npc3::
	msgbox Unova_SeasideCaveB2F_Text_GruntM1SeasideCaveSeenText, MSGBOX_NPC
	end

Unova_SeasideCaveB2F_EventScript_Npc4::
	msgbox Unova_SeasideCaveB2F_Text_GruntM2SeasideCaveSeenText, MSGBOX_NPC
	end

Unova_SeasideCaveB2F_EventScript_Npc5::
	msgbox Unova_SeasideCaveB2F_Text_GruntM3SeasideCaveSeenText, MSGBOX_NPC
	end

Unova_SeasideCaveB2F_EventScript_Npc6::
	msgbox Unova_SeasideCaveB2F_Text_GruntF1SeasideCaveSeenText, MSGBOX_NPC
	end

Unova_SeasideCaveB2F_EventScript_Npc7::
	msgbox Unova_SeasideCaveB2F_Text_GruntF2SeasideCaveSeenText, MSGBOX_NPC
	end

Unova_SeasideCaveB2F_EventScript_Npc8::
	msgbox Unova_SeasideCaveB2F_Text_GruntF3SeasideCaveSeenText, MSGBOX_NPC
	end


Unova_SeasideCaveB2F_Text_GruntM1SeasideCaveSeenText::
	.string "Target acquired!"
	.string "\nTermination will"
	.string "\lnow begin!$"

Unova_SeasideCaveB2F_Text_GruntM2SeasideCaveSeenText::
	.string "Aren't you pretty"
	.string "\nconfident, just"
	.string "\pwaltzing right"
	.string "\ninto the enemy!$"

Unova_SeasideCaveB2F_Text_GruntM3SeasideCaveSeenText::
	.string "Knave! I do ambush"
	.string "\nthee!$"

Unova_SeasideCaveB2F_Text_GruntF1SeasideCaveSeenText::
	.string "How about we see"
	.string "\nhow well I can use"
	.string "\pthis POKéMON I"
	.string "\njust got!$"

Unova_SeasideCaveB2F_Text_GruntF2SeasideCaveSeenText::
	.string "Even if we don't"
	.string "\nhave our king any-"
	.string "\pmore, we still"
	.string "\nwon't lose!$"

Unova_SeasideCaveB2F_Text_GruntF3SeasideCaveSeenText::
	.string "Oh-ho-ho! You've"
	.string "\nbeen ambushed!$"
