@ FoothillTown_House4: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 17.6) por dev_scripts/copia_planta_ex.py.

FoothillTown_House4_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 17.6), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
FoothillTown_House4_EventScript_ExNpc0::
	msgbox FoothillTown_House4_Text_ExNpc0, MSGBOX_NPC
	end

FoothillTown_House4_Text_ExNpc0:
	.string "I love it here!\n"
	.string "Everyone’s so relaxed!$"

FoothillTown_House4_EventScript_ExNpc1::
	msgbox FoothillTown_House4_Text_ExNpc1, MSGBOX_NPC
	end

FoothillTown_House4_Text_ExNpc1:
	.string "We moved here from LILYCOVE CITY. It is\n"
	.string "so much more peaceful here!$"

