SunyshoreCityNortheastHouse_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

SunyshoreCityNortheastHouse_EventScript_Npc1::
	msgbox SunyshoreCityNortheastHouse_Text_Npc1, MSGBOX_NPC
	end

SunyshoreCityNortheastHouse_Text_Npc1:
	.string "Julia: Yawn...\nToday's Saturday...\pI'm feeling lazy and sleepy...\pI wish I had a pillow...\nBut what kind of a pillow?$"
