@ Rt23East do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt23East_MapScripts::
	.byte 0

Unova_Rt23East_EventScript_Npc0::
	msgbox Unova_Rt23East_Text_R23Officer1StopText, MSGBOX_NPC
	end

Unova_Rt23East_EventScript_Npc1::
	msgbox Unova_Rt23East_Text_R23Officer2StopText, MSGBOX_NPC
	end

Unova_Rt23East_EventScript_Npc2::
	msgbox Unova_Rt23East_Text_R23Officer3HaveBadgeText, MSGBOX_NPC
	end

Unova_Rt23East_EventScript_Npc3::
	msgbox Unova_Rt23East_Text_R23Officer4HaveBadgeText, MSGBOX_NPC
	end

Unova_Rt23East_EventScript_Npc4::
	msgbox Unova_Rt23East_Text_R23Officer5HaveBadgeText, MSGBOX_NPC
	end

Unova_Rt23East_EventScript_Npc5::
	msgbox Unova_Rt23East_Text_R23Officer6StopText, MSGBOX_NPC
	end

Unova_Rt23East_EventScript_Npc12::
	msgbox Unova_Rt23East_Text_AceTrainerM1R23SeenText, MSGBOX_NPC
	end

Unova_Rt23East_EventScript_Npc13::
	msgbox Unova_Rt23East_Text_AceTrainerF1R23SeenText, MSGBOX_NPC
	end


Unova_Rt23East_Text_R23Officer1StopText::
	.string "Stop! Ahead lies"
	.string "\nthe path to the"
	.string "\lPOKéMON LEAGUE."
	.string "\pOnly those who"
	.string "\nhave collected"
	.string "\pall 8 POKéMON"
	.string "\nLEAGUE GYM BADGES"
	.string "\lmay enter."
	.string "\pYou cannot pass"
	.string "\nhere unless you"
	.string "\phave the"
	.string "\nSPOOKYBADGE.$"

Unova_Rt23East_Text_R23Officer2StopText::
	.string "Stop! Ahead lies"
	.string "\nthe path to the"
	.string "\lPOKéMON LEAGUE."
	.string "\pOnly those who"
	.string "\nhave collected"
	.string "\pall 8 POKéMON"
	.string "\nLEAGUE GYM BADGES"
	.string "\lmay enter."
	.string "\pYou cannot pass"
	.string "\nhere unless you"
	.string "\phave the"
	.string "\nINSECTBADGE.$"

Unova_Rt23East_Text_R23Officer3HaveBadgeText::
	.string "Oh, that is the"
	.string "\nTOXICBADGE!"
	.string "\pYou may pass.$"

Unova_Rt23East_Text_R23Officer4HaveBadgeText::
	.string "Oh, that is the"
	.string "\nBASICBADGE!"
	.string "\pYou may pass.$"

Unova_Rt23East_Text_R23Officer5HaveBadgeText::
	.string "Oh, that is the"
	.string "\nGARNISHBADGE!"
	.string "\pYou may pass.$"

Unova_Rt23East_Text_R23Officer6StopText::
	.string "Stop! Ahead lies"
	.string "\nthe path to the"
	.string "\lPOKéMON LEAGUE."
	.string "\pOnly those who"
	.string "\nhave collected"
	.string "\pall 8 POKéMON"
	.string "\nLEAGUE GYM BADGES"
	.string "\lmay enter."
	.string "\pYou cannot pass"
	.string "\nhere unless you"
	.string "\phave the"
	.string "\nJETBADGE.$"

Unova_Rt23East_Text_AceTrainerM1R23SeenText::
	.string "Our battle will"
	.string "\nsurely be worth a"
	.string "\ppage in the book"
	.string "\nof your journey!$"

Unova_Rt23East_Text_AceTrainerF1R23SeenText::
	.string "I can see the plea"
	.string "\nin my POKéMON's"
	.string "\peyes. To fight!"
	.string "\nAnd to win!$"
