BellchimeTrail_House_MapScripts::
	.byte 0

BellchimeTrail_House_EventScript_Npc1::
	msgbox BellchimeTrail_House_EventScript_Npc1_Text, MSGBOX_NPC
	end

BellchimeTrail_House_EventScript_Npc1_Text:
	.string "The bell of the tower can be heard from here.\pThey say it only rings for a trainer with a\npure heart. Mine, sadly, is a bit dented.$"

BellchimeTrail_House_EventScript_Npc2::
	msgbox BellchimeTrail_House_EventScript_Npc2_Text, MSGBOX_NPC
	end

BellchimeTrail_House_EventScript_Npc2_Text:
	.string "We keep this house for the pilgrims who walk\nthe trail. Rest here as long as you like.$"
