@ NuvemaMomHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_NuvemaMomHouse_MapScripts::
	.byte 0

Unova_NuvemaMomHouse_EventScript_Placa2::
	msgbox Unova_NuvemaMomHouse_Text_NuvemaMomHouseConsoleText, MSGBOX_SIGN
	end

Unova_NuvemaMomHouse_EventScript_Npc0::
	msgbox Unova_NuvemaMomHouse_Text_NuvemaMomIntroTextM, MSGBOX_NPC
	end

Unova_NuvemaMomHouse_EventScript_Npc1::
	msgbox Unova_NuvemaMomHouse_Text_NuvemaHilbertHildaText, MSGBOX_NPC
	end

Unova_NuvemaMomHouse_EventScript_Npc2::
	msgbox Unova_NuvemaMomHouse_Text_NuvemaHilbertHildaText, MSGBOX_NPC
	end


Unova_NuvemaMomHouse_Text_NuvemaMomHouseConsoleText::
	.string "It's a classic"
	.string "\ngame console, a"
	.string "\lNintendo 64!"
	.string "\pWhoever lived here"
	.string "\nmust have been"
	.string "\pexcited when they"
	.string "\ngot this as a kid!$"

Unova_NuvemaMomHouse_Text_NuvemaMomIntroTextM::
	.string "You're a POKéMON"
	.string "\ntrainer, right?"
	.string "\pMy son is a POKé-"
	.string "\nMON trainer too."
	.string "\pHe always treated"
	.string "\nhis POKéMON with"
	.string "\lcare."
	.string "\pEach POKéMON has"
	.string "\nits own special"
	.string "\lpower."
	.string "\pHere, take this"
	.string "\nTM.$"

Unova_NuvemaMomHouse_Text_NuvemaHilbertHildaText::
	.string "...$"
