SunyshoreCityEastHouse_MapScripts::
	.byte 0

SunyshoreCityEastHouse_EventScript_Npc1::
	msgbox SunyshoreCityEastHouse_Text_Npc1, MSGBOX_NPC
	end

SunyshoreCityEastHouse_Text_Npc1:
	.string "That glaringly bright and cool thing\nyou have!\pIt's undoubtedly a Pokétch!\nThe latest model, no less!\pThey're awesome, yeah?\pI got OK'd by the Pokétch Company\nto develop original Pokétch apps.\pHey, you're a Trainer, right?\nCan you do me a favor?\pYou've got Pokémon with different\nnatures, right? May I see them?$"
