PalParkLobby_MapScripts::
	.byte 0

PalParkLobby_EventScript_Npc1::
	msgbox PalParkLobby_Text_Npc1, MSGBOX_NPC
	end

PalParkLobby_Text_Npc1:
	.string "Pal Park is so scintillating!\pTrainers and Pokémon are so full of\nintensity here!$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

PalParkLobby_EventScript_Npc1::
	msgbox PalParkLobby_Text_Npc1, MSGBOX_NPC
	end

PalParkLobby_Text_Npc1:
	.string "I've heard Trainers complain that\nrare Pokémon take longer to appear.\pIs it easier to start with common\nPokémon?$"

PalParkLobby_EventScript_Npc2::
	msgbox PalParkLobby_Text_Npc2, MSGBOX_NPC
	end

PalParkLobby_Text_Npc2:
	.string "{PLAYER}, my daughter is a big\nfan of yours.\pA day doesn't go by without her\ndemanding we come see Catching Shows.$"

PalParkLobby_EventScript_Npc3::
	msgbox PalParkLobby_Text_Npc3, MSGBOX_NPC
	end

PalParkLobby_Text_Npc3:
	.string "People come here not only to see\nthe Catching Show.\pWe get to see rare and exotic\nPokémon on top of the catches.\pThe excitement gets me all jacked up!$"

PalParkLobby_EventScript_Npc4::
	msgbox PalParkLobby_Text_Npc4, MSGBOX_NPC
	end

PalParkLobby_Text_Npc4:
	.string "Welcome to Pal Park!\pThis is where top-notch Trainers come\nto demonstrate their Pokémon-catching\ptechniques to their peers.\p...Oh?\pAre you maybe...\nAh, you are {PLAYER}!\pWe've all heard rumors about you!\nWord is, you're a hotshot Trainer?!\pWe'd be honored if you would\nparticipate in our Catching Shows.$"

PalParkLobby_EventScript_Npc5::
	msgbox PalParkLobby_Text_Npc5, MSGBOX_NPC
	end

PalParkLobby_Text_Npc5:
	.string "The Catching Show...\pIt's a head-on clash of will and\nwits between Trainer and Pokémon.\pI especially look forward to seeing\nPokémon from Kanto and Hoenn.\pBut it tugs at my heartstrings to\nknow they're so far away from home.$"
