@ MossdeepCity_Ex14_15: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 14.15) por dev_scripts/copia_planta_ex.py.

MossdeepCity_Ex14_15_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 14.15), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
MossdeepCity_Ex14_15_EventScript_ExNpc0::
	msgbox MossdeepCity_Ex14_15_Text_ExNpc0, MSGBOX_NPC
	end

MossdeepCity_Ex14_15_Text_ExNpc0:
	.string "My longest voyage was from here to\n"
	.string "ORRE REGION!$"

MossdeepCity_Ex14_15_EventScript_ExNpc1::
	msgbox MossdeepCity_Ex14_15_Text_ExNpc1, MSGBOX_NPC
	end

MossdeepCity_Ex14_15_Text_ExNpc1:
	.string "Be careful amidst the waves boy!\p"
	.string "I was aboard the SS Tidal when it went\n"
	.string "down.\p"
	.string "A gigantic blue sea-monster emerged\n"
	.string "from the depths with enormous waves!$"

MossdeepCity_Ex14_15_EventScript_ExNpc2::
	msgbox MossdeepCity_Ex14_15_Text_ExNpc2, MSGBOX_NPC
	end

MossdeepCity_Ex14_15_Text_ExNpc2:
	.string "Ha!\n"
	.string "Welcome to the Sailor Lodge!$"

MossdeepCity_Ex14_15_EventScript_ExNpc3::
	msgbox MossdeepCity_Ex14_15_Text_ExNpc3, MSGBOX_NPC
	end

MossdeepCity_Ex14_15_Text_ExNpc3:
	.string "Aye mate, I see ye sail on ye POKéMON!\p"
	.string "Astounding!$"

