@ LentimasAirport do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_LentimasAirport_MapScripts::
	.byte 0

Unova_LentimasAirport_EventScript_Npc0::
	msgbox Unova_LentimasAirport_Text_LentimasAirportRideText, MSGBOX_NPC
	end

Unova_LentimasAirport_EventScript_Npc1::
	msgbox Unova_LentimasAirport_Text_LentimasAirportLassText, MSGBOX_NPC
	end

Unova_LentimasAirport_EventScript_Npc2::
	msgbox Unova_LentimasAirport_Text_LentimasAirportKrokorokText, MSGBOX_NPC
	end


Unova_LentimasAirport_Text_LentimasAirportRideText::
	.string "Welcome to the"
	.string "\nLENTIMAS TOWN"
	.string "\lairport."
	.string "\pWe offer flights"
	.string "\nto MISTRALTON"
	.string "\lCITY."
	.string "\pAre you coming"
	.string "\non board?$"

Unova_LentimasAirport_Text_LentimasAirportLassText::
	.string "I'm fine even"
	.string "\nright by a volcano"
	.string "\pthanks to my lil"
	.string "\nKROKOROK! It"
	.string "\lreally rocks!$"

Unova_LentimasAirport_Text_LentimasAirportKrokorokText::
	.string "Krakaah!$"
