@ VictoryRoadOutdoor2F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VictoryRoadOutdoor2F_MapScripts::
	.byte 0

Unova_VictoryRoadOutdoor2F_EventScript_Lider4::
	trainerbattle_single TRAINER_UNOVA_VETERANM_VICTORY_ROAD_EXT_2, Unova_VictoryRoadOutdoor2F_Text_VeteranMVictoryRoadOutdoor2FSeenText, Unova_VictoryRoadOutdoor2F_Text_VeteranMVictoryRoadOutdoor2FBeatenText
	end

Unova_VictoryRoadOutdoor2F_EventScript_Lider5::
	trainerbattle_single TRAINER_UNOVA_VETERANF_VICTORY_ROAD_EXT_2, Unova_VictoryRoadOutdoor2F_Text_VeteranFVictoryRoadOutdoor2FSeenText, Unova_VictoryRoadOutdoor2F_Text_VeteranFVictoryRoadOutdoor2FBeatenText
	end

Unova_VictoryRoadOutdoor2F_EventScript_Lider6::
	trainerbattle_single TRAINER_UNOVA_ACE_TRAINERM_VICTORY_ROAD_EXT_1, Unova_VictoryRoadOutdoor2F_Text_AceTrainerMVictoryRoadOutdoor2FSeenText, Unova_VictoryRoadOutdoor2F_Text_AceTrainerMVictoryRoadOutdoor2FBeatenText
	end

Unova_VictoryRoadOutdoor2F_EventScript_Lider7::
	trainerbattle_single TRAINER_UNOVA_ACE_TRAINERF_VICTORY_ROAD_EXT_2, Unova_VictoryRoadOutdoor2F_Text_AceTrainerFVictoryRoadOutdoor2FSeenText, Unova_VictoryRoadOutdoor2F_Text_AceTrainerFVictoryRoadOutdoor2FBeatenText
	end

Unova_VictoryRoadOutdoor2F_EventScript_Lider8::
	trainerbattle_single TRAINER_UNOVA_SCIENTISTM_VICTORY_ROAD_EXT, Unova_VictoryRoadOutdoor2F_Text_ScientistMVictoryRoadOutdoor2FSeenText, Unova_VictoryRoadOutdoor2F_Text_ScientistMVictoryRoadOutdoor2FBeatenText
	end

Unova_VictoryRoadOutdoor2F_EventScript_Lider9::
	trainerbattle_single TRAINER_UNOVA_SCIENTISTF_VICTORY_ROAD_EXT, Unova_VictoryRoadOutdoor2F_Text_ScientistFVictoryRoadOutdoor2FSeenText, Unova_VictoryRoadOutdoor2F_Text_ScientistFVictoryRoadOutdoor2FBeatenText
	end

Unova_VictoryRoadOutdoor2F_EventScript_Lider10::
	trainerbattle_single TRAINER_UNOVA_BLACKBELT_VICTORY_ROAD_EXT, Unova_VictoryRoadOutdoor2F_Text_BlackbeltVictoryRoadOutdoor2FSeenText, Unova_VictoryRoadOutdoor2F_Text_BlackbeltVictoryRoadOutdoor2FBeatenText
	end

Unova_VictoryRoadOutdoor2F_EventScript_Lider11::
	trainerbattle_single TRAINER_UNOVA_BATTLE_GIRL_VICTORY_ROAD_EXT, Unova_VictoryRoadOutdoor2F_Text_BattleGirlVictoryRoadOutdoor2FSeenText, Unova_VictoryRoadOutdoor2F_Text_BattleGirlVictoryRoadOutdoor2FBeatenText
	end


Unova_VictoryRoadOutdoor2F_Text_VeteranMVictoryRoadOutdoor2FSeenText::
	.string "The people who"
	.string "\npass by here have"
	.string "\psuch different"
	.string "\nmoods! It's fun to"
	.string "\pwatch, and even"
	.string "\nmore fun to fight"
	.string "\lagainst them!$"

Unova_VictoryRoadOutdoor2F_Text_VeteranMVictoryRoadOutdoor2FBeatenText::
	.string "Mwa haha!"
	.string "\nIt's fun!$"

Unova_VictoryRoadOutdoor2F_Text_VeteranFVictoryRoadOutdoor2FSeenText::
	.string "Are you sure? I'm"
	.string "\nstrong, you know."
	.string "\pYou still want to"
	.string "\ntake me on?$"

Unova_VictoryRoadOutdoor2F_Text_VeteranFVictoryRoadOutdoor2FBeatenText::
	.string "Yes, I'm sure…$"

Unova_VictoryRoadOutdoor2F_Text_AceTrainerMVictoryRoadOutdoor2FSeenText::
	.string "When I win, and"
	.string "\neven when the"
	.string "\pimpossible happens"
	.string "\nand I lose, I"
	.string "\panalyze every one"
	.string "\nof my battles to"
	.string "\lgrow stronger.$"

Unova_VictoryRoadOutdoor2F_Text_AceTrainerMVictoryRoadOutdoor2FBeatenText::
	.string "I want to ride"
	.string "\naway on my POKé-"
	.string "\pMON so I can"
	.string "\nponder why I lost…$"

Unova_VictoryRoadOutdoor2F_Text_AceTrainerFVictoryRoadOutdoor2FSeenText::
	.string "To battle in a"
	.string "\nhigh-up place…"
	.string "\pThis is a perfect"
	.string "\nsituation for an"
	.string "\pACE TRAINER such"
	.string "\nas I!$"

Unova_VictoryRoadOutdoor2F_Text_AceTrainerFVictoryRoadOutdoor2FBeatenText::
	.string "To tell the truth…"
	.string "\nI'm actually"
	.string "\lafraid of heights…$"

Unova_VictoryRoadOutdoor2F_Text_ScientistMVictoryRoadOutdoor2FSeenText::
	.string "Hm… What could be"
	.string "\nthe key to POKéMON"
	.string "\pbattles and POKé-"
	.string "\nMON growth?"
	.string "\pThis, I will study"
	.string "\nin battle with"
	.string "\lyou!$"

Unova_VictoryRoadOutdoor2F_Text_ScientistMVictoryRoadOutdoor2FBeatenText::
	.string "This was very"
	.string "\nhelpful…$"

Unova_VictoryRoadOutdoor2F_Text_ScientistFVictoryRoadOutdoor2FSeenText::
	.string "When I'm stuck"
	.string "\ninside the lab"
	.string "\pevery day, I get"
	.string "\nso stressed out!$"

Unova_VictoryRoadOutdoor2F_Text_ScientistFVictoryRoadOutdoor2FBeatenText::
	.string "Aaaaah! So"
	.string "\nfrustrating!$"

Unova_VictoryRoadOutdoor2F_Text_BlackbeltVictoryRoadOutdoor2FSeenText::
	.string "Let's fight!$"

Unova_VictoryRoadOutdoor2F_Text_BlackbeltVictoryRoadOutdoor2FBeatenText::
	.string "You took a win"
	.string "\nfrom me! It's so"
	.string "\lfrustrating!$"

Unova_VictoryRoadOutdoor2F_Text_BattleGirlVictoryRoadOutdoor2FSeenText::
	.string "Life is all about"
	.string "\novercoming"
	.string "\phurdles! Could you"
	.string "\nbe a hurdle for"
	.string "\lme?$"

Unova_VictoryRoadOutdoor2F_Text_BattleGirlVictoryRoadOutdoor2FBeatenText::
	.string "I couldn't overcome"
	.string "\nthe hurdle you"
	.string "\lpresented to me…$"
