@ VictoryRoadOutdoor2F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VictoryRoadOutdoor2F_MapScripts::
	.byte 0

Unova_VictoryRoadOutdoor2F_EventScript_Npc4::
	msgbox Unova_VictoryRoadOutdoor2F_Text_VeteranMVictoryRoadOutdoor2FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadOutdoor2F_EventScript_Npc5::
	msgbox Unova_VictoryRoadOutdoor2F_Text_VeteranFVictoryRoadOutdoor2FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadOutdoor2F_EventScript_Npc6::
	msgbox Unova_VictoryRoadOutdoor2F_Text_AceTrainerMVictoryRoadOutdoor2FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadOutdoor2F_EventScript_Npc7::
	msgbox Unova_VictoryRoadOutdoor2F_Text_AceTrainerFVictoryRoadOutdoor2FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadOutdoor2F_EventScript_Npc8::
	msgbox Unova_VictoryRoadOutdoor2F_Text_ScientistMVictoryRoadOutdoor2FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadOutdoor2F_EventScript_Npc9::
	msgbox Unova_VictoryRoadOutdoor2F_Text_ScientistFVictoryRoadOutdoor2FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadOutdoor2F_EventScript_Npc10::
	msgbox Unova_VictoryRoadOutdoor2F_Text_BlackbeltVictoryRoadOutdoor2FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadOutdoor2F_EventScript_Npc11::
	msgbox Unova_VictoryRoadOutdoor2F_Text_BattleGirlVictoryRoadOutdoor2FSeenText, MSGBOX_NPC
	end


Unova_VictoryRoadOutdoor2F_Text_VeteranMVictoryRoadOutdoor2FSeenText::
	.string "The people who"
	.string "\npass by here have"
	.string "\psuch different"
	.string "\nmoods! It's fun to"
	.string "\pwatch, and even"
	.string "\nmore fun to fight"
	.string "\lagainst them!$"

Unova_VictoryRoadOutdoor2F_Text_VeteranFVictoryRoadOutdoor2FSeenText::
	.string "Are you sure? I'm"
	.string "\nstrong, you know."
	.string "\pYou still want to"
	.string "\ntake me on?$"

Unova_VictoryRoadOutdoor2F_Text_AceTrainerMVictoryRoadOutdoor2FSeenText::
	.string "When I win, and"
	.string "\neven when the"
	.string "\pimpossible happens"
	.string "\nand I lose, I"
	.string "\panalyze every one"
	.string "\nof my battles to"
	.string "\lgrow stronger.$"

Unova_VictoryRoadOutdoor2F_Text_AceTrainerFVictoryRoadOutdoor2FSeenText::
	.string "To battle in a"
	.string "\nhigh-up place…"
	.string "\pThis is a perfect"
	.string "\nsituation for an"
	.string "\pACE TRAINER such"
	.string "\nas I!$"

Unova_VictoryRoadOutdoor2F_Text_ScientistMVictoryRoadOutdoor2FSeenText::
	.string "Hm… What could be"
	.string "\nthe key to POKéMON"
	.string "\pbattles and POKé-"
	.string "\nMON growth?"
	.string "\pThis, I will study"
	.string "\nin battle with"
	.string "\lyou!$"

Unova_VictoryRoadOutdoor2F_Text_ScientistFVictoryRoadOutdoor2FSeenText::
	.string "When I'm stuck"
	.string "\ninside the lab"
	.string "\pevery day, I get"
	.string "\nso stressed out!$"

Unova_VictoryRoadOutdoor2F_Text_BlackbeltVictoryRoadOutdoor2FSeenText::
	.string "Let's fight!$"

Unova_VictoryRoadOutdoor2F_Text_BattleGirlVictoryRoadOutdoor2FSeenText::
	.string "Life is all about"
	.string "\novercoming"
	.string "\phurdles! Could you"
	.string "\nbe a hurdle for"
	.string "\lme?$"
