@ VirbankComplexB2F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VirbankComplexB2F_MapScripts::
	.byte 0

Unova_VirbankComplexB2F_EventScript_Npc0::
	msgbox Unova_VirbankComplexB2F_Text_GruntMVirbankComplexB2FSeenText, MSGBOX_NPC
	end

Unova_VirbankComplexB2F_EventScript_Npc1::
	msgbox Unova_VirbankComplexB2F_Text_GruntFVirbankComplexB2FSeenText, MSGBOX_NPC
	end

Unova_VirbankComplexB2F_EventScript_Npc2::
	msgbox Unova_VirbankComplexB2F_Text_ScientistMVirbankComplexB2FSeenText, MSGBOX_NPC
	end

Unova_VirbankComplexB2F_EventScript_Npc3::
	msgbox Unova_VirbankComplexB2F_Text_ScientistFVirbankComplexB2FSeenText, MSGBOX_NPC
	end


Unova_VirbankComplexB2F_Text_GruntMVirbankComplexB2FSeenText::
	.string "POKéMON are pawns!"
	.string "\nThey're a means to"
	.string "\lan end."
	.string "\pThat's what I was"
	.string "\ntaught! Don't think"
	.string "\labout it too much.$"

Unova_VirbankComplexB2F_Text_GruntFVirbankComplexB2FSeenText::
	.string "Don't get in our"
	.string "\nway! You bother!"
	.string "\pBother, bother,"
	.string "\nbother!$"

Unova_VirbankComplexB2F_Text_ScientistMVirbankComplexB2FSeenText::
	.string "I used to work in"
	.string "\nthe COMPLEX, but"
	.string "\pnow I run research"
	.string "\nfor TEAM PLASMA!$"

Unova_VirbankComplexB2F_Text_ScientistFVirbankComplexB2FSeenText::
	.string "Even if you win a"
	.string "\nbattle, you won't"
	.string "\pnecessarily get"
	.string "\nthe answer you're"
	.string "\llooking for."
	.string "\pYou might get"
	.string "\nsomething else,"
	.string "\lthough!$"
