@ VirbankComplexB2F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VirbankComplexB2F_MapScripts::
	.byte 0

Unova_VirbankComplexB2F_EventScript_Lider0::
	trainerbattle_single TRAINER_UNOVA_GRUNTM_VIRBANK_COMPLEX_3, Unova_VirbankComplexB2F_Text_GruntMVirbankComplexB2FSeenText, Unova_VirbankComplexB2F_Text_GruntMVirbankComplexB2FBeatenText
	end

Unova_VirbankComplexB2F_EventScript_Lider1::
	trainerbattle_single TRAINER_UNOVA_GRUNTF_VIRBANK_COMPLEX_2, Unova_VirbankComplexB2F_Text_GruntFVirbankComplexB2FSeenText, Unova_VirbankComplexB2F_Text_GruntFVirbankComplexB2FBeatenText
	end

Unova_VirbankComplexB2F_EventScript_Lider2::
	trainerbattle_single TRAINER_UNOVA_SCIENTISTM_VIRBANK_COMPLEX, Unova_VirbankComplexB2F_Text_ScientistMVirbankComplexB2FSeenText, Unova_VirbankComplexB2F_Text_ScientistMVirbankComplexB2FBeatenText
	end

Unova_VirbankComplexB2F_EventScript_Lider3::
	trainerbattle_single TRAINER_UNOVA_SCIENTISTF_VIRBANK_COMPLEX_2, Unova_VirbankComplexB2F_Text_ScientistFVirbankComplexB2FSeenText, Unova_VirbankComplexB2F_Text_ScientistFVirbankComplexB2FBeatenText
	end


Unova_VirbankComplexB2F_Text_GruntMVirbankComplexB2FSeenText::
	.string "POKéMON are pawns!"
	.string "\nThey're a means to"
	.string "\lan end."
	.string "\pThat's what I was"
	.string "\ntaught! Don't think"
	.string "\labout it too much.$"

Unova_VirbankComplexB2F_Text_GruntMVirbankComplexB2FBeatenText::
	.string "You little… You"
	.string "\nknocked out my"
	.string "\lstupid pawns!$"

Unova_VirbankComplexB2F_Text_GruntFVirbankComplexB2FSeenText::
	.string "Don't get in our"
	.string "\nway! You bother!"
	.string "\pBother, bother,"
	.string "\nbother!$"

Unova_VirbankComplexB2F_Text_GruntFVirbankComplexB2FBeatenText::
	.string "Arrgh! Lame!"
	.string "\nStupid! Fool!"
	.string "\lPlasmaaa!$"

Unova_VirbankComplexB2F_Text_ScientistMVirbankComplexB2FSeenText::
	.string "I used to work in"
	.string "\nthe COMPLEX, but"
	.string "\pnow I run research"
	.string "\nfor TEAM PLASMA!$"

Unova_VirbankComplexB2F_Text_ScientistMVirbankComplexB2FBeatenText::
	.string "Battling isn't"
	.string "\nexactly my strong"
	.string "\lsuit…$"

Unova_VirbankComplexB2F_Text_ScientistFVirbankComplexB2FSeenText::
	.string "Even if you win a"
	.string "\nbattle, you won't"
	.string "\pnecessarily get"
	.string "\nthe answer you're"
	.string "\llooking for."
	.string "\pYou might get"
	.string "\nsomething else,"
	.string "\lthough!$"

Unova_VirbankComplexB2F_Text_ScientistFVirbankComplexB2FBeatenText::
	.string "Grr… What even is"
	.string "\nthe point of a"
	.string "\lPOKéMON battle?$"
