PokemonMansion_MapScripts::
	.byte 0

PokemonMansion_EventScript_Npc1::
	msgbox PokemonMansion_Text_Npc1, MSGBOX_NPC
	end

PokemonMansion_Text_Npc1:
	.string "Mr. Backlot is the master of this\nmansion. This is his office.$"

PokemonMansion_EventScript_Npc2::
	msgbox PokemonMansion_Text_Npc2, MSGBOX_NPC
	end

PokemonMansion_Text_Npc2:
	.string "This is the way out to the trophy\ngarden.\pThe garden is open for all visitors\nto enjoy.\pHowever, please beware--wild Pokémon\nmay appear in the garden.$"

PokemonMansion_EventScript_Npc3::
	msgbox PokemonMansion_Text_Npc3, MSGBOX_NPC
	end

PokemonMansion_Text_Npc3:
	.string "I'm so sorry. Everything beyond this\npoint is strictly off-limits.\pPlease, you really mustn't.\nMr. Backlot will be so cross with me!$"
