OreburghCity_Flat2_F1_MapScripts::
	.byte 0

OreburghCity_Flat2_F1_EventScript_Expert::
	msgbox OreburghCity_Flat2_F1_Text_Expert, MSGBOX_NPC
	end

OreburghCity_Flat2_F1_EventScript_SchoolKid::
	msgbox OreburghCity_Flat2_F1_Text_SchoolKid, MSGBOX_NPC
	end

OreburghCity_Flat2_F1_EventScript_Breeder::
	msgbox OreburghCity_Flat2_F1_Text_Breeder, MSGBOX_NPC
	end

OreburghCity_Flat2_F1_Text_Expert:
	.string "I've studied ROCK-type POKéMON for\n"
	.string "years. ROARK still surprises me.$"

OreburghCity_Flat2_F1_Text_SchoolKid:
	.string "I wish I had a MACHOP. I'd love to\n"
	.string "trade for one someday.$"

OreburghCity_Flat2_F1_Text_Breeder:
	.string "Raising POKéMON in a small flat\n"
	.string "isn't easy, but we manage.$"
