OreburghCity_Flat2_F1_MapScripts::
	.byte 0

OreburghCity_Flat2_F1_EventScript_Expert::
	msgbox OreburghCity_Flat2_F1_Text_Expert, MSGBOX_NPC
	end

OreburghCity_Flat2_F1_EventScript_SchoolKid::
	msgbox OreburghCity_Flat2_F1_Text_SchoolKid, MSGBOX_NPC
	end

OreburghCity_Flat2_F1_EventScript_Breeder::
	msgbox OreburghCity_Flat2_F1_Text_Breeder, MSGBOX_NPC
	end

OreburghCity_Flat2_F1_Text_Expert:
	.string "I've studied ROCK-type POKéMON for\n"
	.string "years. ROARK still surprises me.$"

OreburghCity_Flat2_F1_Text_SchoolKid:
	.string "I wish I had a MACHOP. I'd love to\n"
	.string "trade for one someday.$"

OreburghCity_Flat2_F1_Text_Breeder:
	.string "Raising POKéMON in a small flat\n"
	.string "isn't easy, but we manage.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

OreburghCity_Flat2_F1_EventScript_Npc1::
	msgbox OreburghCity_Flat2_F1_Text_Npc1, MSGBOX_NPC
	end

OreburghCity_Flat2_F1_Text_Npc1:
	.string "A Pokémon obtained in a trade grows\nquickly.\pBut if a Pokémon grows too much, it may\nignore the Trainer.\pOf course, it won't matter if you have\nlots of Gym Badges.$"

OreburghCity_Flat2_F1_EventScript_Npc2::
	msgbox OreburghCity_Flat2_F1_Text_Npc2, MSGBOX_NPC
	end

OreburghCity_Flat2_F1_Text_Npc2:
	.string "Listen, listen. Do you have a Pokémon\ncalled MACHOP?\pWould you be willing to trade your\nMACHOP for my ABRA?$"

OreburghCity_Flat2_F1_EventScript_Npc3::
	msgbox OreburghCity_Flat2_F1_Text_Npc3, MSGBOX_NPC
	end

OreburghCity_Flat2_F1_Text_Npc3:
	.string "When you trade a Pokémon, the item it's\nholding is traded as well.\pThat's pretty cool, huh?\pIt means you can send an item as a gift\nalong with your Pokémon in a trade!$"
