@ MarineTubeEntrance do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_MarineTubeEntrance_MapScripts::
	.byte 0

Unova_MarineTubeEntrance_EventScript_Npc0::
	msgbox Unova_MarineTubeEntrance_Text_SilkScarfGiverText, MSGBOX_NPC
	end

Unova_MarineTubeEntrance_EventScript_Npc1::
	msgbox Unova_MarineTubeEntrance_Text_MarineTubeEntranceCooltrainerFText, MSGBOX_NPC
	end


Unova_MarineTubeEntrance_Text_SilkScarfGiverText::
	.string "Oh, this town is"
	.string "\nso lovely…"
	.string "\pOh, you're a POKé-"
	.string "\nMON trainer?"
	.string "\pHere, this may"
	.string "\nhelp you!$"

Unova_MarineTubeEntrance_Text_MarineTubeEntranceCooltrainerFText::
	.string "The view in the"
	.string "\ntube is so"
	.string "\lbeautiful!"
	.string "\pI wish I had"
	.string "\nsomeone to take me"
	.string "\lon a date there…$"
