@ LacunosaTown do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_LacunosaTown_MapScripts::
	.byte 0

Unova_LacunosaTown_EventScript_Placa0::
	msgbox Unova_LacunosaTown_Text_LacunosaTownSignText, MSGBOX_SIGN
	end

Unova_LacunosaTown_EventScript_Npc0::
	msgbox Unova_LacunosaTown_Text_LacunosaTownLassBallsText, MSGBOX_NPC
	end

Unova_LacunosaTown_EventScript_Npc1::
	msgbox Unova_LacunosaTown_Text_LacunosaTownYoungsterText, MSGBOX_NPC
	end

Unova_LacunosaTown_EventScript_Npc2::
	msgbox Unova_LacunosaTown_Text_LacunosaTownYoungster2Text, MSGBOX_NPC
	end

Unova_LacunosaTown_EventScript_Npc3::
	msgbox Unova_LacunosaTown_Text_LacunosaTownPokefanFText, MSGBOX_NPC
	end

Unova_LacunosaTown_EventScript_Npc4::
	msgbox Unova_LacunosaTown_Text_LacunosaTownLass2Text, MSGBOX_NPC
	end

Unova_LacunosaTown_EventScript_Npc5::
	msgbox Unova_LacunosaTown_Text_LacunosaTownTeacherText, MSGBOX_NPC
	end


Unova_LacunosaTown_Text_LacunosaTownSignText::
	.string "LACUNOSA TOWN"
	.string "\pA town as"
	.string "\nmethodical as"
	.string "\lclockwork.$"

Unova_LacunosaTown_Text_LacunosaTownLassBallsText::
	.string "Nice, the MART"
	.string "\nrestocked POKé-"
	.string "\lBALLS!"
	.string "\pI'd better stock"
	.string "\nup to go catch"
	.string "\lsome POKéMON!$"

Unova_LacunosaTown_Text_LacunosaTownYoungsterText::
	.string "You can find items"
	.string "\nhidden on the"
	.string "\lground sometimes."
	.string "\pCheck out any"
	.string "\nplaces that seem"
	.string "\lsuspicious.$"

Unova_LacunosaTown_Text_LacunosaTownYoungster2Text::
	.string "The POKéMON in"
	.string "\nROUTE 12 are"
	.string "\pdifferent from the"
	.string "\nones in ROUTE 13.$"

Unova_LacunosaTown_Text_LacunosaTownPokefanFText::
	.string "Oh, you must be"
	.string "\nfrom out of town."
	.string "\pWelcome to"
	.string "\nLACUNOSA TOWN.$"

Unova_LacunosaTown_Text_LacunosaTownLass2Text::
	.string "Try talking to"
	.string "\npeople that you"
	.string "\lmeet."
	.string "\pThey may give you"
	.string "\nsomething useful!$"

Unova_LacunosaTown_Text_LacunosaTownTeacherText::
	.string "The girls in the"
	.string "\nhouse at the end"
	.string "\pof the path sure"
	.string "\ndo love BERRIES!$"
