IcebergRuins_MapScripts::
	.byte 0

@ >>> B6 Sinnoh S1: esqueletos de cena (dev_scripts/maquina_sinnoh.py) >>>
IcebergRuins_EventScript_DotFarEast::
	@ TODO S?: cena da fonte, rotulo IcebergRuins_DotFarEast
	end

IcebergRuins_EventScript_DotFarWest::
	@ TODO S?: cena da fonte, rotulo IcebergRuins_DotFarWest
	end

IcebergRuins_EventScript_DotMiddle::
	@ TODO S?: cena da fonte, rotulo IcebergRuins_DotMiddle
	end

IcebergRuins_EventScript_DotMiddleEast::
	@ TODO S?: cena da fonte, rotulo IcebergRuins_DotMiddleEast
	end

IcebergRuins_EventScript_DotMiddleWest::
	@ TODO S?: cena da fonte, rotulo IcebergRuins_DotMiddleWest
	end

IcebergRuins_EventScript_DotNorth::
	@ TODO S?: cena da fonte, rotulo IcebergRuins_DotNorth
	end

IcebergRuins_EventScript_DotSouth::
	@ TODO S?: cena da fonte, rotulo IcebergRuins_DotSouth
	end

@ <<< B6 Sinnoh S1: esqueletos de cena <<<

IcebergRuins_EventScript_Placa1::
	msgbox IcebergRuins_Text_Placa1, MSGBOX_SIGN
	end

IcebergRuins_Text_Placa1:
	.string "Something changed in the air...\pAn indescribable power is emanating\nfrom the Pokémon statue...$"

IcebergRuins_EventScript_Placa2::
	msgbox IcebergRuins_Text_Placa2, MSGBOX_SIGN
	end

IcebergRuins_Text_Placa2:
	.string "Something changed in the air...\pAn indescribable power is emanating\nfrom the Pokémon statue...$"

IcebergRuins_EventScript_Placa3::
	msgbox IcebergRuins_Text_Placa3, MSGBOX_SIGN
	end

IcebergRuins_Text_Placa3:
	.string "Something changed in the air...\pAn indescribable power is emanating\nfrom the Pokémon statue...$"
