@ IcirrusHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_IcirrusHouse_MapScripts::
	.byte 0

Unova_IcirrusHouse_EventScript_Npc0::
	msgbox Unova_IcirrusHouse_Text_IcirrusHouseRocketText, MSGBOX_NPC
	end

Unova_IcirrusHouse_EventScript_Npc1::
	msgbox Unova_IcirrusHouse_Text_IcirrusHouseLadyIntroText, MSGBOX_NPC
	end


Unova_IcirrusHouse_Text_IcirrusHouseRocketText::
	.string "Oh! Member of TEAM"
	.string "\nROCKET I was, long"
	.string "\ltime gone!"
	.string "\pBut TEAM ROCKET"
	.string "\nbye-bye a go-go."
	.string "\pI my region went"
	.string "\nhome. Make new"
	.string "\pTEAM ROCKET, I"
	.string "\ndid! So myself I"
	.string "\lpledged!"
	.string "\pBut now I married"
	.string "\nam. Now for TEAM"
	.string "\pROCKET there is no"
	.string "\ntime by me."
	.string "\pBut happy family"
	.string "\nis big hooray!$"

Unova_IcirrusHouse_Text_IcirrusHouseLadyIntroText::
	.string "Hey! I have a lot"
	.string "\nof souvenirs that"
	.string "\pmy husband's old"
	.string "\ncoworkers gave me."
	.string "\pMaybe you can take"
	.string "\none off my hands.$"
