@ MobileBattleRoom do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_MobileBattleRoom_MapScripts::
	.byte 0

Unova_MobileBattleRoom_EventScript_Placa0::
	msgbox Unova_MobileBattleRoom_Text_MobileBattleRoom_HealText, MSGBOX_SIGN
	end


Unova_MobileBattleRoom_Text_MobileBattleRoom_HealText::
	.string "Your POKéMON will"
	.string "\nbe fully healed"
	.string "\lbefore battle.$"
