JubilifeCity_Flat2_F1_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

JubilifeCity_Flat2_F1_EventScript_Npc1::
	msgbox JubilifeCity_Flat2_F1_Text_Npc1, MSGBOX_NPC
	end

JubilifeCity_Flat2_F1_Text_Npc1:
	.string "Pokémon are wonderful, deeply\nmysterious creatures.\pBut to Trainers, the key thing is to do\nbattle with their Pokémon.\pThat's what it boils down to.$"

JubilifeCity_Flat2_F1_EventScript_Npc2::
	msgbox JubilifeCity_Flat2_F1_Text_Npc2, MSGBOX_NPC
	end

JubilifeCity_Flat2_F1_Text_Npc2:
	.string "Hello there, Trainer!\pIf you get stumped and don't know\nwhat to do...\pTalk to people!\nTalk to everyone you see!\pGo places!\nGo wherever you can!\pYou'll find many new places by\ndoing just that.$"
