@ DraydensHouse2F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_DraydensHouse2F_MapScripts::
	.byte 0

Unova_DraydensHouse2F_EventScript_Npc0::
	msgbox Unova_DraydensHouse2F_Text_DraydensHouseIrisRematchText, MSGBOX_NPC
	end


Unova_DraydensHouse2F_Text_DraydensHouseIrisRematchText::
	.string "Oh, hi {PLAYER}!"
	.string "\pAre you back for a"
	.string "\nrematch with me?"
	.string "\pHa! I like that!"
	.string "\nYou have to keep"
	.string "\pup your skills if"
	.string "\nyou want to remain"
	.string "\lChampion!"
	.string "\pNow, show me the"
	.string "\npower you used to"
	.string "\pdefeat the POKéMON"
	.string "\nLEAGUE!$"
