@ SkyarrowBridge do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_SkyarrowBridge_MapScripts::
	.byte 0

Unova_SkyarrowBridge_EventScript_Npc0::
	msgbox Unova_SkyarrowBridge_Text_SkyarrowGentlemanText, MSGBOX_NPC
	end

Unova_SkyarrowBridge_EventScript_Npc1::
	msgbox Unova_SkyarrowBridge_Text_SkyarrowLassText, MSGBOX_NPC
	end

Unova_SkyarrowBridge_EventScript_Npc2::
	msgbox Unova_SkyarrowBridge_Text_SkyarrowYoungsterText, MSGBOX_NPC
	end


Unova_SkyarrowBridge_Text_SkyarrowGentlemanText::
	.string "I'm glad to see"
	.string "\nthe bridge is"
	.string "\lback open."
	.string "\pNow I can make my"
	.string "\nimportant meetings"
	.string "\lin the city.$"

Unova_SkyarrowBridge_Text_SkyarrowLassText::
	.string "I love to look"
	.string "\nover the railing"
	.string "\lof the bridge!"
	.string "\pThe sea is so"
	.string "\nvast! It's"
	.string "\ldizzying!$"

Unova_SkyarrowBridge_Text_SkyarrowYoungsterText::
	.string "I heard something"
	.string "\nis going on in"
	.string "\lthe forest!$"
