EternaCityCondominiums2F_MapScripts::
	.byte 0

EternaCityCondominiums2F_EventScript_Npc1::
	msgbox EternaCityCondominiums2F_Text_Npc1, MSGBOX_NPC
	end

EternaCityCondominiums2F_Text_Npc1:
	.string "I've had this TM Recycle for such\na long time now.\pIt's not anything that I have much\nuse for these days.\pI do hope you'll put it to good\nuse, young Trainer.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

EternaCityCondominiums2F_EventScript_Npc3::
	msgbox EternaCityCondominiums2F_Text_Npc3, MSGBOX_NPC
	end

EternaCityCondominiums2F_Text_Npc3:
	.string "Gardenia, our Gym Leader, goes out\nto Eterna Forest every so often.\pI always wonder what she does there.$"

EternaCityCondominiums2F_EventScript_Npc2::
	msgbox EternaCityCondominiums2F_Text_Npc2, MSGBOX_NPC
	end

EternaCityCondominiums2F_Text_Npc2:
	.string "The move Recycle is to be used during\nbattle.\pWhen you use Recycle, a Pokémon can\nuse its item once again.$"
