Route221House_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

Route221House_EventScript_Placa1::
	msgbox Route221House_Text_Placa1, MSGBOX_SIGN
	end

Route221House_Text_Placa1:
	.string "Win Items from Me!\pBlack Belt: Powers up Fighting-type\nmoves.\pExpert Belt: Powers up moves if they\nare super effective.\pFocus Sash: The bearer avoids\na one-hit KO if its HP is full.$"
