@ NimbasaTMMart do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_NimbasaTMMart_MapScripts::
	.byte 0

Unova_NimbasaTMMart_EventScript_Npc1::
	msgbox Unova_NimbasaTMMart_Text_NimbasaTMMartRoughneckText, MSGBOX_NPC
	end

Unova_NimbasaTMMart_EventScript_Npc2::
	msgbox Unova_NimbasaTMMart_Text_NimbasaTMMartSocialiteText, MSGBOX_NPC
	end


Unova_NimbasaTMMart_Text_NimbasaTMMartRoughneckText::
	.string "Hey. I love strong"
	.string "\nPOKéMON."
	.string "\pI want to use TMs"
	.string "\nto make my POKéMON"
	.string "\leven stronger!$"

Unova_NimbasaTMMart_Text_NimbasaTMMartSocialiteText::
	.string "There are sure to"
	.string "\nbe TMs that are"
	.string "\pjust perfect for"
	.string "\nyour POKéMON.$"
