@ MistraltonGym2F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_MistraltonGym2F_MapScripts::
	.byte 0

Unova_MistraltonGym2F_EventScript_Npc2::
	msgbox Unova_MistraltonGym2F_Text_Pilot1MistraltonGym2FSeenText, MSGBOX_NPC
	end

Unova_MistraltonGym2F_EventScript_Npc3::
	msgbox Unova_MistraltonGym2F_Text_Pilot2MistraltonGym2FSeenText, MSGBOX_NPC
	end


Unova_MistraltonGym2F_Text_Pilot1MistraltonGym2FSeenText::
	.string "Can you figure out"
	.string "\nhow to get through"
	.string "\lour GYM?$"

Unova_MistraltonGym2F_Text_Pilot2MistraltonGym2FSeenText::
	.string "My POKéMON are"
	.string "\nstronger than the"
	.string "\pwind! They're my"
	.string "\npride and joy!$"
