@ Rt4House do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt4House_MapScripts::
	.byte 0

Unova_Rt4House_EventScript_Npc0::
	msgbox Unova_Rt4House_Text_R4HouseGiveTMText, MSGBOX_NPC
	end


Unova_Rt4House_Text_R4HouseGiveTMText::
	.string "This desert is"
	.string "\nfull of raging"
	.string "\lsand."
	.string "\pA sandstorm can"
	.string "\neven damage POKé-"
	.string "\lMON!"
	.string "\pIf you want to"
	.string "\nmake your own"
	.string "\psandstorms, then"
	.string "\ntake this!$"
