SunyshoreCityNorthwestHouse_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

SunyshoreCityNorthwestHouse_EventScript_Npc1::
	msgbox SunyshoreCityNorthwestHouse_Text_Npc1, MSGBOX_NPC
	end

SunyshoreCityNorthwestHouse_Text_Npc1:
	.string "I'd heard that Team Galactic was up to\nno good.\pBut here in Sunyshore, we've never\neven seen any of them around.\pOf course, our Gym Leader Volkner is\ninvincible in every way.$"

SunyshoreCityNorthwestHouse_EventScript_Npc2::
	msgbox SunyshoreCityNorthwestHouse_Text_Npc2, MSGBOX_NPC
	end

SunyshoreCityNorthwestHouse_Text_Npc2:
	.string "A long time ago, there was a boy\nnamed Cyrus who lived here.\pHe seemed to shun others, and he\npreferred the company of machines.\pHe was a brilliant student, I recall.\nI often wonder what became of him.$"
