SandgemTown_House1_MapScripts::
	.byte 0

SandgemTown_House1_EventScript_BreederM::
	msgbox SandgemTown_House1_Text_BreederM, MSGBOX_NPC
	end

SandgemTown_House1_EventScript_BreederF::
	msgbox SandgemTown_House1_Text_BreederF, MSGBOX_NPC
	end

SandgemTown_House1_Text_BreederM:
	.string "Raising POKéMON takes patience, but\n"
	.string "it's worth every minute of it.$"

SandgemTown_House1_Text_BreederF:
	.string "SANDGEM is a quiet town. Good place\n"
	.string "to raise POKéMON, don't you think?$"
