VeilstoneCityNortheastHouse_MapScripts::
	.byte 0

VeilstoneCityNortheastHouse_EventScript_Npc1::
	msgbox VeilstoneCityNortheastHouse_Text_Npc1, MSGBOX_NPC
	end

VeilstoneCityNortheastHouse_Text_Npc1:
	.string "You're a Trainer, aren't you?\pYou see, there's this Pokémon I'd like\nsomeone to look after.\pIt's a Pokémon called PORYGON.\nI found it near Team Galactic's building.\pI'm no Trainer, so can you take it off\nmy hands?$"
