VeilstoneCityNortheastHouse_MapScripts::
	.byte 0

VeilstoneCityNortheastHouse_EventScript_Npc1::
	msgbox VeilstoneCityNortheastHouse_Text_Npc1, MSGBOX_NPC
	end

VeilstoneCityNortheastHouse_Text_Npc1:
	.string "You're a Trainer, aren't you?\p"
	.string "You see, there's this Pokémon I'd like\n"
	.string "someone to look after.\p"
	.string "It's a Pokémon called PORYGON. I found\n"
	.string "it near Team Galactic's building.\p"
	.string "I'm no Trainer, so can you take it off\n"
	.string "my hands?$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

VeilstoneCityNortheastHouse_EventScript_Npc2::
	msgbox VeilstoneCityNortheastHouse_Text_Npc2, MSGBOX_NPC
	end

VeilstoneCityNortheastHouse_Text_Npc2:
	.string "Those thorny things on the building...\nThe way it moves meaninglessly...\pI don't understand their idea of \n'awesomely fashionable' at all.\pStill, Team Galactic does seem to have\na huge supply of energy.$"
