SnowpointTemple1F_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

SnowpointTemple1F_EventScript_Placa1::
	msgbox SnowpointTemple1F_Text_Placa1, MSGBOX_SIGN
	end

SnowpointTemple1F_Text_Placa1:
	.string "It's a statue of a Pokémon.\nOne can sense its power.$"

SnowpointTemple1F_EventScript_Placa2::
	msgbox SnowpointTemple1F_Text_Placa2, MSGBOX_SIGN
	end

SnowpointTemple1F_Text_Placa2:
	.string "It's a statue of a Pokémon.\nOne can sense its power.$"

SnowpointTemple1F_EventScript_Placa3::
	msgbox SnowpointTemple1F_Text_Placa3, MSGBOX_SIGN
	end

SnowpointTemple1F_Text_Placa3:
	.string "It's a statue of a Pokémon.\nOne can sense its power.$"
