UnusedOreburghCityNorthwestHouse4F_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

UnusedOreburghCityNorthwestHouse4F_EventScript_Npc1::
	msgbox UnusedOreburghCityNorthwestHouse4F_Text_Npc1, MSGBOX_NPC
	end

UnusedOreburghCityNorthwestHouse4F_Text_Npc1:
	.string "I set some nasty Traps!\nCatch me if you can!$"

UnusedOreburghCityNorthwestHouse4F_EventScript_Npc2::
	msgbox UnusedOreburghCityNorthwestHouse4F_Text_Npc2, MSGBOX_NPC
	end

UnusedOreburghCityNorthwestHouse4F_Text_Npc2:
	.string "Hahaha!\nI'm gonna swipe your Flag!$"

UnusedOreburghCityNorthwestHouse4F_EventScript_Npc3::
	msgbox UnusedOreburghCityNorthwestHouse4F_Text_Npc3, MSGBOX_NPC
	end

UnusedOreburghCityNorthwestHouse4F_Text_Npc3:
	.string "Thanks to the Gym Leader, we can\nplay underground.$"
