@ FloccesyTownHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_FloccesyTownHouse_MapScripts::
	.byte 0

Unova_FloccesyTownHouse_EventScript_Npc0::
	msgbox Unova_FloccesyTownHouse_Text_FloccesyHouseTwinIntroText, MSGBOX_NPC
	end


Unova_FloccesyTownHouse_Text_FloccesyHouseTwinIntroText::
	.string "I love fairy type"
	.string "\nPOKéMON! They're"
	.string "\lso cute!"
	.string "\pDo you like fairy"
	.string "\ntype POKéMON too?"
	.string "\pYou should give"
	.string "\nthem this!$"
