@ CasteliaBridgeGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_CasteliaBridgeGate_MapScripts::
	.byte 0

Unova_CasteliaBridgeGate_EventScript_Npc0::
	msgbox Unova_CasteliaBridgeGate_Text_CasteliaBridgeGateOfficerText, MSGBOX_NPC
	end

Unova_CasteliaBridgeGate_EventScript_Npc1::
	msgbox Unova_CasteliaBridgeGate_Text_CasteliaBridgeGateOfficerText, MSGBOX_NPC
	end


Unova_CasteliaBridgeGate_Text_CasteliaBridgeGateOfficerText::
	.string "Be careful if"
	.string "\nyou're planning to"
	.string "\pcross the SKY-"
	.string "\nARROW BRIDGE!$"
