HearthomeCityNortheastHouse1F_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

HearthomeCityNortheastHouse1F_EventScript_Npc1::
	msgbox HearthomeCityNortheastHouse1F_Text_Npc1, MSGBOX_NPC
	end

HearthomeCityNortheastHouse1F_Text_Npc1:
	.string "Well, now, you're a Trainer?\pThat makes you both papa and mama\nto your Pokémon.\pYou know how having Pokémon around\nleads to new discoveries?\pIt's the same for parents and kids.\nI'm always learning from my kids.$"

HearthomeCityNortheastHouse1F_EventScript_Npc2::
	msgbox HearthomeCityNortheastHouse1F_Text_Npc2, MSGBOX_NPC
	end

HearthomeCityNortheastHouse1F_Text_Npc2:
	.string "Kuufu fuu!$"

HearthomeCityNortheastHouse1F_EventScript_Npc3::
	msgbox HearthomeCityNortheastHouse1F_Text_Npc3, MSGBOX_NPC
	end

HearthomeCityNortheastHouse1F_Text_Npc3:
	.string "PIKACHU: Pikapii?$"

HearthomeCityNortheastHouse1F_EventScript_Npc4::
	msgbox HearthomeCityNortheastHouse1F_Text_Npc4, MSGBOX_NPC
	end

HearthomeCityNortheastHouse1F_Text_Npc4:
	.string "Babies and Pokémon get along\nperfectly together.\pWhen babies take naps, Pokémon go\nto sleep right next to them.$"

HearthomeCityNortheastHouse1F_EventScript_Npc5::
	msgbox HearthomeCityNortheastHouse1F_Text_Npc5, MSGBOX_NPC
	end

HearthomeCityNortheastHouse1F_Text_Npc5:
	.string "When I get bigger, I'm going to be\na Trainer, too!$"

HearthomeCityNortheastHouse1F_EventScript_Npc6::
	msgbox HearthomeCityNortheastHouse1F_Text_Npc6, MSGBOX_NPC
	end

HearthomeCityNortheastHouse1F_Text_Npc6:
	.string "When I grow up, I want to become\na Pokémon coordinator.$"

HearthomeCityNortheastHouse1F_EventScript_Npc7::
	msgbox HearthomeCityNortheastHouse1F_Text_Npc7, MSGBOX_NPC
	end

HearthomeCityNortheastHouse1F_Text_Npc7:
	.string "Oh, wow, you're a Pokémon Trainer.\pHaving lots of Pokémon around is\na lot of responsibility.\pBut that also comes with a lot\nof fun!$"

HearthomeCityNortheastHouse1F_EventScript_Npc8::
	msgbox HearthomeCityNortheastHouse1F_Text_Npc8, MSGBOX_NPC
	end

HearthomeCityNortheastHouse1F_Text_Npc8:
	.string "...My sisters make so much noise, no\none even notices me.$"
