@ CasteliaCityNorth do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_CasteliaCityNorth_MapScripts::
	.byte 0

Unova_CasteliaCityNorth_EventScript_Placa0::
	msgbox Unova_CasteliaCityNorth_Text_CasteliaCitySignText, MSGBOX_SIGN
	end

Unova_CasteliaCityNorth_EventScript_Placa1::
	msgbox Unova_CasteliaCityNorth_Text_CasteliaGymStreetSignText, MSGBOX_SIGN
	end

Unova_CasteliaCityNorth_EventScript_Placa2::
	msgbox Unova_CasteliaCityNorth_Text_CasteliaAlleySignText, MSGBOX_SIGN
	end

Unova_CasteliaCityNorth_EventScript_Placa3::
	msgbox Unova_CasteliaCityNorth_Text_CasteliaModeStreetSignText, MSGBOX_SIGN
	end

Unova_CasteliaCityNorth_EventScript_Placa4::
	msgbox Unova_CasteliaCityNorth_Text_CasteliaStreetSignText, MSGBOX_SIGN
	end

Unova_CasteliaCityNorth_EventScript_Npc0::
	msgbox Unova_CasteliaCityNorth_Text_CasteliaNorthLassText, MSGBOX_NPC
	end

Unova_CasteliaCityNorth_EventScript_Npc1::
	msgbox Unova_CasteliaCityNorth_Text_CasteliaNorthYoungsterText, MSGBOX_NPC
	end

Unova_CasteliaCityNorth_EventScript_Npc2::
	msgbox Unova_CasteliaCityNorth_Text_CasteliaNorthPokefanFText, MSGBOX_NPC
	end

Unova_CasteliaCityNorth_EventScript_Npc3::
	msgbox Unova_CasteliaCityNorth_Text_CasteliaNorthTwinText, MSGBOX_NPC
	end

Unova_CasteliaCityNorth_EventScript_Npc4::
	msgbox Unova_CasteliaCityNorth_Text_CasteliaNorthTwin2Text, MSGBOX_NPC
	end

Unova_CasteliaCityNorth_EventScript_Npc5::
	msgbox Unova_CasteliaCityNorth_Text_CasteliaNorthLass2Text, MSGBOX_NPC
	end


Unova_CasteliaCityNorth_Text_CasteliaCitySignText::
	.string "CASTELIA CITY."
	.string "\pA city of"
	.string "\ngrandeur.$"

Unova_CasteliaCityNorth_Text_CasteliaGymStreetSignText::
	.string "GYM STREET.$"

Unova_CasteliaCityNorth_Text_CasteliaAlleySignText::
	.string "NARROW ALLEY.$"

Unova_CasteliaCityNorth_Text_CasteliaModeStreetSignText::
	.string "MODE STREET.$"

Unova_CasteliaCityNorth_Text_CasteliaStreetSignText::
	.string "CASTELIA STREET.$"

Unova_CasteliaCityNorth_Text_CasteliaNorthLassText::
	.string "It's wonderful how"
	.string "\nthe POKéMON and"
	.string "\pwomen here are so"
	.string "\nfull of life!$"

Unova_CasteliaCityNorth_Text_CasteliaNorthYoungsterText::
	.string "When you're tired,"
	.string "\nyou should rest!"
	.string "\pDon't force your-"
	.string "\nself to be"
	.string "\lenergetic.$"

Unova_CasteliaCityNorth_Text_CasteliaNorthPokefanFText::
	.string "I wonder what"
	.string "\nCASTELIA was like"
	.string "\pbefore it got"
	.string "\nthis big.$"

Unova_CasteliaCityNorth_Text_CasteliaNorthTwinText::
	.string "My mom has a POKé-"
	.string "\nMON called YANMA."
	.string "\pIt's my favorite!"
	.string "\pShe says if you're"
	.string "\nkind to it, it'll"
	.string "\lturn into a"
	.string "\lstronger POKéMON!$"

Unova_CasteliaCityNorth_Text_CasteliaNorthTwin2Text::
	.string "My mom says there"
	.string "\nare some POKéMON"
	.string "\pthat evolve when"
	.string "\nyou use stones on"
	.string "\pthem. Some of them"
	.string "\nmay not be what"
	.string "\pyou expect. Try"
	.string "\nall of them!$"

Unova_CasteliaCityNorth_Text_CasteliaNorthLass2Text::
	.string "To live surrounded"
	.string "\nby people, do you"
	.string "\phave to grow to"
	.string "\nlike everyone, or"
	.string "\pdo you only have"
	.string "\nto like yourself?$"
