@ Rt4DesertGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt4DesertGate_MapScripts::
	.byte 0

Unova_Rt4DesertGate_EventScript_Npc0::
	msgbox Unova_Rt4DesertGate_Text_R4DesertGateOfficerText, MSGBOX_NPC
	end

Unova_Rt4DesertGate_EventScript_Npc1::
	msgbox Unova_Rt4DesertGate_Text_R4DesertGateGrampsText, MSGBOX_NPC
	end


Unova_Rt4DesertGate_Text_R4DesertGateOfficerText::
	.string "The DESERT RESORT"
	.string "\nkeeps growing"
	.string "\levery year."
	.string "\pMake sure you're"
	.string "\nprepared!$"

Unova_Rt4DesertGate_Text_R4DesertGateGrampsText::
	.string "I used to go and"
	.string "\nvisit the RELIC"
	.string "\lCASTLE in the"
	.string "\ldesert."
	.string "\pBut the sand has"
	.string "\ngotten so thick,"
	.string "\pthe castle is"
	.string "\nnearly buried.$"
