@ MobileTradeRoom do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_MobileTradeRoom_MapScripts::
	.byte 0

Unova_MobileTradeRoom_EventScript_Placa0::
	msgbox Unova_MobileTradeRoom_Text_MobileTradeRoom_EstablishingCommsText, MSGBOX_SIGN
	end


Unova_MobileTradeRoom_Text_MobileTradeRoom_EstablishingCommsText::
	.string "Establishing"
	.string "\ncommunications…$"
