@ FrozenHeights_Ex6_14: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 6.14) por dev_scripts/copia_planta_ex.py.

FrozenHeights_Ex6_14_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 6.14), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
FrozenHeights_Ex6_14_EventScript_ExNpc0::
	msgbox FrozenHeights_Ex6_14_Text_ExNpc0, MSGBOX_NPC
	end

FrozenHeights_Ex6_14_Text_ExNpc0:
	.string "I came up here to catch a SNOM!$"

FrozenHeights_Ex6_14_EventScript_ExNpc1::
	msgbox FrozenHeights_Ex6_14_Text_ExNpc1, MSGBOX_NPC
	end

FrozenHeights_Ex6_14_Text_ExNpc1:
	.string "It’s a long climb up here.\n"
	.string "I don’t understand how so many people\l"
	.string "can scale this mountain!$"

FrozenHeights_Ex6_14_EventScript_ExNpc2::
	msgbox FrozenHeights_Ex6_14_Text_ExNpc2, MSGBOX_NPC
	end

FrozenHeights_Ex6_14_Text_ExNpc2:
	.string "I’m up here to tell Wattson to go back\n"
	.string "to his GYM from time to time.\p"
	.string "But he’s so focused on looking for\n"
	.string "magnets that I can’t get him to listen\l"
	.string "to me.$"

