#ifndef GUARD_CONSTANTS_OPPONENTS_FRLG_H
#define GUARD_CONSTANTS_OPPONENTS_FRLG_H

#include "constants/battle_partner.h"

#define TRAINER_NONE                               0
#define TRAINER_YOUNGSTER_BEN                      1620
#define TRAINER_YOUNGSTER_CALVIN                   1621
#define TRAINER_YOUNGSTER_JOSH                     1367
#define TRAINER_YOUNGSTER_TIMMY                    1629
#define TRAINER_YOUNGSTER_JOEY                     1635
#define TRAINER_YOUNGSTER_DAN                      1636
#define TRAINER_YOUNGSTER_CHAD                     1637
#define TRAINER_YOUNGSTER_TYLER                    1368
#define TRAINER_YOUNGSTER_EDDIE                    1650
#define TRAINER_YOUNGSTER_DILLON                   1651
#define TRAINER_YOUNGSTER_YASU                     1652
#define TRAINER_YOUNGSTER_DAVE                     1653
#define TRAINER_YOUNGSTER_BEN_2                    13
#define TRAINER_BUG_CATCHER_RICK                   1369
#define TRAINER_BUG_CATCHER_DOUG                   1370
#define TRAINER_BUG_CATCHER_SAMMY                  1371
#define TRAINER_BUG_CATCHER_COLTON                 1622
#define TRAINER_BUG_CATCHER_GREG                   1623
#define TRAINER_BUG_CATCHER_JAMES                  1624
#define TRAINER_BUG_CATCHER_KENT                   1372
#define TRAINER_BUG_CATCHER_ROBBY                  1373
#define TRAINER_BUG_CATCHER_CALE                   1630
#define TRAINER_BUG_CATCHER_KEIGO                  1644
#define TRAINER_BUG_CATCHER_ELIJAH                 1645
#define TRAINER_BUG_CATCHER_BRENT                  1660
#define TRAINER_BUG_CATCHER_CONNER                 1661
#define TRAINER_LASS_JANICE                        1625
#define TRAINER_LASS_SALLY                         1626
#define TRAINER_LASS_ROBIN                         1627
#define TRAINER_LASS_CRISSY                        1628
#define TRAINER_LASS_MIRIAM                        1374
#define TRAINER_LASS_IRIS                          1375
#define TRAINER_LASS_RELI                          1631
#define TRAINER_LASS_ALI                           1632
#define TRAINER_LASS_HALEY                         1639
#define TRAINER_LASS_ANN                           1376
#define TRAINER_LASS_DAWN                          1377
#define TRAINER_LASS_PAIGE                         1675
#define TRAINER_LASS_ANDREA                        1676
#define TRAINER_LASS_MEGAN                         1677
#define TRAINER_LASS_JULIA                         1678
#define TRAINER_LASS_KAY                           1378
#define TRAINER_LASS_LISA                          1379
#define TRAINER_SAILOR_EDMOND                      1380
#define TRAINER_SAILOR_TREVOR                      1381
#define TRAINER_SAILOR_LEONARD                     1382
#define TRAINER_SAILOR_DUNCAN                      1383
// Renomeado em 05/08/2026: colidia com TRAINER_SAILOR_HUEY do opponents.h, que
// vale 1349 e e o Huey do Farol de Olivine, o unico dos dois com time de
// verdade em trainers.party. Como o de la vencia a redefinicao, o marinheiro do
// S.S. Anne, em Kanto, lutava com o time do marinheiro de Johto.
// Como TODO nome deste arquivo, este e um APELIDO para o treinador que ja ocupa
// esse id (48 = TRAINER_DUSTY_3, de Hoenn), nao um treinador proprio. Ver o
// modo --treinadores do dev_scripts/testa_critico.py.
#define TRAINER_SAILOR_HUEY_FRLG                   1384
#define TRAINER_SAILOR_DYLAN                       1385
#define TRAINER_SAILOR_PHILLIP                     1386
#define TRAINER_SAILOR_DWAYNE                      1387
#define TRAINER_CAMPER_LIAM                        1388
#define TRAINER_CAMPER_SHANE                       1633
#define TRAINER_CAMPER_ETHAN                       1634
#define TRAINER_CAMPER_RICKY                       1646
#define TRAINER_CAMPER_JEFF                        1647
#define TRAINER_CAMPER_CHRIS                       1662
#define TRAINER_CAMPER_DREW                        1663
#define TRAINER_PICNICKER_DIANA                    1389
#define TRAINER_PICNICKER_NANCY                    1648
#define TRAINER_PICNICKER_ISABELLE                 1649
#define TRAINER_PICNICKER_KELSEY                   1638
#define TRAINER_PICNICKER_ALICIA                   1664
#define TRAINER_PICNICKER_CAITLIN                  1665
#define TRAINER_PICNICKER_HEIDI                    1669
#define TRAINER_PICNICKER_CAROL                    1670
#define TRAINER_PICNICKER_SOFIA                    1390
#define TRAINER_PICNICKER_MARTHA                   1391
#define TRAINER_PICNICKER_TINA                     1392
#define TRAINER_PICNICKER_HANNAH                   70
#define TRAINER_POKEMANIAC_MARK                    1671
#define TRAINER_POKEMANIAC_HERMAN                  1672
#define TRAINER_POKEMANIAC_COOPER                  1393
#define TRAINER_POKEMANIAC_STEVE                   1394
#define TRAINER_POKEMANIAC_WINSTON                 1395
#define TRAINER_POKEMANIAC_DAWSON                  1396
#define TRAINER_POKEMANIAC_ASHTON                  1397
#define TRAINER_SUPER_NERD_JOVAN                   1398
#define TRAINER_SUPER_NERD_MIGUEL                  1399
#define TRAINER_SUPER_NERD_AIDAN                   1679
#define TRAINER_SUPER_NERD_GLENN                   1680
#define TRAINER_SUPER_NERD_LESLIE                  1681
#define TRAINER_SUPER_NERD_ERIK                    1400
#define TRAINER_SUPER_NERD_AVERY                   1401
#define TRAINER_SUPER_NERD_DEREK                   1402
#define TRAINER_SUPER_NERD_ZAC                     1403
#define TRAINER_HIKER_MARCOS                       1404
#define TRAINER_HIKER_FRANKLIN                     1640
#define TRAINER_HIKER_NOB                          1641
#define TRAINER_HIKER_WAYNE                        1642
#define TRAINER_HIKER_ALAN                         1666
#define TRAINER_HIKER_BRICE                        1667
#define TRAINER_HIKER_CLARK                        1673
#define TRAINER_HIKER_TRENT                        1674
#define TRAINER_HIKER_DUDLEY                       1405
#define TRAINER_HIKER_ALLEN                        1406
#define TRAINER_HIKER_ERIC                         1407
#define TRAINER_HIKER_LENNY                        1408
#define TRAINER_HIKER_OLIVER                       1409
#define TRAINER_HIKER_LUCAS                        1410
#define TRAINER_BIKER_JARED                        1695
#define TRAINER_BIKER_MALIK                        1705
#define TRAINER_BIKER_ERNEST                       1716
#define TRAINER_BIKER_ALEX                         1717
#define TRAINER_BIKER_LAO                          1727
#define TRAINER_BIKER_HIDEO                        1728
#define TRAINER_BIKER_RUBEN                        1729
#define TRAINER_BIKER_BILLY                        1734
#define TRAINER_BIKER_NIKOLAS                      1735
#define TRAINER_BIKER_JAXON                        1736
#define TRAINER_BIKER_WILLIAM                      1737
#define TRAINER_BIKER_LUKAS                        1706
#define TRAINER_BIKER_ISAAC                        1707
#define TRAINER_BIKER_GERALD                       1708
#define TRAINER_BURGLAR_QUINN                      1411
#define TRAINER_BURGLAR_RAMON                      1412
#define TRAINER_BURGLAR_DUSTY                      1413
#define TRAINER_BURGLAR_ARNIE                      1414
#define TRAINER_BURGLAR_SIMON                      1415
#define TRAINER_BURGLAR_LEWIS                      1416
#define TRAINER_ENGINEER_BAILY                     1417
#define TRAINER_ENGINEER_BRAXTON                   1654
#define TRAINER_ENGINEER_BERNIE                    1655
#define TRAINER_FISHERMAN_DALE                     1418
#define TRAINER_FISHERMAN_BARNY                    1419
#define TRAINER_FISHERMAN_NED                      1687
#define TRAINER_FISHERMAN_CHIP                     1688
#define TRAINER_FISHERMAN_HANK                     1689
#define TRAINER_FISHERMAN_ELLIOT                   1690
#define TRAINER_FISHERMAN_RONALD                   1768
#define TRAINER_FISHERMAN_CLAUDE                   1769
#define TRAINER_FISHERMAN_WADE                     1770
#define TRAINER_FISHERMAN_NOLAN                    1771
#define TRAINER_FISHERMAN_ANDREW                   1691
#define TRAINER_SWIMMER_MALE_LUIS                  1420
#define TRAINER_SWIMMER_MALE_RICHARD               1747
#define TRAINER_SWIMMER_MALE_REECE                 1748
#define TRAINER_SWIMMER_MALE_MATTHEW               1749
#define TRAINER_SWIMMER_MALE_DOUGLAS               1750
#define TRAINER_SWIMMER_MALE_DAVID                 1751
#define TRAINER_SWIMMER_MALE_TONY                  1752
#define TRAINER_SWIMMER_MALE_AXLE                  1753
#define TRAINER_SWIMMER_MALE_BARRY                 1758
#define TRAINER_SWIMMER_MALE_DEAN                  1759
#define TRAINER_SWIMMER_MALE_DARRIN                1760
#define TRAINER_SWIMMER_MALE_SPENCER               1772
#define TRAINER_SWIMMER_MALE_JACK                  1773
#define TRAINER_SWIMMER_MALE_JEROME                1774
#define TRAINER_SWIMMER_MALE_ROLAND                1775
#define TRAINER_CUE_BALL_KOJI                      1730
#define TRAINER_CUE_BALL_LUKE                      1731
#define TRAINER_CUE_BALL_CAMRON                    1732
#define TRAINER_CUE_BALL_RAUL                      1738
#define TRAINER_CUE_BALL_ISAIAH                    1739
#define TRAINER_CUE_BALL_ZEEK                      1740
#define TRAINER_CUE_BALL_JAMAL                     1741
#define TRAINER_CUE_BALL_COREY                     1742
#define TRAINER_CUE_BALL_CHASE                     158
#define TRAINER_GAMER_HUGO                         1656
#define TRAINER_GAMER_JASPER                       1657
#define TRAINER_GAMER_DIRK                         1658
#define TRAINER_GAMER_DARIAN                       1659
#define TRAINER_GAMER_STAN                         1682
#define TRAINER_GAMER_RICH                         1683
#define TRAINER_BEAUTY_BRIDGET                     1421
#define TRAINER_BEAUTY_TAMIA                       1422
#define TRAINER_BEAUTY_LORI                        1423
#define TRAINER_BEAUTY_LOLA                        1696
#define TRAINER_BEAUTY_SHEILA                      1697
#define TRAINER_SWIMMER_FEMALE_TIFFANY             1761
#define TRAINER_SWIMMER_FEMALE_NORA                1762
#define TRAINER_SWIMMER_FEMALE_MELISSA             1763
#define TRAINER_BEAUTY_GRACE                       1718
#define TRAINER_BEAUTY_OLIVIA                      1719
#define TRAINER_BEAUTY_LAUREN                      175
#define TRAINER_SWIMMER_FEMALE_ANYA                1754
#define TRAINER_SWIMMER_FEMALE_ALICE               1755
#define TRAINER_SWIMMER_FEMALE_CONNIE              1756
#define TRAINER_SWIMMER_FEMALE_SHIRLEY             1764
#define TRAINER_PSYCHIC_JOHAN                      1424
#define TRAINER_PSYCHIC_TYRON                      1425
#define TRAINER_PSYCHIC_CAMERON                    1426
#define TRAINER_PSYCHIC_PRESTON                    1427
#define TRAINER_ROCKER_RANDALL                     184
#define TRAINER_ROCKER_LUCA                        1692
#define TRAINER_JUGGLER_DALTON                     1428
#define TRAINER_JUGGLER_NELSON                     1429
#define TRAINER_JUGGLER_KIRK                       1430
#define TRAINER_JUGGLER_SHAWN                      1431
#define TRAINER_JUGGLER_GREGORY                    1432
#define TRAINER_JUGGLER_EDWARD                     1813
#define TRAINER_JUGGLER_KAYDEN                     1433
#define TRAINER_JUGGLER_NATE                       1434
#define TRAINER_TAMER_PHIL                         1435
#define TRAINER_TAMER_EDGAR                        1436
#define TRAINER_TAMER_JASON                        1437
#define TRAINER_TAMER_COLE                         1438
#define TRAINER_TAMER_VINCENT                      1439
#define TRAINER_TAMER_JOHN                         199
#define TRAINER_BIRD_KEEPER_SEBASTIAN              1698
#define TRAINER_BIRD_KEEPER_PERRY                  1699
#define TRAINER_BIRD_KEEPER_ROBERT                 1700
#define TRAINER_BIRD_KEEPER_DONALD                 1709
#define TRAINER_BIRD_KEEPER_BENNY                  1710
#define TRAINER_BIRD_KEEPER_EDWIN                  1720
#define TRAINER_BIRD_KEEPER_CHESTER                1721
#define TRAINER_BIRD_KEEPER_WILTON                 1744
#define TRAINER_BIRD_KEEPER_RAMIRO                 1745
#define TRAINER_BIRD_KEEPER_JACOB                  1746
#define TRAINER_BIRD_KEEPER_ROGER                  1765
#define TRAINER_BIRD_KEEPER_REED                   211
#define TRAINER_BIRD_KEEPER_KEITH                  212
#define TRAINER_BIRD_KEEPER_CARTER                 1711
#define TRAINER_BIRD_KEEPER_MITCH                  1712
#define TRAINER_BIRD_KEEPER_BECK                   1713
#define TRAINER_BIRD_KEEPER_MARLON                 1714
#define TRAINER_BLACK_BELT_KOICHI                  1440
#define TRAINER_BLACK_BELT_MIKE                    1441
#define TRAINER_BLACK_BELT_HIDEKI                  1442
#define TRAINER_BLACK_BELT_AARON                   1443
#define TRAINER_BLACK_BELT_HITOSHI                 1444
#define TRAINER_BLACK_BELT_ATSUSHI                 1445
#define TRAINER_BLACK_BELT_KIYO                    1446
#define TRAINER_BLACK_BELT_TAKASHI                 1447
#define TRAINER_BLACK_BELT_DAISUKE                 1448
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE            1449
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR           1450
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER          1451
#define TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE       1452
#define TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR      1453
#define TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER     1454
#define TRAINER_RIVAL_CERULEAN_SQUIRTLE            1455
#define TRAINER_RIVAL_CERULEAN_BULBASAUR           1456
#define TRAINER_RIVAL_CERULEAN_CHARMANDER          1457
#define TRAINER_SCIENTIST_TED                      1458
#define TRAINER_SCIENTIST_CONNOR                   1459
#define TRAINER_SCIENTIST_JERRY                    1460
#define TRAINER_SCIENTIST_JOSE                     1461
#define TRAINER_SCIENTIST_RODNEY                   1462
#define TRAINER_SCIENTIST_BEAU                     1463
#define TRAINER_SCIENTIST_TAYLOR                   1464
#define TRAINER_SCIENTIST_JOSHUA                   1465
#define TRAINER_SCIENTIST_PARKER                   1466
#define TRAINER_SCIENTIST_ED                       1467
#define TRAINER_SCIENTIST_TRAVIS                   1468
#define TRAINER_SCIENTIST_BRAYDON                  1469
#define TRAINER_SCIENTIST_IVAN                     1470
#define TRAINER_BOSS_GIOVANNI                      1471
#define TRAINER_BOSS_GIOVANNI_2                    1472
#define TRAINER_LEADER_GIOVANNI                    1473
#define TRAINER_TEAM_ROCKET_GRUNT                  1474
#define TRAINER_TEAM_ROCKET_GRUNT_2                1475
#define TRAINER_TEAM_ROCKET_GRUNT_3                1476
#define TRAINER_TEAM_ROCKET_GRUNT_4                1477
#define TRAINER_TEAM_ROCKET_GRUNT_5                1478
#define TRAINER_TEAM_ROCKET_GRUNT_6                1479
#define TRAINER_TEAM_ROCKET_GRUNT_7                1480
#define TRAINER_TEAM_ROCKET_GRUNT_8                1481
#define TRAINER_TEAM_ROCKET_GRUNT_9                1482
#define TRAINER_TEAM_ROCKET_GRUNT_10               1483
#define TRAINER_TEAM_ROCKET_GRUNT_11               1484
#define TRAINER_TEAM_ROCKET_GRUNT_12               1485
#define TRAINER_TEAM_ROCKET_GRUNT_13               1486
#define TRAINER_TEAM_ROCKET_GRUNT_14               1487
#define TRAINER_TEAM_ROCKET_GRUNT_15               1488
#define TRAINER_TEAM_ROCKET_GRUNT_16               1489
#define TRAINER_TEAM_ROCKET_GRUNT_17               1490
#define TRAINER_TEAM_ROCKET_GRUNT_18               1491
#define TRAINER_TEAM_ROCKET_GRUNT_19               1492
#define TRAINER_TEAM_ROCKET_GRUNT_20               1493
#define TRAINER_TEAM_ROCKET_GRUNT_21               1494
#define TRAINER_TEAM_ROCKET_GRUNT_22               272
#define TRAINER_TEAM_ROCKET_GRUNT_23               1495
#define TRAINER_TEAM_ROCKET_GRUNT_24               1496
#define TRAINER_TEAM_ROCKET_GRUNT_25               1497
#define TRAINER_TEAM_ROCKET_GRUNT_26               1498
#define TRAINER_TEAM_ROCKET_GRUNT_27               1499
#define TRAINER_TEAM_ROCKET_GRUNT_28               1500
#define TRAINER_TEAM_ROCKET_GRUNT_29               1501
#define TRAINER_TEAM_ROCKET_GRUNT_30               1502
#define TRAINER_TEAM_ROCKET_GRUNT_31               1503
#define TRAINER_TEAM_ROCKET_GRUNT_32               1504
#define TRAINER_TEAM_ROCKET_GRUNT_33               1505
#define TRAINER_TEAM_ROCKET_GRUNT_34               1506
#define TRAINER_TEAM_ROCKET_GRUNT_35               1507
#define TRAINER_TEAM_ROCKET_GRUNT_36               1508
#define TRAINER_TEAM_ROCKET_GRUNT_37               1509
#define TRAINER_TEAM_ROCKET_GRUNT_38               1510
#define TRAINER_TEAM_ROCKET_GRUNT_39               1511
#define TRAINER_TEAM_ROCKET_GRUNT_40               1512
#define TRAINER_TEAM_ROCKET_GRUNT_41               1513
#define TRAINER_COOLTRAINER_SAMUEL                 1514
#define TRAINER_COOLTRAINER_GEORGE                 1515
#define TRAINER_COOLTRAINER_COLBY                  1516
#define TRAINER_COOLTRAINER_PAUL                   295
#define TRAINER_COOLTRAINER_ROLANDO                1517
#define TRAINER_COOLTRAINER_GILBERT                297
#define TRAINER_COOLTRAINER_OWEN                   298
#define TRAINER_COOLTRAINER_BERKE                  299
#define TRAINER_COOLTRAINER_YUJI                   1518
#define TRAINER_COOLTRAINER_WARREN                 1519
#define TRAINER_COOLTRAINER_MARY                   1520
#define TRAINER_COOLTRAINER_CAROLINE               1521
#define TRAINER_COOLTRAINER_ALEXA                  1522
#define TRAINER_COOLTRAINER_SHANNON                305
#define TRAINER_COOLTRAINER_NAOMI                  1523
#define TRAINER_COOLTRAINER_BROOKE                 307
#define TRAINER_COOLTRAINER_AUSTINA                308
#define TRAINER_COOLTRAINER_JULIE                  309
#define TRAINER_ELITE_FOUR_LORELEI                 1524
#define TRAINER_ELITE_FOUR_BRUNO                   1525
#define TRAINER_ELITE_FOUR_AGATHA                  1526
#define TRAINER_ELITE_FOUR_LANCE                   1527
#define TRAINER_LEADER_BROCK                       1528
#define TRAINER_LEADER_MISTY                       1529
#define TRAINER_LEADER_LT_SURGE                    1530
#define TRAINER_LEADER_ERIKA                       1531
#define TRAINER_LEADER_KOGA                        1532
#define TRAINER_LEADER_BLAINE                      1533
#define TRAINER_LEADER_SABRINA                     1534
#define TRAINER_GENTLEMAN_THOMAS                   1535
#define TRAINER_GENTLEMAN_ARTHUR                   1536
#define TRAINER_GENTLEMAN_TUCKER                   1537
#define TRAINER_GENTLEMAN_NORTON                   324
#define TRAINER_GENTLEMAN_WALTER                   325
#define TRAINER_RIVAL_SS_ANNE_SQUIRTLE             1538
#define TRAINER_RIVAL_SS_ANNE_BULBASAUR            1539
#define TRAINER_RIVAL_SS_ANNE_CHARMANDER           1540
#define TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE       1541
#define TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR      1542
#define TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER     1543
#define TRAINER_RIVAL_SILPH_SQUIRTLE               1544
#define TRAINER_RIVAL_SILPH_BULBASAUR              1545
#define TRAINER_RIVAL_SILPH_CHARMANDER             1546
#define TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE        1547
#define TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR       1548
#define TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER      1549
#define TRAINER_CHAMPION_FIRST_SQUIRTLE            1550
#define TRAINER_CHAMPION_FIRST_BULBASAUR           1551
#define TRAINER_CHAMPION_FIRST_CHARMANDER          1552
#define TRAINER_CHANNELER_PATRICIA                 1553
#define TRAINER_CHANNELER_CARLY                    1554
#define TRAINER_CHANNELER_HOPE                     1555
#define TRAINER_CHANNELER_PAULA                    1556
#define TRAINER_CHANNELER_LAUREL                   1557
#define TRAINER_CHANNELER_JODY                     1558
#define TRAINER_CHANNELER_TAMMY                    1559
#define TRAINER_CHANNELER_RUTH                     1560
#define TRAINER_CHANNELER_KARINA                   1561
#define TRAINER_CHANNELER_JANAE                    1562
#define TRAINER_CHANNELER_ANGELICA                 1563
#define TRAINER_CHANNELER_EMILIA                   1564
#define TRAINER_CHANNELER_JENNIFER                 1565
#define TRAINER_CHANNELER_AMANDA                   1566
#define TRAINER_CHANNELER_STACY                    1567
#define TRAINER_CHANNELER_TASHA                    1568
#define TRAINER_HIKER_JEREMY                       1668
#define TRAINER_PICNICKER_ALMA                     1701
#define TRAINER_PICNICKER_SUSIE                    1702
#define TRAINER_PICNICKER_VALERIE                  1703
#define TRAINER_PICNICKER_GWEN                     1704
#define TRAINER_BIKER_VIRGIL                       1743
#define TRAINER_CAMPER_FLINT                       1643
#define TRAINER_PICNICKER_MISSY                    1766
#define TRAINER_PICNICKER_IRENE                    1767
#define TRAINER_PICNICKER_DANA                     1569
#define TRAINER_PICNICKER_ARIANA                   1570
#define TRAINER_PICNICKER_LEAH                     1571
#define TRAINER_CAMPER_JUSTIN                      1693
#define TRAINER_PICNICKER_YAZMIN                   1722
#define TRAINER_PICNICKER_KINDRA                   1723
#define TRAINER_PICNICKER_BECKY                    1724
#define TRAINER_PICNICKER_CELIA                    1725
#define TRAINER_GENTLEMAN_BROOKS                   1572
#define TRAINER_GENTLEMAN_LAMAR                    1573
#define TRAINER_TWINS_ELI_ANNE                     1684
#define TRAINER_COOL_COUPLE_RAY_TYRA               1574
#define TRAINER_YOUNG_COUPLE_GIA_JES               1694
#define TRAINER_TWINS_KIRI_JAN                     1715
#define TRAINER_CRUSH_KIN_RON_MYA                  1726
#define TRAINER_YOUNG_COUPLE_LEA_JED               1733
#define TRAINER_SIS_AND_BRO_LIA_LUC                1757
#define TRAINER_SIS_AND_BRO_LIL_IAN                1776
#define TRAINER_YOUNGSTER_BEN_3                    384
#define TRAINER_YOUNGSTER_BEN_4                    385
#define TRAINER_YOUNGSTER_CHAD_2                   386
#define TRAINER_LASS_RELI_2                        387
#define TRAINER_LASS_RELI_3                        388
#define TRAINER_YOUNGSTER_TIMMY_2                  389
#define TRAINER_YOUNGSTER_TIMMY_3                  390
#define TRAINER_YOUNGSTER_TIMMY_4                  391
#define TRAINER_YOUNGSTER_CHAD_3                   392
#define TRAINER_LASS_JANICE_2                      393
#define TRAINER_LASS_JANICE_3                      394
#define TRAINER_YOUNGSTER_CHAD_4                   395
#define TRAINER_HIKER_FRANKLIN_2                   396
#define TRAINER_PKMN_PROF_PROF_OAK                 397
#define TRAINER_TEAM_ROCKET_GRUNT_42               1575
#define TRAINER_PSYCHIC_JACLYN                     1811
#define TRAINER_CRUSH_GIRL_SHARON                  1782
#define TRAINER_TUBER_AMIRA                        1792
#define TRAINER_PKMN_BREEDER_ALIZE                 1803
#define TRAINER_PKMN_RANGER_NICOLAS                1828
#define TRAINER_PKMN_RANGER_MADELINE               1829
#define TRAINER_AROMA_LADY_NIKKI                   1790
#define TRAINER_RUIN_MANIAC_STANLY                 1818
#define TRAINER_LADY_JACKI                         1799
#define TRAINER_PAINTER_DAISY                      1796
#define TRAINER_BIKER_GOON                         1576
#define TRAINER_BIKER_GOON_2                       1577
#define TRAINER_BIKER_GOON_3                       1578
#define TRAINER_BUG_CATCHER_ANTHONY                1579
#define TRAINER_BUG_CATCHER_CHARLIE                1580
#define TRAINER_TWINS_ELI_ANNE_2                   414
#define TRAINER_YOUNGSTER_JOHNSON                  1581
#define TRAINER_BIKER_RICARDO                      1685
#define TRAINER_BIKER_JAREN                        1686
#define TRAINER_TEAM_ROCKET_GRUNT_43               1582
#define TRAINER_TEAM_ROCKET_GRUNT_44               1583
#define TRAINER_TEAM_ROCKET_GRUNT_45               1584
#define TRAINER_TEAM_ROCKET_GRUNT_46               1585
#define TRAINER_TEAM_ROCKET_GRUNT_47               1586
#define TRAINER_TEAM_ROCKET_GRUNT_48               1587
#define TRAINER_TEAM_ROCKET_ADMIN                  1588
#define TRAINER_TEAM_ROCKET_ADMIN_2                1589
#define TRAINER_SCIENTIST_GIDEON                   1590
#define TRAINER_SWIMMER_FEMALE_AMARA               1789
#define TRAINER_SWIMMER_FEMALE_MARIA               1777
#define TRAINER_SWIMMER_FEMALE_ABIGAIL             1778
#define TRAINER_SWIMMER_MALE_FINN                  1779
#define TRAINER_SWIMMER_MALE_GARRETT               1780
#define TRAINER_FISHERMAN_TOMMY                    1781
#define TRAINER_CRUSH_GIRL_TANYA                   1783
#define TRAINER_BLACK_BELT_SHEA                    1784
#define TRAINER_BLACK_BELT_HUGH                    1785
#define TRAINER_CAMPER_BRYCE                       1786
#define TRAINER_PICNICKER_CLAIRE                   1787
#define TRAINER_CRUSH_KIN_MIK_KIA                  1788
#define TRAINER_AROMA_LADY_VIOLET                  1791
#define TRAINER_TUBER_ALEXIS                       1793
#define TRAINER_TWINS_JOY_MEG                      1795
#define TRAINER_SWIMMER_FEMALE_TISHA               1794
#define TRAINER_PAINTER_CELINA                     1797
#define TRAINER_PAINTER_RAYNA                      1798
#define TRAINER_LADY_GILLIAN                       1800
#define TRAINER_YOUNGSTER_DESTIN                   1801
#define TRAINER_SWIMMER_MALE_TOBY                  1802
#define TRAINER_TEAM_ROCKET_GRUNT_49               1591
#define TRAINER_TEAM_ROCKET_GRUNT_50               1592
#define TRAINER_TEAM_ROCKET_GRUNT_51               1593
#define TRAINER_BIRD_KEEPER_MILO                   1804
#define TRAINER_BIRD_KEEPER_CHAZ                   1805
#define TRAINER_BIRD_KEEPER_HAROLD                 1806
#define TRAINER_FISHERMAN_TYLOR                    1807
#define TRAINER_SWIMMER_MALE_MYMO                  1808
#define TRAINER_SWIMMER_FEMALE_NICOLE              1809
#define TRAINER_SIS_AND_BRO_AVA_GEB                1810
#define TRAINER_AROMA_LADY_ROSE                    1812
#define TRAINER_SWIMMER_MALE_SAMIR                 1814
#define TRAINER_SWIMMER_FEMALE_DENISE              1815
#define TRAINER_TWINS_MIU_MIA                      1816
#define TRAINER_HIKER_EARL                         1817
#define TRAINER_RUIN_MANIAC_FOSTER                 1819
#define TRAINER_RUIN_MANIAC_LARRY                  1820
#define TRAINER_HIKER_DARYL                        1821
#define TRAINER_POKEMANIAC_HECTOR                  1822
#define TRAINER_PSYCHIC_DARIO                      1823
#define TRAINER_PSYCHIC_RODETTE                    1824
#define TRAINER_AROMA_LADY_MIAH                    1825
#define TRAINER_YOUNG_COUPLE_EVE_JON               1826
#define TRAINER_JUGGLER_MASON                      1827
#define TRAINER_CRUSH_GIRL_CYNDY                   1830
#define TRAINER_CRUSH_GIRL_JOCELYN                 1594
#define TRAINER_TAMER_EVAN                         1831
#define TRAINER_POKEMANIAC_MARK_2                  475
#define TRAINER_PKMN_RANGER_LOGAN                  1595
#define TRAINER_PKMN_RANGER_JACKSON                1832
#define TRAINER_PKMN_RANGER_BETH                   1596
#define TRAINER_PKMN_RANGER_KATELYN                1833
#define TRAINER_COOLTRAINER_LEROY                  1834
#define TRAINER_COOLTRAINER_MICHELLE               1835
#define TRAINER_COOL_COUPLE_LEX_NYA                1836
#define TRAINER_RUIN_MANIAC_BRANDON                1837
#define TRAINER_RUIN_MANIAC_BENJAMIN               1838
#define TRAINER_PAINTER_EDNA                       1839
#define TRAINER_GENTLEMAN_CLIFFORD                 1840
#define TRAINER_LADY_SELPHY                        1597
#define TRAINER_RUIN_MANIAC_LAWSON                 1598
#define TRAINER_PSYCHIC_LAURA                      1599
#define TRAINER_PKMN_BREEDER_BETHANY               1600
#define TRAINER_PKMN_BREEDER_ALLISON               1601
#define TRAINER_BUG_CATCHER_GARRET                 1602
#define TRAINER_BUG_CATCHER_JONAH                  1603
#define TRAINER_BUG_CATCHER_VANCE                  1604
#define TRAINER_YOUNGSTER_NASH                     1605
#define TRAINER_YOUNGSTER_CORDELL                  1606
#define TRAINER_LASS_DALIA                         1607
#define TRAINER_LASS_JOANA                         1608
#define TRAINER_CAMPER_RILEY                       1609
#define TRAINER_PICNICKER_MARCY                    1610
#define TRAINER_RUIN_MANIAC_LAYTON                 1611
#define TRAINER_PICNICKER_KELSEY_2                 502
#define TRAINER_PICNICKER_KELSEY_3                 503
#define TRAINER_PICNICKER_KELSEY_4                 504
#define TRAINER_CAMPER_RICKY_2                     505
#define TRAINER_CAMPER_RICKY_3                     506
#define TRAINER_CAMPER_RICKY_4                     507
#define TRAINER_CAMPER_JEFF_2                      508
#define TRAINER_CAMPER_JEFF_3                      509
#define TRAINER_CAMPER_JEFF_4                      510
#define TRAINER_PICNICKER_ISABELLE_2               511
#define TRAINER_PICNICKER_ISABELLE_3               512
#define TRAINER_PICNICKER_ISABELLE_4               513
#define TRAINER_YOUNGSTER_YASU_2                   514
#define TRAINER_YOUNGSTER_YASU_3                   515
#define TRAINER_ENGINEER_BERNIE_2                  516
#define TRAINER_GAMER_DARIAN_2                     517
#define TRAINER_CAMPER_CHRIS_2                     518
#define TRAINER_CAMPER_CHRIS_3                     519
#define TRAINER_CAMPER_CHRIS_4                     520
#define TRAINER_PICNICKER_ALICIA_2                 521
#define TRAINER_PICNICKER_ALICIA_3                 522
#define TRAINER_PICNICKER_ALICIA_4                 523
#define TRAINER_HIKER_JEREMY_2                     524
#define TRAINER_POKEMANIAC_MARK_3                  525
#define TRAINER_POKEMANIAC_HERMAN_2                526
#define TRAINER_POKEMANIAC_HERMAN_3                527
#define TRAINER_HIKER_TRENT_2                      528
#define TRAINER_LASS_MEGAN_2                       529
#define TRAINER_LASS_MEGAN_3                       530
#define TRAINER_SUPER_NERD_GLENN_2                 531
#define TRAINER_GAMER_RICH_2                       532
#define TRAINER_BIKER_JAREN_2                      533
#define TRAINER_FISHERMAN_ELLIOT_2                 534
#define TRAINER_ROCKER_LUCA_2                      535
#define TRAINER_BEAUTY_SHEILA_2                    536
#define TRAINER_BIRD_KEEPER_ROBERT_2               537
#define TRAINER_BIRD_KEEPER_ROBERT_3               538
#define TRAINER_PICNICKER_SUSIE_2                  539
#define TRAINER_PICNICKER_SUSIE_3                  540
#define TRAINER_PICNICKER_SUSIE_4                  541
#define TRAINER_BIKER_LUKAS_2                      542
#define TRAINER_BIRD_KEEPER_BENNY_2                543
#define TRAINER_BIRD_KEEPER_BENNY_3                544
#define TRAINER_BIRD_KEEPER_MARLON_2               545
#define TRAINER_BIRD_KEEPER_MARLON_3               546
#define TRAINER_BEAUTY_GRACE_2                     547
#define TRAINER_BIRD_KEEPER_CHESTER_2              548
#define TRAINER_BIRD_KEEPER_CHESTER_3              549
#define TRAINER_PICNICKER_BECKY_2                  550
#define TRAINER_PICNICKER_BECKY_3                  551
#define TRAINER_PICNICKER_BECKY_4                  552
#define TRAINER_CRUSH_KIN_RON_MYA_2                553
#define TRAINER_CRUSH_KIN_RON_MYA_3                554
#define TRAINER_CRUSH_KIN_RON_MYA_4                555
#define TRAINER_BIKER_RUBEN_2                      556
#define TRAINER_CUE_BALL_CAMRON_2                  557
#define TRAINER_BIKER_JAXON_2                      558
#define TRAINER_CUE_BALL_ISAIAH_2                  559
#define TRAINER_CUE_BALL_COREY_2                   560
#define TRAINER_BIRD_KEEPER_JACOB_2                561
#define TRAINER_BIRD_KEEPER_JACOB_3                562
#define TRAINER_SWIMMER_FEMALE_ALICE_2             563
#define TRAINER_SWIMMER_MALE_DARRIN_2              564
#define TRAINER_PICNICKER_MISSY_2                  565
#define TRAINER_PICNICKER_MISSY_3                  566
#define TRAINER_FISHERMAN_WADE_2                   567
#define TRAINER_SWIMMER_MALE_JACK_2                568
#define TRAINER_SIS_AND_BRO_LIL_IAN_2              569
#define TRAINER_SIS_AND_BRO_LIL_IAN_3              570
#define TRAINER_SWIMMER_MALE_FINN_2                571
#define TRAINER_CRUSH_GIRL_SHARON_2                572
#define TRAINER_CRUSH_GIRL_SHARON_3                573
#define TRAINER_CRUSH_GIRL_TANYA_2                 574
#define TRAINER_CRUSH_GIRL_TANYA_3                 575
#define TRAINER_BLACK_BELT_SHEA_2                  576
#define TRAINER_BLACK_BELT_SHEA_3                  577
#define TRAINER_BLACK_BELT_HUGH_2                  578
#define TRAINER_BLACK_BELT_HUGH_3                  579
#define TRAINER_CRUSH_KIN_MIK_KIA_2                580
#define TRAINER_CRUSH_KIN_MIK_KIA_3                581
#define TRAINER_TUBER_AMIRA_2                      582
#define TRAINER_TWINS_JOY_MEG_2                    583
#define TRAINER_PAINTER_RAYNA_2                    584
#define TRAINER_YOUNGSTER_DESTIN_2                 585
#define TRAINER_PKMN_BREEDER_ALIZE_2               586
#define TRAINER_YOUNG_COUPLE_GIA_JES_2             587
#define TRAINER_YOUNG_COUPLE_GIA_JES_3             588
#define TRAINER_BIRD_KEEPER_MILO_2                 589
#define TRAINER_BIRD_KEEPER_CHAZ_2                 590
#define TRAINER_BIRD_KEEPER_HAROLD_2               591
#define TRAINER_SWIMMER_FEMALE_NICOLE_2            592
#define TRAINER_PSYCHIC_JACLYN_2                   593
#define TRAINER_SWIMMER_MALE_SAMIR_2               594
#define TRAINER_HIKER_EARL_2                       595
#define TRAINER_RUIN_MANIAC_LARRY_2                596
#define TRAINER_POKEMANIAC_HECTOR_2                597
#define TRAINER_PSYCHIC_DARIO_2                    598
#define TRAINER_PSYCHIC_RODETTE_2                  599
#define TRAINER_JUGGLER_MASON_2                    600
#define TRAINER_PKMN_RANGER_NICOLAS_2              601
#define TRAINER_PKMN_RANGER_MADELINE_2             602
#define TRAINER_CRUSH_GIRL_CYNDY_2                 603
#define TRAINER_TAMER_EVAN_2                       604
#define TRAINER_PKMN_RANGER_JACKSON_2              605
#define TRAINER_PKMN_RANGER_KATELYN_2              606
#define TRAINER_COOLTRAINER_LEROY_2                607
#define TRAINER_COOLTRAINER_MICHELLE_2             608
#define TRAINER_COOL_COUPLE_LEX_NYA_2              609
#define TRAINER_BUG_CATCHER_COLTON_2               610
#define TRAINER_BUG_CATCHER_COLTON_3               611
#define TRAINER_BUG_CATCHER_COLTON_4               612
#define TRAINER_SWIMMER_MALE_MATTHEW_2             613
#define TRAINER_SWIMMER_MALE_TONY_2                614
#define TRAINER_SWIMMER_FEMALE_MELISSA_2           615
#define TRAINER_ELITE_FOUR_LORELEI_2               1612
#define TRAINER_ELITE_FOUR_BRUNO_2                 1613
#define TRAINER_ELITE_FOUR_AGATHA_2                1614
#define TRAINER_ELITE_FOUR_LANCE_2                 1615
#define TRAINER_CHAMPION_REMATCH_SQUIRTLE          1616
#define TRAINER_CHAMPION_REMATCH_BULBASAUR         1617
#define TRAINER_CHAMPION_REMATCH_CHARMANDER        1618
#define TRAINER_CUE_BALL_PAXTON                    1619
// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is
//       only space for 25 additional trainers before trainer flag space overflows.
//       MAX_TRAINERS_COUNT_FRLG can be increased but will take up additional saveblock space

#define TRAINERS_COUNT_FRLG                      624
#define MAX_TRAINERS_COUNT_FRLG                  768

#endif  // GUARD_CONSTANTS_OPPONENTS_FRLG_H
