#ifndef GUARD_CONSTANTS_OPPONENTS_FRLG_H
#define GUARD_CONSTANTS_OPPONENTS_FRLG_H

#include "constants/battle_partner.h"

#define TRAINER_NONE                               0
#define TRAINER_YOUNGSTER_BEN                      1653
#define TRAINER_YOUNGSTER_CALVIN                   1654
#define TRAINER_YOUNGSTER_JOSH                     1400
#define TRAINER_YOUNGSTER_TIMMY                    1662
#define TRAINER_YOUNGSTER_JOEY                     1668
#define TRAINER_YOUNGSTER_DAN                      1669
#define TRAINER_YOUNGSTER_CHAD                     1670
#define TRAINER_YOUNGSTER_TYLER                    1401
#define TRAINER_YOUNGSTER_EDDIE                    1683
#define TRAINER_YOUNGSTER_DILLON                   1684
#define TRAINER_YOUNGSTER_YASU                     1685
#define TRAINER_YOUNGSTER_DAVE                     1686
#define TRAINER_YOUNGSTER_BEN_2                    13
#define TRAINER_BUG_CATCHER_RICK                   1402
#define TRAINER_BUG_CATCHER_DOUG                   1403
#define TRAINER_BUG_CATCHER_SAMMY                  1404
#define TRAINER_BUG_CATCHER_COLTON                 1655
#define TRAINER_BUG_CATCHER_GREG                   1656
#define TRAINER_BUG_CATCHER_JAMES                  1657
#define TRAINER_BUG_CATCHER_KENT                   1405
#define TRAINER_BUG_CATCHER_ROBBY                  1406
#define TRAINER_BUG_CATCHER_CALE                   1663
#define TRAINER_BUG_CATCHER_KEIGO                  1677
#define TRAINER_BUG_CATCHER_ELIJAH                 1678
#define TRAINER_BUG_CATCHER_BRENT                  1693
#define TRAINER_BUG_CATCHER_CONNER                 1694
#define TRAINER_LASS_JANICE                        1658
#define TRAINER_LASS_SALLY                         1659
#define TRAINER_LASS_ROBIN                         1660
#define TRAINER_LASS_CRISSY                        1661
#define TRAINER_LASS_MIRIAM                        1407
#define TRAINER_LASS_IRIS                          1408
#define TRAINER_LASS_RELI                          1664
#define TRAINER_LASS_ALI                           1665
#define TRAINER_LASS_HALEY                         1672
#define TRAINER_LASS_ANN                           1409
#define TRAINER_LASS_DAWN                          1410
#define TRAINER_LASS_PAIGE                         1708
#define TRAINER_LASS_ANDREA                        1709
#define TRAINER_LASS_MEGAN                         1710
#define TRAINER_LASS_JULIA                         1711
#define TRAINER_LASS_KAY                           1411
#define TRAINER_LASS_LISA                          1412
#define TRAINER_SAILOR_EDMOND                      1413
#define TRAINER_SAILOR_TREVOR                      1414
#define TRAINER_SAILOR_LEONARD                     1415
#define TRAINER_SAILOR_DUNCAN                      1416
// Renomeado em 05/08/2026: colidia com TRAINER_SAILOR_HUEY do opponents.h, que
// vale 1349 e e o Huey do Farol de Olivine, o unico dos dois com time de
// verdade em trainers.party. Como o de la vencia a redefinicao, o marinheiro do
// S.S. Anne, em Kanto, lutava com o time do marinheiro de Johto.
// Como TODO nome deste arquivo, este e um APELIDO para o treinador que ja ocupa
// esse id (48 = TRAINER_DUSTY_3, de Hoenn), nao um treinador proprio. Ver o
// modo --treinadores do dev_scripts/testa_critico.py.
#define TRAINER_SAILOR_HUEY_FRLG                   1417
#define TRAINER_SAILOR_DYLAN                       1418
#define TRAINER_SAILOR_PHILLIP                     1419
#define TRAINER_SAILOR_DWAYNE                      1420
#define TRAINER_CAMPER_LIAM                        1421
#define TRAINER_CAMPER_SHANE                       1666
#define TRAINER_CAMPER_ETHAN                       1667
#define TRAINER_CAMPER_RICKY                       1679
#define TRAINER_CAMPER_JEFF                        1680
#define TRAINER_CAMPER_CHRIS                       1695
#define TRAINER_CAMPER_DREW                        1696
#define TRAINER_PICNICKER_DIANA                    1422
#define TRAINER_PICNICKER_NANCY                    1681
#define TRAINER_PICNICKER_ISABELLE                 1682
#define TRAINER_PICNICKER_KELSEY                   1671
#define TRAINER_PICNICKER_ALICIA                   1697
#define TRAINER_PICNICKER_CAITLIN                  1698
#define TRAINER_PICNICKER_HEIDI                    1702
#define TRAINER_PICNICKER_CAROL                    1703
#define TRAINER_PICNICKER_SOFIA                    1423
#define TRAINER_PICNICKER_MARTHA                   1424
#define TRAINER_PICNICKER_TINA                     1425
#define TRAINER_PICNICKER_HANNAH                   70
#define TRAINER_POKEMANIAC_MARK                    1704
#define TRAINER_POKEMANIAC_HERMAN                  1705
#define TRAINER_POKEMANIAC_COOPER                  1426
#define TRAINER_POKEMANIAC_STEVE                   1427
#define TRAINER_POKEMANIAC_WINSTON                 1428
#define TRAINER_POKEMANIAC_DAWSON                  1429
#define TRAINER_POKEMANIAC_ASHTON                  1430
#define TRAINER_SUPER_NERD_JOVAN                   1431
#define TRAINER_SUPER_NERD_MIGUEL                  1432
#define TRAINER_SUPER_NERD_AIDAN                   1712
#define TRAINER_SUPER_NERD_GLENN                   1713
#define TRAINER_SUPER_NERD_LESLIE                  1714
#define TRAINER_SUPER_NERD_ERIK                    1433
#define TRAINER_SUPER_NERD_AVERY                   1434
#define TRAINER_SUPER_NERD_DEREK                   1435
#define TRAINER_SUPER_NERD_ZAC                     1436
#define TRAINER_HIKER_MARCOS                       1437
#define TRAINER_HIKER_FRANKLIN                     1673
#define TRAINER_HIKER_NOB                          1674
#define TRAINER_HIKER_WAYNE                        1675
#define TRAINER_HIKER_ALAN                         1699
#define TRAINER_HIKER_BRICE                        1700
#define TRAINER_HIKER_CLARK                        1706
#define TRAINER_HIKER_TRENT                        1707
#define TRAINER_HIKER_DUDLEY                       1438
#define TRAINER_HIKER_ALLEN                        1439
#define TRAINER_HIKER_ERIC                         1440
#define TRAINER_HIKER_LENNY                        1441
#define TRAINER_HIKER_OLIVER                       1442
#define TRAINER_HIKER_LUCAS                        1443
#define TRAINER_BIKER_JARED                        1728
#define TRAINER_BIKER_MALIK                        1738
#define TRAINER_BIKER_ERNEST                       1749
#define TRAINER_BIKER_ALEX                         1750
#define TRAINER_BIKER_LAO                          1760
#define TRAINER_BIKER_HIDEO                        1761
#define TRAINER_BIKER_RUBEN                        1762
#define TRAINER_BIKER_BILLY                        1767
#define TRAINER_BIKER_NIKOLAS                      1768
#define TRAINER_BIKER_JAXON                        1769
#define TRAINER_BIKER_WILLIAM                      1770
#define TRAINER_BIKER_LUKAS                        1739
#define TRAINER_BIKER_ISAAC                        1740
#define TRAINER_BIKER_GERALD                       1741
#define TRAINER_BURGLAR_QUINN                      1444
#define TRAINER_BURGLAR_RAMON                      1445
#define TRAINER_BURGLAR_DUSTY                      1446
#define TRAINER_BURGLAR_ARNIE                      1447
#define TRAINER_BURGLAR_SIMON                      1448
#define TRAINER_BURGLAR_LEWIS                      1449
#define TRAINER_ENGINEER_BAILY                     1450
#define TRAINER_ENGINEER_BRAXTON                   1687
#define TRAINER_ENGINEER_BERNIE                    1688
#define TRAINER_FISHERMAN_DALE                     1451
#define TRAINER_FISHERMAN_BARNY                    1452
#define TRAINER_FISHERMAN_NED                      1720
#define TRAINER_FISHERMAN_CHIP                     1721
#define TRAINER_FISHERMAN_HANK                     1722
#define TRAINER_FISHERMAN_ELLIOT                   1723
#define TRAINER_FISHERMAN_RONALD                   2201
#define TRAINER_FISHERMAN_CLAUDE                   2202
#define TRAINER_FISHERMAN_WADE                     2203
#define TRAINER_FISHERMAN_NOLAN                    2204
#define TRAINER_FISHERMAN_ANDREW                   1724
#define TRAINER_SWIMMER_MALE_LUIS                  1453
#define TRAINER_SWIMMER_MALE_RICHARD               1780
#define TRAINER_SWIMMER_MALE_REECE                 1781
#define TRAINER_SWIMMER_MALE_MATTHEW               1782
#define TRAINER_SWIMMER_MALE_DOUGLAS               1783
#define TRAINER_SWIMMER_MALE_DAVID                 1784
#define TRAINER_SWIMMER_MALE_TONY                  1785
#define TRAINER_SWIMMER_MALE_AXLE                  1786
#define TRAINER_SWIMMER_MALE_BARRY                 1791
#define TRAINER_SWIMMER_MALE_DEAN                  1792
#define TRAINER_SWIMMER_MALE_DARRIN                1793
#define TRAINER_SWIMMER_MALE_SPENCER               2205
#define TRAINER_SWIMMER_MALE_JACK                  2206
#define TRAINER_SWIMMER_MALE_JEROME                2207
#define TRAINER_SWIMMER_MALE_ROLAND                2208
#define TRAINER_CUE_BALL_KOJI                      1763
#define TRAINER_CUE_BALL_LUKE                      1764
#define TRAINER_CUE_BALL_CAMRON                    1765
#define TRAINER_CUE_BALL_RAUL                      1771
#define TRAINER_CUE_BALL_ISAIAH                    1772
#define TRAINER_CUE_BALL_ZEEK                      1773
#define TRAINER_CUE_BALL_JAMAL                     1774
#define TRAINER_CUE_BALL_COREY                     1775
#define TRAINER_CUE_BALL_CHASE                     158
#define TRAINER_GAMER_HUGO                         1689
#define TRAINER_GAMER_JASPER                       1690
#define TRAINER_GAMER_DIRK                         1691
#define TRAINER_GAMER_DARIAN                       1692
#define TRAINER_GAMER_STAN                         1715
#define TRAINER_GAMER_RICH                         1716
#define TRAINER_BEAUTY_BRIDGET                     1454
#define TRAINER_BEAUTY_TAMIA                       1455
#define TRAINER_BEAUTY_LORI                        1456
#define TRAINER_BEAUTY_LOLA                        1729
#define TRAINER_BEAUTY_SHEILA                      1730
#define TRAINER_SWIMMER_FEMALE_TIFFANY             1794
#define TRAINER_SWIMMER_FEMALE_NORA                1795
#define TRAINER_SWIMMER_FEMALE_MELISSA             1796
#define TRAINER_BEAUTY_GRACE                       1751
#define TRAINER_BEAUTY_OLIVIA                      1752
#define TRAINER_BEAUTY_LAUREN                      175
#define TRAINER_SWIMMER_FEMALE_ANYA                1787
#define TRAINER_SWIMMER_FEMALE_ALICE               1788
#define TRAINER_SWIMMER_FEMALE_CONNIE              1789
#define TRAINER_SWIMMER_FEMALE_SHIRLEY             1797
#define TRAINER_PSYCHIC_JOHAN                      1457
#define TRAINER_PSYCHIC_TYRON                      1458
#define TRAINER_PSYCHIC_CAMERON                    1459
#define TRAINER_PSYCHIC_PRESTON                    1460
#define TRAINER_ROCKER_RANDALL                     184
#define TRAINER_ROCKER_LUCA                        1725
#define TRAINER_JUGGLER_DALTON                     1461
#define TRAINER_JUGGLER_NELSON                     1462
#define TRAINER_JUGGLER_KIRK                       1463
#define TRAINER_JUGGLER_SHAWN                      1464
#define TRAINER_JUGGLER_GREGORY                    1465
#define TRAINER_JUGGLER_EDWARD                     2246
#define TRAINER_JUGGLER_KAYDEN                     1466
#define TRAINER_JUGGLER_NATE                       1467
#define TRAINER_TAMER_PHIL                         1468
#define TRAINER_TAMER_EDGAR                        1469
#define TRAINER_TAMER_JASON                        1470
#define TRAINER_TAMER_COLE                         1471
#define TRAINER_TAMER_VINCENT                      1472
#define TRAINER_TAMER_JOHN                         199
#define TRAINER_BIRD_KEEPER_SEBASTIAN              1731
#define TRAINER_BIRD_KEEPER_PERRY                  1732
#define TRAINER_BIRD_KEEPER_ROBERT                 1733
#define TRAINER_BIRD_KEEPER_DONALD                 1742
#define TRAINER_BIRD_KEEPER_BENNY                  1743
#define TRAINER_BIRD_KEEPER_EDWIN                  1753
#define TRAINER_BIRD_KEEPER_CHESTER                1754
#define TRAINER_BIRD_KEEPER_WILTON                 1777
#define TRAINER_BIRD_KEEPER_RAMIRO                 1778
#define TRAINER_BIRD_KEEPER_JACOB                  1779
#define TRAINER_BIRD_KEEPER_ROGER                  1798
#define TRAINER_BIRD_KEEPER_REED                   211
#define TRAINER_BIRD_KEEPER_KEITH                  212
#define TRAINER_BIRD_KEEPER_CARTER                 1744
#define TRAINER_BIRD_KEEPER_MITCH                  1745
#define TRAINER_BIRD_KEEPER_BECK                   1746
#define TRAINER_BIRD_KEEPER_MARLON                 1747
#define TRAINER_BLACK_BELT_KOICHI                  1473
#define TRAINER_BLACK_BELT_MIKE                    1474
#define TRAINER_BLACK_BELT_HIDEKI                  1475
#define TRAINER_BLACK_BELT_AARON                   1476
#define TRAINER_BLACK_BELT_HITOSHI                 1477
#define TRAINER_BLACK_BELT_ATSUSHI                 1478
#define TRAINER_BLACK_BELT_KIYO                    1479
#define TRAINER_BLACK_BELT_TAKASHI                 1480
#define TRAINER_BLACK_BELT_DAISUKE                 1481
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE            1482
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR           1483
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER          1484
#define TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE       1485
#define TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR      1486
#define TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER     1487
#define TRAINER_RIVAL_CERULEAN_SQUIRTLE            1488
#define TRAINER_RIVAL_CERULEAN_BULBASAUR           1489
#define TRAINER_RIVAL_CERULEAN_CHARMANDER          1490
#define TRAINER_SCIENTIST_TED                      1491
#define TRAINER_SCIENTIST_CONNOR                   1492
#define TRAINER_SCIENTIST_JERRY                    1493
#define TRAINER_SCIENTIST_JOSE                     1494
#define TRAINER_SCIENTIST_RODNEY                   1495
#define TRAINER_SCIENTIST_BEAU                     1496
#define TRAINER_SCIENTIST_TAYLOR                   1497
#define TRAINER_SCIENTIST_JOSHUA                   1498
#define TRAINER_SCIENTIST_PARKER                   1499
#define TRAINER_SCIENTIST_ED                       1500
#define TRAINER_SCIENTIST_TRAVIS                   1501
#define TRAINER_SCIENTIST_BRAYDON                  1502
#define TRAINER_SCIENTIST_IVAN                     1503
#define TRAINER_BOSS_GIOVANNI                      1504
#define TRAINER_BOSS_GIOVANNI_2                    1505
#define TRAINER_LEADER_GIOVANNI                    1506
#define TRAINER_TEAM_ROCKET_GRUNT                  1507
#define TRAINER_TEAM_ROCKET_GRUNT_2                1508
#define TRAINER_TEAM_ROCKET_GRUNT_3                1509
#define TRAINER_TEAM_ROCKET_GRUNT_4                1510
#define TRAINER_TEAM_ROCKET_GRUNT_5                1511
#define TRAINER_TEAM_ROCKET_GRUNT_6                1512
#define TRAINER_TEAM_ROCKET_GRUNT_7                1513
#define TRAINER_TEAM_ROCKET_GRUNT_8                1514
#define TRAINER_TEAM_ROCKET_GRUNT_9                1515
#define TRAINER_TEAM_ROCKET_GRUNT_10               1516
#define TRAINER_TEAM_ROCKET_GRUNT_11               1517
#define TRAINER_TEAM_ROCKET_GRUNT_12               1518
#define TRAINER_TEAM_ROCKET_GRUNT_13               1519
#define TRAINER_TEAM_ROCKET_GRUNT_14               1520
#define TRAINER_TEAM_ROCKET_GRUNT_15               1521
#define TRAINER_TEAM_ROCKET_GRUNT_16               1522
#define TRAINER_TEAM_ROCKET_GRUNT_17               1523
#define TRAINER_TEAM_ROCKET_GRUNT_18               1524
#define TRAINER_TEAM_ROCKET_GRUNT_19               1525
#define TRAINER_TEAM_ROCKET_GRUNT_20               1526
#define TRAINER_TEAM_ROCKET_GRUNT_21               1527
#define TRAINER_TEAM_ROCKET_GRUNT_22               272
#define TRAINER_TEAM_ROCKET_GRUNT_23               1528
#define TRAINER_TEAM_ROCKET_GRUNT_24               1529
#define TRAINER_TEAM_ROCKET_GRUNT_25               1530
#define TRAINER_TEAM_ROCKET_GRUNT_26               1531
#define TRAINER_TEAM_ROCKET_GRUNT_27               1532
#define TRAINER_TEAM_ROCKET_GRUNT_28               1533
#define TRAINER_TEAM_ROCKET_GRUNT_29               1534
#define TRAINER_TEAM_ROCKET_GRUNT_30               1535
#define TRAINER_TEAM_ROCKET_GRUNT_31               1536
#define TRAINER_TEAM_ROCKET_GRUNT_32               1537
#define TRAINER_TEAM_ROCKET_GRUNT_33               1538
#define TRAINER_TEAM_ROCKET_GRUNT_34               1539
#define TRAINER_TEAM_ROCKET_GRUNT_35               1540
#define TRAINER_TEAM_ROCKET_GRUNT_36               1541
#define TRAINER_TEAM_ROCKET_GRUNT_37               1542
#define TRAINER_TEAM_ROCKET_GRUNT_38               1543
#define TRAINER_TEAM_ROCKET_GRUNT_39               1544
#define TRAINER_TEAM_ROCKET_GRUNT_40               1545
#define TRAINER_TEAM_ROCKET_GRUNT_41               1546
#define TRAINER_COOLTRAINER_SAMUEL                 1547
#define TRAINER_COOLTRAINER_GEORGE                 1548
#define TRAINER_COOLTRAINER_COLBY                  1549
#define TRAINER_COOLTRAINER_PAUL                   295
#define TRAINER_COOLTRAINER_ROLANDO                1550
#define TRAINER_COOLTRAINER_GILBERT                297
#define TRAINER_COOLTRAINER_OWEN                   298
#define TRAINER_COOLTRAINER_BERKE                  299
#define TRAINER_COOLTRAINER_YUJI                   1551
#define TRAINER_COOLTRAINER_WARREN                 1552
#define TRAINER_COOLTRAINER_MARY                   1553
#define TRAINER_COOLTRAINER_CAROLINE               1554
#define TRAINER_COOLTRAINER_ALEXA                  1555
#define TRAINER_COOLTRAINER_SHANNON                305
#define TRAINER_COOLTRAINER_NAOMI                  1556
#define TRAINER_COOLTRAINER_BROOKE                 307
#define TRAINER_COOLTRAINER_AUSTINA                308
#define TRAINER_COOLTRAINER_JULIE                  309
#define TRAINER_ELITE_FOUR_LORELEI                 1557
#define TRAINER_ELITE_FOUR_BRUNO                   1558
#define TRAINER_ELITE_FOUR_AGATHA                  1559
#define TRAINER_ELITE_FOUR_LANCE                   1560
#define TRAINER_LEADER_BROCK                       1561
#define TRAINER_LEADER_MISTY                       1562
#define TRAINER_LEADER_LT_SURGE                    1563
#define TRAINER_LEADER_ERIKA                       1564
#define TRAINER_LEADER_KOGA                        1565
#define TRAINER_LEADER_BLAINE                      1566
#define TRAINER_LEADER_SABRINA                     1567
#define TRAINER_GENTLEMAN_THOMAS                   1568
#define TRAINER_GENTLEMAN_ARTHUR                   1569
#define TRAINER_GENTLEMAN_TUCKER                   1570
#define TRAINER_GENTLEMAN_NORTON                   324
#define TRAINER_GENTLEMAN_WALTER                   325
#define TRAINER_RIVAL_SS_ANNE_SQUIRTLE             1571
#define TRAINER_RIVAL_SS_ANNE_BULBASAUR            1572
#define TRAINER_RIVAL_SS_ANNE_CHARMANDER           1573
#define TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE       1574
#define TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR      1575
#define TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER     1576
#define TRAINER_RIVAL_SILPH_SQUIRTLE               1577
#define TRAINER_RIVAL_SILPH_BULBASAUR              1578
#define TRAINER_RIVAL_SILPH_CHARMANDER             1579
#define TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE        1580
#define TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR       1581
#define TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER      1582
#define TRAINER_CHAMPION_FIRST_SQUIRTLE            1583
#define TRAINER_CHAMPION_FIRST_BULBASAUR           1584
#define TRAINER_CHAMPION_FIRST_CHARMANDER          1585
#define TRAINER_CHANNELER_PATRICIA                 1586
#define TRAINER_CHANNELER_CARLY                    1587
#define TRAINER_CHANNELER_HOPE                     1588
#define TRAINER_CHANNELER_PAULA                    1589
#define TRAINER_CHANNELER_LAUREL                   1590
#define TRAINER_CHANNELER_JODY                     1591
#define TRAINER_CHANNELER_TAMMY                    1592
#define TRAINER_CHANNELER_RUTH                     1593
#define TRAINER_CHANNELER_KARINA                   1594
#define TRAINER_CHANNELER_JANAE                    1595
#define TRAINER_CHANNELER_ANGELICA                 1596
#define TRAINER_CHANNELER_EMILIA                   1597
#define TRAINER_CHANNELER_JENNIFER                 1598
#define TRAINER_CHANNELER_AMANDA                   1599
#define TRAINER_CHANNELER_STACY                    1600
#define TRAINER_CHANNELER_TASHA                    1601
#define TRAINER_HIKER_JEREMY                       1701
#define TRAINER_PICNICKER_ALMA                     1734
#define TRAINER_PICNICKER_SUSIE                    1735
#define TRAINER_PICNICKER_VALERIE                  1736
#define TRAINER_PICNICKER_GWEN                     1737
#define TRAINER_BIKER_VIRGIL                       1776
#define TRAINER_CAMPER_FLINT                       1676
#define TRAINER_PICNICKER_MISSY                    1799
#define TRAINER_PICNICKER_IRENE                    2200
#define TRAINER_PICNICKER_DANA                     1602
#define TRAINER_PICNICKER_ARIANA                   1603
#define TRAINER_PICNICKER_LEAH                     1604
#define TRAINER_CAMPER_JUSTIN                      1726
#define TRAINER_PICNICKER_YAZMIN                   1755
#define TRAINER_PICNICKER_KINDRA                   1756
#define TRAINER_PICNICKER_BECKY                    1757
#define TRAINER_PICNICKER_CELIA                    1758
#define TRAINER_GENTLEMAN_BROOKS                   1605
#define TRAINER_GENTLEMAN_LAMAR                    1606
#define TRAINER_TWINS_ELI_ANNE                     1717
#define TRAINER_COOL_COUPLE_RAY_TYRA               1607
#define TRAINER_YOUNG_COUPLE_GIA_JES               1727
#define TRAINER_TWINS_KIRI_JAN                     1748
#define TRAINER_CRUSH_KIN_RON_MYA                  1759
#define TRAINER_YOUNG_COUPLE_LEA_JED               1766
#define TRAINER_SIS_AND_BRO_LIA_LUC                1790
#define TRAINER_SIS_AND_BRO_LIL_IAN                2209
#define TRAINER_YOUNGSTER_BEN_3                    384
#define TRAINER_YOUNGSTER_BEN_4                    385
#define TRAINER_YOUNGSTER_CHAD_2                   386
#define TRAINER_LASS_RELI_2                        387
#define TRAINER_LASS_RELI_3                        388
#define TRAINER_YOUNGSTER_TIMMY_2                  389
#define TRAINER_YOUNGSTER_TIMMY_3                  390
#define TRAINER_YOUNGSTER_TIMMY_4                  391
#define TRAINER_YOUNGSTER_CHAD_3                   392
#define TRAINER_LASS_JANICE_2                      393
#define TRAINER_LASS_JANICE_3                      394
#define TRAINER_YOUNGSTER_CHAD_4                   395
#define TRAINER_HIKER_FRANKLIN_2                   396
#define TRAINER_PKMN_PROF_PROF_OAK                 397
#define TRAINER_TEAM_ROCKET_GRUNT_42               1608
#define TRAINER_PSYCHIC_JACLYN                     2244
#define TRAINER_CRUSH_GIRL_SHARON                  2215
#define TRAINER_TUBER_AMIRA                        2225
#define TRAINER_PKMN_BREEDER_ALIZE                 2236
#define TRAINER_PKMN_RANGER_NICOLAS                2261
#define TRAINER_PKMN_RANGER_MADELINE               2262
#define TRAINER_AROMA_LADY_NIKKI                   2223
#define TRAINER_RUIN_MANIAC_STANLY                 2251
#define TRAINER_LADY_JACKI                         2232
#define TRAINER_PAINTER_DAISY                      2229
#define TRAINER_BIKER_GOON                         1609
#define TRAINER_BIKER_GOON_2                       1610
#define TRAINER_BIKER_GOON_3                       1611
#define TRAINER_BUG_CATCHER_ANTHONY                1612
#define TRAINER_BUG_CATCHER_CHARLIE                1613
#define TRAINER_TWINS_ELI_ANNE_2                   414
#define TRAINER_YOUNGSTER_JOHNSON                  1614
#define TRAINER_BIKER_RICARDO                      1718
#define TRAINER_BIKER_JAREN                        1719
#define TRAINER_TEAM_ROCKET_GRUNT_43               1615
#define TRAINER_TEAM_ROCKET_GRUNT_44               1616
#define TRAINER_TEAM_ROCKET_GRUNT_45               1617
#define TRAINER_TEAM_ROCKET_GRUNT_46               1618
#define TRAINER_TEAM_ROCKET_GRUNT_47               1619
#define TRAINER_TEAM_ROCKET_GRUNT_48               1620
#define TRAINER_TEAM_ROCKET_ADMIN                  1621
#define TRAINER_TEAM_ROCKET_ADMIN_2                1622
#define TRAINER_SCIENTIST_GIDEON                   1623
#define TRAINER_SWIMMER_FEMALE_AMARA               2222
#define TRAINER_SWIMMER_FEMALE_MARIA               2210
#define TRAINER_SWIMMER_FEMALE_ABIGAIL             2211
#define TRAINER_SWIMMER_MALE_FINN                  2212
#define TRAINER_SWIMMER_MALE_GARRETT               2213
#define TRAINER_FISHERMAN_TOMMY                    2214
#define TRAINER_CRUSH_GIRL_TANYA                   2216
#define TRAINER_BLACK_BELT_SHEA                    2217
#define TRAINER_BLACK_BELT_HUGH                    2218
#define TRAINER_CAMPER_BRYCE                       2219
#define TRAINER_PICNICKER_CLAIRE                   2220
#define TRAINER_CRUSH_KIN_MIK_KIA                  2221
#define TRAINER_AROMA_LADY_VIOLET                  2224
#define TRAINER_TUBER_ALEXIS                       2226
#define TRAINER_TWINS_JOY_MEG                      2228
#define TRAINER_SWIMMER_FEMALE_TISHA               2227
#define TRAINER_PAINTER_CELINA                     2230
#define TRAINER_PAINTER_RAYNA                      2231
#define TRAINER_LADY_GILLIAN                       2233
#define TRAINER_YOUNGSTER_DESTIN                   2234
#define TRAINER_SWIMMER_MALE_TOBY                  2235
#define TRAINER_TEAM_ROCKET_GRUNT_49               1624
#define TRAINER_TEAM_ROCKET_GRUNT_50               1625
#define TRAINER_TEAM_ROCKET_GRUNT_51               1626
#define TRAINER_BIRD_KEEPER_MILO                   2237
#define TRAINER_BIRD_KEEPER_CHAZ                   2238
#define TRAINER_BIRD_KEEPER_HAROLD                 2239
#define TRAINER_FISHERMAN_TYLOR                    2240
#define TRAINER_SWIMMER_MALE_MYMO                  2241
#define TRAINER_SWIMMER_FEMALE_NICOLE              2242
#define TRAINER_SIS_AND_BRO_AVA_GEB                2243
#define TRAINER_AROMA_LADY_ROSE                    2245
#define TRAINER_SWIMMER_MALE_SAMIR                 2247
#define TRAINER_SWIMMER_FEMALE_DENISE              2248
#define TRAINER_TWINS_MIU_MIA                      2249
#define TRAINER_HIKER_EARL                         2250
#define TRAINER_RUIN_MANIAC_FOSTER                 2252
#define TRAINER_RUIN_MANIAC_LARRY                  2253
#define TRAINER_HIKER_DARYL                        2254
#define TRAINER_POKEMANIAC_HECTOR                  2255
#define TRAINER_PSYCHIC_DARIO                      2256
#define TRAINER_PSYCHIC_RODETTE                    2257
#define TRAINER_AROMA_LADY_MIAH                    2258
#define TRAINER_YOUNG_COUPLE_EVE_JON               2259
#define TRAINER_JUGGLER_MASON                      2260
#define TRAINER_CRUSH_GIRL_CYNDY                   2263
#define TRAINER_CRUSH_GIRL_JOCELYN                 1627
#define TRAINER_TAMER_EVAN                         2264
#define TRAINER_POKEMANIAC_MARK_2                  475
#define TRAINER_PKMN_RANGER_LOGAN                  1628
#define TRAINER_PKMN_RANGER_JACKSON                2265
#define TRAINER_PKMN_RANGER_BETH                   1629
#define TRAINER_PKMN_RANGER_KATELYN                2266
#define TRAINER_COOLTRAINER_LEROY                  2267
#define TRAINER_COOLTRAINER_MICHELLE               2268
#define TRAINER_COOL_COUPLE_LEX_NYA                2269
#define TRAINER_RUIN_MANIAC_BRANDON                2270
#define TRAINER_RUIN_MANIAC_BENJAMIN               2271
#define TRAINER_PAINTER_EDNA                       2272
#define TRAINER_GENTLEMAN_CLIFFORD                 2273
#define TRAINER_LADY_SELPHY                        1630
#define TRAINER_RUIN_MANIAC_LAWSON                 1631
#define TRAINER_PSYCHIC_LAURA                      1632
#define TRAINER_PKMN_BREEDER_BETHANY               1633
#define TRAINER_PKMN_BREEDER_ALLISON               1634
#define TRAINER_BUG_CATCHER_GARRET                 1635
#define TRAINER_BUG_CATCHER_JONAH                  1636
#define TRAINER_BUG_CATCHER_VANCE                  1637
#define TRAINER_YOUNGSTER_NASH                     1638
#define TRAINER_YOUNGSTER_CORDELL                  1639
#define TRAINER_LASS_DALIA                         1640
#define TRAINER_LASS_JOANA                         1641
#define TRAINER_CAMPER_RILEY                       1642
#define TRAINER_PICNICKER_MARCY                    1643
#define TRAINER_RUIN_MANIAC_LAYTON                 1644
#define TRAINER_PICNICKER_KELSEY_2                 502
#define TRAINER_PICNICKER_KELSEY_3                 503
#define TRAINER_PICNICKER_KELSEY_4                 504
#define TRAINER_CAMPER_RICKY_2                     505
#define TRAINER_CAMPER_RICKY_3                     506
#define TRAINER_CAMPER_RICKY_4                     507
#define TRAINER_CAMPER_JEFF_2                      508
#define TRAINER_CAMPER_JEFF_3                      509
#define TRAINER_CAMPER_JEFF_4                      510
#define TRAINER_PICNICKER_ISABELLE_2               511
#define TRAINER_PICNICKER_ISABELLE_3               512
#define TRAINER_PICNICKER_ISABELLE_4               513
#define TRAINER_YOUNGSTER_YASU_2                   514
#define TRAINER_YOUNGSTER_YASU_3                   515
#define TRAINER_ENGINEER_BERNIE_2                  516
#define TRAINER_GAMER_DARIAN_2                     517
#define TRAINER_CAMPER_CHRIS_2                     518
#define TRAINER_CAMPER_CHRIS_3                     519
#define TRAINER_CAMPER_CHRIS_4                     520
#define TRAINER_PICNICKER_ALICIA_2                 521
#define TRAINER_PICNICKER_ALICIA_3                 522
#define TRAINER_PICNICKER_ALICIA_4                 523
#define TRAINER_HIKER_JEREMY_2                     524
#define TRAINER_POKEMANIAC_MARK_3                  525
#define TRAINER_POKEMANIAC_HERMAN_2                526
#define TRAINER_POKEMANIAC_HERMAN_3                527
#define TRAINER_HIKER_TRENT_2                      528
#define TRAINER_LASS_MEGAN_2                       529
#define TRAINER_LASS_MEGAN_3                       530
#define TRAINER_SUPER_NERD_GLENN_2                 531
#define TRAINER_GAMER_RICH_2                       532
#define TRAINER_BIKER_JAREN_2                      533
#define TRAINER_FISHERMAN_ELLIOT_2                 534
#define TRAINER_ROCKER_LUCA_2                      535
#define TRAINER_BEAUTY_SHEILA_2                    536
#define TRAINER_BIRD_KEEPER_ROBERT_2               537
#define TRAINER_BIRD_KEEPER_ROBERT_3               538
#define TRAINER_PICNICKER_SUSIE_2                  539
#define TRAINER_PICNICKER_SUSIE_3                  540
#define TRAINER_PICNICKER_SUSIE_4                  541
#define TRAINER_BIKER_LUKAS_2                      542
#define TRAINER_BIRD_KEEPER_BENNY_2                543
#define TRAINER_BIRD_KEEPER_BENNY_3                544
#define TRAINER_BIRD_KEEPER_MARLON_2               545
#define TRAINER_BIRD_KEEPER_MARLON_3               546
#define TRAINER_BEAUTY_GRACE_2                     547
#define TRAINER_BIRD_KEEPER_CHESTER_2              548
#define TRAINER_BIRD_KEEPER_CHESTER_3              549
#define TRAINER_PICNICKER_BECKY_2                  550
#define TRAINER_PICNICKER_BECKY_3                  551
#define TRAINER_PICNICKER_BECKY_4                  552
#define TRAINER_CRUSH_KIN_RON_MYA_2                553
#define TRAINER_CRUSH_KIN_RON_MYA_3                554
#define TRAINER_CRUSH_KIN_RON_MYA_4                555
#define TRAINER_BIKER_RUBEN_2                      556
#define TRAINER_CUE_BALL_CAMRON_2                  557
#define TRAINER_BIKER_JAXON_2                      558
#define TRAINER_CUE_BALL_ISAIAH_2                  559
#define TRAINER_CUE_BALL_COREY_2                   560
#define TRAINER_BIRD_KEEPER_JACOB_2                561
#define TRAINER_BIRD_KEEPER_JACOB_3                562
#define TRAINER_SWIMMER_FEMALE_ALICE_2             563
#define TRAINER_SWIMMER_MALE_DARRIN_2              564
#define TRAINER_PICNICKER_MISSY_2                  565
#define TRAINER_PICNICKER_MISSY_3                  566
#define TRAINER_FISHERMAN_WADE_2                   567
#define TRAINER_SWIMMER_MALE_JACK_2                568
#define TRAINER_SIS_AND_BRO_LIL_IAN_2              569
#define TRAINER_SIS_AND_BRO_LIL_IAN_3              570
#define TRAINER_SWIMMER_MALE_FINN_2                571
#define TRAINER_CRUSH_GIRL_SHARON_2                572
#define TRAINER_CRUSH_GIRL_SHARON_3                573
#define TRAINER_CRUSH_GIRL_TANYA_2                 574
#define TRAINER_CRUSH_GIRL_TANYA_3                 575
#define TRAINER_BLACK_BELT_SHEA_2                  576
#define TRAINER_BLACK_BELT_SHEA_3                  577
#define TRAINER_BLACK_BELT_HUGH_2                  578
#define TRAINER_BLACK_BELT_HUGH_3                  579
#define TRAINER_CRUSH_KIN_MIK_KIA_2                580
#define TRAINER_CRUSH_KIN_MIK_KIA_3                581
#define TRAINER_TUBER_AMIRA_2                      582
#define TRAINER_TWINS_JOY_MEG_2                    583
#define TRAINER_PAINTER_RAYNA_2                    584
#define TRAINER_YOUNGSTER_DESTIN_2                 585
#define TRAINER_PKMN_BREEDER_ALIZE_2               586
#define TRAINER_YOUNG_COUPLE_GIA_JES_2             587
#define TRAINER_YOUNG_COUPLE_GIA_JES_3             588
#define TRAINER_BIRD_KEEPER_MILO_2                 589
#define TRAINER_BIRD_KEEPER_CHAZ_2                 590
#define TRAINER_BIRD_KEEPER_HAROLD_2               591
#define TRAINER_SWIMMER_FEMALE_NICOLE_2            592
#define TRAINER_PSYCHIC_JACLYN_2                   593
#define TRAINER_SWIMMER_MALE_SAMIR_2               594
#define TRAINER_HIKER_EARL_2                       595
#define TRAINER_RUIN_MANIAC_LARRY_2                596
#define TRAINER_POKEMANIAC_HECTOR_2                597
#define TRAINER_PSYCHIC_DARIO_2                    598
#define TRAINER_PSYCHIC_RODETTE_2                  599
#define TRAINER_JUGGLER_MASON_2                    600
#define TRAINER_PKMN_RANGER_NICOLAS_2              601
#define TRAINER_PKMN_RANGER_MADELINE_2             602
#define TRAINER_CRUSH_GIRL_CYNDY_2                 603
#define TRAINER_TAMER_EVAN_2                       604
#define TRAINER_PKMN_RANGER_JACKSON_2              605
#define TRAINER_PKMN_RANGER_KATELYN_2              606
#define TRAINER_COOLTRAINER_LEROY_2                607
#define TRAINER_COOLTRAINER_MICHELLE_2             608
#define TRAINER_COOL_COUPLE_LEX_NYA_2              609
#define TRAINER_BUG_CATCHER_COLTON_2               610
#define TRAINER_BUG_CATCHER_COLTON_3               611
#define TRAINER_BUG_CATCHER_COLTON_4               612
#define TRAINER_SWIMMER_MALE_MATTHEW_2             613
#define TRAINER_SWIMMER_MALE_TONY_2                614
#define TRAINER_SWIMMER_FEMALE_MELISSA_2           615
#define TRAINER_ELITE_FOUR_LORELEI_2               1645
#define TRAINER_ELITE_FOUR_BRUNO_2                 1646
#define TRAINER_ELITE_FOUR_AGATHA_2                1647
#define TRAINER_ELITE_FOUR_LANCE_2                 1648
#define TRAINER_CHAMPION_REMATCH_SQUIRTLE          1649
#define TRAINER_CHAMPION_REMATCH_BULBASAUR         1650
#define TRAINER_CHAMPION_REMATCH_CHARMANDER        1651
#define TRAINER_CUE_BALL_PAXTON                    1652
// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is
//       only space for 25 additional trainers before trainer flag space overflows.
//       MAX_TRAINERS_COUNT_FRLG can be increased but will take up additional saveblock space

#define TRAINERS_COUNT_FRLG                      624
#define MAX_TRAINERS_COUNT_FRLG                  768

#endif  // GUARD_CONSTANTS_OPPONENTS_FRLG_H
