JubilifeCity_Flat1_F3_MapScripts::
	.byte 0

JubilifeCity_Flat1_F3_EventScript_Lass::
	msgbox JubilifeCity_Flat1_F3_Text_Lass, MSGBOX_NPC
	end

JubilifeCity_Flat1_F3_EventScript_Collector::
	msgbox JubilifeCity_Flat1_F3_Text_Collector, MSGBOX_NPC
	end

JubilifeCity_Flat1_F3_Text_Lass:
	.string "I just moved in.\p"
	.string "Still figuring out which floor\n"
	.string "is mine!$"

JubilifeCity_Flat1_F3_Text_Collector:
	.string "My collection of vintage POKé\n"
	.string "BALLS takes up half my\l"
	.string "apartment.\p"
	.string "Worth it.$"
