@ VictoryRoadEntranceNorth do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VictoryRoadEntranceNorth_MapScripts::
	.byte 0

Unova_VictoryRoadEntranceNorth_EventScript_Placa0::
	msgbox Unova_VictoryRoadEntranceNorth_Text_VictoryRoadSignText, MSGBOX_SIGN
	end


Unova_VictoryRoadEntranceNorth_Text_VictoryRoadSignText::
	.string "VICTORY ROAD"
	.string "\nahead.$"
