@ Rt3NacreneGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt3NacreneGate_MapScripts::
	.byte 0

Unova_Rt3NacreneGate_EventScript_Npc0::
	msgbox Unova_Rt3NacreneGate_Text_R3NacreneGateOfficerText, MSGBOX_NPC
	end


Unova_Rt3NacreneGate_Text_R3NacreneGateOfficerText::
	.string "Have you been to"
	.string "\nthe DAY CARE on"
	.string "\lROUTE 3?"
	.string "\pIt's a convenient"
	.string "\nplace to leave"
	.string "\lyour POKéMON.$"
