@ RelicCastle1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_RelicCastle1F_MapScripts::
	.byte 0

Unova_RelicCastle1F_EventScript_Npc1::
	msgbox Unova_RelicCastle1F_Text_PsychicMRelicCastle1FSeenText, MSGBOX_NPC
	end


Unova_RelicCastle1F_Text_PsychicMRelicCastle1FSeenText::
	.string "I will use my"
	.string "\nsupernatural power"
	.string "\pto help my POKé-"
	.string "\nMON!$"
