@ RelicCastle1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_RelicCastle1F_MapScripts::
	.byte 0

Unova_RelicCastle1F_EventScript_Lider1::
	trainerbattle_single TRAINER_UNOVA_PSYCHICM_RELIC_CASTLE, Unova_RelicCastle1F_Text_PsychicMRelicCastle1FSeenText, Unova_RelicCastle1F_Text_PsychicMRelicCastle1FBeatenText
	end


Unova_RelicCastle1F_Text_PsychicMRelicCastle1FSeenText::
	.string "I will use my"
	.string "\nsupernatural power"
	.string "\pto help my POKé-"
	.string "\nMON!$"

Unova_RelicCastle1F_Text_PsychicMRelicCastle1FBeatenText::
	.string "Wow! That's"
	.string "\namazing!$"
