BlackthornCity_House1_MapScripts::
	.byte 0

@ NPCs devolvidos do hns por dev_scripts/restaura_npcs_johto.py

BlackthornCity_House1EventScript_Granny::
	msgbox BlackthornCity_House1_Text_Granny, MSGBOX_NPC
	end

BlackthornCity_House1_Text_Granny::
	.string "A clan of trainers who can freely\n"
	.string "command dragons live right here in\l"
	.string "BLACKTHORN.\p"
	.string "As a result, there are many legends\n"
	.string "about dragons in this town.$"
