@ NacreneOutskirtEast do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_NacreneOutskirtEast_MapScripts::
	.byte 0

Unova_NacreneOutskirtEast_EventScript_Npc0::
	msgbox Unova_NacreneOutskirtEast_Text_BlackbeltNacreneSeenText, MSGBOX_NPC
	end

Unova_NacreneOutskirtEast_EventScript_Npc1::
	msgbox Unova_NacreneOutskirtEast_Text_BattleGirlNacreneSeenText, MSGBOX_NPC
	end


Unova_NacreneOutskirtEast_Text_BlackbeltNacreneSeenText::
	.string "I will read your"
	.string "\nmind and predict"
	.string "\lyour every move!$"

Unova_NacreneOutskirtEast_Text_BattleGirlNacreneSeenText::
	.string "Heh, I wonder what"
	.string "\nwould happen if I"
	.string "\phad all my POKéMON"
	.string "\nattack at once?$"
