PastoriaCityObservatoryGate2F_MapScripts::
	.byte 0

PastoriaCityObservatoryGate2F_EventScript_Placa1::
	msgbox PastoriaCityObservatoryGate2F_Text_Placa1, MSGBOX_SIGN
	end

PastoriaCityObservatoryGate2F_Text_Placa1:
	.string "It's a pair of binoculars...\nPut ¥100 in it?$"

PastoriaCityObservatoryGate2F_EventScript_Placa2::
	msgbox PastoriaCityObservatoryGate2F_Text_Placa2, MSGBOX_SIGN
	end

PastoriaCityObservatoryGate2F_Text_Placa2:
	.string "It's a pair of binoculars...\nPut ¥100 in it?$"

PastoriaCityObservatoryGate2F_EventScript_Placa3::
	msgbox PastoriaCityObservatoryGate2F_Text_Placa3, MSGBOX_SIGN
	end

PastoriaCityObservatoryGate2F_Text_Placa3:
	.string "It's a pair of binoculars...\nPut ¥100 in it?$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

PastoriaCityObservatoryGate2F_EventScript_Npc1::
	msgbox PastoriaCityObservatoryGate2F_Text_Npc1, MSGBOX_NPC
	end

PastoriaCityObservatoryGate2F_Text_Npc1:
	.string "Tell me I'm not imagining this...\pThe Great Marsh's Pokémon seem to be\ndifferent from the ones yesterday...$"

PastoriaCityObservatoryGate2F_EventScript_Npc2::
	msgbox PastoriaCityObservatoryGate2F_Text_Npc2, MSGBOX_NPC
	end

PastoriaCityObservatoryGate2F_Text_Npc2:
	.string "Use a pair of binoculars to look out\nover the Great Marsh.\pYou can see what kinds of Pokémon\ncan be caught, and where they are.$"

PastoriaCityObservatoryGate2F_EventScript_Npc3::
	msgbox PastoriaCityObservatoryGate2F_Text_Npc3, MSGBOX_NPC
	end

PastoriaCityObservatoryGate2F_Text_Npc3:
	.string "There are shuttle trains in the\nmarsh called Quick Trams.\pYou should take those if you're going\nto a deeper area in the marsh.$"

PastoriaCityObservatoryGate2F_EventScript_Npc4::
	msgbox PastoriaCityObservatoryGate2F_Text_Npc4, MSGBOX_NPC
	end

PastoriaCityObservatoryGate2F_Text_Npc4:
	.string "When you're walking on the bog,\nyou sometimes sink right in...\pThere's something pretty cool\nabout it, though.\pIf you turn while you're stuck,\nsometimes Pokémon may pop out.$"
