PastoriaCityObservatoryGate2F_MapScripts::
	.byte 0

PastoriaCityObservatoryGate2F_EventScript_Placa1::
	msgbox PastoriaCityObservatoryGate2F_Text_Placa1, MSGBOX_SIGN
	end

PastoriaCityObservatoryGate2F_Text_Placa1:
	.string "It's a pair of binoculars...\nPut $100 in it?$"

PastoriaCityObservatoryGate2F_EventScript_Placa2::
	msgbox PastoriaCityObservatoryGate2F_Text_Placa2, MSGBOX_SIGN
	end

PastoriaCityObservatoryGate2F_Text_Placa2:
	.string "It's a pair of binoculars...\nPut $100 in it?$"

PastoriaCityObservatoryGate2F_EventScript_Placa3::
	msgbox PastoriaCityObservatoryGate2F_Text_Placa3, MSGBOX_SIGN
	end

PastoriaCityObservatoryGate2F_Text_Placa3:
	.string "It's a pair of binoculars...\nPut $100 in it?$"
