@ VerdanturfTown_Ex6_12: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 6.12) por dev_scripts/copia_planta_ex.py.

VerdanturfTown_Ex6_12_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 6.12), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
VerdanturfTown_Ex6_12_EventScript_ExNpc0::
	msgbox VerdanturfTown_Ex6_12_Text_ExNpc0, MSGBOX_NPC
	end

VerdanturfTown_Ex6_12_Text_ExNpc0:
	.string "My kids get up to all kinds of mischief.\p"
	.string "They can be exhausting...$"

VerdanturfTown_Ex6_12_EventScript_ExNpc1::
	msgbox VerdanturfTown_Ex6_12_Text_ExNpc1, MSGBOX_NPC
	end

VerdanturfTown_Ex6_12_Text_ExNpc1:
	.string "I’m playing hide and seek with my\n"
	.string "brother.\p"
	.string "He started hiding days ago...$"

