@ LilycoveCity_Ex13_25: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 13.25) por dev_scripts/copia_planta_ex.py.

LilycoveCity_Ex13_25_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 13.25), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
LilycoveCity_Ex13_25_EventScript_ExNpc0::
	msgbox LilycoveCity_Ex13_25_Text_ExNpc0, MSGBOX_NPC
	end

LilycoveCity_Ex13_25_Text_ExNpc0:
	.string "A cute young couple just moved into the\n"
	.string "house next door.$"

