@ TwistMountainOutside do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_TwistMountainOutside_MapScripts::
	.byte 0

Unova_TwistMountainOutside_EventScript_Npc6::
	msgbox Unova_TwistMountainOutside_Text_NurseTwistMountainOutsideIntroText, MSGBOX_NPC
	end

Unova_TwistMountainOutside_EventScript_Npc7::
	msgbox Unova_TwistMountainOutside_Text_WorkerTwistMountainOutsideSeenText, MSGBOX_NPC
	end

Unova_TwistMountainOutside_EventScript_Npc8::
	msgbox Unova_TwistMountainOutside_Text_HikerTwistMountainOutsideSeenText, MSGBOX_NPC
	end

Unova_TwistMountainOutside_EventScript_Npc9::
	msgbox Unova_TwistMountainOutside_Text_VeteranMTwistMountainOutsideSeenText, MSGBOX_NPC
	end


Unova_TwistMountainOutside_Text_NurseTwistMountainOutsideIntroText::
	.string "I'm a nurse, but"
	.string "\nI'm also a POKé-"
	.string "\lMON trainer."
	.string "\pIf you can defeat"
	.string "\nme in a battle,"
	.string "\lI'll heal your"
	.string "\lPOKéMON.$"

Unova_TwistMountainOutside_Text_WorkerTwistMountainOutsideSeenText::
	.string "I've found a"
	.string "\nstrong looking"
	.string "\ptrainer during my"
	.string "\npatrol! Go, my"
	.string "\lPOKéMON!$"

Unova_TwistMountainOutside_Text_HikerTwistMountainOutsideSeenText::
	.string "Why do I dig? Why"
	.string "\ndo you fight?$"

Unova_TwistMountainOutside_Text_VeteranMTwistMountainOutsideSeenText::
	.string "OK! I will show"
	.string "\nyou the results of"
	.string "\lmy daily workouts!$"
