@ VictoryRoadGrove do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VictoryRoadGrove_MapScripts::
	.byte 0

Unova_VictoryRoadGrove_EventScript_Npc2::
	msgbox Unova_VictoryRoadGrove_Text_AceTrainerMVictoryRoadGroveSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadGrove_EventScript_Npc3::
	msgbox Unova_VictoryRoadGrove_Text_AceTrainerFVictoryRoadGroveSeenText, MSGBOX_NPC
	end


Unova_VictoryRoadGrove_Text_AceTrainerMVictoryRoadGroveSeenText::
	.string "One, you are a"
	.string "\nPOKéMON trainer."
	.string "\pTwo, I am an ACE"
	.string "\nTRAINER. Put them"
	.string "\ptogether, and it's"
	.string "\nobvious that we're"
	.string "\lgoing to battle!$"

Unova_VictoryRoadGrove_Text_AceTrainerFVictoryRoadGroveSeenText::
	.string "I want to show how"
	.string "\nmuch I love POKé-"
	.string "\lMON by winning!$"
