VeilstoneCityNorthwestHouse_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

VeilstoneCityNorthwestHouse_EventScript_Npc1::
	msgbox VeilstoneCityNorthwestHouse_Text_Npc1, MSGBOX_NPC
	end

VeilstoneCityNorthwestHouse_Text_Npc1:
	.string "A myth says that Mt. Coronet parted\nSinnoh into halves.\pSeeing the Pokémon SHELLOS makes me\nthink maybe the myth is real.$"

VeilstoneCityNorthwestHouse_EventScript_Npc2::
	msgbox VeilstoneCityNorthwestHouse_Text_Npc2, MSGBOX_NPC
	end

VeilstoneCityNorthwestHouse_Text_Npc2:
	.string "If there are people who desire to\nsee them, Pokémon will appear in\pmany different guises.$"
