@ WellspringCave1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_WellspringCave1F_MapScripts::
	.byte 0

Unova_WellspringCave1F_EventScript_Npc4::
	msgbox Unova_WellspringCave1F_Text_BlackbeltWellspring1FSeenText, MSGBOX_NPC
	end


Unova_WellspringCave1F_Text_BlackbeltWellspring1FSeenText::
	.string "Travel the uneven"
	.string "\nroad to hone your-"
	.string "\pself! You've got"
	.string "\nto train your gut!$"
