HearthomeCitySoutheastHouse1F_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

HearthomeCitySoutheastHouse1F_EventScript_Npc1::
	msgbox HearthomeCitySoutheastHouse1F_Text_Npc1, MSGBOX_NPC
	end

HearthomeCitySoutheastHouse1F_Text_Npc1:
	.string "There are the Contests!\nThen, we have Amity Square!\pHearthome gets visitors from all over,\nso things have to be nice and clean!$"

HearthomeCitySoutheastHouse1F_EventScript_Npc2::
	msgbox HearthomeCitySoutheastHouse1F_Text_Npc2, MSGBOX_NPC
	end

HearthomeCitySoutheastHouse1F_Text_Npc2:
	.string "People all over the world follow\nPokémon Contests.\pWhat should I do?\nI could captivate the whole world!$"

HearthomeCitySoutheastHouse1F_EventScript_Npc3::
	msgbox HearthomeCitySoutheastHouse1F_Text_Npc3, MSGBOX_NPC
	end

HearthomeCitySoutheastHouse1F_Text_Npc3:
	.string "My SHROOMISH finds Berries and things\nwhen we go to Amity Square.$"
