Route210GrandmaWilmaHouse_MapScripts::
	.byte 0

Route210GrandmaWilmaHouse_EventScript_Npc1::
	msgbox Route210GrandmaWilmaHouse_Text_Npc1, MSGBOX_NPC
	end

Route210GrandmaWilmaHouse_Text_Npc1:
	.string "Hohoho...\nThey call me Grandma Wilma.\pI came out here by myself from\na town of Dragon Tamers.\pI can teach the strongest of all\nDragon-type moves to the tough\pPokémon of Sinnoh.\pWould you like me to teach that\nmove to one of your Pokémon?$"
