@ CasteliaPlazaPrizeRoom do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_CasteliaPlazaPrizeRoom_MapScripts::
	.byte 0

Unova_CasteliaPlazaPrizeRoom_EventScript_Npc0::
	msgbox Unova_CasteliaPlazaPrizeRoom_Text_CasteliaPlazaPrizeRoomVendorIntroText, MSGBOX_NPC
	end

Unova_CasteliaPlazaPrizeRoom_EventScript_Npc1::
	msgbox Unova_CasteliaPlazaPrizeRoom_Text_CasteliaPlazaPrizeRoomVendorIntroText, MSGBOX_NPC
	end

Unova_CasteliaPlazaPrizeRoom_EventScript_Npc2::
	msgbox Unova_CasteliaPlazaPrizeRoom_Text_CasteliaPlazaPrizeRoomRangerFText, MSGBOX_NPC
	end


Unova_CasteliaPlazaPrizeRoom_Text_CasteliaPlazaPrizeRoomVendorIntroText::
	.string "Welcome!"
	.string "\pWe exchange your"
	.string "\ngame coins for"
	.string "\lfabulous prizes!$"

Unova_CasteliaPlazaPrizeRoom_Text_CasteliaPlazaPrizeRoomRangerFText::
	.string "I've been eyeing"
	.string "\nthat PINSIR and"
	.string "\pHERACROSS, but"
	.string "\nthey're so"
	.string "\lexpensive!"
	.string "\pMaybe if I had"
	.string "\nthem, I could join"
	.string "\lBURGH's GYM…$"
