@ Rt7House do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt7House_MapScripts::
	.byte 0

Unova_Rt7House_EventScript_Npc0::
	msgbox Unova_Rt7House_Text_R7HouseAskText, MSGBOX_NPC
	end


Unova_Rt7House_Text_R7HouseAskText::
	.string "Hey, you're a"
	.string "\ntrainer, right?"
	.string "\pWanna buy this"
	.string "\ncool CLAW I found?"
	.string "\pI'm sure it'll"
	.string "\nbe useful somehow."
	.string "\pI'll give it to"
	.string "\nyou for ¥5000,"
	.string "\lhow bout it?$"
