HearthomeCityWestGateToAmitySquare_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

HearthomeCityWestGateToAmitySquare_EventScript_Npc1::
	msgbox HearthomeCityWestGateToAmitySquare_Text_Npc1, MSGBOX_NPC
	end

HearthomeCityWestGateToAmitySquare_Text_Npc1:
	.string "In Amity Square, you may go for\na stroll with a cute Pokémon.$"

HearthomeCityWestGateToAmitySquare_EventScript_Npc2::
	msgbox HearthomeCityWestGateToAmitySquare_Text_Npc2, MSGBOX_NPC
	end

HearthomeCityWestGateToAmitySquare_Text_Npc2:
	.string "My PIKACHU seems delighted to be out\nof its Poké Ball for a walk outside.\pSee? You can tell because its cheeks\nare twitching away!$"

HearthomeCityWestGateToAmitySquare_EventScript_Npc3::
	msgbox HearthomeCityWestGateToAmitySquare_Text_Npc3, MSGBOX_NPC
	end

HearthomeCityWestGateToAmitySquare_Text_Npc3:
	.string "PIKACHU: Pikappi!$"
