GlobalTerminal3F_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

GlobalTerminal3F_EventScript_Npc1::
	msgbox GlobalTerminal3F_Text_Npc1, MSGBOX_NPC
	end

GlobalTerminal3F_Text_Npc1:
	.string "To treat one's self to Battle Videos\nevery day...\pI would consider that a hobby worthy\nof a true gentleman.$"

GlobalTerminal3F_EventScript_Npc2::
	msgbox GlobalTerminal3F_Text_Npc2, MSGBOX_NPC
	end

GlobalTerminal3F_Text_Npc2:
	.string "The Hiker enjoying the Box Data down\non 2F is my little brother.$"

GlobalTerminal3F_EventScript_Npc3::
	msgbox GlobalTerminal3F_Text_Npc3, MSGBOX_NPC
	end

GlobalTerminal3F_Text_Npc3:
	.string "Let me attempt the alphabet rap using\nJubilife, dig?\pJ... Just to the south of this here\ncity is Sandgem sitting pretty.\pU... Underneath Oreburgh there's a\ncoal mine doing mighty fine.\pB... Beneath the sea sprawls that mine,\nit's not anywhere I'd like to be.\pI... In the north you find Floaroma,\ngrowing flowers for my dear old Ma!\pYeah, I know, lame-o.\nYou give it a try!$"

GlobalTerminal3F_EventScript_Npc4::
	msgbox GlobalTerminal3F_Text_Npc4, MSGBOX_NPC
	end

GlobalTerminal3F_Text_Npc4:
	.string "This is a great idea.\nEveryone and anyone can participate.\pEven if you lose, it could still be a part\nof someone's favorite Battle Video.$"

GlobalTerminal3F_EventScript_Npc5::
	msgbox GlobalTerminal3F_Text_Npc5, MSGBOX_NPC
	end

GlobalTerminal3F_Text_Npc5:
	.string "What an amazing collection!\nI can see why this is so popular.\pJust seeing some of these Battle Videos\nmakes me feel tougher!$"

GlobalTerminal3F_EventScript_Npc6::
	msgbox GlobalTerminal3F_Text_Npc6, MSGBOX_NPC
	end

GlobalTerminal3F_Text_Npc6:
	.string "What you see here is how much people\naround the world love Pokémon.\pWatching Battle Videos lets you share\nthe fun these people had.$"

GlobalTerminal3F_EventScript_Npc7::
	msgbox GlobalTerminal3F_Text_Npc7, MSGBOX_NPC
	end

GlobalTerminal3F_Text_Npc7:
	.string "I have Battle Videos of only cute little\nCLEFAIRY as my favorites.$"

GlobalTerminal3F_EventScript_Npc8::
	msgbox GlobalTerminal3F_Text_Npc8, MSGBOX_NPC
	end

GlobalTerminal3F_Text_Npc8:
	.string "My favorite Battle Video.\nMy favorite Battle Video.\pWhat's on it?\nWhat's on it?\pIt's a secret!\nIt's a secret! And I mean it!$"

GlobalTerminal3F_EventScript_Npc9::
	msgbox GlobalTerminal3F_Text_Npc9, MSGBOX_NPC
	end

GlobalTerminal3F_Text_Npc9:
	.string "This Battle Video rocks hard!\pIt's an incredible turnaround from the\nbrink of a wipeout!$"

GlobalTerminal3F_EventScript_Placa10::
	msgbox GlobalTerminal3F_Text_Placa10, MSGBOX_SIGN
	end

GlobalTerminal3F_Text_Placa10:
	.string "Warps to the GTS and the Trainer\nRankings on 1F.$"

GlobalTerminal3F_EventScript_Placa11::
	msgbox GlobalTerminal3F_Text_Placa11, MSGBOX_SIGN
	end

GlobalTerminal3F_Text_Placa11:
	.string "Warps to the studios for Box Data and\nDress-Up Data on 2F.$"

GlobalTerminal3F_EventScript_Placa12::
	msgbox GlobalTerminal3F_Text_Placa12, MSGBOX_SIGN
	end

GlobalTerminal3F_Text_Placa12:
	.string "Connect to Nintendo Wi-Fi Connection\nto view and post Battle Videos?$"

GlobalTerminal3F_EventScript_Placa13::
	msgbox GlobalTerminal3F_Text_Placa13, MSGBOX_SIGN
	end

GlobalTerminal3F_Text_Placa13:
	.string "Connect to Nintendo Wi-Fi Connection\nto view and post Battle Videos?$"

GlobalTerminal3F_EventScript_Placa14::
	msgbox GlobalTerminal3F_Text_Placa14, MSGBOX_SIGN
	end

GlobalTerminal3F_Text_Placa14:
	.string "Connect to Nintendo Wi-Fi Connection\nto view and post Battle Videos?$"

GlobalTerminal3F_EventScript_Placa15::
	msgbox GlobalTerminal3F_Text_Placa15, MSGBOX_SIGN
	end

GlobalTerminal3F_Text_Placa15:
	.string "Connect to Nintendo Wi-Fi Connection\nto view and post Battle Videos?$"
