VeilstoneCityPokecenterB1F_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

VeilstoneCityPokecenterB1F_EventScript_Npc1::
	msgbox VeilstoneCityPokecenterB1F_Text_Npc1, MSGBOX_NPC
	end

VeilstoneCityPokecenterB1F_Text_Npc1:
	.string "I enjoy Nintendo WFC play with my\ngrandkids at the same time every day.\pIt's so much fun to play Plaza Games\nwith my dear ones.$"
