@ ChargestoneCave1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_ChargestoneCave1F_MapScripts::
	.byte 0

Unova_ChargestoneCave1F_EventScript_Npc7::
	msgbox Unova_ChargestoneCave1F_Text_Guitarist1ChargestoneSeenText, MSGBOX_NPC
	end

Unova_ChargestoneCave1F_EventScript_Npc8::
	msgbox Unova_ChargestoneCave1F_Text_ScientistMChargestoneSeenText, MSGBOX_NPC
	end

Unova_ChargestoneCave1F_EventScript_Npc9::
	msgbox Unova_ChargestoneCave1F_Text_PkmnRangerFChargestoneSeenText, MSGBOX_NPC
	end

Unova_ChargestoneCave1F_EventScript_Npc10::
	msgbox Unova_ChargestoneCave1F_Text_AceTrainerM1ChargestoneSeenText, MSGBOX_NPC
	end

Unova_ChargestoneCave1F_EventScript_Npc11::
	msgbox Unova_ChargestoneCave1F_Text_AceTrainerF1ChargestoneSeenText, MSGBOX_NPC
	end

Unova_ChargestoneCave1F_EventScript_Npc12::
	msgbox Unova_ChargestoneCave1F_Text_Hiker1ChargestoneSeenText, MSGBOX_NPC
	end


Unova_ChargestoneCave1F_Text_Guitarist1ChargestoneSeenText::
	.string "All right, let me"
	.string "\nintroduce you to"
	.string "\pthe other super-"
	.string "\ncool and cute"
	.string "\lmember of my band!$"

Unova_ChargestoneCave1F_Text_ScientistMChargestoneSeenText::
	.string "This cave is full"
	.string "\nof electricity-"
	.string "\lgenerating rocks!"
	.string "\pIt's charging me"
	.string "\nup!$"

Unova_ChargestoneCave1F_Text_PkmnRangerFChargestoneSeenText::
	.string "There was a"
	.string "\nwhisper on the"
	.string "\pwind that told me"
	.string "\nof your coming!$"

Unova_ChargestoneCave1F_Text_AceTrainerM1ChargestoneSeenText::
	.string "Behold the force"
	.string "\ncreated by my"
	.string "\lprized POKéMON!$"

Unova_ChargestoneCave1F_Text_AceTrainerF1ChargestoneSeenText::
	.string "Hey! My POKéMON"
	.string "\nare great. Look,"
	.string "\llook!$"

Unova_ChargestoneCave1F_Text_Hiker1ChargestoneSeenText::
	.string "This HIKER wander-"
	.string "\ning the expanses"
	.string "\pof the world will"
	.string "\nteach a child like"
	.string "\pyou the harshness"
	.string "\nof life and the"
	.string "\pdifficulty of"
	.string "\nPOKéMON battles!$"
