@ ChargestoneCave1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_ChargestoneCave1F_MapScripts::
	.byte 0

Unova_ChargestoneCave1F_EventScript_Lider7::
	trainerbattle_single TRAINER_UNOVA_GUITARIST_CHARGESTONE_1, Unova_ChargestoneCave1F_Text_Guitarist1ChargestoneSeenText, Unova_ChargestoneCave1F_Text_Guitarist1ChargestoneBeatenText
	end

Unova_ChargestoneCave1F_EventScript_Lider8::
	trainerbattle_single TRAINER_UNOVA_SCIENTISTM_CHARGESTONE, Unova_ChargestoneCave1F_Text_ScientistMChargestoneSeenText, Unova_ChargestoneCave1F_Text_ScientistMChargestoneBeatenText
	end

Unova_ChargestoneCave1F_EventScript_Lider9::
	trainerbattle_single TRAINER_UNOVA_PKMN_RANGERF_CHARGESTONE, Unova_ChargestoneCave1F_Text_PkmnRangerFChargestoneSeenText, Unova_ChargestoneCave1F_Text_PkmnRangerFChargestoneBeatenText
	end

Unova_ChargestoneCave1F_EventScript_Lider10::
	trainerbattle_single TRAINER_UNOVA_ACE_TRAINERM_CHARGESTONE_1, Unova_ChargestoneCave1F_Text_AceTrainerM1ChargestoneSeenText, Unova_ChargestoneCave1F_Text_AceTrainerM1ChargestoneBeatenText
	end

Unova_ChargestoneCave1F_EventScript_Lider11::
	trainerbattle_single TRAINER_UNOVA_ACE_TRAINERF_CHARGESTONE_1, Unova_ChargestoneCave1F_Text_AceTrainerF1ChargestoneSeenText, Unova_ChargestoneCave1F_Text_AceTrainerF1ChargestoneBeatenText
	end

Unova_ChargestoneCave1F_EventScript_Lider12::
	trainerbattle_single TRAINER_UNOVA_HIKER_CHARGESTONE_1, Unova_ChargestoneCave1F_Text_Hiker1ChargestoneSeenText, Unova_ChargestoneCave1F_Text_Hiker1ChargestoneBeatenText
	end


Unova_ChargestoneCave1F_Text_Guitarist1ChargestoneSeenText::
	.string "All right, let me"
	.string "\nintroduce you to"
	.string "\pthe other super-"
	.string "\ncool and cute"
	.string "\lmember of my band!$"

Unova_ChargestoneCave1F_Text_Guitarist1ChargestoneBeatenText::
	.string "If we don't"
	.string "\nrecruit more"
	.string "\pmembers, the sound"
	.string "\nwon't have enough"
	.string "\ldepth.$"

Unova_ChargestoneCave1F_Text_ScientistMChargestoneSeenText::
	.string "This cave is full"
	.string "\nof electricity-"
	.string "\lgenerating rocks!"
	.string "\pIt's charging me"
	.string "\nup!$"

Unova_ChargestoneCave1F_Text_ScientistMChargestoneBeatenText::
	.string "Yowch! A lightning"
	.string "\nspark!$"

Unova_ChargestoneCave1F_Text_PkmnRangerFChargestoneSeenText::
	.string "There was a"
	.string "\nwhisper on the"
	.string "\pwind that told me"
	.string "\nof your coming!$"

Unova_ChargestoneCave1F_Text_PkmnRangerFChargestoneBeatenText::
	.string "I will become the"
	.string "\nwind and go…$"

Unova_ChargestoneCave1F_Text_AceTrainerM1ChargestoneSeenText::
	.string "Behold the force"
	.string "\ncreated by my"
	.string "\lprized POKéMON!$"

Unova_ChargestoneCave1F_Text_AceTrainerM1ChargestoneBeatenText::
	.string "Your combined"
	.string "\nforce as a team is"
	.string "\lgreater than ours!$"

Unova_ChargestoneCave1F_Text_AceTrainerF1ChargestoneSeenText::
	.string "Hey! My POKéMON"
	.string "\nare great. Look,"
	.string "\llook!$"

Unova_ChargestoneCave1F_Text_AceTrainerF1ChargestoneBeatenText::
	.string "Argh!!$"

Unova_ChargestoneCave1F_Text_Hiker1ChargestoneSeenText::
	.string "This HIKER wander-"
	.string "\ning the expanses"
	.string "\pof the world will"
	.string "\nteach a child like"
	.string "\pyou the harshness"
	.string "\nof life and the"
	.string "\pdifficulty of"
	.string "\nPOKéMON battles!$"

Unova_ChargestoneCave1F_Text_Hiker1ChargestoneBeatenText::
	.string "The teacher was"
	.string "\nschooled… You're"
	.string "\pvery strict,"
	.string "\naren't you?$"
