@ VirbankComplexElevator do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VirbankComplexElevator_MapScripts::
	.byte 0

Unova_VirbankComplexElevator_EventScript_Placa0::
	msgbox Unova_VirbankComplexElevator_Text_VirbankComplexElevatorNoKeyText, MSGBOX_SIGN
	end


Unova_VirbankComplexElevator_Text_VirbankComplexElevatorNoKeyText::
	.string "A LIFT KEY is"
	.string "\nrequired…$"
