@ Colosseum do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Colosseum_MapScripts::
	.byte 0

Unova_Colosseum_EventScript_Npc0::
	msgbox Unova_Colosseum_Text_CableClubFriendScript, MSGBOX_NPC
	end

Unova_Colosseum_EventScript_Npc1::
	msgbox Unova_Colosseum_Text_CableClubFriendScript, MSGBOX_NPC
	end


Unova_Colosseum_Text_CableClubFriendScript::
	.string "Your friend is"
	.string "\nready.$"
