CelesticTownNortheastHouse_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

CelesticTownNortheastHouse_EventScript_Npc1::
	msgbox CelesticTownNortheastHouse_Text_Npc1, MSGBOX_NPC
	end

CelesticTownNortheastHouse_Text_Npc1:
	.string "Mt. Coronet towers at the center\nof Sinnoh.\pIn a way, it's the closest place to\nthe sky, and to space, in this region.$"

CelesticTownNortheastHouse_EventScript_Npc2::
	msgbox CelesticTownNortheastHouse_Text_Npc2, MSGBOX_NPC
	end

CelesticTownNortheastHouse_Text_Npc2:
	.string "If I climb on top of Mt. Coronet,\nwill I be able to see all of Sinnoh?$"
