@ OpelucidCity do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_OpelucidCity_MapScripts::
	.byte 0

Unova_OpelucidCity_EventScript_Placa0::
	msgbox Unova_OpelucidCity_Text_OpelucidCitySignText, MSGBOX_SIGN
	end

Unova_OpelucidCity_EventScript_Placa1::
	msgbox Unova_OpelucidCity_Text_OpelucidR9SignText, MSGBOX_SIGN
	end

Unova_OpelucidCity_EventScript_Placa2::
	msgbox Unova_OpelucidCity_Text_OpelucidR11SignText, MSGBOX_SIGN
	end

Unova_OpelucidCity_EventScript_Placa3::
	msgbox Unova_OpelucidCity_Text_OpelucidDraydenHouseSignText, MSGBOX_SIGN
	end

Unova_OpelucidCity_EventScript_Npc1::
	msgbox Unova_OpelucidCity_Text_OpelucidCityBlockerText, MSGBOX_NPC
	end

Unova_OpelucidCity_EventScript_Npc3::
	msgbox Unova_OpelucidCity_Text_OpelucidCityLassText, MSGBOX_NPC
	end

Unova_OpelucidCity_EventScript_Npc4::
	msgbox Unova_OpelucidCity_Text_OpelucidCityFisherText, MSGBOX_NPC
	end

Unova_OpelucidCity_EventScript_Npc5::
	msgbox Unova_OpelucidCity_Text_OpelucidCityYoungsterText, MSGBOX_NPC
	end

Unova_OpelucidCity_EventScript_Npc6::
	msgbox Unova_OpelucidCity_Text_OpelucidCityGentlemanText, MSGBOX_NPC
	end


Unova_OpelucidCity_Text_OpelucidCitySignText::
	.string "OPELUCID CITY."
	.string "\pThe city where"
	.string "\npast and future"
	.string "\lintertwine.$"

Unova_OpelucidCity_Text_OpelucidR9SignText::
	.string "WEST to ROUTE 9."
	.string "\pPassage to"
	.string "\nICIRRUS CITY.$"

Unova_OpelucidCity_Text_OpelucidR11SignText::
	.string "EAST to ROUTE 11."
	.string "\pVILLAGE BRIDGE"
	.string "\nahead.$"

Unova_OpelucidCity_Text_OpelucidDraydenHouseSignText::
	.string "Home of DRAYDEN."
	.string "\p(and IRIS!)$"

Unova_OpelucidCity_Text_OpelucidCityBlockerText::
	.string "IRIS: Sorry"
	.string "\n{PLAYER}, my"
	.string "\pgrandpa still"
	.string "\nhasn't come back"
	.string "\lto the gym.$"

Unova_OpelucidCity_Text_OpelucidCityLassText::
	.string "Gym leader DRAYDEN"
	.string "\nleads OPELUCID"
	.string "\lCITY as its mayor."
	.string "\pHe's always train-"
	.string "\ning by wrestling"
	.string "\lwith his POKéMON.$"

Unova_OpelucidCity_Text_OpelucidCityFisherText::
	.string "UNOVA's symbols"
	.string "\nare legendary"
	.string "\ldragon POKéMON."
	.string "\pBut I wonder where"
	.string "\nthey are now?$"

Unova_OpelucidCity_Text_OpelucidCityYoungsterText::
	.string "There was a person"
	.string "\ncalled N who had a"
	.string "\plegendary POKéMON"
	.string "\nwith him. Do you"
	.string "\pthink he was"
	.string "\nreally the hero?$"

Unova_OpelucidCity_Text_OpelucidCityGentlemanText::
	.string "Why do POKéMON"
	.string "\nstay by our sides?"
	.string "\pIf we could talk"
	.string "\nto them, we could"
	.string "\pask. I'm a bit"
	.string "\nscared about what"
	.string "\lthey'd say.$"
