CanalaveCitySoutheastHouse_MapScripts::
	.byte 0

CanalaveCitySoutheastHouse_EventScript_Npc1::
	msgbox CanalaveCitySoutheastHouse_Text_Npc1, MSGBOX_NPC
	end

CanalaveCitySoutheastHouse_Text_Npc1:
	.string "Hello, Trainer!\nThis is something I found.\pIt was mixed in with a load of cargo\nfrom another country.\pIt's not anything that I can use,\nso I think you should take it.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

CanalaveCitySoutheastHouse_EventScript_Npc1::
	msgbox CanalaveCitySoutheastHouse_Text_Npc1, MSGBOX_NPC
	end

CanalaveCitySoutheastHouse_Text_Npc1:
	.string "Somewhere far beyond the vast sea...\pThere are other lands populated by\nPokémon and Trainers.$"
