SolaceonTownEastHouse_MapScripts::
	.byte 0

SolaceonTownEastHouse_EventScript_Npc1::
	msgbox SolaceonTownEastHouse_Text_Npc1, MSGBOX_NPC
	end

SolaceonTownEastHouse_Text_Npc1:
	.string "The Pokémon in this town's ruins look\nlike some kind of strange alphabet.\pI think they're really neat.\nI'm too small to catch them, though.\pInstead, I play with Seals to try\nreading those weird letters.\pIf you can give me Pokémon that look\nlike letters, I'll give you some Seals.$"

SolaceonTownEastHouse_EventScript_Npc2::
	msgbox SolaceonTownEastHouse_Text_Npc2, MSGBOX_NPC
	end

SolaceonTownEastHouse_Text_Npc2:
	.string "You can customize Poké Balls by\naffixing Seals on them.\pOh, you don't have a Seal Case?\nWell, here you go!$"
