SandgemTown_RivalHouse_F2_MapScripts::
	.byte 0

SandgemTown_RivalHouse_F2_EventScript_PCNote::
	msgbox SandgemTown_RivalHouse_F2_Text_PCNote, MSGBOX_SIGN
	end

SandgemTown_RivalHouse_F2_Text_PCNote:
	.string "A note taped to the PC screen.\p"
	.string "Adventure Rule No. 1: The X Button\n"
	.string "opens the menu!\p"
	.string "Adventure Rule No. 2: Record your\n"
	.string "progress with SAVE.$"
