@ VirbankGym do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VirbankGym_MapScripts::
	.byte 0

Unova_VirbankGym_EventScript_Npc0::
	msgbox Unova_VirbankGym_Text_RoxieGymIntroText, MSGBOX_NPC
	end

Unova_VirbankGym_EventScript_Npc1::
	msgbox Unova_VirbankGym_Text_GuitaristVirbankGym1SeenText, MSGBOX_NPC
	end

Unova_VirbankGym_EventScript_Npc2::
	msgbox Unova_VirbankGym_Text_GuitaristVirbankGym2SeenText, MSGBOX_NPC
	end

Unova_VirbankGym_EventScript_Npc3::
	msgbox Unova_VirbankGym_Text_MusicianVirbankGym1SeenText, MSGBOX_NPC
	end

Unova_VirbankGym_EventScript_Npc4::
	msgbox Unova_VirbankGym_Text_MusicianVirbankGym2SeenText, MSGBOX_NPC
	end


Unova_VirbankGym_Text_RoxieGymIntroText::
	.string "Get ready! I'm"
	.string "\ngonna knock some"
	.string "\lsense outta ya!$"

Unova_VirbankGym_Text_GuitaristVirbankGym1SeenText::
	.string "I'm going to take"
	.string "\nyou down! Prepare"
	.string "\lto be stung!$"

Unova_VirbankGym_Text_GuitaristVirbankGym2SeenText::
	.string "Get in my way, and"
	.string "\nI'll knock you"
	.string "\pout! Stay out of"
	.string "\nmy way… and I'll"
	.string "\lknock you out too!$"

Unova_VirbankGym_Text_MusicianVirbankGym1SeenText::
	.string "Hold it there,"
	.string "\nkid. This is an"
	.string "\lexclusive club.$"

Unova_VirbankGym_Text_MusicianVirbankGym2SeenText::
	.string "I can always be"
	.string "\nhonest with myself"
	.string "\pwhen I'm playing"
	.string "\nthe guitar or"
	.string "\phaving a POKéMON"
	.string "\nbattle!$"
