@ DewfordTown_Ex3_6: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 3.6) por dev_scripts/copia_planta_ex.py.

DewfordTown_Ex3_6_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 3.6), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
DewfordTown_Ex3_6_EventScript_ExNpc1::
	msgbox DewfordTown_Ex3_6_Text_ExNpc1, MSGBOX_NPC
	end

DewfordTown_Ex3_6_Text_ExNpc1:
	.string "They have POKéBALLS here that make it\n"
	.string "easier to catch POKéMON while FISHING!$"

DewfordTown_Ex3_6_EventScript_ExNpc2::
	msgbox DewfordTown_Ex3_6_Text_ExNpc2, MSGBOX_NPC
	end

DewfordTown_Ex3_6_Text_ExNpc2:
	.string "Do you think that a POTION will help\n"
	.string "with digestion?$"

