@ Rt20VirbankGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt20VirbankGate_MapScripts::
	.byte 0

Unova_Rt20VirbankGate_EventScript_Npc0::
	msgbox Unova_Rt20VirbankGate_Text_R20VirbankGateOfficerText, MSGBOX_NPC
	end


Unova_Rt20VirbankGate_Text_R20VirbankGateOfficerText::
	.string "VIRBANK CITY is a"
	.string "\nbustling burg."
	.string "\pBe careful around"
	.string "\nthe construction!$"
