JubilifeCity_Flat2_F2_MapScripts::
	.byte 0

JubilifeCity_Flat2_F2_EventScript_Youngster::
	msgbox JubilifeCity_Flat2_F2_Text_Youngster, MSGBOX_NPC
	end

JubilifeCity_Flat2_F2_EventScript_PokefanF::
	msgbox JubilifeCity_Flat2_F2_Text_PokefanF, MSGBOX_NPC
	end

JubilifeCity_Flat2_F2_EventScript_BreederF::
	msgbox JubilifeCity_Flat2_F2_Text_BreederF, MSGBOX_NPC
	end

JubilifeCity_Flat2_F2_Text_Youngster:
	.string "My family just moved to\n"
	.string "JUBILIFE CITY.\p"
	.string "It's way bigger than our old\n"
	.string "town!$"

JubilifeCity_Flat2_F2_Text_PokefanF:
	.string "I keep a photo album of every\n"
	.string "POKéMON I've ever seen.\p"
	.string "JUBILIFE has the most variety!$"

JubilifeCity_Flat2_F2_Text_BreederF:
	.string "Raising POKéMON here means\n"
	.string "walking up and down the\l"
	.string "stairs a lot.\p"
	.string "Good exercise, honestly.$"
