JubilifeCity_Flat2_F2_MapScripts::
	.byte 0

JubilifeCity_Flat2_F2_EventScript_BreederF::
	msgbox JubilifeCity_Flat2_F2_Text_BreederF, MSGBOX_NPC
	end

JubilifeCity_Flat2_F2_Text_BreederF:
	.string "Raising POKéMON here means\n"
	.string "walking up and down the\l"
	.string "stairs a lot.\p"
	.string "Good exercise, honestly.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

JubilifeCity_Flat2_F2_EventScript_Npc1::
	msgbox JubilifeCity_Flat2_F2_Text_Npc1, MSGBOX_NPC
	end

JubilifeCity_Flat2_F2_Text_Npc1:
	.string "Did you know?\pSome kinds of Pokémon evolve when\nthey get stronger from battling!\pWhen they evolve, they can take on\ncompletely different forms!$"

JubilifeCity_Flat2_F2_EventScript_Npc2::
	msgbox JubilifeCity_Flat2_F2_Text_Npc2, MSGBOX_NPC
	end

JubilifeCity_Flat2_F2_Text_Npc2:
	.string "Evolution makes Pokémon just that\nmuch more fascinating.\pThe mysteries of evolution... Can that\ndandy Prof. Rowan unravel them?$"

JubilifeCity_Flat2_F2_EventScript_Npc3::
	msgbox JubilifeCity_Flat2_F2_Text_Npc3, MSGBOX_NPC
	end

JubilifeCity_Flat2_F2_Text_Npc3:
	.string "Didn't Prof. Rowan conduct research\nwith Prof. Oak of the Kanto region?$"
