@ CasteliaSewers do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_CasteliaSewers_MapScripts::
	.byte 0

Unova_CasteliaSewers_EventScript_Npc7::
	msgbox Unova_CasteliaSewers_Text_ScientistMCasteliaSewersSeenText, MSGBOX_NPC
	end

Unova_CasteliaSewers_EventScript_Npc8::
	msgbox Unova_CasteliaSewers_Text_ScientistFCasteliaSewersSeenText, MSGBOX_NPC
	end

Unova_CasteliaSewers_EventScript_Npc9::
	msgbox Unova_CasteliaSewers_Text_Worker1CasteliaSewersSeenText, MSGBOX_NPC
	end

Unova_CasteliaSewers_EventScript_Npc10::
	msgbox Unova_CasteliaSewers_Text_Worker2CasteliaSewersSeenText, MSGBOX_NPC
	end

Unova_CasteliaSewers_EventScript_Npc11::
	msgbox Unova_CasteliaSewers_Text_Janitor1CasteliaSewersSeenText, MSGBOX_NPC
	end

Unova_CasteliaSewers_EventScript_Npc12::
	msgbox Unova_CasteliaSewers_Text_Janitor2CasteliaSewersSeenText, MSGBOX_NPC
	end

Unova_CasteliaSewers_EventScript_Npc13::
	msgbox Unova_CasteliaSewers_Text_Janitor3CasteliaSewersSeenText, MSGBOX_NPC
	end

Unova_CasteliaSewers_EventScript_Npc14::
	msgbox Unova_CasteliaSewers_Text_CasteliaSewersBlockerText, MSGBOX_NPC
	end


Unova_CasteliaSewers_Text_ScientistMCasteliaSewersSeenText::
	.string "I'm studying the"
	.string "\nenvironment here.$"

Unova_CasteliaSewers_Text_ScientistFCasteliaSewersSeenText::
	.string "Hi, would you like"
	.string "\nto assist in my"
	.string "\lresearch?$"

Unova_CasteliaSewers_Text_Worker1CasteliaSewersSeenText::
	.string "We need sewers,"
	.string "\nbut what about"
	.string "\lPOKéMON?$"

Unova_CasteliaSewers_Text_Worker2CasteliaSewersSeenText::
	.string "There's a tunnel"
	.string "\nin the back of"
	.string "\lthe sewers."
	.string "\pIf you can beat"
	.string "\nme, I'll tell you"
	.string "\lhow to get there.$"

Unova_CasteliaSewers_Text_Janitor1CasteliaSewersSeenText::
	.string "Cleaning actually"
	.string "\ntakes a lot of"
	.string "\lstrength…$"

Unova_CasteliaSewers_Text_Janitor2CasteliaSewersSeenText::
	.string "I've been training"
	.string "\nreal hard doing"
	.string "\lall this cleaning!$"

Unova_CasteliaSewers_Text_Janitor3CasteliaSewersSeenText::
	.string "Uh-oh, busted!$"

Unova_CasteliaSewers_Text_CasteliaSewersBlockerText::
	.string "Hey buddy, there's"
	.string "\nimportant stuff"
	.string "\lgoing on in here."
	.string "\pBuzz off!$"
