@ Rt6 do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt6_MapScripts::
	.byte 0

Unova_Rt6_EventScript_Placa0::
	msgbox Unova_Rt6_Text_R6SignText, MSGBOX_SIGN
	end

Unova_Rt6_EventScript_Placa1::
	msgbox Unova_Rt6_Text_R6LabText, MSGBOX_SIGN
	end

Unova_Rt6_EventScript_Placa2::
	msgbox Unova_Rt6_Text_R6ChargestoneText, MSGBOX_SIGN
	end

Unova_Rt6_EventScript_Npc6::
	msgbox Unova_Rt6_Text_AmoongussText, MSGBOX_NPC
	end

Unova_Rt6_EventScript_Npc7::
	msgbox Unova_Rt6_Text_AmoongussText, MSGBOX_NPC
	end

Unova_Rt6_EventScript_Npc8::
	msgbox Unova_Rt6_Text_AmoongussText, MSGBOX_NPC
	end

Unova_Rt6_EventScript_Npc9::
	msgbox Unova_Rt6_Text_ParasolLady1R6SeenText, MSGBOX_NPC
	end

Unova_Rt6_EventScript_Npc10::
	msgbox Unova_Rt6_Text_ParasolLady2R6SeenText, MSGBOX_NPC
	end

Unova_Rt6_EventScript_Npc11::
	msgbox Unova_Rt6_Text_PkmnRangerMR6SeenText, MSGBOX_NPC
	end

Unova_Rt6_EventScript_Npc12::
	msgbox Unova_Rt6_Text_PkmnRangerFR6SeenText, MSGBOX_NPC
	end

Unova_Rt6_EventScript_Npc13::
	msgbox Unova_Rt6_Text_PkmnBreederFR6SeenText, MSGBOX_NPC
	end

Unova_Rt6_EventScript_Npc14::
	msgbox Unova_Rt6_Text_PkmnBreederMR6SeenText, MSGBOX_NPC
	end

Unova_Rt6_EventScript_Npc15::
	msgbox Unova_Rt6_Text_ScientistMR6SeenText, MSGBOX_NPC
	end

Unova_Rt6_EventScript_Npc16::
	msgbox Unova_Rt6_Text_ScientistFR6SeenText, MSGBOX_NPC
	end


Unova_Rt6_Text_R6SignText::
	.string "ROUTE 6."
	.string "\nWest to CHARGE-"
	.string "\lSTONE CAVE.$"

Unova_Rt6_Text_R6LabText::
	.string "ROUTE 6"
	.string "\nWeather Lab.$"

Unova_Rt6_Text_R6ChargestoneText::
	.string "CHARGESTONE CAVE"
	.string "\nahead."
	.string "\pPassage to"
	.string "\nMISTRALTON CITY.$"

Unova_Rt6_Text_AmoongussText::
	.string "Ooong!$"

Unova_Rt6_Text_ParasolLady1R6SeenText::
	.string "Pouring rain…"
	.string "\nFighting POKéMON…$"

Unova_Rt6_Text_ParasolLady2R6SeenText::
	.string "Water fun with"
	.string "\nPOKéMON! Do you"
	.string "\pwant to play with"
	.string "\nus?$"

Unova_Rt6_Text_PkmnRangerMR6SeenText::
	.string "Nature!$"

Unova_Rt6_Text_PkmnRangerFR6SeenText::
	.string "There are some"
	.string "\nPOKéMON that can"
	.string "\pdisguise them-"
	.string "\nselves!$"

Unova_Rt6_Text_PkmnBreederFR6SeenText::
	.string "Going through"
	.string "\ntrials is the best"
	.string "\pfor growing"
	.string "\nstronger!$"

Unova_Rt6_Text_PkmnBreederMR6SeenText::
	.string "We've just got to"
	.string "\ndo what we can!$"

Unova_Rt6_Text_ScientistMR6SeenText::
	.string "Testing out one's"
	.string "\ntheory is all a"
	.string "\lpart of science!$"

Unova_Rt6_Text_ScientistFR6SeenText::
	.string "I shall uncover"
	.string "\nthe mechanism"
	.string "\pbehind trainer and"
	.string "\nPOKéMON relation-"
	.string "\lships!$"
