@ CasteliaGameFreak do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_CasteliaGameFreak_MapScripts::
	.byte 0

Unova_CasteliaGameFreak_EventScript_Placa0::
	msgbox Unova_CasteliaGameFreak_Text_GameFreakSignText, MSGBOX_SIGN
	end

Unova_CasteliaGameFreak_EventScript_Npc0::
	msgbox Unova_CasteliaGameFreak_Text_AzureBusyText, MSGBOX_NPC
	end


Unova_CasteliaGameFreak_Text_GameFreakSignText::
	.string "GAME FREAK HQ."
	.string "\pOffice closed for"
	.string "\nvacation."
	.string "\pInquire at the"
	.string "\nKALOS office for"
	.string "\linformation.$"

Unova_CasteliaGameFreak_Text_AzureBusyText::
	.string "Shh, GAME FREAK"
	.string "\nisn't open right"
	.string "\lnow."
	.string "\pCome back later,"
	.string "\nI'm working on"
	.string "\pporting this game"
	.string "\nto the POLISHED"
	.string "\lCRYSTAL engine…$"
