HearthomeCityEastGateToAmitySquare_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

HearthomeCityEastGateToAmitySquare_EventScript_Npc1::
	msgbox HearthomeCityEastGateToAmitySquare_Text_Npc1, MSGBOX_NPC
	end

HearthomeCityEastGateToAmitySquare_Text_Npc1:
	.string "You can take a cute Pokémon out for\na stroll in Amity Square.$"

HearthomeCityEastGateToAmitySquare_EventScript_Npc2::
	msgbox HearthomeCityEastGateToAmitySquare_Text_Npc2, MSGBOX_NPC
	end

HearthomeCityEastGateToAmitySquare_Text_Npc2:
	.string "I'm appalled!\nThey refused entry to my Pokémon!\pOh, my poor GYARADOS and STEELIX!\nThis is discrimination!$"
