ResortAreaHouse_MapScripts::
	.byte 0

ResortAreaHouse_EventScript_Npc1::
	msgbox ResortAreaHouse_Text_Npc1, MSGBOX_NPC
	end

ResortAreaHouse_Text_Npc1:
	.string "All I need to be happy is my TV.\nThat's all I need.\pI learn so much just sitting here.\nI absorb knowledge!\pI learned about the Pokétch app\nMarking Map, for instance.\pThey say the Marking Map can track\nPokémon that travel around.\p...I've never met any traveling\nPokémon, but I've heard about them.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

ResortAreaHouse_EventScript_Npc2::
	msgbox ResortAreaHouse_Text_Npc2, MSGBOX_NPC
	end

ResortAreaHouse_Text_Npc2:
	.string "The best Trainers from all over\ncongregate at the Battle Frontier.\pIt's not limited to Sinnoh, no.\pIt must be a happy achievement to\nbe able to win there with your favorite\pPokémon you've caught yourself.$"
