@ LavaridgeTown_Ex4_10: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 4.10) por dev_scripts/copia_planta_ex.py.

LavaridgeTown_Ex4_10_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 4.10), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
LavaridgeTown_Ex4_10_EventScript_ExNpc0::
	msgbox LavaridgeTown_Ex4_10_Text_ExNpc0, MSGBOX_NPC
	end

LavaridgeTown_Ex4_10_Text_ExNpc0:
	.string "I only come home when all the trainers\n"
	.string "are gone.\p"
	.string "I’ve been sleeping in the MART...$"

LavaridgeTown_Ex4_10_EventScript_ExNpc1::
	msgbox LavaridgeTown_Ex4_10_Text_ExNpc1, MSGBOX_NPC
	end

LavaridgeTown_Ex4_10_Text_ExNpc1:
	.string "Since FLANNERY is a new GYM LEADER she\n"
	.string "hasn’t found strong trainers to be in\l"
	.string "her GYM yet.\p"
	.string "The POKéMON LEAGUE sent a bunch of\n"
	.string "trainers for the time being.\p"
	.string "ALL of them are staying here...\p"
	.string "ALL OF THEM!$"

