SnowpointCityEastHouse_MapScripts::
	.byte 0

SnowpointCityEastHouse_EventScript_Npc1::
	msgbox SnowpointCityEastHouse_Text_Npc1, MSGBOX_NPC
	end

SnowpointCityEastHouse_Text_Npc1:
	.string "Hello, hello. Would you like to hear\na trendy saying?$"

SnowpointCityEastHouse_EventScript_Npc2::
	msgbox SnowpointCityEastHouse_Text_Npc2, MSGBOX_NPC
	end

SnowpointCityEastHouse_Text_Npc2:
	.string "Share colored Shards with me, and I'll\nteach your Pokémon some moves.\pWant me to teach a move?$"
