@ IcirrusFanClub do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_IcirrusFanClub_MapScripts::
	.byte 0

Unova_IcirrusFanClub_EventScript_Npc0::
	msgbox Unova_IcirrusFanClub_Text_IcirrusFanClubScarfGiver_AskMonText, MSGBOX_NPC
	end

Unova_IcirrusFanClub_EventScript_Npc1::
	msgbox Unova_IcirrusFanClub_Text_IcirrusFanClubElectrizerGiver_AskScaleText, MSGBOX_NPC
	end

Unova_IcirrusFanClub_EventScript_Npc2::
	msgbox Unova_IcirrusFanClub_Text_IcirrusFanClubElectrizerGiver_AskScaleText, MSGBOX_NPC
	end

Unova_IcirrusFanClub_EventScript_Npc3::
	msgbox Unova_IcirrusFanClub_Text_IcirrusFanClubCooltrainerFText, MSGBOX_NPC
	end

Unova_IcirrusFanClub_EventScript_Npc4::
	msgbox Unova_IcirrusFanClub_Text_IcirrusFanClubMunnaText, MSGBOX_NPC
	end

Unova_IcirrusFanClub_EventScript_Npc5::
	msgbox Unova_IcirrusFanClub_Text_IcirrusFanClubGentlemanText, MSGBOX_NPC
	end

Unova_IcirrusFanClub_EventScript_Npc6::
	msgbox Unova_IcirrusFanClub_Text_IcirrusFanClubDucklettText, MSGBOX_NPC
	end


Unova_IcirrusFanClub_Text_IcirrusFanClubScarfGiver_AskMonText::
	.string "If you want to be"
	.string "\nthe best, there's"
	.string "\pone thing that"
	.string "\nmatters above all"
	.string "\lelse: SPEED!"
	.string "\pIf you have a"
	.string "\nPOKéMON that has"
	.string "\pmastered its SPEED"
	.string "\ntraining, show it"
	.string "\lto me!$"

Unova_IcirrusFanClub_Text_IcirrusFanClubElectrizerGiver_AskScaleText::
	.string "I want to make my"
	.string "\nPOKéMON remember"
	.string "\pone of its old"
	.string "\nmoves at the tutor"
	.string "\pin MISTRALTON"
	.string "\nCITY, but I don't"
	.string "\phave any HEART"
	.string "\nSCALES."
	.string "\pCould I have one"
	.string "\nof yours?$"

Unova_IcirrusFanClub_Text_IcirrusFanClubCooltrainerFText::
	.string "Welcome to the"
	.string "\nPOKéMON FAN CLUB!"
	.string "\pWe love all POKé-"
	.string "\nMON, strong and"
	.string "\lcute!$"

Unova_IcirrusFanClub_Text_IcirrusFanClubMunnaText::
	.string "Muuuu!$"

Unova_IcirrusFanClub_Text_IcirrusFanClubGentlemanText::
	.string "Ah, I see you're a"
	.string "\nfan of POKéMON as"
	.string "\lwell!"
	.string "\pThe regulars here"
	.string "\nreally get into"
	.string "\ptheir POKéMON"
	.string "\ntraining!$"

Unova_IcirrusFanClub_Text_IcirrusFanClubDucklettText::
	.string "Dak! Dak!$"
