GlobalTerminal1F_MapScripts::
	.byte 0

GlobalTerminal1F_EventScript_Npc1::
	msgbox GlobalTerminal1F_Text_Npc1, MSGBOX_NPC
	end

GlobalTerminal1F_Text_Npc1:
	.string "Welcome! This is the Global Trade\nStation, or GTS for short.\pWe enable the trading of Pokémon with\npeople worldwide over Nintendo WFC.\pWould you like to do a global\nPokémon trade?$"

GlobalTerminal1F_EventScript_Npc2::
	msgbox GlobalTerminal1F_Text_Npc2, MSGBOX_NPC
	end

GlobalTerminal1F_Text_Npc2:
	.string "Yo, yo, yo!\pWanna let the world know about you?\nThen you gotta tell me, yo!$"

GlobalTerminal1F_EventScript_Npc3::
	msgbox GlobalTerminal1F_Text_Npc3, MSGBOX_NPC
	end

GlobalTerminal1F_Text_Npc3:
	.string "Hi, have you visited the Dress-Up\nData Studio?\pHave you put yours on exhibit?\nOr do you only look at other entries?\pWhether you're an exhibitor or viewer,\nI have a Backdrop for you!$"
