@ DriftveilDrawbridge do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_DriftveilDrawbridge_MapScripts::
	.byte 0

Unova_DriftveilDrawbridge_EventScript_Npc0::
	msgbox Unova_DriftveilDrawbridge_Text_DriftveilDrawbridgeGiveEvioliteText, MSGBOX_NPC
	end


Unova_DriftveilDrawbridge_Text_DriftveilDrawbridgeGiveEvioliteText::
	.string "You're a POKéMON"
	.string "\ntrainer, right?"
	.string "\pI found this rare"
	.string "\nstone in DRIFTVEIL"
	.string "\lCITY."
	.string "\pI think it would"
	.string "\nhelp you more than"
	.string "\lme, take it.$"
