@ Rt2 do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt2_MapScripts::
	.byte 0

Unova_Rt2_EventScript_Placa0::
	msgbox Unova_Rt2_Text_R2SignText, MSGBOX_SIGN
	end

Unova_Rt2_EventScript_Npc8::
	msgbox Unova_Rt2_Text_YoungsterR2SeenText, MSGBOX_NPC
	end

Unova_Rt2_EventScript_Npc9::
	msgbox Unova_Rt2_Text_LassR2SeenText, MSGBOX_NPC
	end

Unova_Rt2_EventScript_Npc10::
	msgbox Unova_Rt2_Text_SocialiteR2SeenText, MSGBOX_NPC
	end

Unova_Rt2_EventScript_Npc11::
	msgbox Unova_Rt2_Text_GentlemanR2SeenText, MSGBOX_NPC
	end

Unova_Rt2_EventScript_Npc12::
	msgbox Unova_Rt2_Text_BackpackerMR2SeenText, MSGBOX_NPC
	end

Unova_Rt2_EventScript_Npc13::
	msgbox Unova_Rt2_Text_BackpackerFR2SeenText, MSGBOX_NPC
	end

Unova_Rt2_EventScript_Npc14::
	msgbox Unova_Rt2_Text_PolicemanR2SeenText, MSGBOX_NPC
	end

Unova_Rt2_EventScript_Npc15::
	msgbox Unova_Rt2_Text_TwinsR2SeenText, MSGBOX_NPC
	end

Unova_Rt2_EventScript_Npc16::
	msgbox Unova_Rt2_Text_TwinsR2SeenText, MSGBOX_NPC
	end


Unova_Rt2_Text_R2SignText::
	.string "ROUTE 2."
	.string "\pSouth to ACCUMULA"
	.string "\nTOWN.$"

Unova_Rt2_Text_YoungsterR2SeenText::
	.string "My POKéMON are"
	.string "\ngonna steam you"
	.string "\lout!$"

Unova_Rt2_Text_LassR2SeenText::
	.string "Hi, hi! Trainer!"
	.string "\nI will let you see"
	.string "\pwhat kind of POKé-"
	.string "\nMON I have!$"

Unova_Rt2_Text_SocialiteR2SeenText::
	.string "Hello there, young"
	.string "\ntrainer. Please,"
	.string "\pbattle with me for"
	.string "\na spell.$"

Unova_Rt2_Text_GentlemanR2SeenText::
	.string "I've asked myself"
	.string "\nif it really is"
	.string "\pnatural for POKé-"
	.string "\nMON to live with"
	.string "\lpeople."
	.string "\pI still haven't"
	.string "\ncome up with an"
	.string "\lanswer.$"

Unova_Rt2_Text_BackpackerMR2SeenText::
	.string "It's 'The Waving"
	.string "\nWeaving Walk'-"
	.string "\pWawalk for short!"
	.string "\pI wonder what kind"
	.string "\nof POKéMON we'll"
	.string "\lmeet today?$"

Unova_Rt2_Text_BackpackerFR2SeenText::
	.string "Let's see who has"
	.string "\nthe most admirable"
	.string "\lPOKéMON!$"

Unova_Rt2_Text_PolicemanR2SeenText::
	.string "Hey, you! Stop"
	.string "\nright there!$"

Unova_Rt2_Text_TwinsR2SeenText::
	.string "Two POKéMON!"
	.string "\pStrong and strong"
	.string "\ncome together to"
	.string "\pbecome…"
	.string "\nvery strong!$"
