@ Rt18House do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt18House_MapScripts::
	.byte 0

Unova_Rt18House_EventScript_Npc0::
	msgbox Unova_Rt18House_Text_R18HouseHealText, MSGBOX_NPC
	end


Unova_Rt18House_Text_R18HouseHealText::
	.string "Oh, you must have"
	.string "\ntraveled a long"
	.string "\lway to get here."
	.string "\pYou should let"
	.string "\nyour POKéMON rest.$"
