RuinManiacCaveLong_MapScripts::
	.byte 0

RuinManiacCaveLong_EventScript_Npc1::
	msgbox RuinManiacCaveLong_Text_Npc1, MSGBOX_NPC
	end

RuinManiacCaveLong_Text_Npc1:
	.string "Everyone calls me the Ruin Maniac.\nOr they used to call me that.\pNow they call me the Digging Maniac.\pI'll just go on chipping away at\nthe rock wall a little at a time.\pDo you know why? I'm a Ruin Maniac\nwho is fascinated by the UNOWN\pand who also loves to dig!$"
