@ AccumulaBallManiacHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_AccumulaBallManiacHouse_MapScripts::
	.byte 0

Unova_AccumulaBallManiacHouse_EventScript_Npc0::
	msgbox Unova_AccumulaBallManiacHouse_Text_AccumulaBallManiacIntroText, MSGBOX_NPC
	end


Unova_AccumulaBallManiacHouse_Text_AccumulaBallManiacIntroText::
	.string "Hi! They call me"
	.string "\nthe POKéBALL"
	.string "\lmaniac!"
	.string "\pI collect all"
	.string "\nkinds of different"
	.string "\lPOKéBALLS."
	.string "\pPeople come from"
	.string "\nall over town to"
	.string "\lSee my collection!"
	.string "\pDifferent kinds of"
	.string "\nPOKéBALL are"
	.string "\pbetter at catching"
	.string "\nPOKéMON, depending"
	.string "\lon the situation."
	.string "\pHow about you? How"
	.string "\nwould you like a"
	.string "\psample of my fine"
	.string "\nPOKéBALLs?$"
