@ VictoryRoadCave1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VictoryRoadCave1F_MapScripts::
	.byte 0

Unova_VictoryRoadCave1F_EventScript_Lider7::
	trainerbattle_single TRAINER_UNOVA_ACE_TRAINERM_VICTORY_ROAD_INT_1, Unova_VictoryRoadCave1F_Text_AceTrainerMVictoryRoadCave1FSeenText, Unova_VictoryRoadCave1F_Text_AceTrainerMVictoryRoadCave1FBeatenText
	end

Unova_VictoryRoadCave1F_EventScript_Lider8::
	trainerbattle_single TRAINER_UNOVA_ACE_TRAINERF_VICTORY_ROAD_INT_2, Unova_VictoryRoadCave1F_Text_AceTrainerFVictoryRoadCave1FSeenText, Unova_VictoryRoadCave1F_Text_AceTrainerFVictoryRoadCave1FBeatenText
	end

Unova_VictoryRoadCave1F_EventScript_Lider9::
	trainerbattle_single TRAINER_UNOVA_VETERANM_VICTORY_ROAD_INT_1, Unova_VictoryRoadCave1F_Text_VeteranMVictoryRoadCave1FSeenText, Unova_VictoryRoadCave1F_Text_VeteranMVictoryRoadCave1FBeatenText
	end

Unova_VictoryRoadCave1F_EventScript_Lider10::
	trainerbattle_single TRAINER_UNOVA_VETERANF_VICTORY_ROAD_INT_1, Unova_VictoryRoadCave1F_Text_VeteranFVictoryRoadCave1FSeenText, Unova_VictoryRoadCave1F_Text_VeteranFVictoryRoadCave1FBeatenText
	end

Unova_VictoryRoadCave1F_EventScript_Lider11::
	trainerbattle_single TRAINER_UNOVA_PSYCHICM_VICTORY_ROAD_INT, Unova_VictoryRoadCave1F_Text_PsychicMVictoryRoadCave1FSeenText, Unova_VictoryRoadCave1F_Text_PsychicMVictoryRoadCave1FBeatenText
	end

Unova_VictoryRoadCave1F_EventScript_Lider12::
	trainerbattle_single TRAINER_UNOVA_PSYCHICF_VICTORY_ROAD_INT, Unova_VictoryRoadCave1F_Text_PsychicFVictoryRoadCave1FSeenText, Unova_VictoryRoadCave1F_Text_PsychicFVictoryRoadCave1FBeatenText
	end

Unova_VictoryRoadCave1F_EventScript_Lider13::
	trainerbattle_single TRAINER_UNOVA_HEX_MANIAC_VICTORY_ROAD_INT, Unova_VictoryRoadCave1F_Text_HexManiacVictoryRoadCave1FSeenText, Unova_VictoryRoadCave1F_Text_HexManiacVictoryRoadCave1FBeatenText
	end


Unova_VictoryRoadCave1F_Text_AceTrainerMVictoryRoadCave1FSeenText::
	.string "An ACE TRAINER"
	.string "\nlike me has pride,"
	.string "\lso I won't lose!$"

Unova_VictoryRoadCave1F_Text_AceTrainerMVictoryRoadCave1FBeatenText::
	.string "I couldn't protect"
	.string "\nmy pride! I'm"
	.string "\lmortified!$"

Unova_VictoryRoadCave1F_Text_AceTrainerFVictoryRoadCave1FSeenText::
	.string "Challenging the"
	.string "\nPOKéMON LEAGUE?"
	.string "\pIt's no wonder you"
	.string "\nmight feel a bit"
	.string "\pnervous, but you"
	.string "\njust have to"
	.string "\pbelieve in your"
	.string "\nPOKéMON and do it!$"

Unova_VictoryRoadCave1F_Text_AceTrainerFVictoryRoadCave1FBeatenText::
	.string "Am I really going"
	.string "\nto be alright with"
	.string "\ponly this trifling"
	.string "\npower?$"

Unova_VictoryRoadCave1F_Text_VeteranMVictoryRoadCave1FSeenText::
	.string "You bothered to"
	.string "\ncome all the way"
	.string "\phere? Good! I will"
	.string "\nreward your hard"
	.string "\pwork by battling"
	.string "\nwith all of my"
	.string "\lstrength!$"

Unova_VictoryRoadCave1F_Text_VeteranMVictoryRoadCave1FBeatenText::
	.string "A battle with a"
	.string "\ngood trainer fills"
	.string "\pmy heart with"
	.string "\nwarmth!$"

Unova_VictoryRoadCave1F_Text_VeteranFVictoryRoadCave1FSeenText::
	.string "Hey, since you"
	.string "\nworked so hard to"
	.string "\pget here, how"
	.string "\nabout I be your"
	.string "\lopponent?$"

Unova_VictoryRoadCave1F_Text_VeteranFVictoryRoadCave1FBeatenText::
	.string "Thanks a bunch. It"
	.string "\nwas a lot of fun!$"

Unova_VictoryRoadCave1F_Text_PsychicMVictoryRoadCave1FSeenText::
	.string "You… Who's brought"
	.string "\nyou this far?$"

Unova_VictoryRoadCave1F_Text_PsychicMVictoryRoadCave1FBeatenText::
	.string "It's your reliable"
	.string "\nPOKéMON who've"
	.string "\pbrought you this"
	.string "\nfar, isn't it?$"

Unova_VictoryRoadCave1F_Text_PsychicFVictoryRoadCave1FSeenText::
	.string "I'll use my psychic"
	.string "\npowers to release"
	.string "\pmy POKéMON from"
	.string "\nits POKéBALL!$"

Unova_VictoryRoadCave1F_Text_PsychicFVictoryRoadCave1FBeatenText::
	.string "Well, that didn't"
	.string "\ngo the way I"
	.string "\lwanted it to!$"

Unova_VictoryRoadCave1F_Text_HexManiacVictoryRoadCave1FSeenText::
	.string "You are no ordin-"
	.string "\nary opponent…"
	.string "\pThat is what my"
	.string "\nghost type POKéMON"
	.string "\pis whispering to"
	.string "\nme.$"

Unova_VictoryRoadCave1F_Text_HexManiacVictoryRoadCave1FBeatenText::
	.string "My premonition was"
	.string "\nspot on!$"
