@ VictoryRoadCave1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VictoryRoadCave1F_MapScripts::
	.byte 0

Unova_VictoryRoadCave1F_EventScript_Npc7::
	msgbox Unova_VictoryRoadCave1F_Text_AceTrainerMVictoryRoadCave1FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadCave1F_EventScript_Npc8::
	msgbox Unova_VictoryRoadCave1F_Text_AceTrainerFVictoryRoadCave1FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadCave1F_EventScript_Npc9::
	msgbox Unova_VictoryRoadCave1F_Text_VeteranMVictoryRoadCave1FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadCave1F_EventScript_Npc10::
	msgbox Unova_VictoryRoadCave1F_Text_VeteranFVictoryRoadCave1FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadCave1F_EventScript_Npc11::
	msgbox Unova_VictoryRoadCave1F_Text_PsychicMVictoryRoadCave1FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadCave1F_EventScript_Npc12::
	msgbox Unova_VictoryRoadCave1F_Text_PsychicFVictoryRoadCave1FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadCave1F_EventScript_Npc13::
	msgbox Unova_VictoryRoadCave1F_Text_HexManiacVictoryRoadCave1FSeenText, MSGBOX_NPC
	end


Unova_VictoryRoadCave1F_Text_AceTrainerMVictoryRoadCave1FSeenText::
	.string "An ACE TRAINER"
	.string "\nlike me has pride,"
	.string "\lso I won't lose!$"

Unova_VictoryRoadCave1F_Text_AceTrainerFVictoryRoadCave1FSeenText::
	.string "Challenging the"
	.string "\nPOKéMON LEAGUE?"
	.string "\pIt's no wonder you"
	.string "\nmight feel a bit"
	.string "\pnervous, but you"
	.string "\njust have to"
	.string "\pbelieve in your"
	.string "\nPOKéMON and do it!$"

Unova_VictoryRoadCave1F_Text_VeteranMVictoryRoadCave1FSeenText::
	.string "You bothered to"
	.string "\ncome all the way"
	.string "\phere? Good! I will"
	.string "\nreward your hard"
	.string "\pwork by battling"
	.string "\nwith all of my"
	.string "\lstrength!$"

Unova_VictoryRoadCave1F_Text_VeteranFVictoryRoadCave1FSeenText::
	.string "Hey, since you"
	.string "\nworked so hard to"
	.string "\pget here, how"
	.string "\nabout I be your"
	.string "\lopponent?$"

Unova_VictoryRoadCave1F_Text_PsychicMVictoryRoadCave1FSeenText::
	.string "You… Who's brought"
	.string "\nyou this far?$"

Unova_VictoryRoadCave1F_Text_PsychicFVictoryRoadCave1FSeenText::
	.string "I'll use my psychic"
	.string "\npowers to release"
	.string "\pmy POKéMON from"
	.string "\nits POKéBALL!$"

Unova_VictoryRoadCave1F_Text_HexManiacVictoryRoadCave1FSeenText::
	.string "You are no ordin-"
	.string "\nary opponent…"
	.string "\pThat is what my"
	.string "\nghost type POKéMON"
	.string "\pis whispering to"
	.string "\nme.$"
