FloaromaTown_House2_MapScripts::
	.byte 0

FloaromaTown_House2_EventScript_PokefanF::
	msgbox FloaromaTown_House2_Text_PokefanF, MSGBOX_NPC
	end

FloaromaTown_House2_EventScript_PokefanM::
	msgbox FloaromaTown_House2_Text_PokefanM, MSGBOX_NPC
	end

FloaromaTown_House2_Text_PokefanF:
	.string "FLOAROMA TOWN smells like flowers\n"
	.string "all year round. I love it here.$"

FloaromaTown_House2_Text_PokefanM:
	.string "Have you visited the FLOWER SHOP yet?\n"
	.string "It's just down the road.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

FloaromaTown_House2_EventScript_Npc1::
	msgbox FloaromaTown_House2_Text_Npc1, MSGBOX_NPC
	end

FloaromaTown_House2_Text_Npc1:
	.string "Floaroma Town was a barren, desolate\nhill long ago, avoided even by Pokémon.\pPeople started planting flowers on it\nbecause it was such a sad place.\pBut nothing would grow...\nPeople didn't know what to do...\pAnd then one day, someone expressed\nthanks for the blessings of nature.\pThen, the whole hill burst into bloom.$"

FloaromaTown_House2_EventScript_Npc2::
	msgbox FloaromaTown_House2_Text_Npc2, MSGBOX_NPC
	end

FloaromaTown_House2_Text_Npc2:
	.string "Do you think it's cute how\nPokémon pluck Berries?$"

FloaromaTown_House2_EventScript_Npc3::
	msgbox FloaromaTown_House2_Text_Npc3, MSGBOX_NPC
	end

FloaromaTown_House2_Text_Npc3:
	.string "CLEFAIRY: Rii?$"
