FloaromaTown_House2_MapScripts::
	.byte 0

FloaromaTown_House2_EventScript_PokefanF::
	msgbox FloaromaTown_House2_Text_PokefanF, MSGBOX_NPC
	end

FloaromaTown_House2_EventScript_PokefanM::
	msgbox FloaromaTown_House2_Text_PokefanM, MSGBOX_NPC
	end

FloaromaTown_House2_Text_PokefanF:
	.string "FLOAROMA TOWN smells like flowers\n"
	.string "all year round. I love it here.$"

FloaromaTown_House2_Text_PokefanM:
	.string "Have you visited the FLOWER SHOP yet?\n"
	.string "It's just down the road.$"
