@ PetalburgCity_House3: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 8.7) por dev_scripts/copia_planta_ex.py.

PetalburgCity_House3_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 8.7), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
PetalburgCity_House3_EventScript_ExNpc0::
	msgbox PetalburgCity_House3_Text_ExNpc0, MSGBOX_NPC
	end

PetalburgCity_House3_Text_ExNpc0:
	.string "LEADER NORMAN is so cool.\p"
	.string "If only he wasn’t losing so much hair...$"

