@ PWTOutside do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_PWTOutside_MapScripts::
	.byte 0

Unova_PWTOutside_EventScript_Npc3::
	msgbox Unova_PWTOutside_Text_AskHiddenPowerText, MSGBOX_NPC
	end

Unova_PWTOutside_EventScript_Npc4::
	msgbox Unova_PWTOutside_Text_DVCheckerAskText, MSGBOX_NPC
	end

Unova_PWTOutside_EventScript_Npc5::
	msgbox Unova_PWTOutside_Text_PwtOutsideBugCatcherText, MSGBOX_NPC
	end

Unova_PWTOutside_EventScript_Npc6::
	msgbox Unova_PWTOutside_Text_PwtOutsideCooltrainerFText, MSGBOX_NPC
	end

Unova_PWTOutside_EventScript_Npc7::
	msgbox Unova_PWTOutside_Text_PwtOutsideCooltrainerMText, MSGBOX_NPC
	end

Unova_PWTOutside_EventScript_Npc8::
	msgbox Unova_PWTOutside_Text_PwtOutsideSailorText, MSGBOX_NPC
	end


Unova_PWTOutside_Text_AskHiddenPowerText::
	.string "I can sense the"
	.string "\nhidden potential"
	.string "\lof POKéMON."
	.string "\pWould you like me"
	.string "\nto tell you the"
	.string "\lhidden potential"
	.string "\lof your POKéMON?$"

Unova_PWTOutside_Text_DVCheckerAskText::
	.string "I can sense the"
	.string "\npotential of a"
	.string "\lPOKéMON's stats."
	.string "\pWould you like to"
	.string "\nknow your POKé-"
	.string "\lMON's potential?$"

Unova_PWTOutside_Text_PwtOutsideBugCatcherText::
	.string "Are you going to"
	.string "\ncompete in the"
	.string "\lTOURNAMENT?$"

Unova_PWTOutside_Text_PwtOutsideCooltrainerFText::
	.string "All the best"
	.string "\ntrainers in the"
	.string "\pregion come to"
	.string "\ncompete here."
	.string "\pI'm getting all"
	.string "\nfired up!$"

Unova_PWTOutside_Text_PwtOutsideCooltrainerMText::
	.string "I wonder who's"
	.string "\ngoing to be"
	.string "\lcompeting this"
	.string "\ltime."
	.string "\pSometimes the GYM"
	.string "\nLEADERs even"
	.string "\lcompete!$"

Unova_PWTOutside_Text_PwtOutsideSailorText::
	.string "Aye! We ship in"
	.string "\nmaterials from"
	.string "\pCASTELIA for the"
	.string "\nTOURNAMENT.$"
