@ Rt4NimbasaGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt4NimbasaGate_MapScripts::
	.byte 0

Unova_Rt4NimbasaGate_EventScript_Npc0::
	msgbox Unova_Rt4NimbasaGate_Text_R4NimbasaGatePokefanMText, MSGBOX_NPC
	end

Unova_Rt4NimbasaGate_EventScript_Npc1::
	msgbox Unova_Rt4NimbasaGate_Text_R4NimbasaGateYoungsterText, MSGBOX_NPC
	end


Unova_Rt4NimbasaGate_Text_R4NimbasaGatePokefanMText::
	.string "This place used to"
	.string "\nbe a shopping"
	.string "\pcenter called JOIN"
	.string "\nAVENUE."
	.string "\pBut after a few"
	.string "\nyears, vendors"
	.string "\lstarted to leave."
	.string "\pNow the place is"
	.string "\nabandoned.$"

Unova_Rt4NimbasaGate_Text_R4NimbasaGateYoungsterText::
	.string "I'm searching to"
	.string "\nsee if any of the"
	.string "\pvendors left any"
	.string "\nof their stuff"
	.string "\lbehind!$"
