UnusedOreburghCityNorthHouse3F_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

UnusedOreburghCityNorthHouse3F_EventScript_Npc1::
	msgbox UnusedOreburghCityNorthHouse3F_Text_Npc1, MSGBOX_NPC
	end

UnusedOreburghCityNorthHouse3F_Text_Npc1:
	.string "We'll keep digging coal.\nThe world needs energy!$"

UnusedOreburghCityNorthHouse3F_EventScript_Npc2::
	msgbox UnusedOreburghCityNorthHouse3F_Text_Npc2, MSGBOX_NPC
	end

UnusedOreburghCityNorthHouse3F_Text_Npc2:
	.string "During the daytime, everyone goes off\nto the mine.\pAt night, everyone's at home\ngetting some well-deserved rest.$"

UnusedOreburghCityNorthHouse3F_EventScript_Npc3::
	msgbox UnusedOreburghCityNorthHouse3F_Text_Npc3, MSGBOX_NPC
	end

UnusedOreburghCityNorthHouse3F_Text_Npc3:
	.string "Everyone, including lots of Pokémon,\ndug the big underground maze!$"
