// ponytail: ids de evento de Sinnoh, grupo "cavernas".
// Arquivo proprio por grupo: varios agentes escrevem em paralelo, e um arquivo
// unico virava corrida de escrita. Padrao: LOCALID_<MAPA>_<QUEM>, de 1 em diante
// dentro de cada mapa.

// MAP_ROUTE220

// MAP_ROUTE221
#define LOCALID_ROUTE221_SIGN_PAL_PARK 5

// MAP_ROUTE222
#define LOCALID_ROUTE222_SIGN_PIKACHU_FAN_CLUB 6
#define LOCALID_ROUTE222_SIGN_SIZE_CONTEST 7

// MAP_ROUTE223

// MAP_ROUTE224

// MAP_ROUTE225
#define LOCALID_ROUTE225_ACE_TRAINER_RODOLFO 1
#define LOCALID_ROUTE225_RANGER_ASHLEE 2
#define LOCALID_ROUTE225_BIRD_KEEPER_AUDREY 3
#define LOCALID_ROUTE225_DRAGON_TAMER_GEOFFREY 4
#define LOCALID_ROUTE225_ACE_TRAINER_QUINN 5
#define LOCALID_ROUTE225_SIGN_FIGHT_AREA 6
#define LOCALID_ROUTE225_SIGN_SURVIVAL_AREA 7

// MAP_ROUTE226
#define LOCALID_ROUTE226_SWIMMER_LYDIA 1
#define LOCALID_ROUTE226_ACE_TRAINER_GRAHAM 2
#define LOCALID_ROUTE226_BIRD_KEEPER_GENEVA 3
#define LOCALID_ROUTE226_SWIMMER_WADE 4
#define LOCALID_ROUTE226_SIGN_SURVIVAL_AREA 5

// MAP_ROUTE227
#define LOCALID_ROUTE227_ACE_TRAINER_SAUL 1
#define LOCALID_ROUTE227_RANGER_FELICIA 2
#define LOCALID_ROUTE227_BLACK_BELT_GRIFFIN 3
#define LOCALID_ROUTE227_ACE_TRAINER_MIKAYLA 4
#define LOCALID_ROUTE227_SIGN_ARROW 5

