// ponytail: ids de evento de Sinnoh, grupo "cidades".
// Arquivo proprio por grupo: varios agentes escrevem em paralelo, e um arquivo
// unico virava corrida de escrita. Padrao: LOCALID_<MAPA>_<QUEM>, de 1 em diante
// dentro de cada mapa.

// EternaCity
#define LOCALID_ETERNA_BREEDER_M       1
#define LOCALID_ETERNA_EXPERT          2
#define LOCALID_ETERNA_NINJA_BOY       3
#define LOCALID_ETERNA_BREEDER_F_1     4
#define LOCALID_ETERNA_ACE_TRAINER     5
#define LOCALID_ETERNA_BREEDER_F_2     6
#define LOCALID_ETERNA_BUG_CATCHER_1   7
#define LOCALID_ETERNA_BUG_CATCHER_2   8

// HearthomeCity
#define LOCALID_HEARTHOME_FISHERMAN     1
#define LOCALID_HEARTHOME_MR_GOODS      2
#define LOCALID_HEARTHOME_POKEFAN_M     3
#define LOCALID_HEARTHOME_BREEDER_F     4
#define LOCALID_HEARTHOME_BATTLE_GIRL_1 5
#define LOCALID_HEARTHOME_BATTLE_GIRL_2 6
#define LOCALID_HEARTHOME_HIKER         7
#define LOCALID_HEARTHOME_BLACK_BELT    8

// SolaceonTown
#define LOCALID_SOLACEON_COWGIRL_1    1
#define LOCALID_SOLACEON_DAYCARE_MAN  2
#define LOCALID_SOLACEON_RUIN_MANIAC  3
#define LOCALID_SOLACEON_RANCHER_1    4
#define LOCALID_SOLACEON_RANCHER_2    5
#define LOCALID_SOLACEON_COWGIRL_2    6

// CelesticTown
#define LOCALID_CELESTIC_EXPERT      1
#define LOCALID_CELESTIC_NINJA_BOY   2
#define LOCALID_CELESTIC_ACE_TRAINER 3

// VeilstoneCity
#define LOCALID_VEILSTONE_GUITARIST_1   1
#define LOCALID_VEILSTONE_POKEFAN_M     2
#define LOCALID_VEILSTONE_BATTLE_GIRL_1 3
#define LOCALID_VEILSTONE_LADY          4
#define LOCALID_VEILSTONE_BATTLE_GIRL_2 5
#define LOCALID_VEILSTONE_ROUGHNECK     6
#define LOCALID_VEILSTONE_GUITARIST_2   7
#define LOCALID_VEILSTONE_BATTLE_GIRL_3 8
#define LOCALID_VEILSTONE_GUITARIST_3   9

// PastoriaCity
#define LOCALID_PASTORIA_BLACK_BELT    1
#define LOCALID_PASTORIA_PARASOL_LADY  2
#define LOCALID_PASTORIA_PICNICKER     3
#define LOCALID_PASTORIA_ACE_TRAINER_1 4
#define LOCALID_PASTORIA_COLLECTOR_1   5
#define LOCALID_PASTORIA_SCIENTIST     6
#define LOCALID_PASTORIA_BEAUTY        7
#define LOCALID_PASTORIA_COLLECTOR_2   8
#define LOCALID_PASTORIA_ACE_TRAINER_2 9

// CanalaveCity
#define LOCALID_CANALAVE_COLLECTOR       1
#define LOCALID_CANALAVE_LASS            2
#define LOCALID_CANALAVE_BREEDER_M       3
#define LOCALID_CANALAVE_ACE_TRAINER     4
#define LOCALID_CANALAVE_OLD_MAN         5
#define LOCALID_CANALAVE_SAILOR_ELDRITCH 6

// SnowpointCity
#define LOCALID_SNOWPOINT_ACE_TRAINER  1
#define LOCALID_SNOWPOINT_NPC_M        2
#define LOCALID_SNOWPOINT_NPC_F_1      3
#define LOCALID_SNOWPOINT_SAILOR       4
#define LOCALID_SNOWPOINT_TEMPLE_GUARD 5
#define LOCALID_SNOWPOINT_NPC_F_2      6

