// ponytail: ids de evento de Sinnoh, grupo "interiores_h".

// MAP_OREBURGH_CITY_POKEMON_CENTER_1F
#define LOCALID_OREBURGH_PC1_NURSE 1

// MAP_OREBURGH_CITY_POKEMON_CENTER_2F
#define LOCALID_OREBURGH_PC2_TEALA_WEST 1
#define LOCALID_OREBURGH_PC2_TEALA_MIDDLE 2
#define LOCALID_OREBURGH_PC2_TEALA_EAST 3

// MAP_OREBURGH_CITY_MART
#define LOCALID_OREBURGH_MART_CASHIER 1

// MAP_FLOAROMA_TOWN_HOUSE1
#define LOCALID_FLOAROMA_HOUSE1_TWIN 1
#define LOCALID_FLOAROMA_HOUSE1_CLEFAIRY 2

// MAP_FLOAROMA_TOWN_HOUSE2
#define LOCALID_FLOAROMA_HOUSE2_POKEFAN_M 1

// MAP_FLOAROMA_TOWN_FLOWER_SHOP
#define LOCALID_FLOAROMA_FLOWERSHOP_BEAUTY 1
#define LOCALID_FLOAROMA_FLOWERSHOP_LASS 2
#define LOCALID_FLOAROMA_FLOWERSHOP_BREEDER 3

// MAP_FLOAROMA_TOWN_POKEMON_CENTER_1F
#define LOCALID_FLOAROMA_PC1_NURSE 1

// MAP_FLOAROMA_TWON_POKEMON_CENTER_2F
#define LOCALID_FLOAROMA_PC2_TEALA_WEST 1
#define LOCALID_FLOAROMA_PC2_TEALA_MIDDLE 2
#define LOCALID_FLOAROMA_PC2_TEALA_EAST 3

// MAP_FLOAROMA_TOWN_MART
#define LOCALID_FLOAROMA_MART_CASHIER 1
