// ponytail: ids de evento de Sinnoh, grupo "interiores_a".
// Arquivo proprio por grupo: varios agentes escrevem em paralelo, e um arquivo
// unico virava corrida de escrita. Padrao: LOCALID_<MAPA>_<QUEM>, de 1 em diante
// dentro de cada mapa.

// MAP_ROUTE228
#define LOCALID_ROUTE228_ACE_TRAINER_JOSE 1
#define LOCALID_ROUTE228_RANGER_KYLER 2
#define LOCALID_ROUTE228_DRAGON_TAMER_KEEGAN 3
#define LOCALID_ROUTE228_BLACK_BELT_DAVON 4

// MAP_ROUTE229
#define LOCALID_ROUTE229_POKEFAN 1
#define LOCALID_ROUTE229_RANGER_DESHAWN 2
#define LOCALID_ROUTE229_ACE_TRAINER_FELIX 3
#define LOCALID_ROUTE229_ACE_TRAINER_DANA 4

// MAP_ROUTE230
#define LOCALID_ROUTE230_SWIMMER_GLENN 1
#define LOCALID_ROUTE230_SWIMMER_JOANNA 2
#define LOCALID_ROUTE230_SWIMMER_KURT 3
#define LOCALID_ROUTE230_SWIMMER_SOPHIA 4

// MAP_VERITY_LAKEFRONT
#define LOCALID_VERITY_LAKEFRONT_HIKER 1
#define LOCALID_VERITY_LAKEFRONT_POKEFAN 2

// MAP_VALOR_LAKEFRONT
#define LOCALID_VALOR_LAKEFRONT_BEAUTY 1
#define LOCALID_VALOR_LAKEFRONT_TOURIST 2
#define LOCALID_VALOR_LAKEFRONT_POKEFAN 3

// MAP_ACUITY_LAKEFRONT
#define LOCALID_ACUITY_LAKEFRONT_HIKER 1
#define LOCALID_ACUITY_LAKEFRONT_POKEFAN 2
#define LOCALID_ACUITY_LAKEFRONT_LASS 3
#define LOCALID_ACUITY_LAKEFRONT_GENTLEMAN 4

// MAP_FIGHT_AREA
#define LOCALID_FIGHT_AREA_SAILOR 1
#define LOCALID_FIGHT_AREA_FISHERMAN 2
#define LOCALID_FIGHT_AREA_CAMPER 3
#define LOCALID_FIGHT_AREA_ACE_TRAINER_M 4
#define LOCALID_FIGHT_AREA_ACE_TRAINER_F 5
#define LOCALID_FIGHT_AREA_TWIN 6

// MAP_SURVIVAL_AREA
#define LOCALID_SURVIVAL_AREA_RUIN_MANIAC 1
#define LOCALID_SURVIVAL_AREA_BATTLE_GIRL 2
#define LOCALID_SURVIVAL_AREA_YOUNGSTER 3
#define LOCALID_SURVIVAL_AREA_CAMERAMAN 4
