// ponytail: ids de evento de Sinnoh, grupo "interiores_c".
// Arquivo proprio por grupo: varios agentes escrevem em paralelo, e um arquivo
// unico virava corrida de escrita. Padrao: LOCALID_<MAPA>_<QUEM>, de 1 em diante
// dentro de cada mapa.

// MAP_OREBURGH_GATE_1F
#define LOCALID_OREBURGH_GATE_1F_HIKER_1 1
#define LOCALID_OREBURGH_GATE_1F_HIKER_2 2

// MAP_OREBURGH_MINE_B1F
#define LOCALID_OREBURGH_MINE_B1F_MINER_1 1
#define LOCALID_OREBURGH_MINE_B1F_MINER_2 2

// MAP_OREBURGH_MINE_B2F
#define LOCALID_OREBURGH_MINE_B2F_MINER_1 1
#define LOCALID_OREBURGH_MINE_B2F_MINER_2 2

// MAP_RAVAGED_PATH
#define LOCALID_RAVAGED_PATH_RANGER 1
#define LOCALID_RAVAGED_PATH_HIKER 2
#define LOCALID_RAVAGED_PATH_CAMPER 3

// MAP_MT_CORONET_B1F
#define LOCALID_MT_CORONET_B1F_HIKER_1 1
#define LOCALID_MT_CORONET_B1F_HIKER_2 2

// MAP_MT_CORONET_1F_SOUTH
#define LOCALID_MT_CORONET_1F_SOUTH_HIKER_1 1
#define LOCALID_MT_CORONET_1F_SOUTH_BLACK_BELT 2
#define LOCALID_MT_CORONET_1F_SOUTH_HIKER_2 3

// MAP_MT_CORONET_1F_NORTH_ROOM1
#define LOCALID_MT_CORONET_1F_NORTH_ROOM1_HIKER_1 1
#define LOCALID_MT_CORONET_1F_NORTH_ROOM1_HIKER_2 2

// MAP_POKMON_LEAGUE
#define LOCALID_POKMON_LEAGUE_YOUNGSTER 1
#define LOCALID_POKMON_LEAGUE_STAFF 2
#define LOCALID_POKMON_LEAGUE_GENTLEMAN 3

// MAP_ROUTE206_NORTH
#define LOCALID_ROUTE206_NORTH_GUARD 1

// MAP_ROUTE206_SOUTH
#define LOCALID_ROUTE206_SOUTH_GUARD 1

// MAP_ROUTE208_ACCESS
#define LOCALID_ROUTE208_ACCESS_GUARD 1

// MAP_ROUTE209_ACCESS
#define LOCALID_ROUTE209_ACCESS_GUARD 1

