// ponytail: ids de evento de Sinnoh, grupo "interiores_g".

// MAP_JUBILIFE_CITY_POKEMON_CENTER_1F
#define LOCALID_JUBILIFE_PC1F_NURSE 1

// MAP_JUBILIFE_CITY_POKEMON_CENTER_2F
#define LOCALID_JUBILIFE_PC2F_CLERK_WEST 1
#define LOCALID_JUBILIFE_PC2F_CLERK_MID 2
#define LOCALID_JUBILIFE_PC2F_CLERK_EAST 3

// MAP_JUBILIFE_CITY_MART
#define LOCALID_JUBILIFE_MART_CASHIER 1

// MAP_OREBURGH_CITY_FLAT1_F1
#define LOCALID_OREBURGH_FLAT1_F1_HIKER 1
#define LOCALID_OREBURGH_FLAT1_F1_VISITOR 2

// MAP_OREBURGH_CITY_FLAT1_F2
#define LOCALID_OREBURGH_FLAT1_F2_YOUNGSTER 1
#define LOCALID_OREBURGH_FLAT1_F2_GENTLEMAN 2
#define LOCALID_OREBURGH_FLAT1_F2_SCIENTIST 3

// MAP_OREBURGH_CITY_FLAT2_F1
#define LOCALID_OREBURGH_FLAT2_F1_SCHOOLKID 1
#define LOCALID_OREBURGH_FLAT2_F1_BREEDER 2

// MAP_OREBURGH_CITY_FLAT2_F2
#define LOCALID_OREBURGH_FLAT2_F2_BREEDER 1

// MAP_OREBURGH_CITY_FLAT3_F1
#define LOCALID_OREBURGH_FLAT3_F1_YOUNGSTER 1
#define LOCALID_OREBURGH_FLAT3_F1_POKEFAN 2

// MAP_OREBURGH_CITY_FLAT3_F2
#define LOCALID_OREBURGH_FLAT3_F2_WORKER 1
#define LOCALID_OREBURGH_FLAT3_F2_SCHOOLKID 2
#define LOCALID_OREBURGH_FLAT3_F2_LASS 3

// MAP_OREBURGH_CITY_HOUSE1
#define LOCALID_OREBURGH_HOUSE1_WORKER 1

// MAP_OREBURGH_CITY_HOUSE2

// MAP_OREBURGH_CITY_HOUSE3
#define LOCALID_OREBURGH_HOUSE3_SCHOOLKID 1
#define LOCALID_OREBURGH_HOUSE3_HIKER 2

// MAP_OREBURGH_CITY_GYM
#define LOCALID_OREBURGH_GYM_VISITOR 1
