// ponytail: ids de evento de Sinnoh, grupo "rotas_leste".
// Arquivo proprio por grupo: varios agentes escrevem em paralelo, e um arquivo
// unico virava corrida de escrita. Padrao: LOCALID_<MAPA>_<QUEM>, de 1 em diante
// dentro de cada mapa.

// Route207
#define LOCALID_ROUTE207_CYCLIST     1
#define LOCALID_ROUTE207_CAMPER      2
#define LOCALID_ROUTE207_PICNICKER   3
#define LOCALID_ROUTE207_HIKER       4

// Route208
#define LOCALID_ROUTE208_BLACK_BELT  1
#define LOCALID_ROUTE208_HIKER       2
#define LOCALID_ROUTE208_BREEDER     3
#define LOCALID_ROUTE208_ARTIST      4

// Route209
#define LOCALID_ROUTE209_FISHERMAN   1
#define LOCALID_ROUTE209_BREEDER     2
#define LOCALID_ROUTE209_COWGIRL     3
#define LOCALID_ROUTE209_POKE_KID    4

// Route210_North
#define LOCALID_ROUTE210_NORTH_ACE_TRAINER_ERNEST  1
#define LOCALID_ROUTE210_NORTH_ACE_TRAINER_ALYSSA  2
#define LOCALID_ROUTE210_NORTH_VETERAN             3
#define LOCALID_ROUTE210_NORTH_BLACK_BELT           4

// Route210_South
#define LOCALID_ROUTE210_SOUTH_ACE_TRAINER   1
#define LOCALID_ROUTE210_SOUTH_BREEDER       2
#define LOCALID_ROUTE210_SOUTH_RANCHER       3
#define LOCALID_ROUTE210_SOUTH_BELLE         4

// Route211_East
#define LOCALID_ROUTE211_EAST_ACE_TRAINER    1
#define LOCALID_ROUTE211_EAST_BIRD_KEEPER    2
#define LOCALID_ROUTE211_EAST_BLACK_BELT     3
#define LOCALID_ROUTE211_EAST_RUIN_MANIAC    4

// Route211_West
#define LOCALID_ROUTE211_WEST_BIRD_KEEPER    1
#define LOCALID_ROUTE211_WEST_HIKER          2
#define LOCALID_ROUTE211_WEST_NINJA_BOY      3

// Route212_North
#define LOCALID_ROUTE212_NORTH_RICH_BOY   1
#define LOCALID_ROUTE212_NORTH_LADY       2
#define LOCALID_ROUTE212_NORTH_YOUNGSTER  3
#define LOCALID_ROUTE212_NORTH_COLLECTOR  4
