// ponytail: ids de evento de Sinnoh, grupo "rotas_norte".
// Arquivo proprio por grupo: varios agentes escrevem em paralelo, e um arquivo
// unico virava corrida de escrita. Padrao: LOCALID_<MAPA>_<QUEM>, de 1 em diante
// dentro de cada mapa.

#define LOCALID_ROUTE212_SOUTH_SCHOOL_KID 1
#define LOCALID_ROUTE212_SOUTH_LADY 2
#define LOCALID_ROUTE212_SOUTH_COLLECTOR 3
#define LOCALID_ROUTE212_SOUTH_FISHERMAN 4

#define LOCALID_ROUTE213_FISHERMAN 1
#define LOCALID_ROUTE213_BEAUTY 2
#define LOCALID_ROUTE213_COLLECTOR 3
#define LOCALID_ROUTE213_SAILOR 4

#define LOCALID_ROUTE214_RICH_BOY 1
#define LOCALID_ROUTE214_COLLECTOR 2
#define LOCALID_ROUTE214_HIKER 3
#define LOCALID_ROUTE214_PSYCHIC 4

#define LOCALID_ROUTE215_BLACK_BELT 1
#define LOCALID_ROUTE215_RUNNER 2
#define LOCALID_ROUTE215_COOLTRAINER 3
#define LOCALID_ROUTE215_HIKER 4

#define LOCALID_ROUTE216_SKIER 1
#define LOCALID_ROUTE216_ACE_TRAINER 2

#define LOCALID_ROUTE217_WOMAN 1
#define LOCALID_ROUTE217_NINJA_BOY 2
#define LOCALID_ROUTE217_BLACK_BELT 3

#define LOCALID_ROUTE218_GUITARIST 1
#define LOCALID_ROUTE218_FISHERMAN_WEST 2
#define LOCALID_ROUTE218_SAILOR 3
#define LOCALID_ROUTE218_FISHERMAN_EAST 4

#define LOCALID_ROUTE219_TUBER_M 1
#define LOCALID_ROUTE219_TUBER_F 2

