// ponytail: ids de evento de Sinnoh, grupo "rotas_oeste".
// Arquivo proprio por grupo: varios agentes escrevem em paralelo, e um arquivo
// unico virava corrida de escrita. Padrao: LOCALID_<MAPA>_<QUEM>, de 1 em diante
// dentro de cada mapa.

// Route201
#define LOCALID_ROUTE201_CASHIER      1
#define LOCALID_ROUTE201_SCHOOLKID    2
#define LOCALID_ROUTE201_LASS         3

// Route202
#define LOCALID_ROUTE202_YOUNGSTER    1
#define LOCALID_ROUTE202_TRISTAN      2
#define LOCALID_ROUTE202_NATALIE      3
#define LOCALID_ROUTE202_LOGAN        4

// Route203
#define LOCALID_ROUTE203_LASS         1
#define LOCALID_ROUTE203_SEBASTIAN    2
#define LOCALID_ROUTE203_MICHAEL      3
#define LOCALID_ROUTE203_KAITLIN      4
#define LOCALID_ROUTE203_DALLAS       5

// Route204
#define LOCALID_ROUTE204_ACE_TRAINER      1
#define LOCALID_ROUTE204_YOUNGSTER_NORTH  2
#define LOCALID_ROUTE204_BRANDON          3
#define LOCALID_ROUTE204_YOUNGSTER_SOUTH  4
#define LOCALID_ROUTE204_SARAH            5

// Route205_North
#define LOCALID_ROUTE205NORTH_FISHERMAN  1
#define LOCALID_ROUTE205NORTH_ANDREW     2
#define LOCALID_ROUTE205NORTH_JOSEPH     3
#define LOCALID_ROUTE205NORTH_ZACHARY    4

// Route205_South
#define LOCALID_ROUTE205SOUTH_BUGCATCHER  1
#define LOCALID_ROUTE205SOUTH_DANIEL      2
#define LOCALID_ROUTE205SOUTH_JACOB       3
#define LOCALID_ROUTE205SOUTH_SIENA       4
#define LOCALID_ROUTE205SOUTH_NICHOLAS    5

// Route206
#define LOCALID_ROUTE206_HIKER      1
#define LOCALID_ROUTE206_AXEL       2
#define LOCALID_ROUTE206_MEGAN      3
#define LOCALID_ROUTE206_JAMES      4
#define LOCALID_ROUTE206_THEODORE   5

// SunyshoreCity
#define LOCALID_SUNYSHORE_JASMINE     1
#define LOCALID_SUNYSHORE_SAILOR1     2
#define LOCALID_SUNYSHORE_POKEFAN_F   3
#define LOCALID_SUNYSHORE_BREEDER_F   4
#define LOCALID_SUNYSHORE_WORKER      5
#define LOCALID_SUNYSHORE_SAILOR2     6


// treinadores de Route203 (referencia de batalha)
#define LOCALID_ROUTE203_TRAINER1 21
#define LOCALID_ROUTE203_TRAINER2 22
#define LOCALID_ROUTE203_TRAINER3 23
#define LOCALID_ROUTE203_TRAINER4 24
#define LOCALID_ROUTE203_TRAINER5 25
