@ IcirrusCitySouth do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_IcirrusCitySouth_MapScripts::
	.byte 0

Unova_IcirrusCitySouth_EventScript_Placa0::
	msgbox Unova_IcirrusCitySouth_Text_IcirrusCitySignText, MSGBOX_SIGN
	end

Unova_IcirrusCitySouth_EventScript_Npc3::
	msgbox Unova_IcirrusCitySouth_Text_IcirrusCitySouthBuenaText, MSGBOX_NPC
	end

Unova_IcirrusCitySouth_EventScript_Npc4::
	msgbox Unova_IcirrusCitySouth_Text_IcirrusCitySouthFisherText, MSGBOX_NPC
	end

Unova_IcirrusCitySouth_EventScript_Npc5::
	msgbox Unova_IcirrusCitySouth_Text_IcirrusCitySouthPokefanMText, MSGBOX_NPC
	end


Unova_IcirrusCitySouth_Text_IcirrusCitySignText::
	.string "ICIRRUS CITY"
	.string "\pSky glittering"
	.string "\nwith flowers of"
	.string "\lsnow.$"

Unova_IcirrusCitySouth_Text_IcirrusCitySouthBuenaText::
	.string "If you walk in the"
	.string "\nwetlands, you"
	.string "\pmight surprise"
	.string "\nwild POKéMON into"
	.string "\lpopping out!$"

Unova_IcirrusCitySouth_Text_IcirrusCitySouthFisherText::
	.string "Two legendary"
	.string "\ndragons, awoken at"
	.string "\lthe tower…"
	.string "\pThe stories I"
	.string "\nheard when I was"
	.string "\plittle turned out"
	.string "\nto be true!$"

Unova_IcirrusCitySouth_Text_IcirrusCitySouthPokefanMText::
	.string "There used to be a"
	.string "\ncave here that led"
	.string "\lto TWIST MOUNTAIN."
	.string "\pBut all the"
	.string "\nconstruction"
	.string "\pcaused the"
	.string "\nentrance to"
	.string "\lcollapse…"
	.string "\pThe crews can"
	.string "\nstill get in and"
	.string "\pout through the"
	.string "\nother side, but it"
	.string "\pis a real"
	.string "\ninconvenience for"
	.string "\lus…$"
