@ NacreneHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_NacreneHouse_MapScripts::
	.byte 0

Unova_NacreneHouse_EventScript_Npc0::
	msgbox Unova_NacreneHouse_Text_NacreneHouseGiveCharcoalText, MSGBOX_NPC
	end


Unova_NacreneHouse_Text_NacreneHouseGiveCharcoalText::
	.string "Hi, did you come"
	.string "\nto see my art?"
	.string "\pNACRENE CITY has a"
	.string "\nlively scene for"
	.string "\llocal artists."
	.string "\pHere, you should"
	.string "\ntry too, take"
	.string "\lthis!$"
