JubilifeCity_Flat3_F3_MapScripts::
	.byte 0

JubilifeCity_Flat3_F3_EventScript_Youngster::
	msgbox JubilifeCity_Flat3_F3_Text_Youngster, MSGBOX_NPC
	end

JubilifeCity_Flat3_F3_EventScript_OldMan::
	msgbox JubilifeCity_Flat3_F3_Text_OldMan, MSGBOX_NPC
	end

JubilifeCity_Flat3_F3_Text_Youngster:
	.string "Top floor is quiet.\p"
	.string "Perfect for letting my\n"
	.string "POKéMON rest.$"

JubilifeCity_Flat3_F3_Text_OldMan:
	.string "I've lived in this building\n"
	.string "longer than anyone.\p"
	.string "Never gets old, watching the\n"
	.string "city change.$"
