Villa_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

Villa_EventScript_Placa1::
	msgbox Villa_Text_Placa1, MSGBOX_SIGN
	end

Villa_Text_Placa1:
	.string "{PLAYER} opened the order form.$"

Villa_EventScript_Placa2::
	msgbox Villa_Text_Placa2, MSGBOX_SIGN
	end

Villa_Text_Placa2:
	.string "{PLAYER} opened the order form.$"

Villa_EventScript_Placa3::
	msgbox Villa_Text_Placa3, MSGBOX_SIGN
	end

Villa_Text_Placa3:
	.string "{PLAYER} opened the order form.$"
