@ ReversalMountainB1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_ReversalMountainB1F_MapScripts::
	.byte 0

Unova_ReversalMountainB1F_EventScript_Npc3::
	msgbox Unova_ReversalMountainB1F_Text_Hiker1ReversalSeenText, MSGBOX_NPC
	end

Unova_ReversalMountainB1F_EventScript_Npc4::
	msgbox Unova_ReversalMountainB1F_Text_BattleGirlReversalSeenText, MSGBOX_NPC
	end


Unova_ReversalMountainB1F_Text_Hiker1ReversalSeenText::
	.string "Me and my POKéMON"
	.string "\nare professional"
	.string "\ptunnellers! We"
	.string "\nhave no rival!$"

Unova_ReversalMountainB1F_Text_BattleGirlReversalSeenText::
	.string "I can feel the"
	.string "\nenergy that over-"
	.string "\pflows from the"
	.string "\nearth!$"
