IronRuins_MapScripts::
	.byte 0

IronRuins_EventScript_Placa1::
	msgbox IronRuins_Text_Placa1, MSGBOX_SIGN
	end

IronRuins_Text_Placa1:
	.string "Something changed in the air...\pAn indescribable power is emanating\nfrom the Pokémon statue...$"

IronRuins_EventScript_Placa2::
	msgbox IronRuins_Text_Placa2, MSGBOX_SIGN
	end

IronRuins_Text_Placa2:
	.string "Something changed in the air...\pAn indescribable power is emanating\nfrom the Pokémon statue...$"

IronRuins_EventScript_Placa3::
	msgbox IronRuins_Text_Placa3, MSGBOX_SIGN
	end

IronRuins_Text_Placa3:
	.string "Something changed in the air...\pAn indescribable power is emanating\nfrom the Pokémon statue...$"
