IronRuins_MapScripts::
	.byte 0

@ >>> B6 Sinnoh S1: esqueletos de cena (dev_scripts/maquina_sinnoh.py) >>>
IronRuins_EventScript_DotEast::
	@ TODO S?: cena da fonte, rotulo IronRuins_DotEast
	end

IronRuins_EventScript_DotMiddle::
	@ TODO S?: cena da fonte, rotulo IronRuins_DotMiddle
	end

IronRuins_EventScript_DotNorthEast::
	@ TODO S?: cena da fonte, rotulo IronRuins_DotNorthEast
	end

IronRuins_EventScript_DotNorthWest::
	@ TODO S?: cena da fonte, rotulo IronRuins_DotNorthWest
	end

IronRuins_EventScript_DotSouthEast::
	@ TODO S?: cena da fonte, rotulo IronRuins_DotSouthEast
	end

IronRuins_EventScript_DotSouthWest::
	@ TODO S?: cena da fonte, rotulo IronRuins_DotSouthWest
	end

IronRuins_EventScript_DotWest::
	@ TODO S?: cena da fonte, rotulo IronRuins_DotWest
	end

@ <<< B6 Sinnoh S1: esqueletos de cena <<<

IronRuins_EventScript_Placa1::
	msgbox IronRuins_Text_Placa1, MSGBOX_SIGN
	end

IronRuins_Text_Placa1:
	.string "Something changed in the air...\pAn indescribable power is emanating\nfrom the Pokémon statue...$"

IronRuins_EventScript_Placa2::
	msgbox IronRuins_Text_Placa2, MSGBOX_SIGN
	end

IronRuins_Text_Placa2:
	.string "Something changed in the air...\pAn indescribable power is emanating\nfrom the Pokémon statue...$"

IronRuins_EventScript_Placa3::
	msgbox IronRuins_Text_Placa3, MSGBOX_SIGN
	end

IronRuins_Text_Placa3:
	.string "Something changed in the air...\pAn indescribable power is emanating\nfrom the Pokémon statue...$"
