@ DewfordTown_Ex3_9: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 3.9) por dev_scripts/copia_planta_ex.py.

DewfordTown_Ex3_9_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 3.9), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
DewfordTown_Ex3_9_EventScript_ExNpc0::
	msgbox DewfordTown_Ex3_9_Text_ExNpc0, MSGBOX_NPC
	end

DewfordTown_Ex3_9_Text_ExNpc0:
	.string "This island is so small.\n"
	.string "I wish I could live in a big city! I bet\l"
	.string "my life would be super exciting!$"

DewfordTown_Ex3_9_EventScript_ExNpc1::
	msgbox DewfordTown_Ex3_9_Text_ExNpc1, MSGBOX_NPC
	end

DewfordTown_Ex3_9_Text_ExNpc1:
	.string "Living out on this island sure makes the\n"
	.string "commute to work easier!$"

DewfordTown_Ex3_9_EventScript_ExNpc2::
	msgbox DewfordTown_Ex3_9_Text_ExNpc2, MSGBOX_NPC
	end

DewfordTown_Ex3_9_Text_ExNpc2:
	.string "There’s a man named STEVEN that comes\n"
	.string "by sometimes.\p"
	.string "He spends a lot of time in GRANITE CAVE\n"
	.string "catching POKéMON.$"

