@ CasteliaBikeShop do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_CasteliaBikeShop_MapScripts::
	.byte 0

Unova_CasteliaBikeShop_EventScript_Placa0::
	msgbox Unova_CasteliaBikeShop_Text_CasteliaBikeShopBicycleText, MSGBOX_SIGN
	end

Unova_CasteliaBikeShop_EventScript_Placa1::
	msgbox Unova_CasteliaBikeShop_Text_CasteliaBikeShopBicycleText, MSGBOX_SIGN
	end

Unova_CasteliaBikeShop_EventScript_Placa2::
	msgbox Unova_CasteliaBikeShop_Text_CasteliaBikeShopBicycleText, MSGBOX_SIGN
	end

Unova_CasteliaBikeShop_EventScript_Placa3::
	msgbox Unova_CasteliaBikeShop_Text_CasteliaBikeShopBicycleText, MSGBOX_SIGN
	end

Unova_CasteliaBikeShop_EventScript_Placa4::
	msgbox Unova_CasteliaBikeShop_Text_CasteliaBikeShopBicycleText, MSGBOX_SIGN
	end

Unova_CasteliaBikeShop_EventScript_Placa5::
	msgbox Unova_CasteliaBikeShop_Text_CasteliaBikeShopBicycleText, MSGBOX_SIGN
	end

Unova_CasteliaBikeShop_EventScript_Placa6::
	msgbox Unova_CasteliaBikeShop_Text_CasteliaBikeShopBicycleText, MSGBOX_SIGN
	end

Unova_CasteliaBikeShop_EventScript_Placa7::
	msgbox Unova_CasteliaBikeShop_Text_CasteliaBikeShopBicycleText, MSGBOX_SIGN
	end

Unova_CasteliaBikeShop_EventScript_Placa8::
	msgbox Unova_CasteliaBikeShop_Text_CasteliaBikeShopBicycleText, MSGBOX_SIGN
	end

Unova_CasteliaBikeShop_EventScript_Npc0::
	msgbox Unova_CasteliaBikeShop_Text_CasteliaBikeShopClerkIntroText, MSGBOX_NPC
	end


Unova_CasteliaBikeShop_Text_CasteliaBikeShopBicycleText::
	.string "It's a shiny new"
	.string "\nBICYCLE!$"

Unova_CasteliaBikeShop_Text_CasteliaBikeShopClerkIntroText::
	.string "…sigh… Welcome to"
	.string "\nCASTELIA CYCLES."
	.string "\pWe sell BICYCLES,"
	.string "\nbut they've gotten"
	.string "\pmuch less popular"
	.string "\nsince RUNNING"
	.string "\lSHOES became about"
	.string "\las fast as biking…"
	.string "\pWill you take one"
	.string "\nof our bikes and"
	.string "\pride it to drum"
	.string "\nup sales?$"
