Cafe_MapScripts::
	.byte 0

Cafe_EventScript_Npc1::
	msgbox Cafe_Text_Npc1, MSGBOX_NPC
	end

Cafe_Text_Npc1:
	.string "How are ya doing?\nWhatcha having?\pCourse, all we ever have is\nMoomoo Milk.\pMoomoo Milk, $500 a bottle.\pWould you like to add some to your\ntraveling supplies?$"

Cafe_EventScript_Npc2::
	msgbox Cafe_Text_Npc2, MSGBOX_NPC
	end

Cafe_Text_Npc2:
	.string "Youngster, you've seen the\nPSYDUCK huddled outside?\pPSYDUCK are Pokémon that suffer from\nchronic headaches...\pI'm afraid we'll have to wait for them\nto get better.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

Cafe_EventScript_Npc1::
	msgbox Cafe_Text_Npc1, MSGBOX_NPC
	end

Cafe_Text_Npc1:
	.string "Howdy, traveler!\pSome of our customers are rowdy\ntypes that want to battle.\pDo what you will with them.\nI don't mind.$"
