OreburghCity_Flat3_F1_MapScripts::
	.byte 0

OreburghCity_Flat3_F1_EventScript_Breeder::
	msgbox OreburghCity_Flat3_F1_Text_Breeder, MSGBOX_NPC
	end

OreburghCity_Flat3_F1_EventScript_Youngster::
	msgbox OreburghCity_Flat3_F1_Text_Youngster, MSGBOX_NPC
	end

OreburghCity_Flat3_F1_EventScript_Pokefan::
	msgbox OreburghCity_Flat3_F1_Text_Pokefan, MSGBOX_NPC
	end

OreburghCity_Flat3_F1_Text_Breeder:
	.string "This flat isn't much, but the rent\n"
	.string "is cheap and the MINE is close.$"

OreburghCity_Flat3_F1_Text_Youngster:
	.string "Have you been to the GYM yet? I\n"
	.string "hear the LEADER uses ROCK types.$"

OreburghCity_Flat3_F1_Text_Pokefan:
	.string "OREBURGH is small, but I love it\n"
	.string "here. Everyone knows everyone.$"
