OreburghCity_Flat3_F1_MapScripts::
	.byte 0

OreburghCity_Flat3_F1_EventScript_Breeder::
	msgbox OreburghCity_Flat3_F1_Text_Breeder, MSGBOX_NPC
	end

OreburghCity_Flat3_F1_EventScript_Youngster::
	msgbox OreburghCity_Flat3_F1_Text_Youngster, MSGBOX_NPC
	end

OreburghCity_Flat3_F1_EventScript_Pokefan::
	msgbox OreburghCity_Flat3_F1_Text_Pokefan, MSGBOX_NPC
	end

OreburghCity_Flat3_F1_Text_Breeder:
	.string "This flat isn't much, but the rent\n"
	.string "is cheap and the MINE is close.$"

OreburghCity_Flat3_F1_Text_Youngster:
	.string "Have you been to the GYM yet? I\n"
	.string "hear the LEADER uses ROCK types.$"

OreburghCity_Flat3_F1_Text_Pokefan:
	.string "OREBURGH is small, but I love it\n"
	.string "here. Everyone knows everyone.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

OreburghCity_Flat3_F1_EventScript_Npc1::
	msgbox OreburghCity_Flat3_F1_Text_Npc1, MSGBOX_NPC
	end

OreburghCity_Flat3_F1_Text_Npc1:
	.string "Hiya! Your Pokémon could use some\ntoughening up.\pWhy not try training in\nthe Oreburgh Mine?$"

OreburghCity_Flat3_F1_EventScript_Npc2::
	msgbox OreburghCity_Flat3_F1_Text_Npc2, MSGBOX_NPC
	end

OreburghCity_Flat3_F1_Text_Npc2:
	.string "I always have a rotten time trying\nto decide which moves my Pokémon\pshould learn.$"

OreburghCity_Flat3_F1_EventScript_Npc3::
	msgbox OreburghCity_Flat3_F1_Text_Npc3, MSGBOX_NPC
	end

OreburghCity_Flat3_F1_Text_Npc3:
	.string "You remind me so much of the time\nI got my first Pokémon.$"
