@ PinwheelBridgeGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_PinwheelBridgeGate_MapScripts::
	.byte 0

Unova_PinwheelBridgeGate_EventScript_Npc0::
	msgbox Unova_PinwheelBridgeGate_Text_PinwheelBridgeGateOfficerText, MSGBOX_NPC
	end


Unova_PinwheelBridgeGate_Text_PinwheelBridgeGateOfficerText::
	.string "Be careful not to"
	.string "\nget lost in the"
	.string "\lforest."
	.string "\pStick to the road"
	.string "\nto get to town.$"
