GameCorner_MapScripts::
	.byte 0

GameCorner_EventScript_Npc1::
	msgbox GameCorner_Text_Npc1, MSGBOX_NPC
	end

GameCorner_Text_Npc1:
	.string "Welcome to the Veilstone Game Corner!$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

GameCorner_EventScript_Npc1::
	msgbox GameCorner_Text_Npc1, MSGBOX_NPC
	end

GameCorner_Text_Npc1:
	.string "I'll explain how the slot machines\nwork at this Game Corner.\pDuring regular play, you should\nstop the reels from the left.\pDuring the bonus round, watch\nwhere CLEFAIRY points and stop\pthe reels in that order.$"

GameCorner_EventScript_Npc2::
	msgbox GameCorner_Text_Npc2, MSGBOX_NPC
	end

GameCorner_Text_Npc2:
	.string "I've been winning a ton today.\nHere, take some Coins!\p{PLAYER} received 20 Coins\nfrom the man.\p{PLAYER} put the Coins away in\nthe Coin Case.$"

GameCorner_EventScript_Npc3::
	msgbox GameCorner_Text_Npc3, MSGBOX_NPC
	end

GameCorner_Text_Npc3:
	.string "Woohoo! CLEFAIRY! Look!\nYeahah! It's a carnival!\pLet me share some of my joy with\nyou!\p{PLAYER} received 50 Coins\nfrom the man.\p{PLAYER} put the Coins away in\nthe Coin Case.$"

GameCorner_EventScript_Npc4::
	msgbox GameCorner_Text_Npc4, MSGBOX_NPC
	end

GameCorner_Text_Npc4:
	.string "A friend in my group scored a ton of\nCoins here.\pWhy mess with a good thing?\nI'll try the same spot, too!$"

GameCorner_EventScript_Npc5::
	msgbox GameCorner_Text_Npc5, MSGBOX_NPC
	end

GameCorner_Text_Npc5:
	.string "I want Coins, of course, but\nsetting records is hot, too!$"

GameCorner_EventScript_Npc6::
	msgbox GameCorner_Text_Npc6, MSGBOX_NPC
	end

GameCorner_Text_Npc6:
	.string "When a Poké Ball appears, it's a\nchance to line up slot marks.\pReplays and PIKACHU line up even if\nyou don't make an effort.\pBut you need to aim for better marks,\nlike Poké Balls and Moon Stones.$"

GameCorner_EventScript_Npc7::
	msgbox GameCorner_Text_Npc7, MSGBOX_NPC
	end

GameCorner_Text_Npc7:
	.string "Sigh...\nNothing's going my way today...\pAre you a Trainer?\nDid you battle the Gym Leader?\pShe happens to be my daughter.\nShe's some kind of tough!$"
