Route228GateToRoute226_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

Route228GateToRoute226_EventScript_Npc1::
	msgbox Route228GateToRoute226_Text_Npc1, MSGBOX_NPC
	end

Route228GateToRoute226_Text_Npc1:
	.string "I've been wondering about this, but\nno one can tell me.\pWhy doesn't anyone study the molting\nof Pokémon?\pI think there would be a lot you could\ntell from their molts.$"

Route228GateToRoute226_EventScript_Npc2::
	msgbox Route228GateToRoute226_Text_Npc2, MSGBOX_NPC
	end

Route228GateToRoute226_Text_Npc2:
	.string "A strong, but a solitary presence...\nOr the weak that mass together...\pWho can say which is better?$"
