@ CasteliaPort do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_CasteliaPort_MapScripts::
	.byte 0

Unova_CasteliaPort_EventScript_Npc0::
	msgbox Unova_CasteliaPort_Text_CasteliaPortRideText, MSGBOX_NPC
	end


Unova_CasteliaPort_Text_CasteliaPortRideText::
	.string "We'll soon set"
	.string "\nsail for VIRBANK."
	.string "\pAre you coming on"
	.string "\nboard?$"
