@ MistraltonCave1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_MistraltonCave1F_MapScripts::
	.byte 0

Unova_MistraltonCave1F_EventScript_Npc5::
	msgbox Unova_MistraltonCave1F_Text_Hiker1MistraltonCaveSeenText, MSGBOX_NPC
	end

Unova_MistraltonCave1F_EventScript_Npc6::
	msgbox Unova_MistraltonCave1F_Text_Hiker2MistraltonCaveSeenText, MSGBOX_NPC
	end


Unova_MistraltonCave1F_Text_Hiker1MistraltonCaveSeenText::
	.string "Whooo! Mountain!!$"

Unova_MistraltonCave1F_Text_Hiker2MistraltonCaveSeenText::
	.string "I'll knock you"
	.string "\ndown with mountain"
	.string "\lpower!$"
