@ AspertiaSubway do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_AspertiaSubway_MapScripts::
	.byte 0

Unova_AspertiaSubway_EventScript_Npc0::
	msgbox Unova_AspertiaSubway_Text_AspertiaSubwayRideText, MSGBOX_NPC
	end

Unova_AspertiaSubway_EventScript_Npc1::
	msgbox Unova_AspertiaSubway_Text_AspertiaSubwayGrampsText, MSGBOX_NPC
	end

Unova_AspertiaSubway_EventScript_Npc2::
	msgbox Unova_AspertiaSubway_Text_AspertiaSubwayLassText, MSGBOX_NPC
	end


Unova_AspertiaSubway_Text_AspertiaSubwayRideText::
	.string "We'll soon depart"
	.string "\nfor NIMBASA."
	.string "\pAre you coming on"
	.string "\nboard?$"

Unova_AspertiaSubway_Text_AspertiaSubwayGrampsText::
	.string "The new subway has"
	.string "\nmade it so much"
	.string "\peasier for me to"
	.string "\nget back and forth"
	.string "\pbetween home and"
	.string "\nthe big city!$"

Unova_AspertiaSubway_Text_AspertiaSubwayLassText::
	.string "Hi. Do you have a"
	.string "\nRAIL PASS? I have"
	.string "\pone. All the peo-"
	.string "\nple in ASPERTIA"
	.string "\pwho ride the sub-"
	.string "\nway have PASSES.$"
