CanalaveLibrary1F_MapScripts::
	.byte 0

CanalaveLibrary1F_EventScript_Npc1::
	msgbox CanalaveLibrary1F_Text_Npc1, MSGBOX_NPC
	end

CanalaveLibrary1F_Text_Npc1:
	.string "Hello.\nThis is the Canalave Library.\pPlease keep quiet while you're on\nthe premises.$"

CanalaveLibrary1F_EventScript_Npc2::
	msgbox CanalaveLibrary1F_Text_Npc2, MSGBOX_NPC
	end

CanalaveLibrary1F_Text_Npc2:
	.string "...$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

CanalaveLibrary1F_EventScript_Placa1::
	msgbox CanalaveLibrary1F_Text_Placa1, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa1:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary1F_EventScript_Placa2::
	msgbox CanalaveLibrary1F_Text_Placa2, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa2:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary1F_EventScript_Placa3::
	msgbox CanalaveLibrary1F_Text_Placa3, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa3:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary1F_EventScript_Placa4::
	msgbox CanalaveLibrary1F_Text_Placa4, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa4:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary1F_EventScript_Placa5::
	msgbox CanalaveLibrary1F_Text_Placa5, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa5:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary1F_EventScript_Placa6::
	msgbox CanalaveLibrary1F_Text_Placa6, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa6:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary1F_EventScript_Placa7::
	msgbox CanalaveLibrary1F_Text_Placa7, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa7:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary1F_EventScript_Placa8::
	msgbox CanalaveLibrary1F_Text_Placa8, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa8:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary1F_EventScript_Placa9::
	msgbox CanalaveLibrary1F_Text_Placa9, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa9:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary1F_EventScript_Placa10::
	msgbox CanalaveLibrary1F_Text_Placa10, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa10:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary1F_EventScript_Placa11::
	msgbox CanalaveLibrary1F_Text_Placa11, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa11:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary1F_EventScript_Placa12::
	msgbox CanalaveLibrary1F_Text_Placa12, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa12:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary1F_EventScript_Placa13::
	msgbox CanalaveLibrary1F_Text_Placa13, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa13:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary1F_EventScript_Placa14::
	msgbox CanalaveLibrary1F_Text_Placa14, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa14:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary1F_EventScript_Placa15::
	msgbox CanalaveLibrary1F_Text_Placa15, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa15:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary1F_EventScript_Placa16::
	msgbox CanalaveLibrary1F_Text_Placa16, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa16:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary1F_EventScript_Placa17::
	msgbox CanalaveLibrary1F_Text_Placa17, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa17:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary1F_EventScript_Placa18::
	msgbox CanalaveLibrary1F_Text_Placa18, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa18:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary1F_EventScript_Placa19::
	msgbox CanalaveLibrary1F_Text_Placa19, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa19:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary1F_EventScript_Placa20::
	msgbox CanalaveLibrary1F_Text_Placa20, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa20:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary1F_EventScript_Placa21::
	msgbox CanalaveLibrary1F_Text_Placa21, MSGBOX_SIGN
	end

CanalaveLibrary1F_Text_Placa21:
	.string "The shelves are lined with books\nworn from being read by many people.$"
