@ TwistMountain3F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_TwistMountain3F_MapScripts::
	.byte 0

Unova_TwistMountain3F_EventScript_Npc1::
	msgbox Unova_TwistMountain3F_Text_Worker1TwistMountain3FSeenText, MSGBOX_NPC
	end

Unova_TwistMountain3F_EventScript_Npc2::
	msgbox Unova_TwistMountain3F_Text_Worker2TwistMountain3FSeenText, MSGBOX_NPC
	end

Unova_TwistMountain3F_EventScript_Npc3::
	msgbox Unova_TwistMountain3F_Text_VeteranFTwistMountain3FSeenText, MSGBOX_NPC
	end


Unova_TwistMountain3F_Text_Worker1TwistMountain3FSeenText::
	.string "TWIST MOUNTAIN has"
	.string "\nchanged over the"
	.string "\pyears, and this"
	.string "\nman changes in"
	.string "\levery battle!$"

Unova_TwistMountain3F_Text_Worker2TwistMountain3FSeenText::
	.string "Let's see you take"
	.string "\na powerful attack"
	.string "\pfrom veteran"
	.string "\nWORKERs like us!$"

Unova_TwistMountain3F_Text_VeteranFTwistMountain3FSeenText::
	.string "TWIST MOUNTAIN's"
	.string "\nnumber one"
	.string "\ptactician! That's"
	.string "\nme!$"
