SnowpointCityWestHouse_MapScripts::
	.byte 0

SnowpointCityWestHouse_EventScript_Npc1::
	msgbox SnowpointCityWestHouse_Text_Npc1, MSGBOX_NPC
	end

SnowpointCityWestHouse_Text_Npc1:
	.string "I love how my girl has so much\nvivacity and charm.$"

SnowpointCityWestHouse_EventScript_Npc2::
	msgbox SnowpointCityWestHouse_Text_Npc2, MSGBOX_NPC
	end

SnowpointCityWestHouse_Text_Npc2:
	.string "By any chance, do you have a Pokémon\ncalled MEDICHAM?\pIf you do, would you like to trade\nyour MEDICHAM for my HAUNTER?$"
