SafariZone_North_MapScripts::
	.byte 0

SafariZone_North_EventScript_Fisherman::
	msgbox SafariZone_North_Text_Fisherman, MSGBOX_NPC
	end

SafariZone_North_EventScript_Man::
	msgbox SafariZone_North_Text_Man, MSGBOX_NPC
	end


@ Eventos novos do Pokémon Emerald EX (mapa 29.1), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
SafariZone_North_EventScript_ExNpc10::
	msgbox SafariZone_North_Text_ExNpc10, MSGBOX_NPC
	end

SafariZone_North_Text_ExNpc10:
	.string "Isn’t it nice how tame all the POKéMON\n"
	.string "are here.$"

