MtCoronet_1F_North_Room1_MapScripts::
	.byte 0

MtCoronet_1F_North_Room1_EventScript_Hiker1::
	msgbox MtCoronet_1F_North_Room1_Text_Hiker1, MSGBOX_NPC
	end

MtCoronet_1F_North_Room1_EventScript_Hiker2::
	msgbox MtCoronet_1F_North_Room1_Text_Hiker2, MSGBOX_NPC
	end

MtCoronet_1F_North_Room1_Text_Hiker1:
	.string "Strange, the fog rolls in thick\n"
	.string "around here.\p"
	.string "Never seen anything like it.$"

MtCoronet_1F_North_Room1_Text_Hiker2:
	.string "I got turned around in here\n"
	.string "earlier.\p"
	.string "Glad to see another face.$"
