@ VerdanturfTown_Ex6_13: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 6.13) por dev_scripts/copia_planta_ex.py.

VerdanturfTown_Ex6_13_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 6.13), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
VerdanturfTown_Ex6_13_EventScript_ExNpc0::
	msgbox VerdanturfTown_Ex6_13_Text_ExNpc0, MSGBOX_NPC
	end

VerdanturfTown_Ex6_13_Text_ExNpc0:
	.string "Hey!\n"
	.string "Go Away!\p"
	.string "I’m playing hide and seek\n"
	.string "You’ll give me away!$"

