@ NimbasaParkOutside do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_NimbasaParkOutside_MapScripts::
	.byte 0

Unova_NimbasaParkOutside_EventScript_Npc3::
	msgbox Unova_NimbasaParkOutside_Text_NimbasaParkOutsideBlockerText, MSGBOX_NPC
	end

Unova_NimbasaParkOutside_EventScript_Npc4::
	msgbox Unova_NimbasaParkOutside_Text_NimbasaParkOutsideNateRosaText, MSGBOX_NPC
	end

Unova_NimbasaParkOutside_EventScript_Npc5::
	msgbox Unova_NimbasaParkOutside_Text_NimbasaParkOutsideNateRosaText, MSGBOX_NPC
	end


Unova_NimbasaParkOutside_Text_NimbasaParkOutsideBlockerText::
	.string "Hey! Don't you"
	.string "\nknow the PARK's"
	.string "\ldangerous?"
	.string "\pGo on, get out"
	.string "\nof here!$"

Unova_NimbasaParkOutside_Text_NimbasaParkOutsideNateRosaText::
	.string "...$"
