FuegoIronworksBuilding_MapScripts::
	.byte 0

FuegoIronworksBuilding_EventScript_Npc1::
	msgbox FuegoIronworksBuilding_Text_Npc1, MSGBOX_NPC
	end

FuegoIronworksBuilding_Text_Npc1:
	.string "Mr. Fuego: Well, hello!\nIt's not often I get a visitor here.\pI tried to make the ironworks run\nbetter with the moving floor tiles.\pBut no one was happy about it! They\nsaid the moving floor made them dizzy!\pBut you don't want to listen to me\nwhine. Here's a souvenir!$"
