@ ChargestoneCaveB2F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_ChargestoneCaveB2F_MapScripts::
	.byte 0

Unova_ChargestoneCaveB2F_EventScript_Npc3::
	msgbox Unova_ChargestoneCaveB2F_Text_Guitarist2ChargestoneSeenText, MSGBOX_NPC
	end

Unova_ChargestoneCaveB2F_EventScript_Npc4::
	msgbox Unova_ChargestoneCaveB2F_Text_Hiker3ChargestoneSeenText, MSGBOX_NPC
	end

Unova_ChargestoneCaveB2F_EventScript_Npc5::
	msgbox Unova_ChargestoneCaveB2F_Text_AceTrainerM2ChargestoneSeenText, MSGBOX_NPC
	end


Unova_ChargestoneCaveB2F_Text_Guitarist2ChargestoneSeenText::
	.string "Here I go!$"

Unova_ChargestoneCaveB2F_Text_Hiker3ChargestoneSeenText::
	.string "It is the way of"
	.string "\ngreeting high in"
	.string "\pthe mountains and"
	.string "\ndown in the caves."
	.string "\pThat's right! We"
	.string "\neach get our POKé-"
	.string "\lMON, and begin!$"

Unova_ChargestoneCaveB2F_Text_AceTrainerM2ChargestoneSeenText::
	.string "I researched on"
	.string "\nthe PC the best"
	.string "\pway to battle, and"
	.string "\nnow I'm sure to"
	.string "\lwin!$"
