BattleFrontierGateToFightArea_MapScripts::
	.byte 0

BattleFrontierGateToFightArea_EventScript_Npc1::
	msgbox BattleFrontierGateToFightArea_Text_Npc1, MSGBOX_NPC
	end

BattleFrontierGateToFightArea_Text_Npc1:
	.string "Welcome to the Battle Frontier!\pShould I explain how the Battle Castle\nworks?$"

BattleFrontierGateToFightArea_EventScript_Npc2::
	msgbox BattleFrontierGateToFightArea_Text_Npc2, MSGBOX_NPC
	end

BattleFrontierGateToFightArea_Text_Npc2:
	.string "Welcome to the Battle Frontier!\pShould I explain how the Battle Factory\nworks?$"

BattleFrontierGateToFightArea_EventScript_Npc3::
	msgbox BattleFrontierGateToFightArea_Text_Npc3, MSGBOX_NPC
	end

BattleFrontierGateToFightArea_Text_Npc3:
	.string "Which topic should I explain?$"

BattleFrontierGateToFightArea_EventScript_Npc4::
	msgbox BattleFrontierGateToFightArea_Text_Npc4, MSGBOX_NPC
	end

BattleFrontierGateToFightArea_Text_Npc4:
	.string "Welcome to the Battle Frontier!\pShould I explain how the Battle Arcade\nworks?$"

BattleFrontierGateToFightArea_EventScript_Npc5::
	msgbox BattleFrontierGateToFightArea_Text_Npc5, MSGBOX_NPC
	end

BattleFrontierGateToFightArea_Text_Npc5:
	.string "Welcome to the Battle Frontier!\pShould I explain how the Battle Hall\nworks?$"

BattleFrontierGateToFightArea_EventScript_Npc6::
	msgbox BattleFrontierGateToFightArea_Text_Npc6, MSGBOX_NPC
	end

BattleFrontierGateToFightArea_Text_Npc6:
	.string "Welcome to the Battle Frontier!\pShould I explain how the Battle Tower\nworks?$"
