RuinManiacCaveShort_MapScripts::
	.byte 0

RuinManiacCaveShort_EventScript_Npc1::
	msgbox RuinManiacCaveShort_Text_Npc1, MSGBOX_NPC
	end

RuinManiacCaveShort_Text_Npc1:
	.string "Everyone calls me the Ruin Maniac.\nI don't care what they call me.\pI'll just keep on chipping away at\nthe rock wall little by little.\pDo you know why? I'm a Ruin Maniac\nwho is fascinated by the UNOWN.\pI know it's a little sudden, but\nhow about you and me have a race?\pYou go and catch the UNOWN,\nand I'll keep digging away.\pWe'll have a race to see who can\nget done faster.$"
