@ CelestialTower do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_CelestialTower_MapScripts::
	.byte 0

Unova_CelestialTower_EventScript_Lider4::
	trainerbattle_single TRAINER_UNOVA_HEX_MANIAC_CELESTIAL_TOWER_1, Unova_CelestialTower_Text_HexManiac1CelestialTowerSeenText, Unova_CelestialTower_Text_HexManiac1CelestialTowerBeatenText
	end

Unova_CelestialTower_EventScript_Lider5::
	trainerbattle_single TRAINER_UNOVA_HEX_MANIAC_CELESTIAL_TOWER_2, Unova_CelestialTower_Text_HexManiac2CelestialTowerSeenText, Unova_CelestialTower_Text_HexManiac2CelestialTowerBeatenText
	end

Unova_CelestialTower_EventScript_Lider6::
	trainerbattle_single TRAINER_UNOVA_MAID_CELESTIAL_TOWER, Unova_CelestialTower_Text_MaidCelestialTowerSeenText, Unova_CelestialTower_Text_MaidCelestialTowerBeatenText
	end

Unova_CelestialTower_EventScript_Lider7::
	trainerbattle_single TRAINER_UNOVA_PSYCHICM_CELESTIAL_TOWER, Unova_CelestialTower_Text_PsychicMCelestialTowerSeenText, Unova_CelestialTower_Text_PsychicMCelestialTowerBeatenText
	end

Unova_CelestialTower_EventScript_Lider8::
	trainerbattle_single TRAINER_UNOVA_PSYCHICF_CELESTIAL_TOWER, Unova_CelestialTower_Text_PsychicFCelestialTowerSeenText, Unova_CelestialTower_Text_PsychicFCelestialTowerBeatenText
	end

Unova_CelestialTower_EventScript_Lider9::
	trainerbattle_single TRAINER_UNOVA_SOCIALITE_CELESTIAL_TOWER, Unova_CelestialTower_Text_SocialiteCelestialTowerSeenText, Unova_CelestialTower_Text_SocialiteCelestialTowerBeatenText
	end

Unova_CelestialTower_EventScript_Lider10::
	trainerbattle_single TRAINER_UNOVA_POKEFANM_CELESTIAL_TOWER, Unova_CelestialTower_Text_PokefanMCelestialTowerSeenText, Unova_CelestialTower_Text_PokefanMCelestialTowerBeatenText
	end

Unova_CelestialTower_EventScript_Lider11::
	trainerbattle_single TRAINER_UNOVA_POKEFANF_CELESTIAL_TOWER, Unova_CelestialTower_Text_PokefanFCelestialTowerSeenText, Unova_CelestialTower_Text_PokefanFCelestialTowerBeatenText
	end

Unova_CelestialTower_EventScript_Lider12::
	trainerbattle_single TRAINER_UNOVA_LASS_CELESTIAL_TOWER, Unova_CelestialTower_Text_LassCelestialTowerSeenText, Unova_CelestialTower_Text_LassCelestialTowerBeatenText
	end

Unova_CelestialTower_EventScript_Lider13::
	trainerbattle_single TRAINER_UNOVA_GENTLEMAN_CELESTIAL_TOWER, Unova_CelestialTower_Text_GentlemanCelestialTowerSeenText, Unova_CelestialTower_Text_GentlemanCelestialTowerBeatenText
	end


Unova_CelestialTower_Text_HexManiac1CelestialTowerSeenText::
	.string "I'll borrow this"
	.string "\ntower's power to…"
	.string "\ppower up my own…"
	.string "\npowers!$"

Unova_CelestialTower_Text_HexManiac1CelestialTowerBeatenText::
	.string "I couldn't expect"
	.string "\nthat to make my"
	.string "\pPOKéMON more"
	.string "\npowerful too…$"

Unova_CelestialTower_Text_HexManiac2CelestialTowerSeenText::
	.string "I'm here to under-"
	.string "\nstand the end of"
	.string "\pthe world, but I"
	.string "\ndon't quite get"
	.string "\pit. If I have a"
	.string "\nbattle, will I be"
	.string "\lenlightened…?$"

Unova_CelestialTower_Text_HexManiac2CelestialTowerBeatenText::
	.string "The end…"
	.string "\nIs that it?$"

Unova_CelestialTower_Text_MaidCelestialTowerSeenText::
	.string "…I still want to"
	.string "\nfight! The wander-"
	.string "\ping spirits are"
	.string "\ncommanding me!$"

Unova_CelestialTower_Text_MaidCelestialTowerBeatenText::
	.string "Hah… Hah… The"
	.string "\nspirit just left"
	.string "\lme.$"

Unova_CelestialTower_Text_PsychicMCelestialTowerSeenText::
	.string "Let's show the"
	.string "\nresting spirits"
	.string "\pthe dazzling"
	.string "\nsplendor of life!$"

Unova_CelestialTower_Text_PsychicMCelestialTowerBeatenText::
	.string "Hm… Was that a"
	.string "\nspirit just now?$"

Unova_CelestialTower_Text_PsychicFCelestialTowerSeenText::
	.string "Indescribable"
	.string "\nenergy is flowing"
	.string "\lto me!$"

Unova_CelestialTower_Text_PsychicFCelestialTowerBeatenText::
	.string "The energy is"
	.string "\nescaping… Aww…$"

Unova_CelestialTower_Text_SocialiteCelestialTowerSeenText::
	.string "Oh my, what a"
	.string "\nyoung trainer. If"
	.string "\pit's all right,"
	.string "\nwhy don't we"
	.string "\lbattle?$"

Unova_CelestialTower_Text_SocialiteCelestialTowerBeatenText::
	.string "There at the end,"
	.string "\nI nearly called"
	.string "\pout my late POKé-"
	.string "\nMON's name.$"

Unova_CelestialTower_Text_PokefanMCelestialTowerSeenText::
	.string "When POKéMON"
	.string "\ntrainers meet,"
	.string "\pwhat we do is, of"
	.string "\ncourse, engage in"
	.string "\la POKéMON battle!$"

Unova_CelestialTower_Text_PokefanMCelestialTowerBeatenText::
	.string "Oh no…"
	.string "\nI'm pathetic…$"

Unova_CelestialTower_Text_PokefanFCelestialTowerSeenText::
	.string "Oh, you want to"
	.string "\nhave a battle with"
	.string "\pme? All right! I"
	.string "\nhave strong POKé-"
	.string "\lMON.$"

Unova_CelestialTower_Text_PokefanFCelestialTowerBeatenText::
	.string "My strongest POKé-"
	.string "\nMON is no longer"
	.string "\lwith me…$"

Unova_CelestialTower_Text_LassCelestialTowerSeenText::
	.string "Instead of a ghost"
	.string "\ntype POKéMON, I've"
	.string "\pfound myself a"
	.string "\nspectacular"
	.string "\ltrainer!$"

Unova_CelestialTower_Text_LassCelestialTowerBeatenText::
	.string "You were spectac-"
	.string "\nular, and more"
	.string "\pthan that, so"
	.string "\nstrong!$"

Unova_CelestialTower_Text_GentlemanCelestialTowerSeenText::
	.string "Let us have our"
	.string "\nPOKéMON battle"
	.string "\pwith gentlemanly"
	.string "\nreserve!$"

Unova_CelestialTower_Text_GentlemanCelestialTowerBeatenText::
	.string "Ho ho ho! Quite"
	.string "\nthe affront!$"

