@ CelestialTower do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_CelestialTower_MapScripts::
	.byte 0

Unova_CelestialTower_EventScript_Npc4::
	msgbox Unova_CelestialTower_Text_HexManiac1CelestialTowerSeenText, MSGBOX_NPC
	end

Unova_CelestialTower_EventScript_Npc5::
	msgbox Unova_CelestialTower_Text_HexManiac2CelestialTowerSeenText, MSGBOX_NPC
	end

Unova_CelestialTower_EventScript_Npc6::
	msgbox Unova_CelestialTower_Text_MaidCelestialTowerSeenText, MSGBOX_NPC
	end

Unova_CelestialTower_EventScript_Npc7::
	msgbox Unova_CelestialTower_Text_PsychicMCelestialTowerSeenText, MSGBOX_NPC
	end

Unova_CelestialTower_EventScript_Npc8::
	msgbox Unova_CelestialTower_Text_PsychicFCelestialTowerSeenText, MSGBOX_NPC
	end

Unova_CelestialTower_EventScript_Npc9::
	msgbox Unova_CelestialTower_Text_SocialiteCelestialTowerSeenText, MSGBOX_NPC
	end

Unova_CelestialTower_EventScript_Npc10::
	msgbox Unova_CelestialTower_Text_PokefanMCelestialTowerSeenText, MSGBOX_NPC
	end

Unova_CelestialTower_EventScript_Npc11::
	msgbox Unova_CelestialTower_Text_PokefanFCelestialTowerSeenText, MSGBOX_NPC
	end

Unova_CelestialTower_EventScript_Npc12::
	msgbox Unova_CelestialTower_Text_LassCelestialTowerSeenText, MSGBOX_NPC
	end

Unova_CelestialTower_EventScript_Npc13::
	msgbox Unova_CelestialTower_Text_GentlemanCelestialTowerSeenText, MSGBOX_NPC
	end


Unova_CelestialTower_Text_HexManiac1CelestialTowerSeenText::
	.string "I'll borrow this"
	.string "\ntower's power to…"
	.string "\ppower up my own…"
	.string "\npowers!$"

Unova_CelestialTower_Text_HexManiac2CelestialTowerSeenText::
	.string "I'm here to under-"
	.string "\nstand the end of"
	.string "\pthe world, but I"
	.string "\ndon't quite get"
	.string "\pit. If I have a"
	.string "\nbattle, will I be"
	.string "\lenlightened…?$"

Unova_CelestialTower_Text_MaidCelestialTowerSeenText::
	.string "…I still want to"
	.string "\nfight! The wander-"
	.string "\ping spirits are"
	.string "\ncommanding me!$"

Unova_CelestialTower_Text_PsychicMCelestialTowerSeenText::
	.string "Let's show the"
	.string "\nresting spirits"
	.string "\pthe dazzling"
	.string "\nsplendor of life!$"

Unova_CelestialTower_Text_PsychicFCelestialTowerSeenText::
	.string "Indescribable"
	.string "\nenergy is flowing"
	.string "\lto me!$"

Unova_CelestialTower_Text_SocialiteCelestialTowerSeenText::
	.string "Oh my, what a"
	.string "\nyoung trainer. If"
	.string "\pit's all right,"
	.string "\nwhy don't we"
	.string "\lbattle?$"

Unova_CelestialTower_Text_PokefanMCelestialTowerSeenText::
	.string "When POKéMON"
	.string "\ntrainers meet,"
	.string "\pwhat we do is, of"
	.string "\ncourse, engage in"
	.string "\la POKéMON battle!$"

Unova_CelestialTower_Text_PokefanFCelestialTowerSeenText::
	.string "Oh, you want to"
	.string "\nhave a battle with"
	.string "\pme? All right! I"
	.string "\nhave strong POKé-"
	.string "\lMON.$"

Unova_CelestialTower_Text_LassCelestialTowerSeenText::
	.string "Instead of a ghost"
	.string "\ntype POKéMON, I've"
	.string "\pfound myself a"
	.string "\nspectacular"
	.string "\ltrainer!$"

Unova_CelestialTower_Text_GentlemanCelestialTowerSeenText::
	.string "Let us have our"
	.string "\nPOKéMON battle"
	.string "\pwith gentlemanly"
	.string "\nreserve!$"
