PokemonMansionMaidsRoom_MapScripts::
	.byte 0

PokemonMansionMaidsRoom_EventScript_Npc1::
	msgbox PokemonMansionMaidsRoom_Text_Npc1, MSGBOX_NPC
	end

PokemonMansionMaidsRoom_Text_Npc1:
	.string "You know how you can catch Pokémon\nin the trophy garden?\pIf you put this on a caught Pokémon,\nit warms up to you faster.\pI'll share one with you, so give it\na try.$"

PokemonMansionMaidsRoom_EventScript_Placa1::
	msgbox PokemonMansionMaidsRoom_Text_Placa1, MSGBOX_SIGN
	end

PokemonMansionMaidsRoom_Text_Placa1:
	.string "It's a bed...\nWant to take a rest?$"

PokemonMansionMaidsRoom_EventScript_Placa2::
	msgbox PokemonMansionMaidsRoom_Text_Placa2, MSGBOX_SIGN
	end

PokemonMansionMaidsRoom_Text_Placa2:
	.string "It's a bed...\nWant to take a rest?$"

PokemonMansionMaidsRoom_EventScript_Placa3::
	msgbox PokemonMansionMaidsRoom_Text_Placa3, MSGBOX_SIGN
	end

PokemonMansionMaidsRoom_Text_Placa3:
	.string "It's a bed...\nWant to take a rest?$"

PokemonMansionMaidsRoom_EventScript_Placa4::
	msgbox PokemonMansionMaidsRoom_Text_Placa4, MSGBOX_SIGN
	end

PokemonMansionMaidsRoom_Text_Placa4:
	.string "It's a bed...\nWant to take a rest?$"

PokemonMansionMaidsRoom_EventScript_Placa5::
	msgbox PokemonMansionMaidsRoom_Text_Placa5, MSGBOX_SIGN
	end

PokemonMansionMaidsRoom_Text_Placa5:
	.string "It's a bed...\nWant to take a rest?$"

PokemonMansionMaidsRoom_EventScript_Placa6::
	msgbox PokemonMansionMaidsRoom_Text_Placa6, MSGBOX_SIGN
	end

PokemonMansionMaidsRoom_Text_Placa6:
	.string "It's a bed...\nWant to take a rest?$"
