@ Mapa CORTADO do escopo (PLANO-ESCOPO.md). O rotulo abaixo fica
@ porque header.inc, gerado, aponta para ele.

PokemonMansionMaidsRoom_MapScripts::
	.byte 0

@ Texto de placa vindo do pokeplatinum (dev_scripts/texto_placas_sinnoh.py)

PokemonMansionMaidsRoom_EventScript_Placa2::
	msgbox PokemonMansionMaidsRoom_Text_Placa2, MSGBOX_SIGN
	end

PokemonMansionMaidsRoom_Text_Placa2:
	.string "It's a bed...\nWant to take a rest?$"

PokemonMansionMaidsRoom_EventScript_Placa3::
	msgbox PokemonMansionMaidsRoom_Text_Placa3, MSGBOX_SIGN
	end

PokemonMansionMaidsRoom_Text_Placa3:
	.string "It's a bed...\nWant to take a rest?$"

PokemonMansionMaidsRoom_EventScript_Placa4::
	msgbox PokemonMansionMaidsRoom_Text_Placa4, MSGBOX_SIGN
	end

PokemonMansionMaidsRoom_Text_Placa4:
	.string "It's a bed...\nWant to take a rest?$"

PokemonMansionMaidsRoom_EventScript_Placa5::
	msgbox PokemonMansionMaidsRoom_Text_Placa5, MSGBOX_SIGN
	end

PokemonMansionMaidsRoom_Text_Placa5:
	.string "It's a bed...\nWant to take a rest?$"

PokemonMansionMaidsRoom_EventScript_Placa6::
	msgbox PokemonMansionMaidsRoom_Text_Placa6, MSGBOX_SIGN
	end

PokemonMansionMaidsRoom_Text_Placa6:
	.string "It's a bed...\nWant to take a rest?$"

PokemonMansionMaidsRoom_EventScript_Placa7::
	msgbox PokemonMansionMaidsRoom_Text_Placa7, MSGBOX_SIGN
	end

PokemonMansionMaidsRoom_Text_Placa7:
	.string "It's a bed...\nWant to take a rest?$"
