MiningMuseum_MapScripts::
	.byte 0

MiningMuseum_EventScript_Npc1::
	msgbox MiningMuseum_Text_Npc1, MSGBOX_NPC
	end

MiningMuseum_Text_Npc1:
	.string "Hello, hello!\nHow are you?\pI study Pokémon Fossils!\nMe! Right here and now!$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

MiningMuseum_EventScript_Npc8::
	msgbox MiningMuseum_Text_Npc8, MSGBOX_NPC
	end

MiningMuseum_Text_Npc8:
	.string "Whoa! So this is coal?\nI never expected something this big!\pAnd that color!\nIt really is as black as they say!$"

MiningMuseum_EventScript_Npc2::
	msgbox MiningMuseum_Text_Npc2, MSGBOX_NPC
	end

MiningMuseum_Text_Npc2:
	.string "Wow! The Pokémon that carried this\nmust be terribly strong!$"

MiningMuseum_EventScript_Npc3::
	msgbox MiningMuseum_Text_Npc3, MSGBOX_NPC
	end

MiningMuseum_Text_Npc3:
	.string "Well, how about that!\pThe Oreburgh Mine extends under\nthe seafloor!$"

MiningMuseum_EventScript_Npc4::
	msgbox MiningMuseum_Text_Npc4, MSGBOX_NPC
	end

MiningMuseum_Text_Npc4:
	.string "Hello! Welcome to the Oreburgh\nMining Museum!$"

MiningMuseum_EventScript_Npc5::
	msgbox MiningMuseum_Text_Npc5, MSGBOX_NPC
	end

MiningMuseum_Text_Npc5:
	.string "It's a little far from here, but there\nis a city called Eterna City.\pI've heard a curious person named the\nUnderground Man lives there.\pWith a name like that, he must be an\nauthority on the Underground.$"

MiningMuseum_EventScript_Npc6::
	msgbox MiningMuseum_Text_Npc6, MSGBOX_NPC
	end

MiningMuseum_Text_Npc6:
	.string "Mining must take a strong mind, not\njust a tough body.\pThink about it. You're in darkness,\ndigging desperately through rock.$"

MiningMuseum_EventScript_Npc7::
	msgbox MiningMuseum_Text_Npc7, MSGBOX_NPC
	end

MiningMuseum_Text_Npc7:
	.string "The history of Oreburgh Mine...\pYou could call it a history of effort and\nfriendship between people and Pokémon.$"

MiningMuseum_EventScript_Placa8::
	msgbox MiningMuseum_Text_Placa8, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa8:
	.string "How Coal Is Made   1\p'In a time long before history,\nvegetative matter was swept along\pby rain and rivers. It came to be\nburied under the ground.'$"

MiningMuseum_EventScript_Placa9::
	msgbox MiningMuseum_Text_Placa9, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa9:
	.string "How Coal Is Made   1\p'In a time long before history,\nvegetative matter was swept along\pby rain and rivers. It came to be\nburied under the ground.'$"

MiningMuseum_EventScript_Placa10::
	msgbox MiningMuseum_Text_Placa10, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa10:
	.string "How Coal Is Made   2\p'The buried plant matter was\nforced ever deeper under the ground\pdue to tremors and fissures caused\nby the shifting landmasses.'$"

MiningMuseum_EventScript_Placa11::
	msgbox MiningMuseum_Text_Placa11, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa11:
	.string "How Coal Is Made   2\p'The buried plant matter was\nforced ever deeper under the ground\pdue to tremors and fissures caused\nby the shifting landmasses.'$"

MiningMuseum_EventScript_Placa12::
	msgbox MiningMuseum_Text_Placa12, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa12:
	.string "How Coal Is Made   3\p'Deep under the ground, the\nplant matter was subjected to heavy\ppressure and the heat of magma.\nIt gradually turned into coal.'$"

MiningMuseum_EventScript_Placa13::
	msgbox MiningMuseum_Text_Placa13, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa13:
	.string "How Coal Is Made   3\p'Deep under the ground, the\nplant matter was subjected to heavy\ppressure and the heat of magma.\nIt gradually turned into coal.'$"

MiningMuseum_EventScript_Placa14::
	msgbox MiningMuseum_Text_Placa14, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa14:
	.string "Samples of coal from different regions\nare displayed.$"

MiningMuseum_EventScript_Placa15::
	msgbox MiningMuseum_Text_Placa15, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa15:
	.string "Samples of coal from different regions\nare displayed.$"

MiningMuseum_EventScript_Placa16::
	msgbox MiningMuseum_Text_Placa16, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa16:
	.string "The box contains categorized samples\nof coal.$"

MiningMuseum_EventScript_Placa17::
	msgbox MiningMuseum_Text_Placa17, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa17:
	.string "The box contains categorized samples\nof coal.$"

MiningMuseum_EventScript_Placa18::
	msgbox MiningMuseum_Text_Placa18, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa18:
	.string "Different kinds of lamps are\ndisplayed.\pThey appear to have been worn\non someone's head while underground.$"

MiningMuseum_EventScript_Placa19::
	msgbox MiningMuseum_Text_Placa19, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa19:
	.string "Different kinds of lamps are\ndisplayed.\pThey appear to have been worn\non someone's head while underground.$"

MiningMuseum_EventScript_Placa20::
	msgbox MiningMuseum_Text_Placa20, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa20:
	.string "Different kinds of lamps are\ndisplayed.\pThey appear to have been worn\non someone's head while underground.$"

MiningMuseum_EventScript_Placa21::
	msgbox MiningMuseum_Text_Placa21, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa21:
	.string "Badly scarred wooden tools are\ndisplayed.\pThey apparently dug out coal using\nthese tools in the olden days.$"

MiningMuseum_EventScript_Placa22::
	msgbox MiningMuseum_Text_Placa22, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa22:
	.string "Badly scarred wooden tools are\ndisplayed.\pThey apparently dug out coal using\nthese tools in the olden days.$"

MiningMuseum_EventScript_Placa23::
	msgbox MiningMuseum_Text_Placa23, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa23:
	.string "Badly scarred wooden tools are\ndisplayed.\pThey apparently dug out coal using\nthese tools in the olden days.$"

MiningMuseum_EventScript_Placa24::
	msgbox MiningMuseum_Text_Placa24, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa24:
	.string "The everyday items and tools of\npast mine workers are displayed.$"

MiningMuseum_EventScript_Placa25::
	msgbox MiningMuseum_Text_Placa25, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa25:
	.string "The everyday items and tools of\npast mine workers are displayed.$"

MiningMuseum_EventScript_Placa26::
	msgbox MiningMuseum_Text_Placa26, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa26:
	.string "The everyday items and tools of\npast mine workers are displayed.$"

MiningMuseum_EventScript_Placa27::
	msgbox MiningMuseum_Text_Placa27, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa27:
	.string "Samples of coal from different regions\nare displayed.$"

MiningMuseum_EventScript_Placa28::
	msgbox MiningMuseum_Text_Placa28, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa28:
	.string "Samples of coal from different regions\nare displayed.$"

MiningMuseum_EventScript_Placa29::
	msgbox MiningMuseum_Text_Placa29, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa29:
	.string "Different kinds of lamps are\ndisplayed.\pThey appear to have been worn\non someone's head while underground.$"

MiningMuseum_EventScript_Placa30::
	msgbox MiningMuseum_Text_Placa30, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa30:
	.string "Different kinds of lamps are\ndisplayed.\pThey appear to have been worn\non someone's head while underground.$"

MiningMuseum_EventScript_Placa31::
	msgbox MiningMuseum_Text_Placa31, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa31:
	.string "Different kinds of lamps are\ndisplayed.\pThey appear to have been worn\non someone's head while underground.$"

MiningMuseum_EventScript_Placa32::
	msgbox MiningMuseum_Text_Placa32, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa32:
	.string "Badly scarred wooden tools are\ndisplayed.\pThey apparently dug out coal using\nthese tools in the olden days.$"

MiningMuseum_EventScript_Placa33::
	msgbox MiningMuseum_Text_Placa33, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa33:
	.string "Badly scarred wooden tools are\ndisplayed.\pThey apparently dug out coal using\nthese tools in the olden days.$"

MiningMuseum_EventScript_Placa34::
	msgbox MiningMuseum_Text_Placa34, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa34:
	.string "Badly scarred wooden tools are\ndisplayed.\pThey apparently dug out coal using\nthese tools in the olden days.$"

MiningMuseum_EventScript_Placa35::
	msgbox MiningMuseum_Text_Placa35, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa35:
	.string "The everyday items and tools of\npast mine workers are displayed.$"

MiningMuseum_EventScript_Placa36::
	msgbox MiningMuseum_Text_Placa36, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa36:
	.string "The everyday items and tools of\npast mine workers are displayed.$"

MiningMuseum_EventScript_Placa37::
	msgbox MiningMuseum_Text_Placa37, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa37:
	.string "The everyday items and tools of\npast mine workers are displayed.$"

MiningMuseum_EventScript_Placa38::
	msgbox MiningMuseum_Text_Placa38, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa38:
	.string "The box contains categorized samples\nof coal.$"

MiningMuseum_EventScript_Placa39::
	msgbox MiningMuseum_Text_Placa39, MSGBOX_SIGN
	end

MiningMuseum_Text_Placa39:
	.string "The box contains categorized samples\nof coal.$"
