@ FoothillTown_House3: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 17.5) por dev_scripts/copia_planta_ex.py.

FoothillTown_House3_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 17.5), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
FoothillTown_House3_EventScript_ExNpc0::
	msgbox FoothillTown_House3_Text_ExNpc0, MSGBOX_NPC
	end

FoothillTown_House3_Text_ExNpc0:
	.string "Our town get’s lots of visitors!\n"
	.string "Right now a bunch of TRIATHLETES are\l"
	.string "here.\p"
	.string "One day I’m going to be like them.$"

FoothillTown_House3_EventScript_ExNpc1::
	msgbox FoothillTown_House3_Text_ExNpc1, MSGBOX_NPC
	end

FoothillTown_House3_Text_ExNpc1:
	.string "My daughter wants to be a TRIATHLETE...\n"
	.string "...\l"
	.string "I hate running...$"

