@ DriftveilHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_DriftveilHouse_MapScripts::
	.byte 0

Unova_DriftveilHouse_EventScript_Npc0::
	msgbox Unova_DriftveilHouse_Text_NimbasaHouseGiveEverstoneText, MSGBOX_NPC
	end


Unova_DriftveilHouse_Text_NimbasaHouseGiveEverstoneText::
	.string "DRIFTVEIL CITY"
	.string "\nis famous for our"
	.string "\lmines!"
	.string "\pWe have all sorts"
	.string "\nof rare stones."
	.string "\pHere, you can"
	.string "\nhave a sample!$"
