PastoriaCityEastHouse_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

PastoriaCityEastHouse_EventScript_Npc1::
	msgbox PastoriaCityEastHouse_Text_Npc1, MSGBOX_NPC
	end

PastoriaCityEastHouse_Text_Npc1:
	.string "Oh! That's it! That's an honest-to-\ngoodness Heart Scale!\pLet me guess, you want me to teach\none of your Pokémon a move?$"

PastoriaCityEastHouse_EventScript_Npc2::
	msgbox PastoriaCityEastHouse_Text_Npc2, MSGBOX_NPC
	end

PastoriaCityEastHouse_Text_Npc2:
	.string "I often go to Solaceon Town for my big\nbrother.\pThe newspaper there gives me Heart\nScales for running errands.$"
