EternaCityEastHouse_MapScripts::
	.byte 0

EternaCityEastHouse_EventScript_Npc1::
	msgbox EternaCityEastHouse_Text_Npc1, MSGBOX_NPC
	end

EternaCityEastHouse_Text_Npc1:
	.string "Sheesh! \nWhat's the world coming to?!\pSomeone ripped off the descriptive\nplate from the Pokémon statue!\pNow no one can read the inscription!\nWhy would someone do that?\pActually, want to know what it said?$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

EternaCityEastHouse_EventScript_Npc3::
	msgbox EternaCityEastHouse_Text_Npc3, MSGBOX_NPC
	end

EternaCityEastHouse_Text_Npc3:
	.string "Eterna came to be long ago in honor\nof ancient Pokémon.\pThough many things have changed,\nwhat is important has not.\pI hope it remains that way forever\nmore...$"

EternaCityEastHouse_EventScript_Npc2::
	msgbox EternaCityEastHouse_Text_Npc2, MSGBOX_NPC
	end

EternaCityEastHouse_Text_Npc2:
	.string "Have you seen the Pokémon statue?\pWhen I was a wee child, it used to be\nthe centerpiece of many festivals...$"
