@ Rt5 do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt5_MapScripts::
	.byte 0

Unova_Rt5_EventScript_Placa0::
	msgbox Unova_Rt5_Text_R5BridgeSignText, MSGBOX_SIGN
	end

Unova_Rt5_EventScript_Placa1::
	msgbox Unova_Rt5_Text_R5NimbasaSignText, MSGBOX_SIGN
	end

Unova_Rt5_EventScript_Npc5::
	msgbox Unova_Rt5_Text_Dancer1R5SeenText, MSGBOX_NPC
	end

Unova_Rt5_EventScript_Npc6::
	msgbox Unova_Rt5_Text_Dancer2R5SeenText, MSGBOX_NPC
	end

Unova_Rt5_EventScript_Npc7::
	msgbox Unova_Rt5_Text_LinebackerR5SeenText, MSGBOX_NPC
	end

Unova_Rt5_EventScript_Npc8::
	msgbox Unova_Rt5_Text_BakerR5SeenText, MSGBOX_NPC
	end

Unova_Rt5_EventScript_Npc9::
	msgbox Unova_Rt5_Text_ArtistR5SeenText, MSGBOX_NPC
	end

Unova_Rt5_EventScript_Npc10::
	msgbox Unova_Rt5_Text_BackersFR5SeenText, MSGBOX_NPC
	end

Unova_Rt5_EventScript_Npc11::
	msgbox Unova_Rt5_Text_BackersFR5SeenText, MSGBOX_NPC
	end

Unova_Rt5_EventScript_Npc12::
	msgbox Unova_Rt5_Text_R5CharlesSeenText, MSGBOX_NPC
	end


Unova_Rt5_Text_R5BridgeSignText::
	.string "DRIFTVEIL"
	.string "\nDRAWBRIDGE."
	.string "\pInquire inside"
	.string "\nfor bridge access.$"

Unova_Rt5_Text_R5NimbasaSignText::
	.string "NIMBASA CITY"
	.string "\nahead.$"

Unova_Rt5_Text_Dancer1R5SeenText::
	.string "Turn around, and"
	.string "\nit's my turn. Turn"
	.string "\paround, and it's"
	.string "\nyour turn!$"

Unova_Rt5_Text_Dancer2R5SeenText::
	.string "I can feel it in"
	.string "\nthe air… This"
	.string "\pbattle will be"
	.string "\nelectrifying!$"

Unova_Rt5_Text_LinebackerR5SeenText::
	.string "Heheh! Nobody can"
	.string "\nbeat my speed and"
	.string "\lfury!$"

Unova_Rt5_Text_BakerR5SeenText::
	.string "These POKéMON"
	.string "\nusually help me"
	.string "\pbake. But today,"
	.string "\nthey'll help me"
	.string "\lbattle you!$"

Unova_Rt5_Text_ArtistR5SeenText::
	.string "Art is explosions!"
	.string "\nLife forces colli-"
	.string "\lding together!$"

Unova_Rt5_Text_BackersFR5SeenText::
	.string "After watching a"
	.string "\nfootball game, we"
	.string "\pwant to get rowdy"
	.string "\nourselves!$"

Unova_Rt5_Text_R5CharlesSeenText::
	.string "I'm a heart-"
	.string "\nbreaker… My name…"
	.string "\lCHARLES…"
	.string "\pYou… You wish to"
	.string "\nchallenge me…?"
	.string "\pPrepare… to be…"
	.string "\nheartbroken…$"
