CanalaveLibrary2F_MapScripts::
	.byte 0

CanalaveLibrary2F_EventScript_Npc1::
	msgbox CanalaveLibrary2F_Text_Npc1, MSGBOX_NPC
	end

CanalaveLibrary2F_Text_Npc1:
	.string "The books on the third floor are\neasy to read.\pThe ones down here are all too tough\nfor me to understand...$"

CanalaveLibrary2F_EventScript_Placa1::
	msgbox CanalaveLibrary2F_Text_Placa1, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa1:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary2F_EventScript_Placa2::
	msgbox CanalaveLibrary2F_Text_Placa2, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa2:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary2F_EventScript_Placa3::
	msgbox CanalaveLibrary2F_Text_Placa3, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa3:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary2F_EventScript_Placa4::
	msgbox CanalaveLibrary2F_Text_Placa4, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa4:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary2F_EventScript_Placa5::
	msgbox CanalaveLibrary2F_Text_Placa5, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa5:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary2F_EventScript_Placa6::
	msgbox CanalaveLibrary2F_Text_Placa6, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa6:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary2F_EventScript_Placa7::
	msgbox CanalaveLibrary2F_Text_Placa7, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa7:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary2F_EventScript_Placa8::
	msgbox CanalaveLibrary2F_Text_Placa8, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa8:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

CanalaveLibrary2F_EventScript_Placa28::
	msgbox CanalaveLibrary2F_Text_Placa28, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa28:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa29::
	msgbox CanalaveLibrary2F_Text_Placa29, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa29:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa30::
	msgbox CanalaveLibrary2F_Text_Placa30, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa30:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa31::
	msgbox CanalaveLibrary2F_Text_Placa31, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa31:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa32::
	msgbox CanalaveLibrary2F_Text_Placa32, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa32:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa33::
	msgbox CanalaveLibrary2F_Text_Placa33, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa33:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa34::
	msgbox CanalaveLibrary2F_Text_Placa34, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa34:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa35::
	msgbox CanalaveLibrary2F_Text_Placa35, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa35:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa9::
	msgbox CanalaveLibrary2F_Text_Placa9, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa9:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa10::
	msgbox CanalaveLibrary2F_Text_Placa10, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa10:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa11::
	msgbox CanalaveLibrary2F_Text_Placa11, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa11:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa12::
	msgbox CanalaveLibrary2F_Text_Placa12, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa12:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa13::
	msgbox CanalaveLibrary2F_Text_Placa13, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa13:
	.string "Please refrain from bringing food\nor beverages into the library.$"

CanalaveLibrary2F_EventScript_Placa14::
	msgbox CanalaveLibrary2F_Text_Placa14, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa14:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa15::
	msgbox CanalaveLibrary2F_Text_Placa15, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa15:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa16::
	msgbox CanalaveLibrary2F_Text_Placa16, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa16:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa17::
	msgbox CanalaveLibrary2F_Text_Placa17, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa17:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa18::
	msgbox CanalaveLibrary2F_Text_Placa18, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa18:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa19::
	msgbox CanalaveLibrary2F_Text_Placa19, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa19:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa20::
	msgbox CanalaveLibrary2F_Text_Placa20, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa20:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa21::
	msgbox CanalaveLibrary2F_Text_Placa21, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa21:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa22::
	msgbox CanalaveLibrary2F_Text_Placa22, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa22:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa23::
	msgbox CanalaveLibrary2F_Text_Placa23, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa23:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa24::
	msgbox CanalaveLibrary2F_Text_Placa24, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa24:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa25::
	msgbox CanalaveLibrary2F_Text_Placa25, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa25:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa26::
	msgbox CanalaveLibrary2F_Text_Placa26, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa26:
	.string "The shelves are lined with books\nworn from being read by many people.$"

CanalaveLibrary2F_EventScript_Placa27::
	msgbox CanalaveLibrary2F_Text_Placa27, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa27:
	.string "The shelves are lined with books\nworn from being read by many people.$"
