CanalaveLibrary2F_MapScripts::
	.byte 0

CanalaveLibrary2F_EventScript_Npc1::
	msgbox CanalaveLibrary2F_Text_Npc1, MSGBOX_NPC
	end

CanalaveLibrary2F_Text_Npc1:
	.string "The books on the third floor are\neasy to read.\pThe ones down here are all too tough\nfor me to understand...$"

CanalaveLibrary2F_EventScript_Placa1::
	msgbox CanalaveLibrary2F_Text_Placa1, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa1:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary2F_EventScript_Placa2::
	msgbox CanalaveLibrary2F_Text_Placa2, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa2:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary2F_EventScript_Placa3::
	msgbox CanalaveLibrary2F_Text_Placa3, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa3:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary2F_EventScript_Placa4::
	msgbox CanalaveLibrary2F_Text_Placa4, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa4:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary2F_EventScript_Placa5::
	msgbox CanalaveLibrary2F_Text_Placa5, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa5:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary2F_EventScript_Placa6::
	msgbox CanalaveLibrary2F_Text_Placa6, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa6:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary2F_EventScript_Placa7::
	msgbox CanalaveLibrary2F_Text_Placa7, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa7:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"

CanalaveLibrary2F_EventScript_Placa8::
	msgbox CanalaveLibrary2F_Text_Placa8, MSGBOX_SIGN
	end

CanalaveLibrary2F_Text_Placa8:
	.string "The ceiling-high bookshelves are\ncrammed with books.$"
