@ Rt2AccumulaGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt2AccumulaGate_MapScripts::
	.byte 0

Unova_Rt2AccumulaGate_EventScript_Npc0::
	msgbox Unova_Rt2AccumulaGate_Text_R2AccumulaGateOfficerText, MSGBOX_NPC
	end


Unova_Rt2AccumulaGate_Text_R2AccumulaGateOfficerText::
	.string "Sometimes, I can"
	.string "\nhear a pleasant"
	.string "\psong coming from"
	.string "\nout the window."
	.string "\pIt makes me want"
	.string "\nto get up and go"
	.string "\lfor a walk!$"
