@ Rt11VillageBridgeGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt11VillageBridgeGate_MapScripts::
	.byte 0

Unova_Rt11VillageBridgeGate_EventScript_Npc0::
	msgbox Unova_Rt11VillageBridgeGate_Text_R11VillageBridgeGateOfficerText, MSGBOX_NPC
	end


Unova_Rt11VillageBridgeGate_Text_R11VillageBridgeGateOfficerText::
	.string "VILLAGE BRIDGE is"
	.string "\na bridge that was"
	.string "\pbuilt around an"
	.string "\nold village."
	.string "\pMost of that"
	.string "\noriginal village"
	.string "\pbecame OPELUCID"
	.string "\nCITY, though there"
	.string "\pare still houses"
	.string "\nbuilt around the"
	.string "\lbridge.$"
