@ Rt16LostlornGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt16LostlornGate_MapScripts::
	.byte 0

Unova_Rt16LostlornGate_EventScript_Npc0::
	msgbox Unova_Rt16LostlornGate_Text_Rt16LostlornGateOfficerText, MSGBOX_NPC
	end

Unova_Rt16LostlornGate_EventScript_Npc1::
	msgbox Unova_Rt16LostlornGate_Text_Rt16LostlornGateRangerMText, MSGBOX_NPC
	end


Unova_Rt16LostlornGate_Text_Rt16LostlornGateOfficerText::
	.string "LOSTLORN FOREST"
	.string "\nis big! Don't get"
	.string "\llost.$"

Unova_Rt16LostlornGate_Text_Rt16LostlornGateRangerMText::
	.string "There are trainers"
	.string "\nout on the road."
	.string "\pIt's a good place"
	.string "\nto train.$"
