GrandLakeRoute213NorthwestHouse_MapScripts::
	.byte 0

GrandLakeRoute213NorthwestHouse_EventScript_Npc1::
	msgbox GrandLakeRoute213NorthwestHouse_Text_Npc1, MSGBOX_NPC
	end

GrandLakeRoute213NorthwestHouse_Text_Npc1:
	.string "We're a traveling troupe of street\nperformers.\pIn place of a formal introduction,\nplease take this!$"

GrandLakeRoute213NorthwestHouse_EventScript_Npc2::
	msgbox GrandLakeRoute213NorthwestHouse_Text_Npc2, MSGBOX_NPC
	end

GrandLakeRoute213NorthwestHouse_Text_Npc2:
	.string "Let me gaze into your eyes...\nI will read your fortune...\p...$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

GrandLakeRoute213NorthwestHouse_EventScript_Npc1::
	msgbox GrandLakeRoute213NorthwestHouse_Text_Npc1, MSGBOX_NPC
	end

GrandLakeRoute213NorthwestHouse_Text_Npc1:
	.string "Me, I'm just a simple guy.\nI let my guitar do all my talking.\pAll I need is music and Pokémon.\pI can shine wherever I go if I have\nthose things in my life.\pI hear there are guys like me who go\naround Pokémon Centers.$"
