@ Rt1Rt17Gate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt1Rt17Gate_MapScripts::
	.byte 0

Unova_Rt1Rt17Gate_EventScript_Npc0::
	msgbox Unova_Rt1Rt17Gate_Text_R1R17GateOfficerText, MSGBOX_NPC
	end


Unova_Rt1Rt17Gate_Text_R1R17GateOfficerText::
	.string "It's been a while"
	.string "\nsince someone's"
	.string "\lcome this way!"
	.string "\pHonestly, I enjoy"
	.string "\nthis quiet post.$"
