PastoriaCitySouthwestHouse_MapScripts::
	.byte 0

PastoriaCitySouthwestHouse_EventScript_Npc1::
	msgbox PastoriaCitySouthwestHouse_Text_Npc1, MSGBOX_NPC
	end

PastoriaCitySouthwestHouse_Text_Npc1:
	.string "I've been hiking all around the\nSinnoh region.\pI love planting Berries wherever\nI go.\pI'll give you a Berry, too.\nPlease plant it somewhere.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

PastoriaCitySouthwestHouse_EventScript_Npc2::
	msgbox PastoriaCitySouthwestHouse_Text_Npc2, MSGBOX_NPC
	end

PastoriaCitySouthwestHouse_Text_Npc2:
	.string "My sister gathers Berries every day!\nPlease come visit again!\pWe cook the Berries, too!\nWe mix them up! They're yummy!$"
