@ Rt3 do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt3_MapScripts::
	.byte 0

Unova_Rt3_EventScript_Placa0::
	msgbox Unova_Rt3_Text_R3WellspringSignText, MSGBOX_SIGN
	end

Unova_Rt3_EventScript_Placa1::
	msgbox Unova_Rt3_Text_R3DayCareSignText, MSGBOX_SIGN
	end

Unova_Rt3_EventScript_Npc4::
	msgbox Unova_Rt3_Text_PkmnRangerMR3SeenText, MSGBOX_NPC
	end

Unova_Rt3_EventScript_Npc5::
	msgbox Unova_Rt3_Text_PkmnRangerFR3SeenText, MSGBOX_NPC
	end

Unova_Rt3_EventScript_Npc6::
	msgbox Unova_Rt3_Text_SocialiteR3SeenText, MSGBOX_NPC
	end

Unova_Rt3_EventScript_Npc7::
	msgbox Unova_Rt3_Text_Fisher1R3SeenText, MSGBOX_NPC
	end

Unova_Rt3_EventScript_Npc8::
	msgbox Unova_Rt3_Text_Fisher2R3SeenText, MSGBOX_NPC
	end

Unova_Rt3_EventScript_Npc9::
	msgbox Unova_Rt3_Text_ArtistR3SeenText, MSGBOX_NPC
	end

Unova_Rt3_EventScript_Npc10::
	msgbox Unova_Rt3_Text_GentlemanR3SeenText, MSGBOX_NPC
	end


Unova_Rt3_Text_R3WellspringSignText::
	.string "WELLSPRING CAVE."
	.string "\pBeware of wild"
	.string "\nPOKéMON!$"

Unova_Rt3_Text_R3DayCareSignText::
	.string "DAY CARE."
	.string "\pLet your POKéMON"
	.string "\nplay with us!$"

Unova_Rt3_Text_PkmnRangerMR3SeenText::
	.string "Forming a team of"
	.string "\nPOKéMON that can"
	.string "\pwork well together"
	.string "\nis key in battle!"
	.string "\lLet's begin!$"

Unova_Rt3_Text_PkmnRangerFR3SeenText::
	.string "Melding into the"
	.string "\nwild landscape…"
	.string "\pThat's what a POKé-"
	.string "\nMON RANGER does!$"

Unova_Rt3_Text_SocialiteR3SeenText::
	.string "Two years ago, I"
	.string "\nparted ways with"
	.string "\lmy POKéMON…"
	.string "\pYet in my heart,"
	.string "\nI've never stopped"
	.string "\pbeing a POKéMON"
	.string "\ntrainer!$"

Unova_Rt3_Text_Fisher1R3SeenText::
	.string "I am a wonderful"
	.string "\nfisherman who"
	.string "\lloves everything!$"

Unova_Rt3_Text_Fisher2R3SeenText::
	.string "Hey! What kinds of"
	.string "\ngreat POKéMON have"
	.string "\lyou caught?$"

Unova_Rt3_Text_ArtistR3SeenText::
	.string "A high level"
	.string "\nbattling technique"
	.string "\pis art in its own"
	.string "\nway!$"

Unova_Rt3_Text_GentlemanR3SeenText::
	.string "I came here"
	.string "\nbecause this place"
	.string "\pfeels quite"
	.string "\nnostalgic to me…"
	.string "\pBut I'd rather"
	.string "\nbattle than stroll"
	.string "\ldown memory lane!$"
