@ RelicCastleB2F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_RelicCastleB2F_MapScripts::
	.byte 0

Unova_RelicCastleB2F_EventScript_Lider1::
	trainerbattle_single TRAINER_UNOVA_PSYCHICF_RELIC_CASTLE_2, Unova_RelicCastleB2F_Text_PsychicFRelicCastleB2FSeenText, Unova_RelicCastleB2F_Text_PsychicFRelicCastleB2FBeatenText
	end


Unova_RelicCastleB2F_Text_PsychicFRelicCastleB2FSeenText::
	.string "…When I am here, I"
	.string "\nfeel like I might"
	.string "\pbe crushed by"
	.string "\nsorrow. You there…"
	.string "\lLet's have a bout!$"

Unova_RelicCastleB2F_Text_PsychicFRelicCastleB2FBeatenText::
	.string "This bout… I will"
	.string "\nnot forget it…$"
