@ LacunosaHouse2 do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_LacunosaHouse2_MapScripts::
	.byte 0

Unova_LacunosaHouse2_EventScript_Npc0::
	msgbox Unova_LacunosaHouse2_Text_LacunosaHouse2ManText, MSGBOX_NPC
	end


Unova_LacunosaHouse2_Text_LacunosaHouse2ManText::
	.string "Have you heard of"
	.string "\nhidden grottoes?"
	.string "\pIf you see a dark"
	.string "\nspot between the"
	.string "\ltrees, check"
	.string "\linside."
	.string "\pPOKéMON like to"
	.string "\nstash shiny items"
	.string "\lthey find there."
	.string "\pIf you come back"
	.string "\nafter a while, you"
	.string "\lmay find something"
	.string "\lnew there!$"
