@ MistraltonHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_MistraltonHouse_MapScripts::
	.byte 0

Unova_MistraltonHouse_EventScript_Npc0::
	msgbox Unova_MistraltonHouse_Text_MistraltonHouseGiveBeakText, MSGBOX_NPC
	end


Unova_MistraltonHouse_Text_MistraltonHouseGiveBeakText::
	.string "FLYING type POKé-"
	.string "\nMON are the"
	.string "\lcoolest!"
	.string "\pYou should train"
	.string "\nFLYING type POKé-"
	.string "\lMON too!"
	.string "\pHere, I'll show"
	.string "\nyou how cool they"
	.string "\lare!$"
