@ PkmnLeagueMain do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_PkmnLeagueMain_MapScripts::
	.byte 0

Unova_PkmnLeagueMain_EventScript_Placa0::
	msgbox Unova_PkmnLeagueMain_Text_PkmnLeagueMainStatueText, MSGBOX_SIGN
	end

Unova_PkmnLeagueMain_EventScript_Placa1::
	msgbox Unova_PkmnLeagueMain_Text_PkmnLeagueMainStatueText, MSGBOX_SIGN
	end


Unova_PkmnLeagueMain_Text_PkmnLeagueMainStatueText::
	.string "Four great"
	.string "\nwarriors form this"
	.string "\lPOKéMON LEAGUE."
	.string "\pTo the southwest"
	.string "\nis one who has"
	.string "\pgreat knowledge of"
	.string "\nthe steel type."
	.string "\pTo the southeast"
	.string "\nis one who"
	.string "\pchannels the power"
	.string "\nof the fighting"
	.string "\ltype."
	.string "\pTo the northwest"
	.string "\nis one who has"
	.string "\pmastered the dark"
	.string "\ntype."
	.string "\pTo the northeast"
	.string "\nis one who shines"
	.string "\pwith the electric"
	.string "\ntype."
	.string "\pIf you can defeat"
	.string "\nthese warriors"
	.string "\pwith your courage"
	.string "\nand wisdom, you"
	.string "\pshall be led to"
	.string "\nthe summit, where"
	.string "\pthe strongest"
	.string "\nCHAMPION awaits.$"
