@ Rt13UndellaGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt13UndellaGate_MapScripts::
	.byte 0

Unova_Rt13UndellaGate_EventScript_Npc0::
	msgbox Unova_Rt13UndellaGate_Text_Rt13UndellaGateSocialiteText, MSGBOX_NPC
	end

Unova_Rt13UndellaGate_EventScript_Npc1::
	msgbox Unova_Rt13UndellaGate_Text_Rt13UndellaGateFisherText, MSGBOX_NPC
	end


Unova_Rt13UndellaGate_Text_Rt13UndellaGateSocialiteText::
	.string "Living out here by"
	.string "\nthe beach is so"
	.string "\ppleasant. The"
	.string "\nMARINE TUBE has"
	.string "\pmade it convenient"
	.string "\nto travel quickly"
	.string "\lto HUMILAU CITY.$"

Unova_Rt13UndellaGate_Text_Rt13UndellaGateFisherText::
	.string "I wonder how many"
	.string "\nkinds of POKéMON"
	.string "\pthere are in the"
	.string "\nworld."
	.string "\pWe now know of"
	.string "\nover 600 POKé-"
	.string "\lMON!$"
