@ LentimasLostlornGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_LentimasLostlornGate_MapScripts::
	.byte 0

Unova_LentimasLostlornGate_EventScript_Npc0::
	msgbox Unova_LentimasLostlornGate_Text_LentimasLostlornGateSocialiteText, MSGBOX_NPC
	end

Unova_LentimasLostlornGate_EventScript_Npc1::
	msgbox Unova_LentimasLostlornGate_Text_LentimasLostlornGateYanmaText, MSGBOX_NPC
	end

Unova_LentimasLostlornGate_EventScript_Npc2::
	msgbox Unova_LentimasLostlornGate_Text_LentimasLostlornGateLassText, MSGBOX_NPC
	end


Unova_LentimasLostlornGate_Text_LentimasLostlornGateSocialiteText::
	.string "Oh, honey. You're"
	.string "\ngoing into the"
	.string "\lwoods?"
	.string "\pIt must be scary"
	.string "\nwhen wild POKéMON"
	.string "\lare always around."
	.string "\pHere, have this.$"

Unova_LentimasLostlornGate_Text_LentimasLostlornGateYanmaText::
	.string "YANMA: Yaan!$"

Unova_LentimasLostlornGate_Text_LentimasLostlornGateLassText::
	.string "Be careful, this"
	.string "\nforest is dark."
	.string "\pLots of people"
	.string "\nhave gotten lost"
	.string "\lin there."
	.string "\pI think there must"
	.string "\nbe some POKéMON"
	.string "\pwith tricky powers"
	.string "\nliving in there.$"
