CelesticTownNorthHouse_MapScripts::
	.byte 0

CelesticTownNorthHouse_EventScript_Npc1::
	msgbox CelesticTownNorthHouse_Text_Npc1, MSGBOX_NPC
	end

CelesticTownNorthHouse_Text_Npc1:
	.string "Where are you from?\p...\pHm, Twinleaf Town, you say.\nIsn't that close to Lake Verity?\pThat lake is said to be home to MESPRIT,\n'The Being of Emotion.'\pThat Pokémon may well be watching\nover you.\pWould you like to know more about\nMESPRIT?$"
