PoffinHouse_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

PoffinHouse_EventScript_Npc1::
	msgbox PoffinHouse_Text_Npc1, MSGBOX_NPC
	end

PoffinHouse_Text_Npc1:
	.string "Hi!\nLet's get cooking!\pHere's my advice on cooking tasty\nPoffins for your Pokémon crew!\pIn the beginning, while it's still\na batter, swirl it gently and avoid\pspillage.\pWhen it starts to harden, churn it\nfast in big circles!\pAt the end, make a wish for it to\nturn scrumptious and whirl it!$"

PoffinHouse_EventScript_Npc2::
	msgbox PoffinHouse_Text_Npc2, MSGBOX_NPC
	end

PoffinHouse_Text_Npc2:
	.string "Eating good food makes people and\nPokémon more energetic and happy.\pIn that sense, we're exactly alike.$"

PoffinHouse_EventScript_Npc3::
	msgbox PoffinHouse_Text_Npc3, MSGBOX_NPC
	end

PoffinHouse_Text_Npc3:
	.string "Have you got some Berries?\pTo make delicious Poffins, the key\ningredient is a rare Berry.\pAnd, the more cooks you have,\nthe more delicious the Poffin!$"

PoffinHouse_EventScript_Npc4::
	msgbox PoffinHouse_Text_Npc4, MSGBOX_NPC
	end

PoffinHouse_Text_Npc4:
	.string "At the Wi-Fi Club, I can cook up Poffins\nwith my friends!$"
