OreburghCity_PokemonCenter_2F_MapScripts::
	.byte 0

OreburghCity_PokemonCenter_2F_EventScript_TealaWest::
	msgbox OreburghCity_PokemonCenter_2F_Text_Teala, MSGBOX_NPC
	end

OreburghCity_PokemonCenter_2F_EventScript_TealaMiddle::
	msgbox OreburghCity_PokemonCenter_2F_Text_Teala, MSGBOX_NPC
	end

OreburghCity_PokemonCenter_2F_EventScript_TealaEast::
	msgbox OreburghCity_PokemonCenter_2F_Text_Teala, MSGBOX_NPC
	end

OreburghCity_PokemonCenter_2F_Text_Teala:
	.string "Feel free to use this room to trade\n"
	.string "and battle with other TRAINERS.$"
