@ NsRoom do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_NsRoom_MapScripts::
	.byte 0

Unova_NsRoom_EventScript_Npc0::
	msgbox Unova_NsRoom_Text_NsRoomIntroText, MSGBOX_NPC
	end


Unova_NsRoom_Text_NsRoomIntroText::
	.string "You…"
	.string "\pYou're the one who"
	.string "\nstopped the PLASMA"
	.string "\pSHADOWs' ill"
	.string "\nconceived plan,"
	.string "\laren't you?"
	.string "\pTheir plot was a"
	.string "\nfoolish one, but I"
	.string "\pwouldn't neces-"
	.string "\nsarily call them"
	.string "\levil…"
	.string "\pI can understand"
	.string "\nthe desire to get"
	.string "\pback someone"
	.string "\nprecious to you,"
	.string "\peven if you know"
	.string "\ndeep down that it"
	.string "\pwill never be the"
	.string "\nsame as it once"
	.string "\lwas…"
	.string "\pBut they put an"
	.string "\ninnocent POKéMON"
	.string "\pin danger, and"
	.string "\nthat, I cannot"
	.string "\lforgive."
	.string "\pThat creature…"
	.string "\pThough it was"
	.string "\ncreated artific-"
	.string "\lially, it is still"
	.string "\la POKéMON."
	.string "\pIt deserves to"
	.string "\nlive a happy life,"
	.string "\pas all POKéMON and"
	.string "\npeople do."
	.string "\pYou… You've come"
	.string "\nin search of the"
	.string "\lPOKéMON, right?"
	.string "\pWell, it's no"
	.string "\nlonger here."
	.string "\pBut before I tell"
	.string "\nyou where it went,"
	.string "\pI need to see what"
	.string "\nkind of a trainer"
	.string "\lyou are."
	.string "\pCome! Show me the"
	.string "\npower of the POKé-"
	.string "\lMON who defeated"
	.string "\lTEAM PLASMA!$"
