@ VirbankCity do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VirbankCity_MapScripts::
	.byte 0

Unova_VirbankCity_EventScript_Placa0::
	msgbox Unova_VirbankCity_Text_VirbankCitySignText, MSGBOX_SIGN
	end

Unova_VirbankCity_EventScript_Placa1::
	msgbox Unova_VirbankCity_Text_VirbankGameCornerSignText, MSGBOX_SIGN
	end

Unova_VirbankCity_EventScript_Placa2::
	msgbox Unova_VirbankCity_Text_VirbankComplexSignText, MSGBOX_SIGN
	end

Unova_VirbankCity_EventScript_Placa3::
	msgbox Unova_VirbankCity_Text_VirbankFerrySignText, MSGBOX_SIGN
	end

Unova_VirbankCity_EventScript_Npc4::
	msgbox Unova_VirbankCity_Text_VirbankCityBlockerText, MSGBOX_NPC
	end

Unova_VirbankCity_EventScript_Npc5::
	msgbox Unova_VirbankCity_Text_VirbankFerryManText, MSGBOX_NPC
	end

Unova_VirbankCity_EventScript_Npc6::
	msgbox Unova_VirbankCity_Text_VirbankCityGoodRodText, MSGBOX_NPC
	end

Unova_VirbankCity_EventScript_Npc7::
	msgbox Unova_VirbankCity_Text_VirbankCityTeacher1Text, MSGBOX_NPC
	end

Unova_VirbankCity_EventScript_Npc8::
	msgbox Unova_VirbankCity_Text_VirbankCityTeacher2Text, MSGBOX_NPC
	end

Unova_VirbankCity_EventScript_Npc9::
	msgbox Unova_VirbankCity_Text_VirbankCitySailorText, MSGBOX_NPC
	end

Unova_VirbankCity_EventScript_Npc10::
	msgbox Unova_VirbankCity_Text_VirbankCityRoughneckText, MSGBOX_NPC
	end

Unova_VirbankCity_EventScript_Npc11::
	msgbox Unova_VirbankCity_Text_VirbankCityYoungsterText, MSGBOX_NPC
	end

Unova_VirbankCity_EventScript_Npc12::
	msgbox Unova_VirbankCity_Text_VirbankCityPokefanMText, MSGBOX_NPC
	end


Unova_VirbankCity_Text_VirbankCitySignText::
	.string "VIRBANK CITY"
	.string "\pCity of falling"
	.string "\nfog and rising"
	.string "\lstars!$"

Unova_VirbankCity_Text_VirbankGameCornerSignText::
	.string "VIRBANK CITY"
	.string "\nGAME CORNER!"
	.string "\pCome win fabulous"
	.string "\nprizes!$"

Unova_VirbankCity_Text_VirbankComplexSignText::
	.string "VIRBANK COMPLEX"
	.string "\nahead.$"

Unova_VirbankCity_Text_VirbankFerrySignText::
	.string "FERRY service to"
	.string "\nCASTELIA CITY."
	.string "\pInquire within.$"

Unova_VirbankCity_Text_VirbankCityBlockerText::
	.string "Sorry kid, POKé-"
	.string "\nSTAR STUDIOS is"
	.string "\pclosed to the"
	.string "\npublic."
	.string "\pYou should go"
	.string "\ncheck out the new"
	.string "\lGAME CORNER.$"

Unova_VirbankCity_Text_VirbankFerryManText::
	.string "Ahoy! This be the"
	.string "\nFERRY to CASTELIA"
	.string "\lCITY."
	.string "\pIf ye've got a"
	.string "\nticket, go show it"
	.string "\lto the fellow"
	.string "\linside!$"

Unova_VirbankCity_Text_VirbankCityGoodRodText::
	.string "Hi there! Do you"
	.string "\nlike to fish?$"

Unova_VirbankCity_Text_VirbankCityTeacher1Text::
	.string "I lost at the slot"
	.string "\nmachines again…"
	.string "\pThe new GAME"
	.string "\nCORNER is a branch"
	.string "\pof the one in"
	.string "\nCASTELIA CITY."
	.string "\pI think they have"
	.string "\ndifferent prizes.$"

Unova_VirbankCity_Text_VirbankCityTeacher2Text::
	.string "ROXIE's poison is"
	.string "\nintense! It"
	.string "\lreally stings!"
	.string "\pBut you know what?"
	.string "\nCatch a MAGNEMITE"
	.string "\pin the COMPLEX and"
	.string "\nyou'll be just"
	.string "\lfine!$"

Unova_VirbankCity_Text_VirbankCitySailorText::
	.string "Aww man, I lost my"
	.string "\nFERRY TICKET at"
	.string "\lthe COMPLEX again…"
	.string "\pBoss is gonna be"
	.string "\nso mad!$"

Unova_VirbankCity_Text_VirbankCityRoughneckText::
	.string "I tried to get"
	.string "\ninto the GYM, but"
	.string "\pI couldn't figure"
	.string "\nout their puzzle!$"

Unova_VirbankCity_Text_VirbankCityYoungsterText::
	.string "CASTELIA CITY is"
	.string "\nacross the sea."
	.string "\pI want to ride"
	.string "\nthe ferry!$"

Unova_VirbankCity_Text_VirbankCityPokefanMText::
	.string "VIRBANK CITY is"
	.string "\nthe city of"
	.string "\lindustry!"
	.string "\pWe're proud of our"
	.string "\nbustling burg!$"
