@ AccumulaHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_AccumulaHouse_MapScripts::
	.byte 0

Unova_AccumulaHouse_EventScript_Npc0::
	msgbox Unova_AccumulaHouse_Text_AccumulaHouseTwin1Text, MSGBOX_NPC
	end

Unova_AccumulaHouse_EventScript_Npc1::
	msgbox Unova_AccumulaHouse_Text_AccumulaHouseTwin2Text, MSGBOX_NPC
	end

Unova_AccumulaHouse_EventScript_Npc2::
	msgbox Unova_AccumulaHouse_Text_AccumulaHouseTwin3Text, MSGBOX_NPC
	end


Unova_AccumulaHouse_Text_AccumulaHouseTwin1Text::
	.string "I'm thirsty, do"
	.string "\nyou have some"
	.string "\lSODA POP?$"

Unova_AccumulaHouse_Text_AccumulaHouseTwin2Text::
	.string "I'm thirsty, do"
	.string "\nyou have some"
	.string "\lFRESH WATER?$"

Unova_AccumulaHouse_Text_AccumulaHouseTwin3Text::
	.string "I'm thirsty, do"
	.string "\nyou have some"
	.string "\lLEMONADE?$"
