@ CasteliaCityStreets do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_CasteliaCityStreets_MapScripts::
	.byte 0

Unova_CasteliaCityStreets_EventScript_Placa0::
	msgbox Unova_CasteliaCityStreets_Text_CasteliaBikeSignText, MSGBOX_SIGN
	end

Unova_CasteliaCityStreets_EventScript_Placa1::
	msgbox Unova_CasteliaCityStreets_Text_CasteliaMassageSignText, MSGBOX_SIGN
	end

Unova_CasteliaCityStreets_EventScript_Placa2::
	msgbox Unova_CasteliaCityStreets_Text_CasteliaGameFreakSignText, MSGBOX_SIGN
	end

Unova_CasteliaCityStreets_EventScript_Placa5::
	msgbox Unova_CasteliaCityStreets_Text_CasteliaConeSignText, MSGBOX_SIGN
	end

Unova_CasteliaCityStreets_EventScript_Npc0::
	msgbox Unova_CasteliaCityStreets_Text_CasteliaconeBuyText, MSGBOX_NPC
	end

Unova_CasteliaCityStreets_EventScript_Npc1::
	msgbox Unova_CasteliaCityStreets_Text_CasteliaGiveRestText, MSGBOX_NPC
	end

Unova_CasteliaCityStreets_EventScript_Npc2::
	msgbox Unova_CasteliaCityStreets_Text_CasteliaStreetsYoungsterText, MSGBOX_NPC
	end

Unova_CasteliaCityStreets_EventScript_Npc3::
	msgbox Unova_CasteliaCityStreets_Text_CasteliaStreetsTeacherText, MSGBOX_NPC
	end

Unova_CasteliaCityStreets_EventScript_Npc4::
	msgbox Unova_CasteliaCityStreets_Text_CasteliaStreetsLassText, MSGBOX_NPC
	end

Unova_CasteliaCityStreets_EventScript_Npc5::
	msgbox Unova_CasteliaCityStreets_Text_CasteliaStreetsCooltrainerMText, MSGBOX_NPC
	end


Unova_CasteliaCityStreets_Text_CasteliaBikeSignText::
	.string "CASTELIA CYCLES.$"

Unova_CasteliaCityStreets_Text_CasteliaMassageSignText::
	.string "POKéMON massage"
	.string "\nparlor.$"

Unova_CasteliaCityStreets_Text_CasteliaGameFreakSignText::
	.string "GAME FREAK HQ.$"

Unova_CasteliaCityStreets_Text_CasteliaConeSignText::
	.string "Tasty and refresh-"
	.string "\ning! Get your"
	.string "\lCASTELIACONE"
	.string "\ltoday!$"

Unova_CasteliaCityStreets_Text_CasteliaconeBuyText::
	.string "Hi! Welcome to"
	.string "\nCASTELIA CITY!"
	.string "\pHow would you like"
	.string "\nto try a specialty"
	.string "\lCASTELIACONE?"
	.string "\pIt's just ¥100."
	.string "\pYou can buy just"
	.string "\none, or a dozen."
	.string "\pHow about it?$"

Unova_CasteliaCityStreets_Text_CasteliaGiveRestText::
	.string "…zzzzz…"
	.string "\p…wha, huh?"
	.string "\pHey, I'm trying"
	.string "\nto sleep here!"
	.string "\pTake this and go"
	.string "\naway…$"

Unova_CasteliaCityStreets_Text_CasteliaStreetsYoungsterText::
	.string "I've been training"
	.string "\nout in the desert"
	.string "\pto take on the"
	.string "\nGYM!$"

Unova_CasteliaCityStreets_Text_CasteliaStreetsTeacherText::
	.string "Have you tried a"
	.string "\nCASTELIACONE?"
	.string "\pThey're all the"
	.string "\nrage!$"

Unova_CasteliaCityStreets_Text_CasteliaStreetsLassText::
	.string "I love being"
	.string "\nsurrounded by tall"
	.string "\lbuildings!$"

Unova_CasteliaCityStreets_Text_CasteliaStreetsCooltrainerMText::
	.string "Should I change my"
	.string "\nPOKéMON's moves or"
	.string "\lits held items?$"
