@ MistraltonAirport do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_MistraltonAirport_MapScripts::
	.byte 0

Unova_MistraltonAirport_EventScript_Npc0::
	msgbox Unova_MistraltonAirport_Text_MistraltonAirportRideText, MSGBOX_NPC
	end

Unova_MistraltonAirport_EventScript_Npc1::
	msgbox Unova_MistraltonAirport_Text_MistraltonAirportPokefanFText, MSGBOX_NPC
	end

Unova_MistraltonAirport_EventScript_Npc2::
	msgbox Unova_MistraltonAirport_Text_MistraltonAirportOfficerText, MSGBOX_NPC
	end

Unova_MistraltonAirport_EventScript_Npc3::
	msgbox Unova_MistraltonAirport_Text_MistraltonAirportAskHeartScaleText, MSGBOX_NPC
	end


Unova_MistraltonAirport_Text_MistraltonAirportRideText::
	.string "Welcome to the"
	.string "\nMISTRALTON CITY"
	.string "\lairport."
	.string "\pWe offer flights"
	.string "\nto LENTIMAS TOWN."
	.string "\pAre you coming"
	.string "\non board?$"

Unova_MistraltonAirport_Text_MistraltonAirportPokefanFText::
	.string "I'm planning my"
	.string "\ntrip to LENTIMAS"
	.string "\lTOWN."
	.string "\pIt will be nice to"
	.string "\nspend some time"
	.string "\pout in the"
	.string "\nmountains.$"

Unova_MistraltonAirport_Text_MistraltonAirportOfficerText::
	.string "We mostly ship out"
	.string "\ncargo planes, but"
	.string "\lYou can take a"
	.string "\ppassenger flight"
	.string "\nif you have a"
	.string "\lBOARDINGPASS.$"

Unova_MistraltonAirport_Text_MistraltonAirportAskHeartScaleText::
	.string "Hi, I'm looking"
	.string "\nfor HEART SCALES!"
	.string "\pIf you have a"
	.string "\nHEART SCALE, would"
	.string "\pyou mind giving it"
	.string "\nto me in exchange"
	.string "\lfor a SHARD?$"
