GalacticHq4F_MapScripts::
	.byte 0

@ >>> B6 Sinnoh S1: esqueletos de cena (dev_scripts/maquina_sinnoh.py) >>>
GalacticHq4F_EventScript_CoordEvent_Cyrus::
	@ TODO S6: cena da fonte, rotulo GalacticHQ4F_CoordEvent_Cyrus
	end

@ <<< B6 Sinnoh S1: esqueletos de cena <<<

GalacticHq4F_EventScript_Placa1::
	msgbox GalacticHq4F_Text_Placa1, MSGBOX_SIGN
	end

GalacticHq4F_Text_Placa1:
	.string "Team Galactic Report$"
