@ Rt5Truck do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt5Truck_MapScripts::
	.byte 0

Unova_Rt5Truck_EventScript_Npc0::
	msgbox Unova_Rt5Truck_Text_Rt5TruckGiveBerryText, MSGBOX_NPC
	end


Unova_Rt5Truck_Text_Rt5TruckGiveBerryText::
	.string "Cooking with"
	.string "\nBERRIES is very"
	.string "\phealthy! Even"
	.string "\nPOKéMON love them!"
	.string "\pHere, have a"
	.string "\nBERRY for your"
	.string "\lPOKéMON.$"
