@ GrimsleysRoom do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_GrimsleysRoom_MapScripts::
	.byte 0

Unova_GrimsleysRoom_EventScript_Lider0::
	trainerbattle_single TRAINER_UNOVA_E4_GRIMSLEY, Unova_GrimsleysRoom_Text_EliteFourGrimsleyIntroText, Unova_GrimsleysRoom_Text_EliteFourGrimsleyWinText
	end


Unova_GrimsleysRoom_Text_EliteFourGrimsleyIntroText::
	.string "What will be"
	.string "\ndetermined here is"
	.string "\lwhich of us can"
	.string "\pabsorb the oppo-"
	.string "\nnent's light and"
	.string "\lshine…"
	.string "\pBut who will"
	.string "\ndecide that? It"
	.string "\pshall be I,"
	.string "\nGRIMSLEY of the"
	.string "\lELITE FOUR, and I"
	.string "\pwill fulfill my"
	.string "\nduty to be your"
	.string "\lopponent.$"

Unova_GrimsleysRoom_Text_EliteFourGrimsleyWinText::
	.string "Whether or not you"
	.string "\nget to fight at"
	.string "\pfull strength,"
	.string "\nwhether or not"
	.string "\pluck smiles on"
	.string "\nyou- none of that"
	.string "\pmatters. Only"
	.string "\nresults matter."
	.string "\pAnd a loss is a"
	.string "\nloss. See, victory"
	.string "\pshines like a"
	.string "\nbright light. And"
	.string "\pright now, you and"
	.string "\nyour POKéMON are"
	.string "\lshining!$"
