@ TwistMountain2F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_TwistMountain2F_MapScripts::
	.byte 0

Unova_TwistMountain2F_EventScript_Npc3::
	msgbox Unova_TwistMountain2F_Text_WorkerTwistMountain2FSeenText, MSGBOX_NPC
	end

Unova_TwistMountain2F_EventScript_Npc4::
	msgbox Unova_TwistMountain2F_Text_HikerTwistMountain2FSeenText, MSGBOX_NPC
	end

Unova_TwistMountain2F_EventScript_Npc5::
	msgbox Unova_TwistMountain2F_Text_VeteranFTwistMountain2FSeenText, MSGBOX_NPC
	end


Unova_TwistMountain2F_Text_WorkerTwistMountain2FSeenText::
	.string "Hold up there,"
	.string "\nyoungster!"
	.string "\pA battle will help"
	.string "\nyou warm up!$"

Unova_TwistMountain2F_Text_HikerTwistMountain2FSeenText::
	.string "When I'm surrounded"
	.string "\nby rocks, my"
	.string "\lspirit goes up!$"

Unova_TwistMountain2F_Text_VeteranFTwistMountain2FSeenText::
	.string "In battles, it's"
	.string "\nalso important to"
	.string "\pknow what moves"
	.string "\nnot to make.$"
