GrandLakeRoute213NortheastHouse_MapScripts::
	.byte 0

GrandLakeRoute213NortheastHouse_EventScript_Npc1::
	msgbox GrandLakeRoute213NortheastHouse_Text_Npc1, MSGBOX_NPC
	end

GrandLakeRoute213NortheastHouse_Text_Npc1:
	.string "The reservations were full up,\nbut they managed to get us in here.\pWe're finally alone, the two of us,\nif you'd leave, that is.\pThis is something we don't need\nanymore. Will you take it?$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

GrandLakeRoute213NortheastHouse_EventScript_Npc1::
	msgbox GrandLakeRoute213NortheastHouse_Text_Npc1, MSGBOX_NPC
	end

GrandLakeRoute213NortheastHouse_Text_Npc1:
	.string "That Coin Toss is why we ended up in\nthis musty, old, and stinky suite...$"
