@ StriatonCity do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_StriatonCity_MapScripts::
	.byte 0

Unova_StriatonCity_EventScript_Placa0::
	msgbox Unova_StriatonCity_Text_StriatonCitySignText, MSGBOX_SIGN
	end

Unova_StriatonCity_EventScript_Npc5::
	msgbox Unova_StriatonCity_Text_StriatonCitySocialiteText, MSGBOX_NPC
	end

Unova_StriatonCity_EventScript_Npc6::
	msgbox Unova_StriatonCity_Text_StriatonCityRangerMText, MSGBOX_NPC
	end

Unova_StriatonCity_EventScript_Npc7::
	msgbox Unova_StriatonCity_Text_StriatonCityLassText, MSGBOX_NPC
	end

Unova_StriatonCity_EventScript_Npc8::
	msgbox Unova_StriatonCity_Text_StriatonCityGentlemanText, MSGBOX_NPC
	end


Unova_StriatonCity_Text_StriatonCitySignText::
	.string "STRIATON CITY"
	.string "\pThree stars,"
	.string "\ntogether as one.$"

Unova_StriatonCity_Text_StriatonCitySocialiteText::
	.string "This garden is a"
	.string "\ngreat place to"
	.string "\lcome to relax."
	.string "\pI feel zen just"
	.string "\nstanding here.$"

Unova_StriatonCity_Text_StriatonCityRangerMText::
	.string "DR.FENNEL and DR."
	.string "\nAMANITA live in"
	.string "\lthis city."
	.string "\pThey created many"
	.string "\nthings, even the"
	.string "\lPOKéMON storage"
	.string "\lsystem!$"

Unova_StriatonCity_Text_StriatonCityLassText::
	.string "STRIATON CITY used"
	.string "\nto have three GYM"
	.string "\pleaders, but they"
	.string "\nstepped down."
	.string "\pOne of the leaders"
	.string "\nrecently came back"
	.string "\lto run the GYM,"
	.string "\lthough!$"

Unova_StriatonCity_Text_StriatonCityGentlemanText::
	.string "Going to new, un-"
	.string "\nknown places and"
	.string "\lseeing new people…"
	.string "\pThose are the joys"
	.string "\nof travel.$"
