@ Rt9OpelucidGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt9OpelucidGate_MapScripts::
	.byte 0

Unova_Rt9OpelucidGate_EventScript_Npc0::
	msgbox Unova_Rt9OpelucidGate_Text_R9OpelucidGateOfficerText, MSGBOX_NPC
	end


Unova_Rt9OpelucidGate_Text_R9OpelucidGateOfficerText::
	.string "Are you a POKéMON"
	.string "\ntrainer? The MALL"
	.string "\pon ROUTE 9 has all"
	.string "\nkinds of items"
	.string "\lfor sale."
	.string "\pJust watch out for"
	.string "\nthe tough guys who"
	.string "\pgather out on the"
	.string "\nroad!$"
