OreburghCity_Flat1_F2_MapScripts::
	.byte 0

OreburghCity_Flat1_F2_EventScript_Youngster::
	msgbox OreburghCity_Flat1_F2_Text_Youngster, MSGBOX_NPC
	end

OreburghCity_Flat1_F2_EventScript_Gentleman::
	msgbox OreburghCity_Flat1_F2_Text_Gentleman, MSGBOX_NPC
	end

OreburghCity_Flat1_F2_EventScript_Scientist::
	msgbox OreburghCity_Flat1_F2_Text_Scientist, MSGBOX_NPC
	end

OreburghCity_Flat1_F2_Text_Youngster:
	.string "My dad works at the MINE. He comes\n"
	.string "home covered in coal dust!$"

OreburghCity_Flat1_F2_Text_Gentleman:
	.string "A quiet flat with a good view of\n"
	.string "the GYM. I couldn't ask for more.$"

OreburghCity_Flat1_F2_Text_Scientist:
	.string "I'm studying the rock strata around\n"
	.string "OREBURGH. Fascinating stuff.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

OreburghCity_Flat1_F2_EventScript_Npc1::
	msgbox OreburghCity_Flat1_F2_Text_Npc1, MSGBOX_NPC
	end

OreburghCity_Flat1_F2_Text_Npc1:
	.string "Giving nicknames to Pokémon is\nthe way to go.\pIt makes you feel as if they're your\nvery own.$"

OreburghCity_Flat1_F2_EventScript_Npc2::
	msgbox OreburghCity_Flat1_F2_Text_Npc2, MSGBOX_NPC
	end

OreburghCity_Flat1_F2_Text_Npc2:
	.string "But he named our PSYDUCK 'Yellow'\njust because of its color...\pI don't understand the logic behind\nthat at all.$"

OreburghCity_Flat1_F2_EventScript_Npc3::
	msgbox OreburghCity_Flat1_F2_Text_Npc3, MSGBOX_NPC
	end

OreburghCity_Flat1_F2_Text_Npc3:
	.string "Are you catching Pokémon?\nHere, take this if you'd like.$"

OreburghCity_Flat1_F2_EventScript_Npc4::
	msgbox OreburghCity_Flat1_F2_Text_Npc4, MSGBOX_NPC
	end

OreburghCity_Flat1_F2_Text_Npc4:
	.string "Yellow: Duuuck?$"
