JubilifeCity_JubilifeTV_F2_MapScripts::
	.byte 0

JubilifeCity_JubilifeTV_F2_EventScript_Idol::
	msgbox JubilifeCity_JubilifeTV_F2_Text_Idol, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F2_EventScript_Deskman::
	msgbox JubilifeCity_JubilifeTV_F2_Text_Deskman, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F2_EventScript_Roughneck::
	msgbox JubilifeCity_JubilifeTV_F2_Text_Roughneck, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F2_Text_Idol:
	.string "I'm here for the accessory photo\n"
	.string "shoot. How do I look?$"

JubilifeCity_JubilifeTV_F2_Text_Deskman:
	.string "The star of tomorrow could be you!\n"
	.string "Keep your POKéMON looking sharp.$"

JubilifeCity_JubilifeTV_F2_Text_Roughneck:
	.string "This floor's always busy. Cameras,\n"
	.string "lights, the whole deal.$"
