JubilifeCity_JubilifeTV_F2_MapScripts::
	.byte 0

JubilifeCity_JubilifeTV_F2_EventScript_Idol::
	msgbox JubilifeCity_JubilifeTV_F2_Text_Idol, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F2_EventScript_Deskman::
	msgbox JubilifeCity_JubilifeTV_F2_Text_Deskman, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F2_Text_Idol:
	.string "I'm here for the accessory photo\n"
	.string "shoot. How do I look?$"

JubilifeCity_JubilifeTV_F2_Text_Deskman:
	.string "The star of tomorrow could be you!\n"
	.string "Keep your POKéMON looking sharp.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

JubilifeCity_JubilifeTV_F2_EventScript_Npc1::
	msgbox JubilifeCity_JubilifeTV_F2_Text_Npc1, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F2_Text_Npc1:
	.string "I don't know what to do.\pWhat Accessories will go well with\nmy dress today?$"

JubilifeCity_JubilifeTV_F2_EventScript_Npc2::
	msgbox JubilifeCity_JubilifeTV_F2_Text_Npc2, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F2_Text_Npc2:
	.string "The star of tomorrow is... You!\nYour Pokémon has a glow about it!\pSo, a gift for our future star!$"

JubilifeCity_JubilifeTV_F2_EventScript_Npc3::
	msgbox JubilifeCity_JubilifeTV_F2_Text_Npc3, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F2_Text_Npc3:
	.string "The room at the back is our dreamy\nfitting room.\pOnce you're done in there, get our\ndreamy Hiker to take a dreamy photo!$"
