@ LentimasGym do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_LentimasGym_MapScripts::
	.byte 0

Unova_LentimasGym_EventScript_Npc0::
	msgbox Unova_LentimasGym_Text_ShauntalGymIntroText, MSGBOX_NPC
	end

Unova_LentimasGym_EventScript_Npc1::
	msgbox Unova_LentimasGym_Text_LentimasGymGuyText, MSGBOX_NPC
	end

Unova_LentimasGym_EventScript_Npc2::
	msgbox Unova_LentimasGym_Text_HexManiacLentimasGym1AfterText, MSGBOX_NPC
	end

Unova_LentimasGym_EventScript_Npc3::
	msgbox Unova_LentimasGym_Text_HexManiacLentimasGym2AfterText, MSGBOX_NPC
	end

Unova_LentimasGym_EventScript_Npc4::
	msgbox Unova_LentimasGym_Text_HexManiacLentimasGym3AfterText, MSGBOX_NPC
	end

Unova_LentimasGym_EventScript_Npc5::
	msgbox Unova_LentimasGym_Text_HexManiacLentimasGym4AfterText, MSGBOX_NPC
	end


Unova_LentimasGym_Text_ShauntalGymIntroText::
	.string "Hmm…"
	.string "\p… … … …$"

Unova_LentimasGym_Text_LentimasGymGuyText::
	.string "Yo, challenger!"
	.string "\pSHAUNTAL may look"
	.string "\nlike a bookworm,"
	.string "\pbut she's got"
	.string "\nserious knowledge"
	.string "\lof ghosts!"
	.string "\pIt's going to be"
	.string "\ntough without my"
	.string "\ladvice."
	.string "\pLet's see… Ghost"
	.string "\nPOKéMON don't like"
	.string "\lbeing hit by"
	.string "\lother ghosts."
	.string "\pDark-type moves"
	.string "\nare super-effec-"
	.string "\ltive too.$"

Unova_LentimasGym_Text_HexManiacLentimasGym1AfterText::
	.string "Ghost type POKéMON"
	.string "\ncannot be harmed"
	.string "\pby normal type"
	.string "\nattacks!$"

Unova_LentimasGym_Text_HexManiacLentimasGym2AfterText::
	.string "We hide in the"
	.string "\nshadows and wait"
	.string "\pto scare passers-"
	.string "\nby. Just like a"
	.string "\lghost!$"

Unova_LentimasGym_Text_HexManiacLentimasGym3AfterText::
	.string "I need more guid-"
	.string "\nance from SHAUNTAL"
	.string "\pif I want to get"
	.string "\nstronger…"
	.string "\pShe should hurry"
	.string "\nup and put out the"
	.string "\lnext book already!$"

Unova_LentimasGym_Text_HexManiacLentimasGym4AfterText::
	.string "I came to this"
	.string "\ntown to search for"
	.string "\pghosts. It's great"
	.string "\nif you're into the"
	.string "\lsupernatural!$"
