Route34_House1_MapScripts::
	.byte 0

Route34_House1_EventScript_Npc1::
	msgbox Route34_House1_EventScript_Npc1_Text, MSGBOX_NPC
	end

Route34_House1_EventScript_Npc1_Text:
	.string "I built this place for the fishing.\pThe water south of here is thick with\nTENTACOOL. Bring a good rod.$"

Route34_House1_EventScript_Npc2::
	msgbox Route34_House1_EventScript_Npc2_Text, MSGBOX_NPC
	end

Route34_House1_EventScript_Npc2_Text:
	.string "The Day Care is just up the road.\nThey opened the front door again!$"
