OreburghCityPokecenterB1F_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

OreburghCityPokecenterB1F_EventScript_Npc1::
	msgbox OreburghCityPokecenterB1F_Text_Npc1, MSGBOX_NPC
	end

OreburghCityPokecenterB1F_Text_Npc1:
	.string "I want to become friends with an\nexperienced Trainer I really admire.\pI can't wait for us to register each\nother in our Pal Pads.\pThen, we can play together using\nthe Wi-Fi Club!$"
