@ DriftveilStoneEmporium do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_DriftveilStoneEmporium_MapScripts::
	.byte 0

Unova_DriftveilStoneEmporium_EventScript_Placa0::
	msgbox Unova_DriftveilStoneEmporium_Text_StoneEmporiumSignText, MSGBOX_SIGN
	end

Unova_DriftveilStoneEmporium_EventScript_Placa1::
	msgbox Unova_DriftveilStoneEmporium_Text_StoneEmporiumElevatorText, MSGBOX_SIGN
	end

Unova_DriftveilStoneEmporium_EventScript_Npc0::
	msgbox Unova_DriftveilStoneEmporium_Text_StoneEmporiumReceptionistText, MSGBOX_NPC
	end

Unova_DriftveilStoneEmporium_EventScript_Npc1::
	msgbox Unova_DriftveilStoneEmporium_Text_TutorAskTeachRedText, MSGBOX_NPC
	end

Unova_DriftveilStoneEmporium_EventScript_Npc2::
	msgbox Unova_DriftveilStoneEmporium_Text_TutorAskTeachBlueText, MSGBOX_NPC
	end

Unova_DriftveilStoneEmporium_EventScript_Npc3::
	msgbox Unova_DriftveilStoneEmporium_Text_TutorAskTeachGreenText, MSGBOX_NPC
	end

Unova_DriftveilStoneEmporium_EventScript_Npc4::
	msgbox Unova_DriftveilStoneEmporium_Text_TutorAskTeachYellowText, MSGBOX_NPC
	end


Unova_DriftveilStoneEmporium_Text_StoneEmporiumSignText::
	.string "DRIFTVEIL STONE"
	.string "\nEMPORIUM"
	.string "\pProprietor: CLAY$"

Unova_DriftveilStoneEmporium_Text_StoneEmporiumElevatorText::
	.string "Entry to the mines"
	.string "\nis restricted to"
	.string "\lstaff. -CLAY$"

Unova_DriftveilStoneEmporium_Text_StoneEmporiumReceptionistText::
	.string "Welcome to the"
	.string "\nDRIFTVEIL STONE"
	.string "\lEMPORIUM!"
	.string "\pPeople come from"
	.string "\nall over to seek"
	.string "\lout rare stones.$"

Unova_DriftveilStoneEmporium_Text_TutorAskTeachRedText::
	.string "Hi, I'm looking"
	.string "\nfor RED SHARDS!"
	.string "\pIf you give me"
	.string "\nsome, I can teach"
	.string "\lyour POKéMON some"
	.string "\lmoves in return."
	.string "\pHow about it?$"

Unova_DriftveilStoneEmporium_Text_TutorAskTeachBlueText::
	.string "Hi, I'm looking"
	.string "\nfor BLUE SHARDS!"
	.string "\pIf you give me"
	.string "\nsome, I can teach"
	.string "\lyour POKéMON some"
	.string "\lmoves in return."
	.string "\pHow about it?$"

Unova_DriftveilStoneEmporium_Text_TutorAskTeachGreenText::
	.string "Hi, I'm looking"
	.string "\nfor GREEN SHARDS!"
	.string "\pIf you give me"
	.string "\nsome, I can teach"
	.string "\lyour POKéMON some"
	.string "\lmoves in return."
	.string "\pHow about it?$"

Unova_DriftveilStoneEmporium_Text_TutorAskTeachYellowText::
	.string "Hi, I'm looking"
	.string "\nfor YELLOW SHARDS!"
	.string "\pIf you give me"
	.string "\nsome, I can teach"
	.string "\lyour POKéMON some"
	.string "\lmoves in return."
	.string "\pHow about it?$"
