@ Rt21 do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt21_MapScripts::
	.byte 0

Unova_Rt21_EventScript_Npc3::
	msgbox Unova_Rt21_Text_SwimmerM1R21SeenText, MSGBOX_NPC
	end

Unova_Rt21_EventScript_Npc4::
	msgbox Unova_Rt21_Text_SwimmerM2R21SeenText, MSGBOX_NPC
	end

Unova_Rt21_EventScript_Npc5::
	msgbox Unova_Rt21_Text_SwimmerM3R21SeenText, MSGBOX_NPC
	end

Unova_Rt21_EventScript_Npc6::
	msgbox Unova_Rt21_Text_SwimmerF1R21SeenText, MSGBOX_NPC
	end

Unova_Rt21_EventScript_Npc7::
	msgbox Unova_Rt21_Text_SwimmerF2R21SeenText, MSGBOX_NPC
	end

Unova_Rt21_EventScript_Npc8::
	msgbox Unova_Rt21_Text_SwimmerF3R21SeenText, MSGBOX_NPC
	end

Unova_Rt21_EventScript_Npc9::
	msgbox Unova_Rt21_Text_BlackbeltR21SeenText, MSGBOX_NPC
	end


Unova_Rt21_Text_SwimmerM1R21SeenText::
	.string "I trained with"
	.string "\nMARLON, the gym"
	.string "\pleader of HUMILAU"
	.string "\nCITY!$"

Unova_Rt21_Text_SwimmerM2R21SeenText::
	.string "It is said that"
	.string "\nwater will not"
	.string "\pgrow stagnant as"
	.string "\nlong as it keeps"
	.string "\lflowing…"
	.string "\pSo as long as I"
	.string "\nkeep moving on…$"

Unova_Rt21_Text_SwimmerM3R21SeenText::
	.string "You see this enor-"
	.string "\nmous puddle? They"
	.string "\lcall it an ocean!$"

Unova_Rt21_Text_SwimmerF1R21SeenText::
	.string "The thing about"
	.string "\nwater is that it's"
	.string "\lalways changing…"
	.string "\pFrom the piercing"
	.string "\nstrength of a jet,"
	.string "\pto the crushing"
	.string "\npower of a wave…"
	.string "\pThat's what I'm"
	.string "\nabout to show you!$"

Unova_Rt21_Text_SwimmerF2R21SeenText::
	.string "Catch this! My"
	.string "\nPOKéMON is huge!$"

Unova_Rt21_Text_SwimmerF3R21SeenText::
	.string "I learned all the"
	.string "\ngood points of my"
	.string "\pwater type POKéMON"
	.string "\nby swimming with"
	.string "\lthem!$"

Unova_Rt21_Text_BlackbeltR21SeenText::
	.string "Hi-yah! Hi-yah!"
	.string "\nI'm practicing my"
	.string "\ppunching technique"
	.string "\nin front of the"
	.string "\psea! Give it a"
	.string "\ntry!$"
