@ Rt21 do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt21_MapScripts::
	.byte 0

Unova_Rt21_EventScript_Lider3::
	trainerbattle_single TRAINER_UNOVA_SWIMMER_M_R21_1, Unova_Rt21_Text_SwimmerM1R21SeenText, Unova_Rt21_Text_SwimmerM1R21BeatenText
	end

Unova_Rt21_EventScript_Lider4::
	trainerbattle_single TRAINER_UNOVA_SWIMMER_M_R21_2, Unova_Rt21_Text_SwimmerM2R21SeenText, Unova_Rt21_Text_SwimmerM2R21BeatenText
	end

Unova_Rt21_EventScript_Lider5::
	trainerbattle_single TRAINER_UNOVA_SWIMMER_M_R21_3, Unova_Rt21_Text_SwimmerM3R21SeenText, Unova_Rt21_Text_SwimmerM3R21BeatenText
	end

Unova_Rt21_EventScript_Lider6::
	trainerbattle_single TRAINER_UNOVA_SWIMMER_F_R21_1, Unova_Rt21_Text_SwimmerF1R21SeenText, Unova_Rt21_Text_SwimmerF1R21BeatenText
	end

Unova_Rt21_EventScript_Lider7::
	trainerbattle_single TRAINER_UNOVA_SWIMMER_F_R21_2, Unova_Rt21_Text_SwimmerF2R21SeenText, Unova_Rt21_Text_SwimmerF2R21BeatenText
	end

Unova_Rt21_EventScript_Lider8::
	trainerbattle_single TRAINER_UNOVA_SWIMMER_F_R21_3, Unova_Rt21_Text_SwimmerF3R21SeenText, Unova_Rt21_Text_SwimmerF3R21BeatenText
	end

Unova_Rt21_EventScript_Lider9::
	trainerbattle_single TRAINER_UNOVA_BLACKBELT_R21, Unova_Rt21_Text_BlackbeltR21SeenText, Unova_Rt21_Text_BlackbeltR21BeatenText
	end


Unova_Rt21_Text_SwimmerM1R21SeenText::
	.string "I trained with"
	.string "\nMARLON, the gym"
	.string "\pleader of HUMILAU"
	.string "\nCITY!$"

Unova_Rt21_Text_SwimmerM1R21BeatenText::
	.string "I still have room"
	.string "\nto improve!$"

Unova_Rt21_Text_SwimmerM2R21SeenText::
	.string "It is said that"
	.string "\nwater will not"
	.string "\pgrow stagnant as"
	.string "\nlong as it keeps"
	.string "\lflowing…"
	.string "\pSo as long as I"
	.string "\nkeep moving on…$"

Unova_Rt21_Text_SwimmerM2R21BeatenText::
	.string "Looks like I've"
	.string "\ngotten stagnant…$"

Unova_Rt21_Text_SwimmerM3R21SeenText::
	.string "You see this enor-"
	.string "\nmous puddle? They"
	.string "\lcall it an ocean!$"

Unova_Rt21_Text_SwimmerM3R21BeatenText::
	.string "Woah! You're"
	.string "\nenormous too!$"

Unova_Rt21_Text_SwimmerF1R21SeenText::
	.string "The thing about"
	.string "\nwater is that it's"
	.string "\lalways changing…"
	.string "\pFrom the piercing"
	.string "\nstrength of a jet,"
	.string "\pto the crushing"
	.string "\npower of a wave…"
	.string "\pThat's what I'm"
	.string "\nabout to show you!$"

Unova_Rt21_Text_SwimmerF1R21BeatenText::
	.string "You're just as"
	.string "\nstrong, perhaps"
	.string "\leven stronger!$"

Unova_Rt21_Text_SwimmerF2R21SeenText::
	.string "Catch this! My"
	.string "\nPOKéMON is huge!$"

Unova_Rt21_Text_SwimmerF2R21BeatenText::
	.string "Wow, you're even"
	.string "\nmore than I"
	.string "\lexpected!$"

Unova_Rt21_Text_SwimmerF3R21SeenText::
	.string "I learned all the"
	.string "\ngood points of my"
	.string "\pwater type POKéMON"
	.string "\nby swimming with"
	.string "\lthem!$"

Unova_Rt21_Text_SwimmerF3R21BeatenText::
	.string "What a fresh"
	.string "\ntrainer! Really,"
	.string "\lreally fresh!$"

Unova_Rt21_Text_BlackbeltR21SeenText::
	.string "Hi-yah! Hi-yah!"
	.string "\nI'm practicing my"
	.string "\ppunching technique"
	.string "\nin front of the"
	.string "\psea! Give it a"
	.string "\ntry!$"

Unova_Rt21_Text_BlackbeltR21BeatenText::
	.string "I won't stop"
	.string "\npunching just"
	.string "\lbecause I lost!$"
