JubilifeCity_Flat1_F1_MapScripts::
	.byte 0

JubilifeCity_Flat1_F1_EventScript_ExpertF::
	msgbox JubilifeCity_Flat1_F1_Text_ExpertF, MSGBOX_NPC
	end

JubilifeCity_Flat1_F1_EventScript_Pikachu::
	msgbox JubilifeCity_Flat1_F1_Text_Pikachu, MSGBOX_NPC
	end

JubilifeCity_Flat1_F1_EventScript_Beauty::
	msgbox JubilifeCity_Flat1_F1_Text_Beauty, MSGBOX_NPC
	end

JubilifeCity_Flat1_F1_Text_ExpertF:
	.string "This building is quiet enough\n"
	.string "for tea, loud enough for\l"
	.string "POKéMON chatter.\p"
	.string "I like the balance.$"

JubilifeCity_Flat1_F1_Text_Pikachu:
	.string "Pika pika!$"

JubilifeCity_Flat1_F1_Text_Beauty:
	.string "Oh, your POKéMON is quite\n"
	.string "adorable! Here, try making it\l"
	.string "hold a Quick Claw.\p"
	.string "A POKéMON holding that can\n"
	.string "sometimes attack first, even if\l"
	.string "it's normally a little slow.\p"
	.string "There are other items that are\n"
	.string "only useful when held. Try\l"
	.string "finding some yourself...\p"
	.string "I sound like a teacher or\n"
	.string "something.$"
