@ P2Lab do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_P2Lab_MapScripts::
	.byte 0

Unova_P2Lab_EventScript_Placa0::
	msgbox Unova_P2Lab_Text_P2LabDoorText, MSGBOX_SIGN
	end

Unova_P2Lab_EventScript_Placa1::
	msgbox Unova_P2Lab_Text_P2LabDoorText, MSGBOX_SIGN
	end

Unova_P2Lab_EventScript_Placa2::
	msgbox Unova_P2Lab_Text_P2LabDoorText, MSGBOX_SIGN
	end

Unova_P2Lab_EventScript_Placa3::
	msgbox Unova_P2Lab_Text_P2LabDoorText, MSGBOX_SIGN
	end

Unova_P2Lab_EventScript_Placa4::
	msgbox Unova_P2Lab_Text_P2LabDoorText, MSGBOX_SIGN
	end

Unova_P2Lab_EventScript_Placa5::
	msgbox Unova_P2Lab_Text_P2LabDiaryText1, MSGBOX_SIGN
	end

Unova_P2Lab_EventScript_Placa6::
	msgbox Unova_P2Lab_Text_P2LabDiaryText2, MSGBOX_SIGN
	end

Unova_P2Lab_EventScript_Placa7::
	msgbox Unova_P2Lab_Text_P2LabDiaryText3, MSGBOX_SIGN
	end

Unova_P2Lab_EventScript_Placa8::
	msgbox Unova_P2Lab_Text_P2LabDiaryText4, MSGBOX_SIGN
	end

Unova_P2Lab_EventScript_Npc7::
	msgbox Unova_P2Lab_Text_GruntM1P2LabSeenText, MSGBOX_NPC
	end

Unova_P2Lab_EventScript_Npc8::
	msgbox Unova_P2Lab_Text_GruntM2P2LabSeenText, MSGBOX_NPC
	end

Unova_P2Lab_EventScript_Npc9::
	msgbox Unova_P2Lab_Text_GruntF1P2LabSeenText, MSGBOX_NPC
	end

Unova_P2Lab_EventScript_Npc10::
	msgbox Unova_P2Lab_Text_GruntF2P2LabSeenText, MSGBOX_NPC
	end

Unova_P2Lab_EventScript_Npc11::
	msgbox Unova_P2Lab_Text_ScientistP2LabSeenText, MSGBOX_NPC
	end


Unova_P2Lab_Text_P2LabDoorText::
	.string "There's a switch."
	.string "\nPress it?$"

Unova_P2Lab_Text_P2LabDiaryText1::
	.string "There's a document"
	.string "\non the PC…"
	.string "\pGENESIS PROJECT-"
	.string "\pToday, …e"
	.string "\nspec…en arr…ed."
	.string "\p… …st be"
	.string "\n…ions of years"
	.string "\lol… …"
	.string "\p… …n't wait …"
	.string "\n…n the proj… …$"

Unova_P2Lab_Text_P2LabDiaryText2::
	.string "There's a document"
	.string "\non the PC…"
	.string "\pGENESIS PROJECT-"
	.string "\pThe …ect …"
	.string "\n…ov… …lower tha…"
	.string "\l…pected…"
	.string "\p… …have had"
	.string "\n…ficulty … …ith"
	.string "\l…tegrati… the…"
	.string "\p…bernetic parts"
	.string "\n… …hout serio…"
	.string "\l…gradation."
	.string "\pSt… …e must"
	.string "\npr… on.$"

Unova_P2Lab_Text_P2LabDiaryText3::
	.string "There's a document"
	.string "\non the PC…"
	.string "\pGENESIS PROJECT-"
	.string "\p… …reakthrough!"
	.string "\n… project was"
	.string "\p… …ught fully"
	.string "\nonl… …oday."
	.string "\pDespi… …oss of"
	.string "\ncontr… …he proof"
	.string "\lof conc… …as"
	.string "\l…idated!"
	.string "\p…will not be"
	.string "\n…ng now…$"

Unova_P2Lab_Text_P2LabDiaryText4::
	.string "There's a document"
	.string "\non the PC…"
	.string "\pGENESIS PROJECT-"
	.string "\p…rd fro… …pper"
	.string "\nmanag… …ject has"
	.string "\l…n cancel… …"
	.string "\p…se fools do… …"
	.string "\n… …will no… …"
	.string "\pI wi… …rry out"
	.string "\n… …NESIS P… …T to"
	.string "\l… …letion. I m… …"
	.string "\p… … … …$"

Unova_P2Lab_Text_GruntM1P2LabSeenText::
	.string "This time, we'll"
	.string "\ntake over the"
	.string "\lUNOVA region!$"

Unova_P2Lab_Text_GruntM2P2LabSeenText::
	.string "I'm the fighting"
	.string "\nsweeper! I'll"
	.string "\pclean up garbage"
	.string "\nlike you!$"

Unova_P2Lab_Text_GruntF1P2LabSeenText::
	.string "I'm going to go"
	.string "\nahead and say it:"
	.string "\pPlasmaaaa!!$"

Unova_P2Lab_Text_GruntF2P2LabSeenText::
	.string "Our king is gone…"
	.string "\nBut we are still"
	.string "\lhere!$"

Unova_P2Lab_Text_ScientistP2LabSeenText::
	.string "You! You've come"
	.string "\nto steal my work!"
	.string "\pI'll never let my"
	.string "\nproject be taken!$"
