GlobalTerminal2F_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

GlobalTerminal2F_EventScript_Npc1::
	msgbox GlobalTerminal2F_Text_Npc1, MSGBOX_NPC
	end

GlobalTerminal2F_Text_Npc1:
	.string "Did you know?\nAbout my PC Box, I mean.\pIt's full of Pokémon everyone longs\nfor, like...\p...No, it would be immodest for me to\nsay. It would sound like bragging.\pIf you really must know, you can always\nfind out yourself.$"

GlobalTerminal2F_EventScript_Npc2::
	msgbox GlobalTerminal2F_Text_Npc2, MSGBOX_NPC
	end

GlobalTerminal2F_Text_Npc2:
	.string "What I like to do...\pI like sneaking glances at the people\nchecking out Dress-Up Data.$"

GlobalTerminal2F_EventScript_Npc3::
	msgbox GlobalTerminal2F_Text_Npc3, MSGBOX_NPC
	end

GlobalTerminal2F_Text_Npc3:
	.string "The combination of that Pokémon with\nthose Accessories...\pIt was so stunningly wonderful, I feel\nas if I've been zapped!$"

GlobalTerminal2F_EventScript_Npc4::
	msgbox GlobalTerminal2F_Text_Npc4, MSGBOX_NPC
	end

GlobalTerminal2F_Text_Npc4:
	.string "The same kind of Accessory can create\nentirely different impressions.\pIt really depends on where and how\nit's used.$"

GlobalTerminal2F_EventScript_Npc5::
	msgbox GlobalTerminal2F_Text_Npc5, MSGBOX_NPC
	end

GlobalTerminal2F_Text_Npc5:
	.string "I got a Backdrop from a nice lady\ndownstairs. For free!$"

GlobalTerminal2F_EventScript_Npc6::
	msgbox GlobalTerminal2F_Text_Npc6, MSGBOX_NPC
	end

GlobalTerminal2F_Text_Npc6:
	.string "Oh, dear me! Gracious!\nThis is almost scandalous!$"

GlobalTerminal2F_EventScript_Npc7::
	msgbox GlobalTerminal2F_Text_Npc7, MSGBOX_NPC
	end

GlobalTerminal2F_Text_Npc7:
	.string "Sneaking a peek at other people's PC\nBoxes fills me with guilty glee.\pBut it's a secret sort of pleasure I'd\nrather not have others know about.\p...Ignoring the fact that me being here\nis a surefire giveaway.$"

GlobalTerminal2F_EventScript_Npc8::
	msgbox GlobalTerminal2F_Text_Npc8, MSGBOX_NPC
	end

GlobalTerminal2F_Text_Npc8:
	.string "I visit every day to check on other\npeople's Dress-Up Data.\pFor me, it's like the first step to\nfashion!$"

GlobalTerminal2F_EventScript_Npc9::
	msgbox GlobalTerminal2F_Text_Npc9, MSGBOX_NPC
	end

GlobalTerminal2F_Text_Npc9:
	.string "This is discriminatory!\nWhy are there only shots of Pokémon?\pWhy aren't there any shots of ladies?\nI call discrimination!$"

GlobalTerminal2F_EventScript_Placa10::
	msgbox GlobalTerminal2F_Text_Placa10, MSGBOX_SIGN
	end

GlobalTerminal2F_Text_Placa10:
	.string "Warps to the GTS and the Trainer\nRankings on 1F.$"

GlobalTerminal2F_EventScript_Placa11::
	msgbox GlobalTerminal2F_Text_Placa11, MSGBOX_SIGN
	end

GlobalTerminal2F_Text_Placa11:
	.string "Warps to the Battle Video Gallery on 3F.$"

GlobalTerminal2F_EventScript_Placa12::
	msgbox GlobalTerminal2F_Text_Placa12, MSGBOX_SIGN
	end

GlobalTerminal2F_Text_Placa12:
	.string "Connect to Nintendo Wi-Fi Connection\nto view and post Box Data?$"

GlobalTerminal2F_EventScript_Placa13::
	msgbox GlobalTerminal2F_Text_Placa13, MSGBOX_SIGN
	end

GlobalTerminal2F_Text_Placa13:
	.string "Connect to Nintendo Wi-Fi Connection\nto view and post Box Data?$"

GlobalTerminal2F_EventScript_Placa14::
	msgbox GlobalTerminal2F_Text_Placa14, MSGBOX_SIGN
	end

GlobalTerminal2F_Text_Placa14:
	.string "Connect to Nintendo Wi-Fi Connection\nto view and post Dress-Up Data?$"

GlobalTerminal2F_EventScript_Placa15::
	msgbox GlobalTerminal2F_Text_Placa15, MSGBOX_SIGN
	end

GlobalTerminal2F_Text_Placa15:
	.string "Connect to Nintendo Wi-Fi Connection\nto view and post Dress-Up Data?$"

GlobalTerminal2F_EventScript_Placa16::
	msgbox GlobalTerminal2F_Text_Placa16, MSGBOX_SIGN
	end

GlobalTerminal2F_Text_Placa16:
	.string "Connect to Nintendo Wi-Fi Connection\nto view and post Dress-Up Data?$"

GlobalTerminal2F_EventScript_Placa17::
	msgbox GlobalTerminal2F_Text_Placa17, MSGBOX_SIGN
	end

GlobalTerminal2F_Text_Placa17:
	.string "Connect to Nintendo Wi-Fi Connection\nto view and post Dress-Up Data?$"

GlobalTerminal2F_EventScript_Placa18::
	msgbox GlobalTerminal2F_Text_Placa18, MSGBOX_SIGN
	end

GlobalTerminal2F_Text_Placa18:
	.string "Connect to Nintendo Wi-Fi Connection\nto view and post Box Data?$"

GlobalTerminal2F_EventScript_Placa19::
	msgbox GlobalTerminal2F_Text_Placa19, MSGBOX_SIGN
	end

GlobalTerminal2F_Text_Placa19:
	.string "Connect to Nintendo Wi-Fi Connection\nto view and post Box Data?$"
