MtCoronet_1F_South_MapScripts::
	.byte 0

MtCoronet_1F_South_EventScript_Hiker1::
	msgbox MtCoronet_1F_South_Text_Hiker1, MSGBOX_NPC
	end

MtCoronet_1F_South_EventScript_BlackBelt::
	msgbox MtCoronet_1F_South_Text_BlackBelt, MSGBOX_NPC
	end

MtCoronet_1F_South_EventScript_Hiker2::
	msgbox MtCoronet_1F_South_Text_Hiker2, MSGBOX_NPC
	end

MtCoronet_1F_South_Text_Hiker1:
	.string "MOUNT CORONET splits SINNOH right\n"
	.string "down the middle.\p"
	.string "Quite a climb, isn't it?$"

MtCoronet_1F_South_Text_BlackBelt:
	.string "Training on a mountain like this\n"
	.string "toughens you up fast.$"

MtCoronet_1F_South_Text_Hiker2:
	.string "Watch for loose rocks.\p"
	.string "This place doesn't forgive a\n"
	.string "careless step.$"
