ValleyWindworksBuilding_MapScripts::
	.byte 0

ValleyWindworksBuilding_EventScript_Npc1::
	msgbox ValleyWindworksBuilding_Text_Npc1, MSGBOX_NPC
	end

ValleyWindworksBuilding_Text_Npc1:
	.string "Papa: Oh, yes, a balloon Pokémon\nappears in front of the windworks.\pIt's always a certain day of the week,\nbut I'm not sure which day.\pCould its appearance have something\nto do with this windworks using\pwind-generated energy?$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

ValleyWindworksBuilding_EventScript_Placa1::
	msgbox ValleyWindworksBuilding_Text_Placa1, MSGBOX_SIGN
	end

ValleyWindworksBuilding_Text_Placa1:
	.string "The bringer of wars...\pYour target is the energy of the power\nplant.\pThe bringer of contentment...\pYour target is the Pokémon statue of\nEterna City.\pThe bringer of aging...\pYour target is the Pokémon that sleeps\non today.\pThe dream energy.\n           Team Galactic$"

ValleyWindworksBuilding_EventScript_Placa2::
	msgbox ValleyWindworksBuilding_Text_Placa2, MSGBOX_SIGN
	end

ValleyWindworksBuilding_Text_Placa2:
	.string "The bringer of wars...\pYour target is the energy of the power\nplant.\pThe bringer of contentment...\pYour target is the Pokémon statue of\nEterna City.\pThe bringer of aging...\pYour target is the Pokémon that sleeps\non today.\pThe dream energy.\n           Team Galactic$"
