@ LacunosaHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_LacunosaHouse_MapScripts::
	.byte 0

Unova_LacunosaHouse_EventScript_Npc0::
	msgbox Unova_LacunosaHouse_Text_LacunosaHouseGiveBerryText, MSGBOX_NPC
	end

Unova_LacunosaHouse_EventScript_Npc1::
	msgbox Unova_LacunosaHouse_Text_LacunosaHouseGiveBerryText, MSGBOX_NPC
	end


Unova_LacunosaHouse_Text_LacunosaHouseGiveBerryText::
	.string "You know, POKéMON"
	.string "\neat BERRIES."
	.string "\pDifferent BERRIES"
	.string "\nhelp POKéMON in"
	.string "\ldifferent ways."
	.string "\pHere. I'll share"
	.string "\none with you!$"
