SunyshoreCityWestHouse_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

SunyshoreCityWestHouse_EventScript_Npc1::
	msgbox SunyshoreCityWestHouse_Text_Npc1, MSGBOX_NPC
	end

SunyshoreCityWestHouse_Text_Npc1:
	.string "Have you gone underground lately?\pDepending on where you go down, you\nend up in different places.\pThat's why I use my Explorer Kit in as\nmany places as I can.$"

SunyshoreCityWestHouse_EventScript_Npc2::
	msgbox SunyshoreCityWestHouse_Text_Npc2, MSGBOX_NPC
	end

SunyshoreCityWestHouse_Text_Npc2:
	.string "The Spheres found in the underground\ntunnels are like gems.\pYou can obtain goodies by trading\nthe Spheres away.$"

SunyshoreCityWestHouse_EventScript_Npc3::
	msgbox SunyshoreCityWestHouse_Text_Npc3, MSGBOX_NPC
	end

SunyshoreCityWestHouse_Text_Npc3:
	.string "Some underground Traps need to be\ndefused by touch or by using the\pmicrophone!$"

SunyshoreCityWestHouse_EventScript_Npc4::
	msgbox SunyshoreCityWestHouse_Text_Npc4, MSGBOX_NPC
	end

SunyshoreCityWestHouse_Text_Npc4:
	.string "The Underground Man in Eterna and\nByron of Canalave are related.\pAdd Byron's son Roark, and you have\na trio of dedicated diggers.$"

SunyshoreCityWestHouse_EventScript_Npc5::
	msgbox SunyshoreCityWestHouse_Text_Npc5, MSGBOX_NPC
	end

SunyshoreCityWestHouse_Text_Npc5:
	.string "If you bury Spheres, they grow\na little every day.\pThey're really weird that way.\pOh, right! I'd better dig mine up!\nI forgot I had some buried!$"

SunyshoreCityWestHouse_EventScript_Npc6::
	msgbox SunyshoreCityWestHouse_Text_Npc6, MSGBOX_NPC
	end

SunyshoreCityWestHouse_Text_Npc6:
	.string "Get Flags from your friends to make\nyour Secret Base better.\pTry to hide your Secret Base, and\nget good at discovering your\pfriends' bases.$"

SunyshoreCityWestHouse_EventScript_Npc7::
	msgbox SunyshoreCityWestHouse_Text_Npc7, MSGBOX_NPC
	end

SunyshoreCityWestHouse_Text_Npc7:
	.string "Go underground and have fun down\nthere. Make it an adventure!$"
