@ DragonspiralTower5F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_DragonspiralTower5F_MapScripts::
	.byte 0

Unova_DragonspiralTower5F_EventScript_Lider3::
	trainerbattle_single TRAINER_UNOVA_GORM2, Unova_DragonspiralTower5F_Text_DragonspiralTowerGormSeenText, Unova_DragonspiralTower5F_Text_DragonspiralTowerGormBeatenText
	end


Unova_DragonspiralTower5F_Text_DragonspiralTowerGormSeenText::
	.string "… … … …"
	.string "\pTEAM PLASMA…$"

Unova_DragonspiralTower5F_Text_DragonspiralTowerGormBeatenText::
	.string "…$"
