FightAreaMiddleHouse_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

FightAreaMiddleHouse_EventScript_Npc1::
	msgbox FightAreaMiddleHouse_Text_Npc1, MSGBOX_NPC
	end

FightAreaMiddleHouse_Text_Npc1:
	.string "Even from here, we could see the\npeak of Mt. Coronet.\pMost people didn't notice what\nhappened up there, but I did.\pBut I don't know what took place\nexactly, or anything like that.$"

FightAreaMiddleHouse_EventScript_Npc2::
	msgbox FightAreaMiddleHouse_Text_Npc2, MSGBOX_NPC
	end

FightAreaMiddleHouse_Text_Npc2:
	.string "Everyone's fanatical about battling\nhere.$"

FightAreaMiddleHouse_EventScript_Npc3::
	msgbox FightAreaMiddleHouse_Text_Npc3, MSGBOX_NPC
	end

FightAreaMiddleHouse_Text_Npc3:
	.string "People are people, and I'm me.\nI don't like to be compared.\pBut comparing with other people reveals\nthings about yourself sometimes, too.\pThat's why you should check out the\nGlobal Terminal in Jubilife City.$"
