@ PWTDriftveilGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_PWTDriftveilGate_MapScripts::
	.byte 0

Unova_PWTDriftveilGate_EventScript_Npc0::
	msgbox Unova_PWTDriftveilGate_Text_PwtDriftveilGateOfficerText, MSGBOX_NPC
	end


Unova_PWTDriftveilGate_Text_PwtDriftveilGateOfficerText::
	.string "The POKéMON WORLD"
	.string "\nTOUNAMENT brings"
	.string "\pin the best"
	.string "\ntrainers in UNOVA!$"
