@ Rt11Truck do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt11Truck_MapScripts::
	.byte 0

Unova_Rt11Truck_EventScript_Npc0::
	msgbox Unova_Rt11Truck_Text_RockCollectorIntroText, MSGBOX_NPC
	end


Unova_Rt11Truck_Text_RockCollectorIntroText::
	.string "Hi there, they"
	.string "\ncall me the ROCK"
	.string "\lCOLLECTOR."
	.string "\pI've gathered rare"
	.string "\nrocks and stones"
	.string "\lfrom all over!"
	.string "\pFor just ¥2000,"
	.string "\nI'll sell you a"
	.string "\prock from my"
	.string "\ncollection."
	.string "\pHow about it?$"
