OldChateauSideRooms_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

OldChateauSideRooms_EventScript_Placa1::
	msgbox OldChateauSideRooms_Text_Placa1, MSGBOX_SIGN
	end

OldChateauSideRooms_Text_Placa1:
	.string "It's an old notebook.\nThere's something scrawled in it...\p'Som...hing so pecu...r shou...\nmake off ...ith the mot...'\pThe rest of the pages are blank.$"
