ContestHallStageNoContest_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

ContestHallStageNoContest_EventScript_Npc1::
	msgbox ContestHallStageNoContest_Text_Npc1, MSGBOX_NPC
	end

ContestHallStageNoContest_Text_Npc1:
	.string "For the Visual judging, you want to\ndress up your Pokémon nicely with\pAccessories matched to the theme.\pThat means you'll be at an advantage\nif you have lots of Accessories.$"

ContestHallStageNoContest_EventScript_Npc2::
	msgbox ContestHallStageNoContest_Text_Npc2, MSGBOX_NPC
	end

ContestHallStageNoContest_Text_Npc2:
	.string "For the Dance competition, your\nPokémon needs to perfectly mimic\pthe dance steps of the lead dancer.$"

ContestHallStageNoContest_EventScript_Npc3::
	msgbox ContestHallStageNoContest_Text_Npc3, MSGBOX_NPC
	end

ContestHallStageNoContest_Text_Npc3:
	.string "For the performance aspect of\nContests, Pokémon need the right\pkinds of moves.\pBut what's even more important is\nyour choice of the Judge.\pIf everyone performs for the same\nJudge, your Pokémon leaves less of\pan impression on that Judge.$"

ContestHallStageNoContest_EventScript_Npc4::
	msgbox ContestHallStageNoContest_Text_Npc4, MSGBOX_NPC
	end

ContestHallStageNoContest_Text_Npc4:
	.string "At the Cool Contest you gotta pull\noff a cool move!\pGets the Judges all excited!\pIf the Judge's excitement peaks, you\nscore massive bonus points! So hot!$"
