@ VirbankStatExpHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VirbankStatExpHouse_MapScripts::
	.byte 0

Unova_VirbankStatExpHouse_EventScript_Npc0::
	msgbox Unova_VirbankStatExpHouse_Text_VirbankStatExpHouse_AskMonText, MSGBOX_NPC
	end


Unova_VirbankStatExpHouse_Text_VirbankStatExpHouse_AskMonText::
	.string "Hey! I'm looking"
	.string "\nto see a POKéMON"
	.string "\pwith a strong"
	.string "\nATTACK stat!"
	.string "\pCan you show me a"
	.string "\nPOKéMON that's"
	.string "\ptrained its ATTACK"
	.string "\nstat a lot?$"
