@ MossdeepCity_Ex14_17: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 14.17) por dev_scripts/copia_planta_ex.py.

MossdeepCity_Ex14_17_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 14.17), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
MossdeepCity_Ex14_17_EventScript_ExNpc1::
	msgbox MossdeepCity_Ex14_17_Text_ExNpc1, MSGBOX_NPC
	end

MossdeepCity_Ex14_17_Text_ExNpc1:
	.string "Shh!\n"
	.string "I’m hiding from my mom!$"

