@ IcirrusCityNorth do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_IcirrusCityNorth_MapScripts::
	.byte 0

Unova_IcirrusCityNorth_EventScript_Placa0::
	msgbox Unova_IcirrusCityNorth_Text_IcirrusBoutiqueText, MSGBOX_SIGN
	end

Unova_IcirrusCityNorth_EventScript_Placa1::
	msgbox Unova_IcirrusCityNorth_Text_IcirrusFanClubSignText, MSGBOX_SIGN
	end

Unova_IcirrusCityNorth_EventScript_Npc1::
	msgbox Unova_IcirrusCityNorth_Text_IcirrusCityNorthBuenaText, MSGBOX_NPC
	end

Unova_IcirrusCityNorth_EventScript_Npc2::
	msgbox Unova_IcirrusCityNorth_Text_IcirrusCityNorthBlackbeltText, MSGBOX_NPC
	end


Unova_IcirrusCityNorth_Text_IcirrusBoutiqueText::
	.string "ICIRRUS BOUTIQUE"
	.string "\pAll things fashion"
	.string "\nfor people and"
	.string "\lPOKéMON!$"

Unova_IcirrusCityNorth_Text_IcirrusFanClubSignText::
	.string "POKéMON FAN CLUB"
	.string "\pShare your love"
	.string "\nof POKéMON!$"

Unova_IcirrusCityNorth_Text_IcirrusCityNorthBuenaText::
	.string "Always, the tower"
	.string "\nlooms, disdainful"
	.string "\pof the wind and"
	.string "\nsnow. Perhaps its"
	.string "\ppresence is tell-"
	.string "\ning us not to"
	.string "\pforget dreams and"
	.string "\nideals…$"

Unova_IcirrusCityNorth_Text_IcirrusCityNorthBlackbeltText::
	.string "Our former GYM"
	.string "\nLEADER, BRYCEN,"
	.string "\phas been surround-"
	.string "\ned by ice type"
	.string "\pPOKéMON and has"
	.string "\ntrained in the"
	.string "\pmartial arts ever"
	.string "\nsince he was a"
	.string "\lchild."
	.string "\pHe's become an"
	.string "\naction star using"
	.string "\lthat experience!$"
