@ FortreeCity_Ex12_10: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 12.10) por dev_scripts/copia_planta_ex.py.

FortreeCity_Ex12_10_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 12.10), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
FortreeCity_Ex12_10_EventScript_ExNpc0::
	msgbox FortreeCity_Ex12_10_Text_ExNpc0, MSGBOX_NPC
	end

FortreeCity_Ex12_10_Text_ExNpc0:
	.string "The neighbor kids like creepy bugs!\p"
	.string "He’s mean.\p"
	.string "He always jumps out and scares me...$"

FortreeCity_Ex12_10_EventScript_ExNpc1::
	msgbox FortreeCity_Ex12_10_Text_ExNpc1, MSGBOX_NPC
	end

FortreeCity_Ex12_10_Text_ExNpc1:
	.string "What impressive POKéMON you have.\p"
	.string "You must be doing the GYM challenge$"

