ResortAreaRibbonSyndicate1F_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

ResortAreaRibbonSyndicate1F_EventScript_Npc1::
	msgbox ResortAreaRibbonSyndicate1F_Text_Npc1, MSGBOX_NPC
	end

ResortAreaRibbonSyndicate1F_Text_Npc1:
	.string "Welcome! We've looked forward to\nseeing you, {PLAYER}.\pI do hope you will enjoy the luxurious\natmosphere and services that only\pwe can provide.$"

ResortAreaRibbonSyndicate1F_EventScript_Npc2::
	msgbox ResortAreaRibbonSyndicate1F_Text_Npc2, MSGBOX_NPC
	end

ResortAreaRibbonSyndicate1F_Text_Npc2:
	.string "Just being in here is a sign of\nstatus, just so you know.$"

ResortAreaRibbonSyndicate1F_EventScript_Npc3::
	msgbox ResortAreaRibbonSyndicate1F_Text_Npc3, MSGBOX_NPC
	end

ResortAreaRibbonSyndicate1F_Text_Npc3:
	.string "SKITTY: Skiii!$"

ResortAreaRibbonSyndicate1F_EventScript_Npc4::
	msgbox ResortAreaRibbonSyndicate1F_Text_Npc4, MSGBOX_NPC
	end

ResortAreaRibbonSyndicate1F_Text_Npc4:
	.string "PSYDUCK: Gyaugyau!$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

ResortAreaRibbonSyndicate1F_EventScript_Npc5::
	msgbox ResortAreaRibbonSyndicate1F_Text_Npc5, MSGBOX_NPC
	end

ResortAreaRibbonSyndicate1F_Text_Npc5:
	.string "Welcome.\pMay I interest you in top-grade\nRibbons we had specially imported?\pThese Ribbons are available only\nthrough us.\p{PLAYER}, would you like one\nfor a Pokémon, perhaps?\pRight now, I can offer you\nthe Gorgeous Ribbon.\pFor a mere ¥10,000, you can be the\nproud owner of one.$"
