@ FoothillTown_House6: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 17.8) por dev_scripts/copia_planta_ex.py.

FoothillTown_House6_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 17.8), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
FoothillTown_House6_EventScript_ExNpc0::
	msgbox FoothillTown_House6_Text_ExNpc0, MSGBOX_NPC
	end

FoothillTown_House6_Text_ExNpc0:
	.string "FOOTHILL TOWN was so peaceful until all\n"
	.string "these fishermen showed up.$"

FoothillTown_House6_EventScript_ExNpc1::
	msgbox FoothillTown_House6_Text_ExNpc1, MSGBOX_NPC
	end

FoothillTown_House6_Text_ExNpc1:
	.string "I wouldn’t mind all these people in\n"
	.string "FOOTHILL TOWN except they don’t do\l"
	.string "anything but fish!\p"
	.string "They whole town is starting to smell\n"
	.string "like MAGIKARP!$"

