@ VictoryRoadOutdoor1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VictoryRoadOutdoor1F_MapScripts::
	.byte 0

Unova_VictoryRoadOutdoor1F_EventScript_Npc3::
	msgbox Unova_VictoryRoadOutdoor1F_Text_VictoryRoadNurseIntroText, MSGBOX_NPC
	end

Unova_VictoryRoadOutdoor1F_EventScript_Npc4::
	msgbox Unova_VictoryRoadOutdoor1F_Text_BackpackerFVictoryRoadOutdoor1FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadOutdoor1F_EventScript_Npc5::
	msgbox Unova_VictoryRoadOutdoor1F_Text_VeteranFVictoryRoadOutdoor1FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadOutdoor1F_EventScript_Npc6::
	msgbox Unova_VictoryRoadOutdoor1F_Text_VeteranMVictoryRoadOutdoor1FSeenText, MSGBOX_NPC
	end


Unova_VictoryRoadOutdoor1F_Text_VictoryRoadNurseIntroText::
	.string "I'm a nurse, but"
	.string "\nI'm also a POKé-"
	.string "\lMON trainer."
	.string "\pIf you can defeat"
	.string "\nme in a battle,"
	.string "\lI'll heal your"
	.string "\lPOKéMON.$"

Unova_VictoryRoadOutdoor1F_Text_BackpackerFVictoryRoadOutdoor1FSeenText::
	.string "I am…"
	.string "\pEx-TEAM PLASMA!$"

Unova_VictoryRoadOutdoor1F_Text_VeteranFVictoryRoadOutdoor1FSeenText::
	.string "Wait! You, young"
	.string "\ntrainer over"
	.string "\pthere! Look at my"
	.string "\nPOKéMON.$"

Unova_VictoryRoadOutdoor1F_Text_VeteranMVictoryRoadOutdoor1FSeenText::
	.string "Are you sure you"
	.string "\nwant to seriously"
	.string "\ptake on someone"
	.string "\nlike me, who"
	.string "\lbattles seriously?$"
