UnusedOreburghCityEastHouse3F_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

UnusedOreburghCityEastHouse3F_EventScript_Npc1::
	msgbox UnusedOreburghCityEastHouse3F_Text_Npc1, MSGBOX_NPC
	end

UnusedOreburghCityEastHouse3F_Text_Npc1:
	.string "The coal mine here's fully automated.\pCoal mining was brutally hard in the\nold days, but not anymore!$"

UnusedOreburghCityEastHouse3F_EventScript_Npc2::
	msgbox UnusedOreburghCityEastHouse3F_Text_Npc2, MSGBOX_NPC
	end

UnusedOreburghCityEastHouse3F_Text_Npc2:
	.string "You remind me so much of the time\nI got my first Pokémon.$"
