Route216House_MapScripts::
	.byte 0

Route216House_EventScript_Npc1::
	msgbox Route216House_Text_Npc1, MSGBOX_NPC
	end

Route216House_Text_Npc1:
	.string "Yahoo! This lodge's seen better days,\nbut relax, make yourself at home!$"

Route216House_EventScript_Placa1::
	msgbox Route216House_Text_Placa1, MSGBOX_SIGN
	end

Route216House_Text_Placa1:
	.string "It's a bed...\nWant to take a rest?$"

Route216House_EventScript_Placa2::
	msgbox Route216House_Text_Placa2, MSGBOX_SIGN
	end

Route216House_Text_Placa2:
	.string "It's a bed...\nWant to take a rest?$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

Route216House_EventScript_Npc2::
	msgbox Route216House_Text_Npc2, MSGBOX_NPC
	end

Route216House_Text_Npc2:
	.string "I don't have Thick Fat like some\nPokémon.\pThat's why I'm bundled up in layers of\nthick clothes.\pIncidentally, do you know what the\nability Thick Fat does?\pIt halves the damage taken from Ice-\nand Fire-type moves.$"
