Route216House_MapScripts::
	.byte 0

Route216House_EventScript_Npc1::
	msgbox Route216House_Text_Npc1, MSGBOX_NPC
	end

Route216House_Text_Npc1:
	.string "Yahoo! This lodge's seen better days,\nbut relax, make yourself at home!$"

Route216House_EventScript_Placa1::
	msgbox Route216House_Text_Placa1, MSGBOX_SIGN
	end

Route216House_Text_Placa1:
	.string "It's a bed...\nWant to take a rest?$"

Route216House_EventScript_Placa2::
	msgbox Route216House_Text_Placa2, MSGBOX_SIGN
	end

Route216House_Text_Placa2:
	.string "It's a bed...\nWant to take a rest?$"
