PastoriaCityObservatoryGate1F_MapScripts::
	.byte 0

PastoriaCityObservatoryGate1F_EventScript_Npc1::
	msgbox PastoriaCityObservatoryGate1F_Text_Npc1, MSGBOX_NPC
	end

PastoriaCityObservatoryGate1F_Text_Npc1:
	.string "Welcome to the Great Marsh!\nIs this your first Safari Game?$"

PastoriaCityObservatoryGate1F_EventScript_Npc2::
	msgbox PastoriaCityObservatoryGate1F_Text_Npc2, MSGBOX_NPC
	end

PastoriaCityObservatoryGate1F_Text_Npc2:
	.string "Howdy.\nYou're playing the Safari Game?\pHow would you like to try my game out\nat the same time?\pThe rule--yep, there's only one--is\nreal simple.\pAll you have to do is capture five or\nmore Pokémon in one Safari Game.\pIf you can do that, I'll give you the\nPokétch app Matchup Checker.$"
