@ UndellaOldRodHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_UndellaOldRodHouse_MapScripts::
	.byte 0

Unova_UndellaOldRodHouse_EventScript_Npc0::
	msgbox Unova_UndellaOldRodHouse_Text_OfferOldRodText, MSGBOX_NPC
	end


Unova_UndellaOldRodHouse_Text_OfferOldRodText::
	.string "This town is a"
	.string "\ngreat fishing"
	.string "\lspot."
	.string "\pHow about"
	.string "\nyou?"
	.string "\pWould you like one"
	.string "\nof my RODS?$"
