@ MoorOfIcirrus do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_MoorOfIcirrus_MapScripts::
	.byte 0

Unova_MoorOfIcirrus_EventScript_Npc8::
	msgbox Unova_MoorOfIcirrus_Text_Fisher1MoorOfIcirrusSeenText, MSGBOX_NPC
	end

Unova_MoorOfIcirrus_EventScript_Npc9::
	msgbox Unova_MoorOfIcirrus_Text_Fisher2MoorOfIcirrusSeenText, MSGBOX_NPC
	end

Unova_MoorOfIcirrus_EventScript_Npc10::
	msgbox Unova_MoorOfIcirrus_Text_PkmnRangerFMoorOfIcirrusSeenText, MSGBOX_NPC
	end

Unova_MoorOfIcirrus_EventScript_Npc11::
	msgbox Unova_MoorOfIcirrus_Text_PkmnRangerMMoorOfIcirrusSeenText, MSGBOX_NPC
	end


Unova_MoorOfIcirrus_Text_Fisher1MoorOfIcirrusSeenText::
	.string "Check out my POKé-"
	.string "\nMON! It took me"
	.string "\p100 POKé BALLs to"
	.string "\ncatch it!$"

Unova_MoorOfIcirrus_Text_Fisher2MoorOfIcirrusSeenText::
	.string "I'll have a battle"
	.string "\nwith you using my"
	.string "\pfreshly caught"
	.string "\nPOKéMON!$"

Unova_MoorOfIcirrus_Text_PkmnRangerFMoorOfIcirrusSeenText::
	.string "POKéMON trainers"
	.string "\nnurture friendship"
	.string "\lwith battles!$"

Unova_MoorOfIcirrus_Text_PkmnRangerMMoorOfIcirrusSeenText::
	.string "Knowing oneself,"
	.string "\nknowing the other,"
	.string "\pand knowing the"
	.string "\nsurroundings…"
	.string "\pThat's a RANGER!$"
