@ Route125_Ex14_13: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 14.13) por dev_scripts/copia_planta_ex.py.

Route125_Ex14_13_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 14.13), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
Route125_Ex14_13_EventScript_ExNpc0::
	msgbox Route125_Ex14_13_Text_ExNpc0, MSGBOX_NPC
	end

Route125_Ex14_13_Text_ExNpc0:
	.string "I have a crush on the woman next door.\p"
	.string "Should I ask her out on a date?$"

