@ NimbasaCity do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_NimbasaCity_MapScripts::
	.byte 0

Unova_NimbasaCity_EventScript_Placa0::
	msgbox Unova_NimbasaCity_Text_NimbasaR5SignText, MSGBOX_SIGN
	end

Unova_NimbasaCity_EventScript_Placa1::
	msgbox Unova_NimbasaCity_Text_NimbasaR16SignText, MSGBOX_SIGN
	end

Unova_NimbasaCity_EventScript_Placa2::
	msgbox Unova_NimbasaCity_Text_NimbasaR4SignText, MSGBOX_SIGN
	end

Unova_NimbasaCity_EventScript_Placa3::
	msgbox Unova_NimbasaCity_Text_NimbasaSubwaySignText, MSGBOX_SIGN
	end

Unova_NimbasaCity_EventScript_Placa4::
	msgbox Unova_NimbasaCity_Text_NimbasaBallMartSignText, MSGBOX_SIGN
	end

Unova_NimbasaCity_EventScript_Placa5::
	msgbox Unova_NimbasaCity_Text_NimbasaVitaminMartSignText, MSGBOX_SIGN
	end

Unova_NimbasaCity_EventScript_Placa6::
	msgbox Unova_NimbasaCity_Text_NimbasaTMMartSignText, MSGBOX_SIGN
	end

Unova_NimbasaCity_EventScript_Npc1::
	msgbox Unova_NimbasaCity_Text_NimbasaCityYoungsterText, MSGBOX_NPC
	end

Unova_NimbasaCity_EventScript_Npc2::
	msgbox Unova_NimbasaCity_Text_NimbasaCityGrampsText, MSGBOX_NPC
	end

Unova_NimbasaCity_EventScript_Npc3::
	msgbox Unova_NimbasaCity_Text_NimbasaCityTeacherText, MSGBOX_NPC
	end

Unova_NimbasaCity_EventScript_Npc4::
	msgbox Unova_NimbasaCity_Text_NimbasaCityLassText, MSGBOX_NPC
	end

Unova_NimbasaCity_EventScript_Npc5::
	msgbox Unova_NimbasaCity_Text_NimbasaCityBugCatcherText1, MSGBOX_NPC
	end

Unova_NimbasaCity_EventScript_Npc6::
	msgbox Unova_NimbasaCity_Text_NimbasaCityRangerFText, MSGBOX_NPC
	end

Unova_NimbasaCity_EventScript_Npc7::
	msgbox Unova_NimbasaCity_Text_NimbasaCityCooltrainerFText, MSGBOX_NPC
	end

Unova_NimbasaCity_EventScript_Npc8::
	msgbox Unova_NimbasaCity_Text_NimbasaCityYoungster2Text, MSGBOX_NPC
	end


Unova_NimbasaCity_Text_NimbasaR5SignText::
	.string "ROUTE 5 ahead."
	.string "\pPassage to"
	.string "\nDRIFTVEIL CITY.$"

Unova_NimbasaCity_Text_NimbasaR16SignText::
	.string "ROUTE 16 ahead."
	.string "\pPassage to"
	.string "\nLOSTLORN FOREST.$"

Unova_NimbasaCity_Text_NimbasaR4SignText::
	.string "ROUTE 4 ahead."
	.string "\pPassage to"
	.string "\nCASTELIA CITY."
	.string "\pWatch out for"
	.string "\ncontruction!$"

Unova_NimbasaCity_Text_NimbasaSubwaySignText::
	.string "NIMBASA CITY"
	.string "\nSUBWAY station.$"

Unova_NimbasaCity_Text_NimbasaBallMartSignText::
	.string "NIMBASA CITY"
	.string "\nPOKéBALL SHOP"
	.string "\pGet equipped to"
	.string "\ncatch POKéMON!$"

Unova_NimbasaCity_Text_NimbasaVitaminMartSignText::
	.string "NIMBASA CITY"
	.string "\nVITAMIN MART."
	.string "\pIncrease your"
	.string "\nPOKéMON's health.$"

Unova_NimbasaCity_Text_NimbasaTMMartSignText::
	.string "NIMBASA CITY"
	.string "\nTM SHOP."
	.string "\pPower up your"
	.string "\nPOKéMON with new"
	.string "\lmoves!$"

Unova_NimbasaCity_Text_NimbasaCityYoungsterText::
	.string "E-he-he-he…"
	.string "\pI got in trouble"
	.string "\nfor playing in the"
	.string "\lold PARK…$"

Unova_NimbasaCity_Text_NimbasaCityGrampsText::
	.string "Whew! This is one"
	.string "\nbig town. I don't"
	.string "\pknow where any-"
	.string "\nthing is.$"

Unova_NimbasaCity_Text_NimbasaCityTeacherText::
	.string "There used to be"
	.string "\na GYM in the PARK"
	.string "\lin town."
	.string "\pBut ever since the"
	.string "\nGYM LEADER, ELESA,"
	.string "\lleft for bigger"
	.string "\land better things,"
	.string "\pthe PARK has"
	.string "\nfallen into dis-"
	.string "\lrepair…$"

Unova_NimbasaCity_Text_NimbasaCityLassText::
	.string "I'm taking the"
	.string "\nSUBWAY to visit"
	.string "\pmy friend in"
	.string "\nASPERTIA CITY."
	.string "\pA rail pass sure"
	.string "\nis nice for"
	.string "\ltraveling!$"

Unova_NimbasaCity_Text_NimbasaCityBugCatcherText1::
	.string "A mean man was"
	.string "\nstanding outside"
	.string "\lthe PARK."
	.string "\pHe wouldn't let"
	.string "\nme in. It was"
	.string "\lscary…$"

Unova_NimbasaCity_Text_NimbasaCityRangerFText::
	.string "The man at that"
	.string "\nhouse rates your"
	.string "\lPOKéMON names."
	.string "\pHe can even rename"
	.string "\nyour POKéMON.$"

Unova_NimbasaCity_Text_NimbasaCityCooltrainerFText::
	.string "The shops here in"
	.string "\ntown sell all"
	.string "\pkinds of useful"
	.string "\nthings for POKé-"
	.string "\lMON trainers!$"

Unova_NimbasaCity_Text_NimbasaCityYoungster2Text::
	.string "There used to be"
	.string "\na fun PARK in"
	.string "\ptown, but it"
	.string "\nclosed down.$"
