@ Rt23West do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt23West_MapScripts::
	.byte 0

Unova_Rt23West_EventScript_Npc1::
	msgbox Unova_Rt23West_Text_R23Officer7StopText, MSGBOX_NPC
	end

Unova_Rt23West_EventScript_Npc11::
	msgbox Unova_Rt23West_Text_AceTrainerM2R23SeenText, MSGBOX_NPC
	end

Unova_Rt23West_EventScript_Npc12::
	msgbox Unova_Rt23West_Text_AceTrainerF2R23SeenText, MSGBOX_NPC
	end

Unova_Rt23West_EventScript_Npc13::
	msgbox Unova_Rt23West_Text_BackpackerMR23SeenText, MSGBOX_NPC
	end

Unova_Rt23West_EventScript_Npc14::
	msgbox Unova_Rt23West_Text_BackpackerFR23SeenText, MSGBOX_NPC
	end

Unova_Rt23West_EventScript_Npc15::
	msgbox Unova_Rt23West_Text_PkmnRangerMR23SeenText, MSGBOX_NPC
	end

Unova_Rt23West_EventScript_Npc16::
	msgbox Unova_Rt23West_Text_PkmnRangerFR23SeenText, MSGBOX_NPC
	end

Unova_Rt23West_EventScript_Npc17::
	msgbox Unova_Rt23West_Text_BattleGirlR23SeenText, MSGBOX_NPC
	end

Unova_Rt23West_EventScript_Npc18::
	msgbox Unova_Rt23West_Text_VeteranMR23SeenText, MSGBOX_NPC
	end


Unova_Rt23West_Text_R23Officer7StopText::
	.string "Stop! Ahead lies"
	.string "\nthe path to the"
	.string "\lPOKéMON LEAGUE."
	.string "\pOnly those who"
	.string "\nhave collected"
	.string "\pall 8 POKéMON"
	.string "\nLEAGUE GYM BADGES"
	.string "\lmay enter."
	.string "\pYou cannot pass"
	.string "\nhere unless you"
	.string "\phave the"
	.string "\nLEGENDBADGE.$"

Unova_Rt23West_Text_AceTrainerM2R23SeenText::
	.string "I keep a tally of"
	.string "\nall of the times"
	.string "\pthat I have won or"
	.string "\nlost up until"
	.string "\ptoday. If I battle"
	.string "\nyou, I wonder"
	.string "\pwhich number will"
	.string "\nbe increased.$"

Unova_Rt23West_Text_AceTrainerF2R23SeenText::
	.string "This is the"
	.string "\nconcerto I perform"
	.string "\pwith my most"
	.string "\nbeloved POKéMON!$"

Unova_Rt23West_Text_BackpackerMR23SeenText::
	.string "You look like an"
	.string "\nopponent who will"
	.string "\phighlight my"
	.string "\nweaknesses.$"

Unova_Rt23West_Text_BackpackerFR23SeenText::
	.string "A heated battle is"
	.string "\ngood, but get too"
	.string "\phot and you might"
	.string "\nend up getting"
	.string "\lburned!$"

Unova_Rt23West_Text_PkmnRangerMR23SeenText::
	.string "I've been waiting"
	.string "\nfor this! Waiting"
	.string "\pfor this very"
	.string "\nmoment!$"

Unova_Rt23West_Text_PkmnRangerFR23SeenText::
	.string "Oh trainer,"
	.string "\nembarking on the"
	.string "\ppath to VICTORY"
	.string "\nROAD! Won't you"
	.string "\pshow me your true"
	.string "\npower?!$"

Unova_Rt23West_Text_BattleGirlR23SeenText::
	.string "Your POKéMON must"
	.string "\nbe really some-"
	.string "\pthing if you're"
	.string "\nhere on ROUTE 23!$"

Unova_Rt23West_Text_VeteranMR23SeenText::
	.string "Hey there, future"
	.string "\nchampion!$"
