@ OpelucidGym do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_OpelucidGym_MapScripts::
	.byte 0

Unova_OpelucidGym_EventScript_Npc0::
	msgbox Unova_OpelucidGym_Text_DraydenGymIntroText, MSGBOX_NPC
	end

Unova_OpelucidGym_EventScript_Npc1::
	msgbox Unova_OpelucidGym_Text_VeteranM1OpelucidGymSeenText, MSGBOX_NPC
	end

Unova_OpelucidGym_EventScript_Npc2::
	msgbox Unova_OpelucidGym_Text_VeteranM2OpelucidGymSeenText, MSGBOX_NPC
	end

Unova_OpelucidGym_EventScript_Npc3::
	msgbox Unova_OpelucidGym_Text_VeteranM3OpelucidGymSeenText, MSGBOX_NPC
	end

Unova_OpelucidGym_EventScript_Npc4::
	msgbox Unova_OpelucidGym_Text_VeteranF1OpelucidGymSeenText, MSGBOX_NPC
	end

Unova_OpelucidGym_EventScript_Npc5::
	msgbox Unova_OpelucidGym_Text_VeteranF2OpelucidGymSeenText, MSGBOX_NPC
	end

Unova_OpelucidGym_EventScript_Npc6::
	msgbox Unova_OpelucidGym_Text_VeteranF3OpelucidGymSeenText, MSGBOX_NPC
	end

Unova_OpelucidGym_EventScript_Npc7::
	msgbox Unova_OpelucidGym_Text_OpelucidGymGuyText, MSGBOX_NPC
	end


Unova_OpelucidGym_Text_DraydenGymIntroText::
	.string "Welcome. Thank you"
	.string "\nfor coming. I am"
	.string "\pthe OPELUCID GYM"
	.string "\nLEADER, DRAYDEN."
	.string "\pAs mayor, I've"
	.string "\ngiven everything"
	.string "\pto developing the"
	.string "\ncity. As a"
	.string "\ptrainer, I've been"
	.string "\npursuing greater"
	.string "\lstrength."
	.string "\pWhat I'm searching"
	.string "\nfor now is a young"
	.string "\ptrainer who can"
	.string "\nshow me a bright"
	.string "\pfuture. Perhaps"
	.string "\nyou can show me"
	.string "\pthat future, the"
	.string "\nway IRIS has?$"

Unova_OpelucidGym_Text_VeteranM1OpelucidGymSeenText::
	.string "Always aim for the"
	.string "\ntop, like a dragon"
	.string "\ltaking flight!$"

Unova_OpelucidGym_Text_VeteranM2OpelucidGymSeenText::
	.string "A strong defense"
	.string "\nis everything!$"

Unova_OpelucidGym_Text_VeteranM3OpelucidGymSeenText::
	.string "Use your POKéMON"
	.string "\nin combination to"
	.string "\praise their"
	.string "\ndestructive power!$"

Unova_OpelucidGym_Text_VeteranF1OpelucidGymSeenText::
	.string "I believe the best"
	.string "\ndefense is a"
	.string "\lstrong offense!$"

Unova_OpelucidGym_Text_VeteranF2OpelucidGymSeenText::
	.string "In battles, how"
	.string "\nyour POKéMON"
	.string "\pfollow each other"
	.string "\nis key.$"

Unova_OpelucidGym_Text_VeteranF3OpelucidGymSeenText::
	.string "I just felt a"
	.string "\ngreat wind… Are"
	.string "\pyou the one who"
	.string "\nkicked it up?$"

Unova_OpelucidGym_Text_OpelucidGymGuyText::
	.string "Yo, challenger!"
	.string "\pThis GYM's LEADER"
	.string "\nis DRAYDEN, the"
	.string "\lmaster of dragons."
	.string "\pAll of his pupils"
	.string "\ntrain with dragon-"
	.string "\ltype POKéMON too."
	.string "\pThey're wild and"
	.string "\nunpredictable!"
	.string "\pYour best bet"
	.string "\nwould be to bring"
	.string "\la fairy-type POKé-"
	.string "\lMON."
	.string "\pDragons also don't"
	.string "\nlike the cold, so"
	.string "\ptry using ice-type"
	.string "\nmoves too!$"
