@ FallarborTown_Ex5_10: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 5.10) por dev_scripts/copia_planta_ex.py.

FallarborTown_Ex5_10_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 5.10), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
FallarborTown_Ex5_10_EventScript_ExNpc0::
	msgbox FallarborTown_Ex5_10_Text_ExNpc0, MSGBOX_NPC
	end

FallarborTown_Ex5_10_Text_ExNpc0:
	.string "Our kids spend all their time at the GYM.\p"
	.string "I’m not worried though LUCY takes good\n"
	.string "care of them!$"

FallarborTown_Ex5_10_EventScript_ExNpc1::
	msgbox FallarborTown_Ex5_10_Text_ExNpc1, MSGBOX_NPC
	end

FallarborTown_Ex5_10_Text_ExNpc1:
	.string "GYM LEADER LUCY has really broken a lot\n"
	.string "of the young people in town out of\l"
	.string "their shells!$"

