@ CaitlinsHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_CaitlinsHouse_MapScripts::
	.byte 0

Unova_CaitlinsHouse_EventScript_Npc0::
	msgbox Unova_CaitlinsHouse_Text_CaitlinsHouseCaitlinBattleIntroText, MSGBOX_NPC
	end

Unova_CaitlinsHouse_EventScript_Npc1::
	msgbox Unova_CaitlinsHouse_Text_CaitlinsHouseCynthiaBattleIntroText, MSGBOX_NPC
	end


Unova_CaitlinsHouse_Text_CaitlinsHouseCaitlinBattleIntroText::
	.string "Hmf… It's you"
	.string "\nagain. Still, you"
	.string "\ppossess that"
	.string "\ncombination of"
	.string "\pkindness and"
	.string "\nstrength. You seem"
	.string "\pstronger than"
	.string "\nbefore… Do be sure"
	.string "\pnot to bore me"
	.string "\nwith a snooze-"
	.string "\linducing battle."
	.string "\pIs that clear?$"

Unova_CaitlinsHouse_Text_CaitlinsHouseCynthiaBattleIntroText::
	.string "How terrific to"
	.string "\nsee you again!"
	.string "\pI've got to tell"
	.string "\nyou… My POKéMON"
	.string "\pare excited to"
	.string "\nbattle yours."
	.string "\pWould you care to"
	.string "\nbe my opponent?$"
