@ NimbasaBallMart do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_NimbasaBallMart_MapScripts::
	.byte 0

Unova_NimbasaBallMart_EventScript_Npc1::
	msgbox Unova_NimbasaBallMart_Text_NimbasaBallMartRangerMText, MSGBOX_NPC
	end

Unova_NimbasaBallMart_EventScript_Npc2::
	msgbox Unova_NimbasaBallMart_Text_NimbasaBallMartLassText, MSGBOX_NPC
	end


Unova_NimbasaBallMart_Text_NimbasaBallMartRangerMText::
	.string "Different kinds of"
	.string "\nPOKéBALLS are good"
	.string "\pfor different"
	.string "\nsituations. Use"
	.string "\pthe best BALL for"
	.string "\nthe job!$"

Unova_NimbasaBallMart_Text_NimbasaBallMartLassText::
	.string "NET BALLS are good"
	.string "\nfor catching bug"
	.string "\land water type"
	.string "\lPOKéMON.$"
