@ PinwheelForest do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_PinwheelForest_MapScripts::
	.byte 0

Unova_PinwheelForest_EventScript_Npc6::
	msgbox Unova_PinwheelForest_Text_PkmnRangerMPinwheel1SeenText, MSGBOX_NPC
	end

Unova_PinwheelForest_EventScript_Npc7::
	msgbox Unova_PinwheelForest_Text_PkmnRangerMPinwheel2SeenText, MSGBOX_NPC
	end

Unova_PinwheelForest_EventScript_Npc8::
	msgbox Unova_PinwheelForest_Text_PkmnRangerFPinwheel1SeenText, MSGBOX_NPC
	end

Unova_PinwheelForest_EventScript_Npc9::
	msgbox Unova_PinwheelForest_Text_PkmnRangerFPinwheel2SeenText, MSGBOX_NPC
	end

Unova_PinwheelForest_EventScript_Npc10::
	msgbox Unova_PinwheelForest_Text_YoungsterPinwheelSeenText, MSGBOX_NPC
	end

Unova_PinwheelForest_EventScript_Npc11::
	msgbox Unova_PinwheelForest_Text_PsychicMPinwheelSeenText, MSGBOX_NPC
	end

Unova_PinwheelForest_EventScript_Npc12::
	msgbox Unova_PinwheelForest_Text_HexManiacPinwheelSeenText, MSGBOX_NPC
	end

Unova_PinwheelForest_EventScript_Npc13::
	msgbox Unova_PinwheelForest_Text_LassPinwheelSeenText, MSGBOX_NPC
	end

Unova_PinwheelForest_EventScript_Npc14::
	msgbox Unova_PinwheelForest_Text_PinwheelOfficerText, MSGBOX_NPC
	end

Unova_PinwheelForest_EventScript_Npc15::
	msgbox Unova_PinwheelForest_Text_PinwheelOfficerText, MSGBOX_NPC
	end


Unova_PinwheelForest_Text_PkmnRangerMPinwheel1SeenText::
	.string "Onward, my bug"
	.string "\nPOKéMON swarm!$"

Unova_PinwheelForest_Text_PkmnRangerMPinwheel2SeenText::
	.string "Hey, hey, hey! It's"
	.string "\nall because of"
	.string "\phavin' love for"
	.string "\nPOKéMON, right?"
	.string "\pYeah, you know"
	.string "\nwhat I mean!$"

Unova_PinwheelForest_Text_PkmnRangerFPinwheel1SeenText::
	.string "I hold no grudge,"
	.string "\nwhether I win or"
	.string "\plose. The point of"
	.string "\nbattle is to train"
	.string "\pmy POKéMON, after"
	.string "\nall.$"

Unova_PinwheelForest_Text_PkmnRangerFPinwheel2SeenText::
	.string "Get great powers"
	.string "\ndrawn from nature"
	.string "\pwithout opposing"
	.string "\nit. That is the"
	.string "\pstrength of POKé-"
	.string "\nMON RANGERs!$"

Unova_PinwheelForest_Text_YoungsterPinwheelSeenText::
	.string "The forest is full"
	.string "\nof little hollows"
	.string "\pand hillocks, and"
	.string "\nwalking in it is"
	.string "\lso fun!$"

Unova_PinwheelForest_Text_PsychicMPinwheelSeenText::
	.string "This is a power"
	.string "\nspot! It awakens"
	.string "\pyour dormant"
	.string "\npower!$"

Unova_PinwheelForest_Text_HexManiacPinwheelSeenText::
	.string "You… Who are you?"
	.string "\pThere is another"
	.string "\nperson here aside"
	.string "\lfrom me?$"

Unova_PinwheelForest_Text_LassPinwheelSeenText::
	.string "Oh! And I just"
	.string "\nheard a POKéMON,"
	.string "\ltoo! Oh, boo…$"

Unova_PinwheelForest_Text_PinwheelOfficerText::
	.string "There's been a"
	.string "\nrobbery in NACRENE"
	.string "\lCITY."
	.string "\pWe're not letting"
	.string "\nanyone through"
	.string "\lright now.$"
