EternaCityCondominiums1F_MapScripts::
	.byte 0

EternaCityCondominiums1F_EventScript_Npc1::
	msgbox EternaCityCondominiums1F_Text_Npc1, MSGBOX_NPC
	end

EternaCityCondominiums1F_Text_Npc1:
	.string "Excuse me, but do you got that\nPokémon named BUIZEL?\pWanna trade it for my CHATOT?$"

EternaCityCondominiums1F_EventScript_Npc2::
	msgbox EternaCityCondominiums1F_Text_Npc2, MSGBOX_NPC
	end

EternaCityCondominiums1F_Text_Npc2:
	.string "Hello, hello!\nI am the official Name Rater!\pWant me to rate the nicknames of\nyour Pokémon?$"
