@ PetalburgCity_House5: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 8.9) por dev_scripts/copia_planta_ex.py.

PetalburgCity_House5_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 8.9), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
PetalburgCity_House5_EventScript_ExNpc0::
	msgbox PetalburgCity_House5_Text_ExNpc0, MSGBOX_NPC
	end

PetalburgCity_House5_Text_ExNpc0:
	.string "Grrr...\p"
	.string "Those COOL TRAINERS in the PETALBURG\n"
	.string "GYM are so strong.\n"
	.string "I can’t keep up!$"

