OreburghCity_Flat2_F2_MapScripts::
	.byte 0

OreburghCity_Flat2_F2_EventScript_Breeder::
	msgbox OreburghCity_Flat2_F2_Text_Breeder, MSGBOX_NPC
	end

OreburghCity_Flat2_F2_Text_Breeder:
	.string "There are so many kinds of POKéMON\n"
	.string "out there. I want to see them all!$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

OreburghCity_Flat2_F2_EventScript_Npc1::
	msgbox OreburghCity_Flat2_F2_Text_Npc1, MSGBOX_NPC
	end

OreburghCity_Flat2_F2_Text_Npc1:
	.string "All Pokémon have a special power\ncalled an ability.$"

OreburghCity_Flat2_F2_EventScript_Npc2::
	msgbox OreburghCity_Flat2_F2_Text_Npc2, MSGBOX_NPC
	end

OreburghCity_Flat2_F2_Text_Npc2:
	.string "My favorite Pokémon ability is my\nPACHIRISU's Pickup.\pMy darling picks up a lot of dropped\nitems without me noticing!$"

OreburghCity_Flat2_F2_EventScript_Npc3::
	msgbox OreburghCity_Flat2_F2_Text_Npc3, MSGBOX_NPC
	end

OreburghCity_Flat2_F2_Text_Npc3:
	.string "The view is good from the second floor,\nbut it's a pain going outside.\pIf you don't mind, how about showing me\na Pokémon called GEODUDE?\pOh! That Pokémon!\nThat's a GEODUDE!\pWow, that's cool...\nIt's so cute...\pThat does it!\nI'll go out and catch Pokémon, too!\pThank you, my friend!\nThis is a token of my thanks!$"
