HearthomeCityDpGymElevatorRoom2_MapScripts::
	.byte 0

HearthomeCityDpGymElevatorRoom2_EventScript_Placa1::
	msgbox HearthomeCityDpGymElevatorRoom2_Text_Placa1, MSGBOX_SIGN
	end

HearthomeCityDpGymElevatorRoom2_Text_Placa1:
	.string "Question: The first room's answer?\nAnswer: ←2 ↑16 →15$"

HearthomeCityDpGymElevatorRoom2_EventScript_Placa2::
	msgbox HearthomeCityDpGymElevatorRoom2_Text_Placa2, MSGBOX_SIGN
	end

HearthomeCityDpGymElevatorRoom2_Text_Placa2:
	.string "Correct!\nCongratulations!$"
