OldChateauBackMiddleWestRoom_MapScripts::
	.byte 0

OldChateauBackMiddleWestRoom_EventScript_Placa1::
	msgbox OldChateauBackMiddleWestRoom_Text_Placa1, MSGBOX_SIGN
	end

OldChateauBackMiddleWestRoom_Text_Placa1:
	.string "Inside the TV...\nThere appears to be a Pokémon?...\pThe Pokémon appears as if it will come\nout. Want to thump the TV?$"

OldChateauBackMiddleWestRoom_EventScript_Placa2::
	msgbox OldChateauBackMiddleWestRoom_Text_Placa2, MSGBOX_SIGN
	end

OldChateauBackMiddleWestRoom_Text_Placa2:
	.string "Inside the TV...\nThere appears to be a Pokémon?...\pThe Pokémon appears as if it will come\nout. Want to thump the TV?$"
