@ MauvilleCity_Ex10_8: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 10.8) por dev_scripts/copia_planta_ex.py.

MauvilleCity_Ex10_8_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 10.8), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
MauvilleCity_Ex10_8_EventScript_ExNpc0::
	msgbox MauvilleCity_Ex10_8_Text_ExNpc0, MSGBOX_NPC
	end

MauvilleCity_Ex10_8_Text_ExNpc0:
	.string "I’m preparing for a journey where I’ll\n"
	.string "meet all kinds of POKéMON.\p"
	.string "I just need to do a few more years of\n"
	.string "research to be fully prepared!$"

MauvilleCity_Ex10_8_EventScript_ExNpc1::
	msgbox MauvilleCity_Ex10_8_Text_ExNpc1, MSGBOX_NPC
	end

MauvilleCity_Ex10_8_Text_ExNpc1:
	.string "My son spends all his time studying\n"
	.string "POKéMON.\p"
	.string "I don’t mind it, but I think he should go\n"
	.string "out and catch some POKéMON for real.$"

