@ CasteliaPlazaGameCorner do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_CasteliaPlazaGameCorner_MapScripts::
	.byte 0

Unova_CasteliaPlazaGameCorner_EventScript_Placa24::
	msgbox Unova_CasteliaPlazaGameCorner_Text_CasteliaPlazaGameCornerSignText, MSGBOX_SIGN
	end

Unova_CasteliaPlazaGameCorner_EventScript_Npc1::
	msgbox Unova_CasteliaPlazaGameCorner_Text_CasteliaPlazaGameCornerReceptionistText, MSGBOX_NPC
	end

Unova_CasteliaPlazaGameCorner_EventScript_Npc2::
	msgbox Unova_CasteliaPlazaGameCorner_Text_CasteliaPlazaGameCornerTeacherText, MSGBOX_NPC
	end

Unova_CasteliaPlazaGameCorner_EventScript_Npc3::
	msgbox Unova_CasteliaPlazaGameCorner_Text_CasteliaPlazaGameCornerPokefanMText, MSGBOX_NPC
	end

Unova_CasteliaPlazaGameCorner_EventScript_Npc4::
	msgbox Unova_CasteliaPlazaGameCorner_Text_CasteliaPlazaGameCornerSuperNerdText, MSGBOX_NPC
	end

Unova_CasteliaPlazaGameCorner_EventScript_Npc5::
	msgbox Unova_CasteliaPlazaGameCorner_Text_CasteliaPlazaGameCornerFisherText1, MSGBOX_NPC
	end


Unova_CasteliaPlazaGameCorner_Text_CasteliaPlazaGameCornerSignText::
	.string "CASTELIA PLAZA"
	.string "\nGAME CORNER."
	.string "\pEarn coins to win"
	.string "\nfabulous prizes!$"

Unova_CasteliaPlazaGameCorner_Text_CasteliaPlazaGameCornerReceptionistText::
	.string "Welcome!"
	.string "\pYou may exchange"
	.string "\nyour coins for"
	.string "\pfabulous prizes"
	.string "\nupstairs.$"

Unova_CasteliaPlazaGameCorner_Text_CasteliaPlazaGameCornerTeacherText::
	.string "It's this machine"
	.string "\nI want."
	.string "\pIt cleaned me out"
	.string "\nyesterday, so it"
	.string "\pshould pay out"
	.string "\ntoday.$"

Unova_CasteliaPlazaGameCorner_Text_CasteliaPlazaGameCornerPokefanMText::
	.string "Hmmm… The odds are"
	.string "\nsurely better for"
	.string "\pPIKACHU's line,"
	.string "\nbut… What to do?$"

Unova_CasteliaPlazaGameCorner_Text_CasteliaPlazaGameCornerSuperNerdText::
	.string "I think this slot"
	.string "\nmachine will pay"
	.string "\lout…"
	.string "\pThe odds vary"
	.string "\namong machines.$"

Unova_CasteliaPlazaGameCorner_Text_CasteliaPlazaGameCornerFisherText1::
	.string "Gahahaha!"
	.string "\pThe coins just"
	.string "\nkeep popping out!"
	.string "\pHm? What, kid? You"
	.string "\nwant to play?"
	.string "\pI'll share my luck"
	.string "\nwith you!$"
