@ FloccesyRanchBarn do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_FloccesyRanchBarn_MapScripts::
	.byte 0

Unova_FloccesyRanchBarn_EventScript_Npc0::
	msgbox Unova_FloccesyRanchBarn_Text_FloccesyRanchBarnTwinMoomooIsSickText, MSGBOX_NPC
	end

Unova_FloccesyRanchBarn_EventScript_Npc1::
	msgbox Unova_FloccesyRanchBarn_Text_FloccesyRanchBarnTwinMoomooIsSickText, MSGBOX_NPC
	end

Unova_FloccesyRanchBarn_EventScript_Npc2::
	msgbox Unova_FloccesyRanchBarn_Text_MoomooWeakMooText, MSGBOX_NPC
	end


Unova_FloccesyRanchBarn_Text_FloccesyRanchBarnTwinMoomooIsSickText::
	.string "WOOLIE is sick…"
	.string "\pShe needs lots of"
	.string "\nORAN BERRIES.$"

Unova_FloccesyRanchBarn_Text_MoomooWeakMooText::
	.string "WOOLIE: …Baa…$"
