@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup199.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_199
	voice_directsound 60, 0, DirectSoundWaveData_dp_clavi_c1_16, 255, 249, 0, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_clavi_c2_16, 255, 249, 0, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_clavi_c3_16, 255, 249, 0, 16
