@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup197.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_197
	voice_directsound 60, 0, DirectSoundWaveData_dp_el_pia_c3_22, 255, 243, 0, 32
	voice_directsound 60, 0, DirectSoundWaveData_dp_el_pia_c4_22, 255, 243, 0, 32
