@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup224.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_224
	voice_directsound 60, 0, DirectSoundWaveData_dp_dis_gt_c1_16, 255, 247, 255, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_dis_gt_c2_16, 255, 247, 255, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_dis_gt_c3_16, 255, 247, 255, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_dis_gt_c4_16, 255, 247, 255, 176
