@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup260.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_260
	voice_directsound 60, 0, DirectSoundWaveData_hg_133timpg3, 255, 251, 25, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_132timpc4, 255, 251, 25, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_134timpg4, 255, 251, 25, 192
