@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup222.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_222
	voice_directsound 60, 0, DirectSoundWaveData_dp_tp_cs3_16, 255, 243, 191, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_tp_cs4_16, 255, 243, 191, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_tp_b4_16, 255, 235, 191, 208
