@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup253.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_253
	voice_directsound 60, 0, DirectSoundWaveData_hg_041ampega2, 255, 234, 159, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_042ampega3, 255, 234, 159, 192
