@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup270.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_270
	voice_directsound 60, 0, DirectSoundWaveData_hg_125squarc4, 255, 242, 191, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_126squarc5, 255, 242, 191, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_127squarc6, 255, 234, 191, 171
