@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup226.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_226
	voice_directsound 60, 0, DirectSoundWaveData_dp_flute_c4_16, 255, 247, 159, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_flute_c5_16, 255, 247, 127, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_flute_c6_16, 255, 247, 71, 196
