@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup240.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_240
	voice_directsound 60, 0, DirectSoundWaveData_hg_156xylo1c4, 255, 248, 25, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_155xylo1a4, 255, 248, 25, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_157xylo1f5, 255, 248, 57, 192
