@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup204.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_204
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano36, 255, 249, 0, 226
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano48, 255, 249, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano60, 255, 249, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano72, 255, 248, 0, 208
