@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup244.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_244
	voice_directsound 60, 0, DirectSoundWaveData_hg_038drawbc3, 255, 197, 227, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_039drawbc4, 255, 0, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_040drawbc5, 255, 0, 255, 205
