@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup241.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_241
	voice_directsound 60, 0, DirectSoundWaveData_hg_147tbellg4, 255, 248, 25, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_146tbellc5, 255, 248, 25, 205
