@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup250.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_250
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_e1_16, 255, 253, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_c2_16, 255, 253, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_e3_16, 255, 253, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_e4_16, 255, 253, 0, 171
