@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup263.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_263
	voice_directsound 60, 0, DirectSoundWaveData_hg_016fhsolof3, 255, 0, 252, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_015fhsolod4, 255, 0, 252, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_014fhsolob4, 255, 0, 252, 192
