@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup205.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_205
	voice_directsound 60, 0, DirectSoundWaveData_dp_org1_c2_16, 255, 0, 255, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_org1_c3_16, 255, 200, 227, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_org1_c4_16, 255, 0, 255, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_org1_c5_16, 255, 0, 255, 208
