@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup207.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_207
	voice_directsound 60, 0, DirectSoundWaveData_dp_accordion_c1_16, 255, 0, 255, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_accordion_c2_16, 255, 0, 255, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_accordion_c3_16, 100, 200, 217, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_accordion_c4_16, 81, 200, 191, 196
