@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup213.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_213
	voice_directsound 60, 0, DirectSoundWaveData_dp_violin_c1_16, 100, 243, 255, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_violin_c3_16, 100, 247, 255, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_violin_c4_16, 67, 247, 118, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_violin_c5_16, 45, 247, 78, 208
