@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup242.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_242
	voice_directsound 60, 0, DirectSoundWaveData_hg_049glocknc4, 255, 248, 2, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_050glocknc5, 255, 248, 2, 205
