@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup255.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_255
	voice_directsound 60, 0, DirectSoundWaveData_hg_120str1c4, 255, 242, 191, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_119str1a4, 255, 242, 191, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_122str1f5, 254, 242, 191, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_121str1c6, 254, 242, 191, 192
