@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup228.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_228
	voice_directsound 60, 0, DirectSoundWaveData_dp_banjo48, 255, 243, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_banjo60, 255, 243, 0, 208
