@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup243.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_243
	voice_directsound 60, 0, DirectSoundWaveData_hg_071musboxc4, 255, 246, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_072musboxc5, 255, 246, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_073musboxc6, 255, 246, 0, 205
