@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup216.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_216
	voice_directsound 60, 0, DirectSoundWaveData_dp_timpany_e_16, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_dp_timpany_as_16, 255, 248, 0, 205
