@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup234.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_234
	voice_directsound 60, 0, DirectSoundWaveData_hg_005pnoffc4, 255, 249, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_006pnoffc5, 255, 249, 0, 171
