@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup225.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_225
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_g1_16, 255, 0, 255, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_gs2_16, 255, 0, 255, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_d3_16, 255, 0, 255, 176
