@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup247.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_247
	voice_directsound 60, 0, DirectSoundWaveData_hg_077nylong2, 255, 251, 6, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_078nylong3, 255, 251, 6, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_076nylone4, 255, 251, 6, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_075nylonc5, 255, 251, 6, 205
