@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup233.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_233
	voice_directsound 60, 0, DirectSoundWaveData_hg_051pnoc2, 255, 249, 0, 224
	voice_directsound 60, 0, DirectSoundWaveData_hg_052pnoc3, 255, 249, 0, 224
	voice_directsound 60, 0, DirectSoundWaveData_hg_053pnoc4, 255, 249, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_054pnoc5, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_055pnoc6, 255, 247, 0, 205
