@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup251.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_251
	voice_directsound 60, 0, DirectSoundWaveData_hg_029cleang2, 255, 246, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_030cleang3, 255, 246, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_028cleane4, 255, 246, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_hg_027cleanc5, 255, 246, 0, 171
