@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup217.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_217
	voice_directsound 60, 0, DirectSoundWaveData_dp_strings_c1_16, 255, 243, 227, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_strings_c2_16, 255, 240, 191, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_strings_c3_16, 135, 235, 159, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_strings_c4_16, 135, 225, 127, 208
