@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup264.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_264
	voice_directsound 60, 0, DirectSoundWaveData_hg_048fhnsf3, 255, 216, 219, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_047fhnsd4, 255, 216, 219, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_046fhnsb4, 255, 216, 255, 205
