@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup223.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_223
	voice_directsound 60, 0, DirectSoundWaveData_dp_f_horn_c2_16, 62, 219, 219, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_f_horn_c4_16, 255, 219, 255, 208
