@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup206.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_206
	voice_directsound 60, 0, DirectSoundWaveData_dp_org4_c3_16, 255, 0, 255, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_org4_c4_16, 255, 0, 255, 208
