@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup262.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_262
	voice_directsound 60, 0, DirectSoundWaveData_hg_142tbng2, 255, 242, 159, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_141tbne3, 255, 242, 159, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_140tbnc4, 255, 242, 159, 205
