@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup237.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_237
	voice_directsound 60, 0, DirectSoundWaveData_hg_043rhodc4, 255, 250, 0, 32
	voice_directsound 60, 0, DirectSoundWaveData_hg_044rhodc5, 255, 250, 0, 32
