@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup259.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_259
	voice_directsound 60, 0, DirectSoundWaveData_hg_058harpc3, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_059harpc4, 255, 246, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_060harpc5, 255, 242, 0, 205
