@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup227.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_227
	voice_directsound 60, 0, DirectSoundWaveData_pl_musicbox62, 255, 250, 2, 236
	voice_directsound 60, 0, DirectSoundWaveData_pl_musicbox79, 255, 248, 2, 224
