@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup220.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_220
	voice_directsound 60, 0, DirectSoundWaveData_dp_trombone_c2_16, 255, 243, 159, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_trombone_c3_16, 255, 243, 159, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_trombone_c4_16, 255, 243, 159, 208
