@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup201.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_201
	voice_directsound 60, 0, DirectSoundWaveData_dp_marin_c3_16, 255, 247, 0, 216
	voice_directsound 60, 0, DirectSoundWaveData_dp_marin_c4_16, 255, 247, 0, 216
	voice_directsound 60, 0, DirectSoundWaveData_dp_marin_c5_16, 255, 247, 0, 216
