@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup221.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_221
	voice_directsound 60, 0, DirectSoundWaveData_dp_tuba_c1_22, 255, 0, 252, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_tuba_c2_22, 255, 0, 252, 196
