@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup214.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_214
	voice_directsound 60, 0, DirectSoundWaveData_dp_pic_g4_16, 255, 235, 159, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_pic_g5_16, 255, 228, 159, 188
