@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup273.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_273
	voice_directsound 60, 0, DirectSoundWaveData_hg_pno4c2, 255, 249, 0, 224
	voice_directsound 60, 0, DirectSoundWaveData_hg_pno4a2, 255, 249, 0, 224
	voice_directsound 60, 0, DirectSoundWaveData_hg_pno4f3, 255, 249, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_pno4d4, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_pno4b4, 255, 247, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_pno4g5, 255, 247, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_pno4e6, 255, 247, 0, 205
