@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup239.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_239
	voice_directsound 60, 0, DirectSoundWaveData_hg_068marimc4, 255, 246, 0, 214
	voice_directsound 60, 0, DirectSoundWaveData_hg_069marimc5, 255, 246, 0, 214
	voice_directsound 60, 0, DirectSoundWaveData_hg_070marimc6, 255, 246, 0, 214
