@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup269.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_269
	voice_directsound 60, 0, DirectSoundWaveData_hg_086orchitc4, 255, 248, 25, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_087orchitc5, 255, 248, 25, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_089orchitg5, 255, 248, 25, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_088orchitc6, 255, 248, 25, 205
