@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup200.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_200
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c1_16, 255, 247, 0, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c2_16, 255, 247, 0, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c3_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c4_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c5_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c6_16, 255, 247, 0, 208
