@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup208.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_208
	voice_directsound 60, 0, DirectSoundWaveData_dp_acgt_e1_16, 255, 253, 127, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_acgt_e2_16, 255, 253, 127, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_acgt_e3_16, 255, 253, 127, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_acgt_e4_16, 255, 253, 127, 208
