@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup202.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_202
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c2_16, 255, 249, 25, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c3_16, 255, 249, 25, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c4_16, 255, 249, 57, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c5_16, 255, 249, 57, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c6_16, 255, 247, 25, 196
