@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup256.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_256
	voice_directsound 60, 0, DirectSoundWaveData_hg_152violne4, 254, 242, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_151violnc5, 254, 246, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_150violna5, 254, 246, 255, 205
