@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup261.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_261
	voice_directsound 60, 0, DirectSoundWaveData_hg_144tptc4, 255, 242, 191, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_143tpta4, 255, 242, 191, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_145tptg5, 255, 234, 191, 205
