@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup246.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_246
	voice_directsound 60, 0, DirectSoundWaveData_hg_002accorc3, 255, 0, 217, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_003accorc4, 255, 0, 217, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_004accorc5, 254, 197, 217, 192
