@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup265.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_265
	voice_directsound 60, 0, DirectSoundWaveData_hg_081oboee4, 255, 242, 191, 214
	voice_directsound 60, 0, DirectSoundWaveData_hg_080oboec5, 255, 242, 191, 214
	voice_directsound 60, 0, DirectSoundWaveData_hg_079oboea5, 255, 242, 191, 214
