@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup245.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_245
	voice_directsound 60, 0, DirectSoundWaveData_hg_091jazorgc3, 255, 0, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_092jazorgc4, 255, 0, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_093jazorgc5, 255, 0, 255, 205
