@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup248.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_248
	voice_directsound 60, 0, DirectSoundWaveData_hg_117marting2, 255, 251, 14, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_118marting3, 255, 251, 14, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_116martine4, 255, 251, 14, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_115martinc5, 255, 251, 14, 192
