@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup257.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_257
	voice_directsound 60, 0, DirectSoundWaveData_hg_021cellog2, 254, 242, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_020celloe3, 254, 246, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_019celloc4, 254, 246, 255, 205
