@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup252.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_252
	voice_directsound 60, 0, DirectSoundWaveData_hg_000uprigc2, 255, 251, 0, 192
	voice_directsound 60, 0, DirectSoundWaveData_hg_001uprigc3, 255, 251, 0, 192
