@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup211.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_211
	voice_directsound 60, 0, DirectSoundWaveData_dp_power_gt_e1_16, 255, 251, 127, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_power_gt_b1_16, 255, 251, 127, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_power_gt_e2_16, 255, 251, 127, 16
