@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup268.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_268
	voice_directsound 60, 0, DirectSoundWaveData_hg_012bsne2, 255, 242, 127, 214
	voice_directsound 60, 0, DirectSoundWaveData_hg_011bsnc3, 255, 242, 127, 214
	voice_directsound 60, 0, DirectSoundWaveData_hg_010bsna3, 255, 242, 127, 214
