@ Importado de fontes-mapas/hns/sound/voicegroups/voicegroup235.inc
@ por dev_scripts/importa_musica_ds.py. Renomeado de numerado para nomeado,
@ que é a convenção desta base (`voice_group nome` gera o
@ símbolo `voicegroup_nome`, que o mid2agb recebe como -G_nome).
	.align 2
	voice_group ds_235
	voice_directsound 60, 0, DirectSoundWaveData_hg_082octpnoc2, 255, 249, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_083octpnoc3, 255, 249, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_084octpnoc4, 255, 249, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_085octpnoc5, 255, 249, 0, 205
