@ CasteliaPlazaRestaurant do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_CasteliaPlazaRestaurant_MapScripts::
	.byte 0

Unova_CasteliaPlazaRestaurant_EventScript_Npc0::
	msgbox Unova_CasteliaPlazaRestaurant_Text_CasteliaPlazaRestaurantReceptionistText, MSGBOX_NPC
	end

Unova_CasteliaPlazaRestaurant_EventScript_Npc1::
	msgbox Unova_CasteliaPlazaRestaurant_Text_CasteliaPlazaRestaurantPokefanMText, MSGBOX_NPC
	end

Unova_CasteliaPlazaRestaurant_EventScript_Npc2::
	msgbox Unova_CasteliaPlazaRestaurant_Text_CasteliaPlazaRestaurantBeautyIntroText, MSGBOX_NPC
	end

Unova_CasteliaPlazaRestaurant_EventScript_Npc3::
	msgbox Unova_CasteliaPlazaRestaurant_Text_CasteliaPlazaRestaurantAmanitaIntroText, MSGBOX_NPC
	end

Unova_CasteliaPlazaRestaurant_EventScript_Npc4::
	msgbox Unova_CasteliaPlazaRestaurant_Text_CasteliaPlazaRestaurantBlockerText, MSGBOX_NPC
	end


Unova_CasteliaPlazaRestaurant_Text_CasteliaPlazaRestaurantReceptionistText::
	.string "Welcome to the"
	.string "\nCASTELIA PLAZA"
	.string "\lrestaurant."
	.string "\pWe're sorry, you"
	.string "\nwill need to make"
	.string "\pa reservation in"
	.string "\nadvance if you'd"
	.string "\llike to be served.$"

Unova_CasteliaPlazaRestaurant_Text_CasteliaPlazaRestaurantPokefanMText::
	.string "I went bust at the"
	.string "\nslots. I'm flat"
	.string "\lbroke!"
	.string "\pI got frustrated"
	.string "\nand threw out my"
	.string "\pCOIN CASE at the"
	.string "\ndocks.$"

Unova_CasteliaPlazaRestaurant_Text_CasteliaPlazaRestaurantBeautyIntroText::
	.string "Oh! Your POKéMON"
	.string "\nare so darling!"
	.string "\pHere, you should"
	.string "\nhave this. It's"
	.string "\pjust perfect for"
	.string "\nsuch cute POKéMON!$"

Unova_CasteliaPlazaRestaurant_Text_CasteliaPlazaRestaurantAmanitaIntroText::
	.string "Oh, hi! Are you a"
	.string "\nPOKéMON trainer?"
	.string "\pMy name's AMANITA."
	.string "\nI set up the POKé-"
	.string "\pMON storage system"
	.string "\nhere in UNOVA!"
	.string "\pI live in STRIATON"
	.string "\nCITY, but I travel"
	.string "\pto CASTELIA often"
	.string "\nfor work."
	.string "\pListen! While I"
	.string "\nwas working on the"
	.string "\pPC storage network"
	.string "\nhere, a POKéMON"
	.string "\psuddenly came out"
	.string "\nfrom the PC!"
	.string "\pI've been keeping"
	.string "\nit, but I don't"
	.string "\phave time to care"
	.string "\nfor it properly."
	.string "\pI think it would"
	.string "\nbe much happier"
	.string "\lwith a trainer!"
	.string "\pWould you take it"
	.string "\nwith you?$"

Unova_CasteliaPlazaRestaurant_Text_CasteliaPlazaRestaurantBlockerText::
	.string "Sorry, the floors"
	.string "\nbeyond here are"
	.string "\pfor residents"
	.string "\nonly.$"
