JubilifeCity_JubilifeTV_F3_MapScripts::
	.byte 0

JubilifeCity_JubilifeTV_F3_EventScript_Beauty1::
	msgbox JubilifeCity_JubilifeTV_F3_Text_Beauty1, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_EventScript_GymGuide1::
	msgbox JubilifeCity_JubilifeTV_F3_Text_GymGuide1, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_EventScript_Beauty2::
	msgbox JubilifeCity_JubilifeTV_F3_Text_Beauty2, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_EventScript_GymGuide2::
	msgbox JubilifeCity_JubilifeTV_F3_Text_GymGuide2, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_Text_Beauty1:
	.string "The room closest to the stairs is\n"
	.string "the Group Ranking Room.$"

JubilifeCity_JubilifeTV_F3_Text_GymGuide1:
	.string "I'm scouting for the next big battle\n"
	.string "special. Got any good stories?$"

JubilifeCity_JubilifeTV_F3_Text_Beauty2:
	.string "The room on the far side is the\n"
	.string "Global Ranking Room.$"

JubilifeCity_JubilifeTV_F3_Text_GymGuide2:
	.string "I'm a TV producer here. Keep your\n"
	.string "channel tuned to JUBILIFE TV!$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

JubilifeCity_JubilifeTV_F3_EventScript_Npc1::
	msgbox JubilifeCity_JubilifeTV_F3_Text_Npc1, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_Text_Npc1:
	.string "The room closest to the stairs is the\nGroup Ranking Room.$"

JubilifeCity_JubilifeTV_F3_EventScript_Npc2::
	msgbox JubilifeCity_JubilifeTV_F3_Text_Npc2, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_Text_Npc2:
	.string "I just realized something awesome!\nI should be trading Pokémon more!\pThe more trades I make, the better my\nodds of winning the Pokémon Lottery!\pWhy? Because the ID No. of a Pokémon\nis different from Trainer to Trainer!$"

JubilifeCity_JubilifeTV_F3_EventScript_Npc3::
	msgbox JubilifeCity_JubilifeTV_F3_Text_Npc3, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_Text_Npc3:
	.string "Records are fine things.\nThey tell you the history of stuff.\pYou can really sense the dramatic\nstories behind all those numbers!$"

JubilifeCity_JubilifeTV_F3_EventScript_Npc4::
	msgbox JubilifeCity_JubilifeTV_F3_Text_Npc4, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_Text_Npc4:
	.string "Hey, there!\nHow's it going?\pI'm a TV producer here.\nAre you watching TV?\pSo, let me ask you.\nWill you tell me your opinion on TV?$"
