JubilifeCity_JubilifeTV_F3_MapScripts::
	.byte 0

JubilifeCity_JubilifeTV_F3_EventScript_Beauty1::
	msgbox JubilifeCity_JubilifeTV_F3_Text_Beauty1, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_EventScript_GymGuide1::
	msgbox JubilifeCity_JubilifeTV_F3_Text_GymGuide1, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_EventScript_Beauty2::
	msgbox JubilifeCity_JubilifeTV_F3_Text_Beauty2, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_EventScript_GymGuide2::
	msgbox JubilifeCity_JubilifeTV_F3_Text_GymGuide2, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_Text_Beauty1:
	.string "The room closest to the stairs is\n"
	.string "the Group Ranking Room.$"

JubilifeCity_JubilifeTV_F3_Text_GymGuide1:
	.string "I'm scouting for the next big battle\n"
	.string "special. Got any good stories?$"

JubilifeCity_JubilifeTV_F3_Text_Beauty2:
	.string "The room on the far side is the\n"
	.string "Global Ranking Room.$"

JubilifeCity_JubilifeTV_F3_Text_GymGuide2:
	.string "I'm a TV producer here. Keep your\n"
	.string "channel tuned to JUBILIFE TV!$"
