@ LentimasTown do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_LentimasTown_MapScripts::
	.byte 0

Unova_LentimasTown_EventScript_Placa0::
	msgbox Unova_LentimasTown_Text_LentimasAirportSignText, MSGBOX_SIGN
	end

Unova_LentimasTown_EventScript_Placa1::
	msgbox Unova_LentimasTown_Text_LentimasTownSignText, MSGBOX_SIGN
	end

Unova_LentimasTown_EventScript_Npc2::
	msgbox Unova_LentimasTown_Text_LentimasTownGuardNoPassText, MSGBOX_NPC
	end

Unova_LentimasTown_EventScript_Npc3::
	msgbox Unova_LentimasTown_Text_LentimasTownGrannyText, MSGBOX_NPC
	end

Unova_LentimasTown_EventScript_Npc4::
	msgbox Unova_LentimasTown_Text_LentimasTownGrampsText, MSGBOX_NPC
	end

Unova_LentimasTown_EventScript_Npc5::
	msgbox Unova_LentimasTown_Text_LentimasTownRangerFText, MSGBOX_NPC
	end


Unova_LentimasTown_Text_LentimasAirportSignText::
	.string "LENTIMAS AIRPORT.$"

Unova_LentimasTown_Text_LentimasTownSignText::
	.string "LENTIMAS TOWN."
	.string "\pTown of jagged"
	.string "\nmountain paths.$"

Unova_LentimasTown_Text_LentimasTownGuardNoPassText::
	.string "This is the"
	.string "\nLENTIMAS TOWN"
	.string "\lairport. Only"
	.string "\pthose with a"
	.string "\nBOARDINGPASS may"
	.string "\lenter. Come back"
	.string "\pwhen you have a"
	.string "\nBOARDINGPASS.$"

Unova_LentimasTown_Text_LentimasTownGrannyText::
	.string "What brings one so"
	.string "\nyoung as you to"
	.string "\pour sleepy little"
	.string "\ntown?"
	.string "\pStrange things are"
	.string "\nknown to have"
	.string "\lhappened here…$"

Unova_LentimasTown_Text_LentimasTownGrampsText::
	.string "This town was"
	.string "\nfounded just a"
	.string "\phandful of years"
	.string "\nago. But the house"
	.string "\poutside of town"
	.string "\nhas been standing"
	.string "\lfor far longer…$"

Unova_LentimasTown_Text_LentimasTownRangerFText::
	.string "Shhh…"
	.string "\pI'm in training to"
	.string "\nbecome a HEX"
	.string "\lMANIAC."
	.string "\pBut first, I need"
	.string "\nto be able to at"
	.string "\pleast see the"
	.string "\nspirits…$"
