VeilstoneCitySoutheastHouse_MapScripts::
	.byte 0

VeilstoneCitySoutheastHouse_EventScript_Npc1::
	msgbox VeilstoneCitySoutheastHouse_Text_Npc1, MSGBOX_NPC
	end

VeilstoneCitySoutheastHouse_Text_Npc1:
	.string "You there.\nWatch this Coin.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

VeilstoneCitySoutheastHouse_EventScript_Npc2::
	msgbox VeilstoneCitySoutheastHouse_Text_Npc2, MSGBOX_NPC
	end

VeilstoneCitySoutheastHouse_Text_Npc2:
	.string "There are many magicians in the world.\nYou know, the performance artists?\pDon't you think that maybe, say,\nfive percent are actually psychics?$"
