Battleground_MapScripts::
	.byte 0

Battleground_EventScript_Npc1::
	msgbox Battleground_Text_Npc1, MSGBOX_NPC
	end

Battleground_Text_Npc1:
	.string "What should we talk about today?\n...Ah, I know.\pLet me tell you about the volcano named\nStark Mountain.\pThat volcano dates to when Sinnoh was\nmade by the melding of time and space.\pFiery lava spilled out and pooled, and\nthen it became a Pokémon.\pIt's said the Magma Stone was used\nto keep the Pokémon pinned down.\pIt kept the Pokémon from rampaging\nand the volcano from erupting.$"
