OreburghCity_House3_MapScripts::
	.byte 0

OreburghCity_House3_EventScript_SchoolKid::
	msgbox OreburghCity_House3_Text_SchoolKid, MSGBOX_NPC
	end

OreburghCity_House3_EventScript_Hiker::
	msgbox OreburghCity_House3_Text_Hiker, MSGBOX_NPC
	end

OreburghCity_House3_Text_SchoolKid:
	.string "I want to be as strong a TRAINER\n"
	.string "as the GYM LEADER someday.$"

OreburghCity_House3_Text_Hiker:
	.string "The OREBURGH MINE has some tricky\n"
	.string "paths. Watch your footing in there.$"
