@ Rt7North do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt7North_MapScripts::
	.byte 0

Unova_Rt7North_EventScript_Placa0::
	msgbox Unova_Rt7North_Text_R7NorthSignText, MSGBOX_SIGN
	end

Unova_Rt7North_EventScript_Npc4::
	msgbox Unova_Rt7North_Text_BackpackerMR7NorthSeenText, MSGBOX_NPC
	end

Unova_Rt7North_EventScript_Npc5::
	msgbox Unova_Rt7North_Text_BackpackerFR7NorthSeenText, MSGBOX_NPC
	end

Unova_Rt7North_EventScript_Npc6::
	msgbox Unova_Rt7North_Text_HarlequinR7NorthSeenText, MSGBOX_NPC
	end

Unova_Rt7North_EventScript_Npc7::
	msgbox Unova_Rt7North_Text_TwinsR7NorthSeenText, MSGBOX_NPC
	end

Unova_Rt7North_EventScript_Npc8::
	msgbox Unova_Rt7North_Text_TwinsR7NorthSeenText, MSGBOX_NPC
	end


Unova_Rt7North_Text_R7NorthSignText::
	.string "TWIST MOUNTAIN"
	.string "\nahead.$"

Unova_Rt7North_Text_BackpackerMR7NorthSeenText::
	.string "I travel the world"
	.string "\nbecause I'm look-"
	.string "\ling for danger!"
	.string "\pAre you dangerous?$"

Unova_Rt7North_Text_BackpackerFR7NorthSeenText::
	.string "Oh my! My POKéMON"
	.string "\nreally seem raring"
	.string "\lto go today!$"

Unova_Rt7North_Text_HarlequinR7NorthSeenText::
	.string "POKéMON battles"
	.string "\nare no joking"
	.string "\lmatter!$"

Unova_Rt7North_Text_TwinsR7NorthSeenText::
	.string "The teamwork of"
	.string "\ntwins… A true"
	.string "\pexample of"
	.string "\nperfection!$"
