FightAreaSouthHouse_MapScripts::
	.byte 0

FightAreaSouthHouse_EventScript_Npc1::
	msgbox FightAreaSouthHouse_Text_Npc1, MSGBOX_NPC
	end

FightAreaSouthHouse_Text_Npc1:
	.string "I am the Item Expert!\nI have mastery in the way of items!\pYour Pokémon...\nDo they hold items?\pThe better the item they hold, the \nstronger they become.\pThere are items that are worthy of my\nrecommendation. Care to know?$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

FightAreaSouthHouse_EventScript_Npc1::
	msgbox FightAreaSouthHouse_Text_Npc1, MSGBOX_NPC
	end

FightAreaSouthHouse_Text_Npc1:
	.string "The Battle Zone used to attract only\nthe hardiest of the Trainers.\pThey were considered eccentric for\ngathering at a place like this.\pIt's hard to believe how much it's\nchanged since then.\pPlaces like the Fight Area and the\nSurvival Area just seemed to spring\pup overnight.$"

FightAreaSouthHouse_EventScript_Npc2::
	msgbox FightAreaSouthHouse_Text_Npc2, MSGBOX_NPC
	end

FightAreaSouthHouse_Text_Npc2:
	.string "He was one of those early eccentrics\nwho were around during the early days\pof the Battle Zone. Well, I was too.$"
