@ WellspringCaveB1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_WellspringCaveB1F_MapScripts::
	.byte 0

Unova_WellspringCaveB1F_EventScript_Npc3::
	msgbox Unova_WellspringCaveB1F_Text_BlackbeltWellspringB1FSeenText, MSGBOX_NPC
	end

Unova_WellspringCaveB1F_EventScript_Npc4::
	msgbox Unova_WellspringCaveB1F_Text_BattleGirlWellspringB1FSeenText, MSGBOX_NPC
	end

Unova_WellspringCaveB1F_EventScript_Npc5::
	msgbox Unova_WellspringCaveB1F_Text_HikerWellspringB1FSeenText, MSGBOX_NPC
	end


Unova_WellspringCaveB1F_Text_BlackbeltWellspringB1FSeenText::
	.string "Here in the dark-"
	.string "\nness… I feel my"
	.string "\pway through thanks"
	.string "\nto my POKéMON!"
	.string "\pI'll show you the"
	.string "\npower of our bond!$"

Unova_WellspringCaveB1F_Text_BattleGirlWellspringB1FSeenText::
	.string "You gotta have"
	.string "\nstamina! Burn the"
	.string "\pflames of life,"
	.string "\nand never stop"
	.string "\lmoving forward!$"

Unova_WellspringCaveB1F_Text_HikerWellspringB1FSeenText::
	.string "A lake that"
	.string "\nspreads beneath"
	.string "\pthe earth… And the"
	.string "\nHIKER who waits"
	.string "\lbeside it!$"
