@ Rt20 do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt20_MapScripts::
	.byte 0

Unova_Rt20_EventScript_Npc4::
	msgbox Unova_Rt20_Text_SchoolKidM1R20SeenText, MSGBOX_NPC
	end

Unova_Rt20_EventScript_Npc5::
	msgbox Unova_Rt20_Text_SchoolKidM2R20SeenText, MSGBOX_NPC
	end

Unova_Rt20_EventScript_Npc6::
	msgbox Unova_Rt20_Text_SchoolKidM3R20SeenText, MSGBOX_NPC
	end

Unova_Rt20_EventScript_Npc7::
	msgbox Unova_Rt20_Text_TwinsR20SeenText, MSGBOX_NPC
	end

Unova_Rt20_EventScript_Npc8::
	msgbox Unova_Rt20_Text_TwinsR20SeenText, MSGBOX_NPC
	end

Unova_Rt20_EventScript_Npc9::
	msgbox Unova_Rt20_Text_SchoolKidF1R20SeenText, MSGBOX_NPC
	end

Unova_Rt20_EventScript_Npc10::
	msgbox Unova_Rt20_Text_SchoolKidF2R20SeenText, MSGBOX_NPC
	end

Unova_Rt20_EventScript_Npc11::
	msgbox Unova_Rt20_Text_SchoolKidF3R20SeenText, MSGBOX_NPC
	end

Unova_Rt20_EventScript_Npc12::
	msgbox Unova_Rt20_Text_NurseryAideR20SeenText, MSGBOX_NPC
	end


Unova_Rt20_Text_SchoolKidM1R20SeenText::
	.string "To me, the battle-"
	.string "\nfield is a place"
	.string "\lfor learning!$"

Unova_Rt20_Text_SchoolKidM2R20SeenText::
	.string "Hey, you! You're"
	.string "\ngonna lose and"
	.string "\lcry!$"

Unova_Rt20_Text_SchoolKidM3R20SeenText::
	.string "You look tough!"
	.string "\pAll right! My"
	.string "\nPOKéMON are burn-"
	.string "\ling for a fight"
	.string "\pagainst a tough"
	.string "\nopponent!$"

Unova_Rt20_Text_TwinsR20SeenText::
	.string "The two of us make"
	.string "\nan amazing"
	.string "\lcombination!"
	.string "\pLet's battle!$"

Unova_Rt20_Text_SchoolKidF1R20SeenText::
	.string "Is that a POKéDEX?"
	.string "\pI'd love it if you"
	.string "\nwould show me lots"
	.string "\pof different kinds"
	.string "\nof POKéMON!$"

Unova_Rt20_Text_SchoolKidF2R20SeenText::
	.string "Hi, hi! Trainer!"
	.string "\nPlease show me"
	.string "\pwhat kinds of"
	.string "\nPOKéMON you are"
	.string "\ltraining!$"

Unova_Rt20_Text_SchoolKidF3R20SeenText::
	.string "Ta-da! Here's my"
	.string "\ncute POKéMON!$"

Unova_Rt20_Text_NurseryAideR20SeenText::
	.string "I always give it"
	.string "\nmy best when I'm"
	.string "\paround kids and"
	.string "\nPOKéMON!$"
