@ MistraltonCity do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_MistraltonCity_MapScripts::
	.byte 0

Unova_MistraltonCity_EventScript_Placa0::
	msgbox Unova_MistraltonCity_Text_MistraltonCitySignText, MSGBOX_SIGN
	end

Unova_MistraltonCity_EventScript_Placa1::
	msgbox Unova_MistraltonCity_Text_MistraltonAirportSignText, MSGBOX_SIGN
	end

Unova_MistraltonCity_EventScript_Npc0::
	msgbox Unova_MistraltonCity_Text_MistraltonCityGymGuyText, MSGBOX_NPC
	end

Unova_MistraltonCity_EventScript_Npc4::
	msgbox Unova_MistraltonCity_Text_MistraltonCityOfficerText, MSGBOX_NPC
	end

Unova_MistraltonCity_EventScript_Npc5::
	msgbox Unova_MistraltonCity_Text_MistraltonCityYoungsterText, MSGBOX_NPC
	end

Unova_MistraltonCity_EventScript_Npc6::
	msgbox Unova_MistraltonCity_Text_MistraltonCityTeacherText, MSGBOX_NPC
	end

Unova_MistraltonCity_EventScript_Npc7::
	msgbox Unova_MistraltonCity_Text_MistraltonCityTwinText, MSGBOX_NPC
	end


Unova_MistraltonCity_Text_MistraltonCitySignText::
	.string "MISTRALTON CITY."
	.string "\pThe city where"
	.string "\nwinds gather the"
	.string "\lflowers.$"

Unova_MistraltonCity_Text_MistraltonAirportSignText::
	.string "MISTRALTON CITY"
	.string "\nAIRPORT.$"

Unova_MistraltonCity_Text_MistraltonCityGymGuyText::
	.string "Oh, are you here"
	.string "\nto challenge the"
	.string "\lGYM LEADER?"
	.string "\pSorry, she's not"
	.string "\nin right now."
	.string "\pI think she may"
	.string "\nhave gone off to"
	.string "\lCELESTIAL TOWER,"
	.string "\lup on ROUTE 7.$"

Unova_MistraltonCity_Text_MistraltonCityOfficerText::
	.string "MISTRALTON CITY"
	.string "\nhas the biggest"
	.string "\lairport in UNOVA.$"

Unova_MistraltonCity_Text_MistraltonCityYoungsterText::
	.string "I love airplanes!"
	.string "\nI want to be a"
	.string "\ppilot when I grow"
	.string "\nup, just like"
	.string "\lMiss SKYLA!$"

Unova_MistraltonCity_Text_MistraltonCityTeacherText::
	.string "We can grow crops"
	.string "\nin the greenhouses"
	.string "\lall year long!"
	.string "\pWe export them all"
	.string "\nover UNOVA.$"

Unova_MistraltonCity_Text_MistraltonCityTwinText::
	.string "I love playing in"
	.string "\nthe puddles!$"
