PokmonLeague_MapScripts::
	.byte 0

PokmonLeague_EventScript_Youngster::
	msgbox PokmonLeague_Text_Youngster, MSGBOX_NPC
	end

PokmonLeague_EventScript_Staff::
	msgbox PokmonLeague_Text_Staff, MSGBOX_NPC
	end

PokmonLeague_EventScript_Gentleman::
	msgbox PokmonLeague_Text_Gentleman, MSGBOX_NPC
	end

PokmonLeague_Text_Youngster:
	.string "The CHAMPION's up there...\p"
	.string "I don't know if I'm ready.$"

PokmonLeague_Text_Staff:
	.string "Challengers line up over there.\p"
	.string "Good luck on the ELITE FOUR.$"

PokmonLeague_Text_Gentleman:
	.string "Every step past this gate belongs\n"
	.string "to Trainers strong enough to take\n"
	.string "on SINNOH's best.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

PokmonLeague_EventScript_Placa1::
	msgbox PokmonLeague_Text_Placa1, MSGBOX_SIGN
	end

PokmonLeague_Text_Placa1:
	.string "Victory Road Ahead$"

PokmonLeague_EventScript_Placa2::
	msgbox PokmonLeague_Text_Placa2, MSGBOX_SIGN
	end

PokmonLeague_Text_Placa2:
	.string "Pokémon League Ahead$"

PokmonLeague_EventScript_Placa3::
	msgbox PokmonLeague_Text_Placa3, MSGBOX_SIGN
	end

PokmonLeague_Text_Placa3:
	.string "Pokémon League\nThe Pinnacle of Trainerdom!$"

PokmonLeague_EventScript_Placa4::
	msgbox PokmonLeague_Text_Placa4, MSGBOX_SIGN
	end

PokmonLeague_Text_Placa4:
	.string "Pokémon League\nThe Pinnacle of Trainerdom!$"

PokmonLeague_EventScript_Placa5::
	msgbox PokmonLeague_Text_Placa5, MSGBOX_SIGN
	end

PokmonLeague_Text_Placa5:
	.string "Pokémon League\nThe Pinnacle of Trainerdom!$"

PokmonLeague_EventScript_Placa6::
	msgbox PokmonLeague_Text_Placa6, MSGBOX_SIGN
	end

PokmonLeague_Text_Placa6:
	.string "Pokémon League\nThe Pinnacle of Trainerdom!$"

PokmonLeague_EventScript_Placa7::
	msgbox PokmonLeague_Text_Placa7, MSGBOX_SIGN
	end

PokmonLeague_Text_Placa7:
	.string "Pokémon League\nThe Pinnacle of Trainerdom!$"

PokmonLeague_EventScript_Placa8::
	msgbox PokmonLeague_Text_Placa8, MSGBOX_SIGN
	end

PokmonLeague_Text_Placa8:
	.string "Pokémon League\nThe Pinnacle of Trainerdom!$"

PokmonLeague_EventScript_Placa9::
	msgbox PokmonLeague_Text_Placa9, MSGBOX_SIGN
	end

PokmonLeague_Text_Placa9:
	.string "Pokémon League\nThe Pinnacle of Trainerdom!$"

PokmonLeague_EventScript_Placa10::
	msgbox PokmonLeague_Text_Placa10, MSGBOX_SIGN
	end

PokmonLeague_Text_Placa10:
	.string "Pokémon League\nThe Pinnacle of Trainerdom!$"
