@ VillageBridge do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VillageBridge_MapScripts::
	.byte 0

Unova_VillageBridge_EventScript_Lider6::
	trainerbattle_single TRAINER_UNOVA_MUSICIAN_VILLAGE_BRIDGE, Unova_VillageBridge_Text_MusicianVillageBridgeSeenText, Unova_VillageBridge_Text_MusicianVillageBridgeBeatenText
	end

Unova_VillageBridge_EventScript_Lider7::
	trainerbattle_single TRAINER_UNOVA_SMASHER_VILLAGE_BRIDGE_1, Unova_VillageBridge_Text_Smasher1VillageBridgeSeenText, Unova_VillageBridge_Text_Smasher1VillageBridgeBeatenText
	end

Unova_VillageBridge_EventScript_Lider8::
	trainerbattle_single TRAINER_UNOVA_SMASHER_VILLAGE_BRIDGE_2, Unova_VillageBridge_Text_Smasher2VillageBridgeSeenText, Unova_VillageBridge_Text_Smasher2VillageBridgeBeatenText
	end

Unova_VillageBridge_EventScript_Lider9::
	trainerbattle_single TRAINER_UNOVA_LINEBACKER_VILLAGE_BRIDGE, Unova_VillageBridge_Text_LinebackerVillageBridgeSeenText, Unova_VillageBridge_Text_LinebackerVillageBridgeBeatenText
	end

Unova_VillageBridge_EventScript_Lider10::
	trainerbattle_single TRAINER_UNOVA_HOOPSTER_VILLAGE_BRIDGE_1, Unova_VillageBridge_Text_Hoopster1VillageBridgeSeenText, Unova_VillageBridge_Text_Hoopster1VillageBridgeBeatenText
	end

Unova_VillageBridge_EventScript_Lider11::
	trainerbattle_single TRAINER_UNOVA_HOOPSTER_VILLAGE_BRIDGE_2, Unova_VillageBridge_Text_Hoopster2VillageBridgeSeenText, Unova_VillageBridge_Text_Hoopster2VillageBridgeBeatenText
	end


Unova_VillageBridge_Text_MusicianVillageBridgeSeenText::
	.string "Hum fiercely! My"
	.string "\nbattle song!"
	.string "\pBattle fiercely!"
	.string "\nMy POKéMON!$"

Unova_VillageBridge_Text_MusicianVillageBridgeBeatenText::
	.string "Hm… I guess"
	.string "\nstrumming instead"
	.string "\pof tapping would"
	.string "\nbe best…$"

Unova_VillageBridge_Text_Smasher1VillageBridgeSeenText::
	.string "My serve is 120"
	.string "\nmiles per hour!"
	.string "\pThat's the kind of"
	.string "\nkiller attack I'm"
	.string "\labout to show you!$"

Unova_VillageBridge_Text_Smasher1VillageBridgeBeatenText::
	.string "I wanted to cont-"
	.string "\ninue the rally a"
	.string "\llittle bit longer!$"

Unova_VillageBridge_Text_Smasher2VillageBridgeSeenText::
	.string "Watch my furious"
	.string "\ntennis footwork!"
	.string "\pyou get it now?"
	.string "\nWe're tough!$"

Unova_VillageBridge_Text_Smasher2VillageBridgeBeatenText::
	.string "But… I'm tough"
	.string "\nenough to play all"
	.string "\lday and all night…$"

Unova_VillageBridge_Text_LinebackerVillageBridgeSeenText::
	.string "Shut up and battle"
	.string "\nwith me!$"

Unova_VillageBridge_Text_LinebackerVillageBridgeBeatenText::
	.string "…!$"

Unova_VillageBridge_Text_Hoopster1VillageBridgeSeenText::
	.string "Oh! You look"
	.string "\npretty good! Let's"
	.string "\lplay some pickup!$"

Unova_VillageBridge_Text_Hoopster1VillageBridgeBeatenText::
	.string "That's game! You"
	.string "\ntotally crushed"
	.string "\lme!$"

Unova_VillageBridge_Text_Hoopster2VillageBridgeSeenText::
	.string "Fooling you fair"
	.string "\nand square! That's"
	.string "\pwhat we call a"
	.string "\ntrick play!$"

Unova_VillageBridge_Text_Hoopster2VillageBridgeBeatenText::
	.string "What the hoops? I"
	.string "\nwas the one who"
	.string "\lwas tricked!$"
