@ VillageBridge do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VillageBridge_MapScripts::
	.byte 0

Unova_VillageBridge_EventScript_Npc6::
	msgbox Unova_VillageBridge_Text_MusicianVillageBridgeSeenText, MSGBOX_NPC
	end

Unova_VillageBridge_EventScript_Npc7::
	msgbox Unova_VillageBridge_Text_Smasher1VillageBridgeSeenText, MSGBOX_NPC
	end

Unova_VillageBridge_EventScript_Npc8::
	msgbox Unova_VillageBridge_Text_Smasher2VillageBridgeSeenText, MSGBOX_NPC
	end

Unova_VillageBridge_EventScript_Npc9::
	msgbox Unova_VillageBridge_Text_LinebackerVillageBridgeSeenText, MSGBOX_NPC
	end

Unova_VillageBridge_EventScript_Npc10::
	msgbox Unova_VillageBridge_Text_Hoopster1VillageBridgeSeenText, MSGBOX_NPC
	end

Unova_VillageBridge_EventScript_Npc11::
	msgbox Unova_VillageBridge_Text_Hoopster2VillageBridgeSeenText, MSGBOX_NPC
	end


Unova_VillageBridge_Text_MusicianVillageBridgeSeenText::
	.string "Hum fiercely! My"
	.string "\nbattle song!"
	.string "\pBattle fiercely!"
	.string "\nMy POKéMON!$"

Unova_VillageBridge_Text_Smasher1VillageBridgeSeenText::
	.string "My serve is 120"
	.string "\nmiles per hour!"
	.string "\pThat's the kind of"
	.string "\nkiller attack I'm"
	.string "\labout to show you!$"

Unova_VillageBridge_Text_Smasher2VillageBridgeSeenText::
	.string "Watch my furious"
	.string "\ntennis footwork!"
	.string "\pyou get it now?"
	.string "\nWe're tough!$"

Unova_VillageBridge_Text_LinebackerVillageBridgeSeenText::
	.string "Shut up and battle"
	.string "\nwith me!$"

Unova_VillageBridge_Text_Hoopster1VillageBridgeSeenText::
	.string "Oh! You look"
	.string "\npretty good! Let's"
	.string "\lplay some pickup!$"

Unova_VillageBridge_Text_Hoopster2VillageBridgeSeenText::
	.string "Fooling you fair"
	.string "\nand square! That's"
	.string "\pwhat we call a"
	.string "\ntrick play!$"
