@ MossdeepCity_Ex14_16: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 14.16) por dev_scripts/copia_planta_ex.py.

MossdeepCity_Ex14_16_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 14.16), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
MossdeepCity_Ex14_16_EventScript_ExNpc0::
	msgbox MossdeepCity_Ex14_16_Text_ExNpc0, MSGBOX_NPC
	end

MossdeepCity_Ex14_16_Text_ExNpc0:
	.string "I wonder where my youngest boy might\n"
	.string "be?$"

MossdeepCity_Ex14_16_EventScript_ExNpc1::
	msgbox MossdeepCity_Ex14_16_Text_ExNpc1, MSGBOX_NPC
	end

MossdeepCity_Ex14_16_Text_ExNpc1:
	.string "My brother is hiding somewhere.$"

