@ TwistMountain1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_TwistMountain1F_MapScripts::
	.byte 0

Unova_TwistMountain1F_EventScript_Npc2::
	msgbox Unova_TwistMountain1F_Text_WorkerTwistMountain1FSeenText, MSGBOX_NPC
	end

Unova_TwistMountain1F_EventScript_Npc3::
	msgbox Unova_TwistMountain1F_Text_VeteranMTwistMountain1FSeenText, MSGBOX_NPC
	end


Unova_TwistMountain1F_Text_WorkerTwistMountain1FSeenText::
	.string "Check out the"
	.string "\ncombination of my"
	.string "\pcool POKéMON and"
	.string "\nmy hot fighting"
	.string "\lspirit!$"

Unova_TwistMountain1F_Text_VeteranMTwistMountain1FSeenText::
	.string "I come here every"
	.string "\nyear to train. The"
	.string "\pcold, harsh envi-"
	.string "\nronment really"
	.string "\pbrings out a POKé-"
	.string "\nMON's strength!$"
