RockPeakRuins_MapScripts::
	.byte 0

@ >>> B6 Sinnoh S1: esqueletos de cena (dev_scripts/maquina_sinnoh.py) >>>
RockPeakRuins_EventScript_DotEast::
	@ TODO S?: cena da fonte, rotulo RockPeakRuins_DotEast
	end

RockPeakRuins_EventScript_DotMiddle::
	@ TODO S?: cena da fonte, rotulo RockPeakRuins_DotMiddle
	end

RockPeakRuins_EventScript_DotNorthEast::
	@ TODO S?: cena da fonte, rotulo RockPeakRuins_DotNorthEast
	end

RockPeakRuins_EventScript_DotNorthWest::
	@ TODO S?: cena da fonte, rotulo RockPeakRuins_DotNorthWest
	end

RockPeakRuins_EventScript_DotSouthEast::
	@ TODO S?: cena da fonte, rotulo RockPeakRuins_DotSouthEast
	end

RockPeakRuins_EventScript_DotSouthWest::
	@ TODO S?: cena da fonte, rotulo RockPeakRuins_DotSouthWest
	end

RockPeakRuins_EventScript_DotWest::
	@ TODO S?: cena da fonte, rotulo RockPeakRuins_DotWest
	end

@ <<< B6 Sinnoh S1: esqueletos de cena <<<

RockPeakRuins_EventScript_Placa1::
	msgbox RockPeakRuins_Text_Placa1, MSGBOX_SIGN
	end

RockPeakRuins_Text_Placa1:
	.string "Something changed in the air...\pAn indescribable power is emanating\nfrom the Pokémon statue...$"

RockPeakRuins_EventScript_Placa2::
	msgbox RockPeakRuins_Text_Placa2, MSGBOX_SIGN
	end

RockPeakRuins_Text_Placa2:
	.string "Something changed in the air...\pAn indescribable power is emanating\nfrom the Pokémon statue...$"

RockPeakRuins_EventScript_Placa3::
	msgbox RockPeakRuins_Text_Placa3, MSGBOX_SIGN
	end

RockPeakRuins_Text_Placa3:
	.string "Something changed in the air...\pAn indescribable power is emanating\nfrom the Pokémon statue...$"
