RockPeakRuins_MapScripts::
	.byte 0

RockPeakRuins_EventScript_Placa1::
	msgbox RockPeakRuins_Text_Placa1, MSGBOX_SIGN
	end

RockPeakRuins_Text_Placa1:
	.string "Something changed in the air...\pAn indescribable power is emanating\nfrom the Pokémon statue...$"

RockPeakRuins_EventScript_Placa2::
	msgbox RockPeakRuins_Text_Placa2, MSGBOX_SIGN
	end

RockPeakRuins_Text_Placa2:
	.string "Something changed in the air...\pAn indescribable power is emanating\nfrom the Pokémon statue...$"

RockPeakRuins_EventScript_Placa3::
	msgbox RockPeakRuins_Text_Placa3, MSGBOX_SIGN
	end

RockPeakRuins_Text_Placa3:
	.string "Something changed in the air...\pAn indescribable power is emanating\nfrom the Pokémon statue...$"
