@ NacreneStatExpHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_NacreneStatExpHouse_MapScripts::
	.byte 0

Unova_NacreneStatExpHouse_EventScript_Npc0::
	msgbox Unova_NacreneStatExpHouse_Text_NacreneStatExpHouse_AskMonText, MSGBOX_NPC
	end


Unova_NacreneStatExpHouse_Text_NacreneStatExpHouse_AskMonText::
	.string "Hi, I'm interested"
	.string "\nIn POKéMON's"
	.string "\lSPECIAL stats."
	.string "\pIn particular, I'd"
	.string "\nlike to see a"
	.string "\pPOKéMON that's"
	.string "\ndone a lot of"
	.string "\ptraining in its"
	.string "\nSPECIAL stats."
	.string "\lCan you show me?$"
