@ FoothillTown_House2: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 17.4) por dev_scripts/copia_planta_ex.py.

FoothillTown_House2_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 17.4), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
FoothillTown_House2_EventScript_ExNpc0::
	msgbox FoothillTown_House2_Text_ExNpc0, MSGBOX_NPC
	end

FoothillTown_House2_Text_ExNpc0:
	.string "While sailing around the SEVII ISLANDS\n"
	.string "my ship was attacked by a GYARADOS!\p"
	.string "It’s power was amazing.\n"
	.string "I’ve been searching for one to catch\l"
	.string "ever since...$"

FoothillTown_House2_EventScript_ExNpc1::
	msgbox FoothillTown_House2_Text_ExNpc1, MSGBOX_NPC
	end

FoothillTown_House2_Text_ExNpc1:
	.string "My friends are counting on me to hook a\n"
	.string "GYARADOS, and I’m counting on them to\l"
	.string "battle and catch it!$"

FoothillTown_House2_EventScript_ExNpc2::
	msgbox FoothillTown_House2_Text_ExNpc2, MSGBOX_NPC
	end

FoothillTown_House2_Text_ExNpc2:
	.string "I’m waiting for someone to catch a\n"
	.string "powerful POKéMON for me to battle!$"

