@ DreamyardB1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_DreamyardB1F_MapScripts::
	.byte 0

Unova_DreamyardB1F_EventScript_Npc4::
	msgbox Unova_DreamyardB1F_Text_ScientistMDreamyardSeenText, MSGBOX_NPC
	end

Unova_DreamyardB1F_EventScript_Npc5::
	msgbox Unova_DreamyardB1F_Text_ScientistFDreamyardSeenText, MSGBOX_NPC
	end

Unova_DreamyardB1F_EventScript_Npc6::
	msgbox Unova_DreamyardB1F_Text_PsychicMDreamyardSeenText, MSGBOX_NPC
	end

Unova_DreamyardB1F_EventScript_Npc7::
	msgbox Unova_DreamyardB1F_Text_PsychicFDreamyardSeenText, MSGBOX_NPC
	end


Unova_DreamyardB1F_Text_ScientistMDreamyardSeenText::
	.string "Let us conduct"
	.string "\nsome POKéMON"
	.string "\presearch. Yes, let"
	.string "\nus show each"
	.string "\lother our POKéMON.$"

Unova_DreamyardB1F_Text_ScientistFDreamyardSeenText::
	.string "The mysterious"
	.string "\npsychic power! You"
	.string "\pcannot see it, yet"
	.string "\nit is definitely"
	.string "\lthere!$"

Unova_DreamyardB1F_Text_PsychicMDreamyardSeenText::
	.string "Heheh…"
	.string "\pI always know who"
	.string "\nwins in every"
	.string "\lbattle!$"

Unova_DreamyardB1F_Text_PsychicFDreamyardSeenText::
	.string "I foresaw your"
	.string "\nmove… Should I run"
	.string "\laway from you?$"
