@ VictoryRoadCave3F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VictoryRoadCave3F_MapScripts::
	.byte 0

Unova_VictoryRoadCave3F_EventScript_Npc1::
	msgbox Unova_VictoryRoadCave3F_Text_VeteranFVictoryRoadCave3FSeenText, MSGBOX_NPC
	end


Unova_VictoryRoadCave3F_Text_VeteranFVictoryRoadCave3FSeenText::
	.string "All I want are"
	.string "\npowerful POKéMON!$"
