@ VictoryRoadCave3F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VictoryRoadCave3F_MapScripts::
	.byte 0

Unova_VictoryRoadCave3F_EventScript_Lider1::
	trainerbattle_single TRAINER_UNOVA_VETERANF_VICTORY_ROAD_INT_2, Unova_VictoryRoadCave3F_Text_VeteranFVictoryRoadCave3FSeenText, Unova_VictoryRoadCave3F_Text_VeteranFVictoryRoadCave3FBeatenText
	end


Unova_VictoryRoadCave3F_Text_VeteranFVictoryRoadCave3FSeenText::
	.string "All I want are"
	.string "\npowerful POKéMON!$"

Unova_VictoryRoadCave3F_Text_VeteranFVictoryRoadCave3FBeatenText::
	.string "I can't comprehend"
	.string "\nthis! How could my"
	.string "\lPOKéMON lose?$"
