HearthomeCityPokemonFanClub_MapScripts::
	.byte 0

HearthomeCityPokemonFanClub_EventScript_Npc1::
	msgbox HearthomeCityPokemonFanClub_Text_Npc1, MSGBOX_NPC
	end

HearthomeCityPokemonFanClub_Text_Npc1:
	.string "Hello, hello!\nHow, I say, do you do?\pI am the Pokémon Fan Club Chairman!\nIndeed, yes I am!\pWhen you wish to treat your Pokémon\nto a treat, what, I say, do you do?\pIf I may say so, and I will, I feed\nPoffins to my Pokémon!\pAnd why, I say, would I do that?\pBecause the giving of Poffins is\na way of expressing your love!\pFor example! If I were to give a\nSweet Poffin, the Pokémon eating it\pwould become more cute!\pFor example! A Spicy Poffin will add\nto the coolness of a Pokémon!\pIn such ways I say that Poffins have\nnothing but goodness for Pokémon!\pTherefore!\pI declare this Poffin Case to be\na gift from me to you!$"
