@ Rt12VillageBridgeGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt12VillageBridgeGate_MapScripts::
	.byte 0

Unova_Rt12VillageBridgeGate_EventScript_Npc0::
	msgbox Unova_Rt12VillageBridgeGate_Text_R12VillageBridgeGateOfficerText, MSGBOX_NPC
	end


Unova_Rt12VillageBridgeGate_Text_R12VillageBridgeGateOfficerText::
	.string "The bridge has"
	.string "\nfinally been"
	.string "\lfixed!"
	.string "\pGo on ahead.$"
