Route208House_MapScripts::
	.byte 0

Route208House_EventScript_Npc1::
	msgbox Route208House_Text_Npc1, MSGBOX_NPC
	end

Route208House_Text_Npc1:
	.string "Everyone seems to call me the Berry\nMaster.\pI hand out Berries daily because\nI want people to learn how wonderful\pthey are.\pYou're deserving of one!$"

Route208House_EventScript_Npc2::
	msgbox Route208House_Text_Npc2, MSGBOX_NPC
	end

Route208House_Text_Npc2:
	.string "Are you the forgetful type who\nforgets where Berries are planted?$"

Route208House_EventScript_Npc3::
	msgbox Route208House_Text_Npc3, MSGBOX_NPC
	end

Route208House_Text_Npc3:
	.string "Um... Would you like some Mulch?\pIf you're going to grow Berries,\nMulch is a good fertilizer.$"
