Route38_FarmHouse_MapScripts::
	.byte 0

Route38_FarmHouse_EventScript_Npc1::
	msgbox Route38_FarmHouse_EventScript_Npc1_Text, MSGBOX_NPC
	end

Route38_FarmHouse_EventScript_Npc1_Text:
	.string "Our herd grazes the whole east pasture.\pMooMoo Milk from Route 39 gets all the fame,\nbut ours is the sweeter one. Don't tell them.$"

Route38_FarmHouse_EventScript_Npc2::
	msgbox Route38_FarmHouse_EventScript_Npc2_Text, MSGBOX_NPC
	end

Route38_FarmHouse_EventScript_Npc2_Text:
	.string "A MILTANK that is not brushed every day will\nnot give a single drop. They are proud.$"
