@ Rt19AspertiaGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt19AspertiaGate_MapScripts::
	.byte 0

Unova_Rt19AspertiaGate_EventScript_Npc0::
	msgbox Unova_Rt19AspertiaGate_Text_Rt19AspertiaGateOfficerText, MSGBOX_NPC
	end

Unova_Rt19AspertiaGate_EventScript_Npc1::
	msgbox Unova_Rt19AspertiaGate_Text_Rt19AspertiaGateYoungsterText, MSGBOX_NPC
	end


Unova_Rt19AspertiaGate_Text_Rt19AspertiaGateOfficerText::
	.string "The path ahead"
	.string "\nleads to FLOCCESY"
	.string "\lTOWN."
	.string "\pThere are a lot of"
	.string "\ntrainers out on"
	.string "\pthe path, so be"
	.string "\nprepared!$"

Unova_Rt19AspertiaGate_Text_Rt19AspertiaGateYoungsterText::
	.string "Some POKéMON only"
	.string "\nappear out at the"
	.string "\lFLOCESSY RANCH!"
	.string "\pIf you want to"
	.string "\ncatch them all,"
	.string "\pyou have to look"
	.string "\neverywhere!$"
