@ DriftveilFossilHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_DriftveilFossilHouse_MapScripts::
	.byte 0

Unova_DriftveilFossilHouse_EventScript_Npc0::
	msgbox Unova_DriftveilFossilHouse_Text_FossilHouseAskText, MSGBOX_NPC
	end


Unova_DriftveilFossilHouse_Text_FossilHouseAskText::
	.string "Hi, I'm a FOSSIL"
	.string "\nMANIAC."
	.string "\pHave you heard of"
	.string "\nPOKéMON fossils?"
	.string "\pThere's a place in"
	.string "\nNACRENE CITY where"
	.string "\pfossils can be"
	.string "\nrevived into"
	.string "\lPOKéMON!"
	.string "\pIf you have a"
	.string "\nPOKéMON revived"
	.string "\pfrom a fossil,"
	.string "\ncould I see it?$"
