@ VirbankHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VirbankHouse_MapScripts::
	.byte 0

Unova_VirbankHouse_EventScript_Npc0::
	msgbox Unova_VirbankHouse_Text_VirbankHousePharmacistIntroText, MSGBOX_NPC
	end


Unova_VirbankHouse_Text_VirbankHousePharmacistIntroText::
	.string "What's the coolest"
	.string "\ntype of POKéMON?"
	.string "\pPOISON POKéMON!"
	.string "\pTheir sick powers"
	.string "\ndrain the life"
	.string "\lfrom their"
	.string "\lenemies!"
	.string "\pUse this to power"
	.string "\nup your POISON"
	.string "\lPOKéMON!$"
