VeilstoneCitySouthwestHouse_MapScripts::
	.byte 0

VeilstoneCitySouthwestHouse_EventScript_Npc1::
	msgbox VeilstoneCitySouthwestHouse_Text_Npc1, MSGBOX_NPC
	end

VeilstoneCitySouthwestHouse_Text_Npc1:
	.string "Oh, looking a little tired?\n...Oh, no, not you.\pI meant your Pokémon.\pIf you'd like, I can give a massage\nto a Pokémon. Would you like that?$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

VeilstoneCitySouthwestHouse_EventScript_Npc1::
	msgbox VeilstoneCitySouthwestHouse_Text_Npc1, MSGBOX_NPC
	end

VeilstoneCitySouthwestHouse_Text_Npc1:
	.string "My sister's boyfriend is the Scarf\nGuy in Pastoria City.\pThey send Mail to each other by\nletting Pokémon deliver it.$"
