@ Rt16NimbasaGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt16NimbasaGate_MapScripts::
	.byte 0

Unova_Rt16NimbasaGate_EventScript_Npc0::
	msgbox Unova_Rt16NimbasaGate_Text_Rt16NimbasaGateOfficerText, MSGBOX_NPC
	end

Unova_Rt16NimbasaGate_EventScript_Npc1::
	msgbox Unova_Rt16NimbasaGate_Text_Rt16NimbasaGateCooltrainerFText, MSGBOX_NPC
	end


Unova_Rt16NimbasaGate_Text_Rt16NimbasaGateOfficerText::
	.string "NIMBASA CITY is"
	.string "\na bustling burg!"
	.string "\pStay out of"
	.string "\ntrouble, now!$"

Unova_Rt16NimbasaGate_Text_Rt16NimbasaGateCooltrainerFText::
	.string "There are a lot"
	.string "\nof shops in"
	.string "\lNIMBASA CITY!$"
