@ OpelucidSuperRodHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_OpelucidSuperRodHouse_MapScripts::
	.byte 0

Unova_OpelucidSuperRodHouse_EventScript_Npc0::
	msgbox Unova_OpelucidSuperRodHouse_Text_OfferSuperRodText, MSGBOX_NPC
	end


Unova_OpelucidSuperRodHouse_Text_OfferSuperRodText::
	.string "Fishing is great,"
	.string "\nbut to catch the"
	.string "\pbest fish, you"
	.string "\nneed the best rod."
	.string "\pDo you have what"
	.string "\nit takes to be a"
	.string "\lpro angler?$"
