EcruteakCity_House3_MapScripts::
	.byte 0

EcruteakCity_House3_EventScript_Npc1::
	msgbox EcruteakCity_House3_EventScript_Npc1_Text, MSGBOX_NPC
	end

EcruteakCity_House3_EventScript_Npc1_Text:
	.string "This side of town is quiet since the tower\nburned. Only the wind walks the east road.$"

EcruteakCity_House3_EventScript_Npc2::
	msgbox EcruteakCity_House3_EventScript_Npc2_Text, MSGBOX_NPC
	end

EcruteakCity_House3_EventScript_Npc2_Text:
	.string "Grandma says three POKéMON woke up in the\nBurned Tower and ran off. I saw nothing!$"
