@ UndellaTown do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_UndellaTown_MapScripts::
	.byte 0

Unova_UndellaTown_EventScript_Placa0::
	msgbox Unova_UndellaTown_Text_UndellaReversalSignText, MSGBOX_SIGN
	end

Unova_UndellaTown_EventScript_Placa1::
	msgbox Unova_UndellaTown_Text_UndellaFishingSignText, MSGBOX_SIGN
	end

Unova_UndellaTown_EventScript_Placa2::
	msgbox Unova_UndellaTown_Text_UndellaMarineTubeSignText, MSGBOX_SIGN
	end

Unova_UndellaTown_EventScript_Placa3::
	msgbox Unova_UndellaTown_Text_UndellaTownSignText, MSGBOX_SIGN
	end

Unova_UndellaTown_EventScript_Placa6::
	msgbox Unova_UndellaTown_Text_UndellaLockedDoorText, MSGBOX_SIGN
	end

Unova_UndellaTown_EventScript_Npc0::
	msgbox Unova_UndellaTown_Text_UndellaTownBlockerText_Dangerous, MSGBOX_NPC
	end

Unova_UndellaTown_EventScript_Npc1::
	msgbox Unova_UndellaTown_Text_UndellaTownBugCatcherText, MSGBOX_NPC
	end

Unova_UndellaTown_EventScript_Npc2::
	msgbox Unova_UndellaTown_Text_Fisher1UndellaTownSeenText, MSGBOX_NPC
	end

Unova_UndellaTown_EventScript_Npc3::
	msgbox Unova_UndellaTown_Text_Fisher2UndellaTownSeenText, MSGBOX_NPC
	end

Unova_UndellaTown_EventScript_Npc4::
	msgbox Unova_UndellaTown_Text_UndellaTownFisher3Text, MSGBOX_NPC
	end

Unova_UndellaTown_EventScript_Npc5::
	msgbox Unova_UndellaTown_Text_UndellaTownCooltrainerMText, MSGBOX_NPC
	end


Unova_UndellaTown_Text_UndellaReversalSignText::
	.string "REVERSAL MOUNTAIN"
	.string "\pEnter at your"
	.string "\nown risk!$"

Unova_UndellaTown_Text_UndellaFishingSignText::
	.string "FISHING GURU's"
	.string "\nhouse.$"

Unova_UndellaTown_Text_UndellaMarineTubeSignText::
	.string "MARINE TUBE"
	.string "\pPassage to"
	.string "\nHUMILAU CITY.$"

Unova_UndellaTown_Text_UndellaTownSignText::
	.string "UNDELLA TOWN"
	.string "\pA town of"
	.string "\nrippling waves.$"

Unova_UndellaTown_Text_UndellaLockedDoorText::
	.string "Huh? It's locked…$"

Unova_UndellaTown_Text_UndellaTownBlockerText_Dangerous::
	.string "REVERSAL MOUNTAIN"
	.string "\nis a dangerous"
	.string "\lplace, full of"
	.string "\lwild POKéMON."
	.string "\pYou should at"
	.string "\nleast have a GYM"
	.string "\lBADGE before"
	.string "\pentering a place"
	.string "\nlike this.$"

Unova_UndellaTown_Text_UndellaTownBugCatcherText::
	.string "I wanted to learn"
	.string "\nhow to fish for"
	.string "\pPOKéMON, but my"
	.string "\nmom says it's too"
	.string "\ldangerous…$"

Unova_UndellaTown_Text_Fisher1UndellaTownSeenText::
	.string "Okay, good catch!"
	.string "\nMy next catch will"
	.string "\lbe called victory!$"

Unova_UndellaTown_Text_Fisher2UndellaTownSeenText::
	.string "I'll battle you"
	.string "\nwith my freshly"
	.string "\lcaught POKéMON!$"

Unova_UndellaTown_Text_UndellaTownFisher3Text::
	.string "This little beach-"
	.string "\nside town is so"
	.string "\lnice for fishing!"
	.string "\pIf you want to"
	.string "\nlearn to fish,"
	.string "\pgo see the fishing"
	.string "\nguru in town!$"

Unova_UndellaTown_Text_UndellaTownCooltrainerMText::
	.string "The kids at the"
	.string "\nschool put on a"
	.string "\pcontest for POKé-"
	.string "\nMON trainers on"
	.string "\lROUTE 14."
	.string "\pBeat all five"
	.string "\ntrainers, and you"
	.string "\lreceive a prize.$"
