@ Rt23House do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt23House_MapScripts::
	.byte 0

Unova_Rt23House_EventScript_Npc0::
	msgbox Unova_Rt23House_Text_R23HouseGiveSpecsText, MSGBOX_NPC
	end


Unova_Rt23House_Text_R23HouseGiveSpecsText::
	.string "Hm, you must be"
	.string "\nan accomplished"
	.string "\ptrainer to have"
	.string "\nmade it all the"
	.string "\lway out here."
	.string "\pAre you planning"
	.string "\nto climb VICTORY"
	.string "\lROAD?"
	.string "\pThen you should"
	.string "\ntake these with"
	.string "\lyou.$"
