@ NimbasaVitaminMart do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_NimbasaVitaminMart_MapScripts::
	.byte 0

Unova_NimbasaVitaminMart_EventScript_Npc1::
	msgbox Unova_NimbasaVitaminMart_Text_NimbasaVitaminMartGrannyText, MSGBOX_NPC
	end


Unova_NimbasaVitaminMart_Text_NimbasaVitaminMartGrannyText::
	.string "Vitamins will make"
	.string "\nyour POKéMON"
	.string "\lstronger."
	.string "\pPROTEIN increases"
	.string "\nATTACK, IRON makes"
	.string "\lDEFENSE increase."
	.string "\pCARBOS boosts"
	.string "\nSPEED, and CALCIUM"
	.string "\lworks on both"
	.string "\lSPECIAL stats.$"
