@ ChargestoneCaveB1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_ChargestoneCaveB1F_MapScripts::
	.byte 0

Unova_ChargestoneCaveB1F_EventScript_Npc3::
	msgbox Unova_ChargestoneCaveB1F_Text_AceTrainerF2ChargestoneSeenText, MSGBOX_NPC
	end

Unova_ChargestoneCaveB1F_EventScript_Npc4::
	msgbox Unova_ChargestoneCaveB1F_Text_Hiker2ChargestoneSeenText, MSGBOX_NPC
	end

Unova_ChargestoneCaveB1F_EventScript_Npc5::
	msgbox Unova_ChargestoneCaveB1F_Text_BattleGirlChargestoneSeenText, MSGBOX_NPC
	end

Unova_ChargestoneCaveB1F_EventScript_Npc6::
	msgbox Unova_ChargestoneCaveB1F_Text_ChargestoneDoctorIntroText, MSGBOX_NPC
	end

Unova_ChargestoneCaveB1F_EventScript_Npc7::
	msgbox Unova_ChargestoneCaveB1F_Text_ScientistFChargestoneSeenText, MSGBOX_NPC
	end

Unova_ChargestoneCaveB1F_EventScript_Npc8::
	msgbox Unova_ChargestoneCaveB1F_Text_PkmnRangerMChargestoneSeenText, MSGBOX_NPC
	end


Unova_ChargestoneCaveB1F_Text_AceTrainerF2ChargestoneSeenText::
	.string "My beloved POKéMON"
	.string "\nwill make their"
	.string "\ldebut!$"

Unova_ChargestoneCaveB1F_Text_Hiker2ChargestoneSeenText::
	.string "When I say dig,"
	.string "\nsay, How low?$"

Unova_ChargestoneCaveB1F_Text_BattleGirlChargestoneSeenText::
	.string "Ai! Ai! Ai!"
	.string "\nHi-yaaah!$"

Unova_ChargestoneCaveB1F_Text_ChargestoneDoctorIntroText::
	.string "I'm a doctor, but"
	.string "\nI'm also a POKé-"
	.string "\lMON trainer."
	.string "\pIf you can defeat"
	.string "\nme in a battle,"
	.string "\lI'll heal your"
	.string "\lPOKéMON.$"

Unova_ChargestoneCaveB1F_Text_ScientistFChargestoneSeenText::
	.string "I love this place!"
	.string "\nThe electricity"
	.string "\pcharges up my"
	.string "\ninspiration!$"

Unova_ChargestoneCaveB1F_Text_PkmnRangerMChargestoneSeenText::
	.string "I am a POKéMON"
	.string "\nRANGER, here to"
	.string "\pgather up some"
	.string "\nelectric power!$"
