JubilifeCity_Flat3_F1_MapScripts::
	.byte 0

JubilifeCity_Flat3_F1_EventScript_Youngster::
	msgbox JubilifeCity_Flat3_F1_Text_Youngster, MSGBOX_NPC
	end

JubilifeCity_Flat3_F1_EventScript_Pikachu::
	msgbox JubilifeCity_Flat3_F1_Text_Pikachu, MSGBOX_NPC
	end

JubilifeCity_Flat3_F1_EventScript_President::
	msgbox JubilifeCity_Flat3_F1_Text_President, MSGBOX_NPC
	end

JubilifeCity_Flat3_F1_Text_Youngster:
	.string "I dare you to race me to the\n"
	.string "stairs!\p"
	.string "...Okay, maybe not.$"

JubilifeCity_Flat3_F1_Text_Pikachu:
	.string "Pika pika!$"

JubilifeCity_Flat3_F1_Text_President:
	.string "Even the head of a Pokétch\n"
	.string "Company needs a quiet\l"
	.string "apartment to come home to.$"
