JubilifeCity_Flat3_F1_MapScripts::
	.byte 0

JubilifeCity_Flat3_F1_EventScript_President::
	msgbox JubilifeCity_Flat3_F1_Text_President, MSGBOX_NPC
	end

JubilifeCity_Flat3_F1_Text_President:
	.string "Even the head of a Pokétch\n"
	.string "Company needs a quiet\l"
	.string "apartment to come home to.$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

JubilifeCity_Flat3_F1_EventScript_Npc1::
	msgbox JubilifeCity_Flat3_F1_Text_Npc1, MSGBOX_NPC
	end

JubilifeCity_Flat3_F1_Text_Npc1:
	.string "I got my PIKACHU through a trade from\nsomeone somewhere in the world.\pIt grows quickly, so its level goes up\nquickly, too.\pBut it doesn't always listen to me...\pThat's because I only have one\nGym Badge.\pWe don't always have an easy time,\nbut it's still my irreplaceable partner!$"

JubilifeCity_Flat3_F1_EventScript_Npc2::
	msgbox JubilifeCity_Flat3_F1_Text_Npc2, MSGBOX_NPC
	end

JubilifeCity_Flat3_F1_Text_Npc2:
	.string "PIKACHU: Pikapikapikaaah!$"

JubilifeCity_Flat3_F1_EventScript_Npc3::
	msgbox JubilifeCity_Flat3_F1_Text_Npc3, MSGBOX_NPC
	end

JubilifeCity_Flat3_F1_Text_Npc3:
	.string "If everyone around the world had\nPokémon...\pThen everyone around the world could\ncommunicate!$"
