@ LavaridgeTown_Ex4_8: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 4.8) por dev_scripts/copia_planta_ex.py.

LavaridgeTown_Ex4_8_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 4.8), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
LavaridgeTown_Ex4_8_EventScript_ExNpc0::
	msgbox LavaridgeTown_Ex4_8_Text_ExNpc0, MSGBOX_NPC
	end

LavaridgeTown_Ex4_8_Text_ExNpc0:
	.string "My granddaughter spends lots of time\n"
	.string "here.\p"
	.string "She loves to come and visit.$"

LavaridgeTown_Ex4_8_EventScript_ExNpc1::
	msgbox LavaridgeTown_Ex4_8_Text_ExNpc1, MSGBOX_NPC
	end

LavaridgeTown_Ex4_8_Text_ExNpc1:
	.string "FLANNERY’S so cool.\n"
	.string "I’ve known her since I was little, and\l"
	.string "now she’s the NEW GYM LEADER!$"

