@ AspertiaBlackbeltHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_AspertiaBlackbeltHouse_MapScripts::
	.byte 0

Unova_AspertiaBlackbeltHouse_EventScript_Npc0::
	msgbox Unova_AspertiaBlackbeltHouse_Text_AspertiaBlackbeltHouseGiveBandText, MSGBOX_NPC
	end


Unova_AspertiaBlackbeltHouse_Text_AspertiaBlackbeltHouseGiveBandText::
	.string "Hm? Are you"
	.string "\ntraining to become"
	.string "\la master?"
	.string "\pYou must steel"
	.string "\nyour resolve and"
	.string "\lclear your focus!"
	.string "\pHere, take this!$"
