#ifndef GUARD_CONSTANTS_JOHTO_INTERIORES_H
#define GUARD_CONSTANTS_JOHTO_INTERIORES_H

// ponytail: local ids dos NPCs de Centro Pokemon e Loja de Johto. Os mapas
// vieram da importacao so com stubs de OBJ_EVENT_GFX_ITEM_BALL (decoracao,
// script "0"); aqui e onde cada posicao virou NPC de verdade. O numero de
// cada define e a posicao (1-indexed) do objeto dentro do array
// "object_events" do map.json daquele mapa — nao invente, confira o json.

// MAP_AZALEA_TOWN_POKEMON_CENTER
#define LOCALID_AZALEA_PC_NURSE 1
#define LOCALID_AZALEA_PC_POKEFAN 3
#define LOCALID_AZALEA_PC_FISHER 4
#define LOCALID_AZALEA_PC_GENTLEMAN 5

// MAP_AZALEA_TOWN_MART
#define LOCALID_AZALEA_MART_BUGCATCHER 1
#define LOCALID_AZALEA_MART_TRAINER 2
#define LOCALID_AZALEA_MART_CLERK 3

// MAP_BLACKTHORN_CITY_POKEMON_CENTER
#define LOCALID_BLACKTHORN_PC_NURSE 1
#define LOCALID_BLACKTHORN_PC_GENTLEMAN 3
#define LOCALID_BLACKTHORN_PC_TWIN 4

// MAP_BLACKTHORN_CITY_MART
#define LOCALID_BLACKTHORN_MART_BLACKBELT 1
#define LOCALID_BLACKTHORN_MART_TRAINER 2
#define LOCALID_BLACKTHORN_MART_CLERK 3

// MAP_CHERRYGROVE_CITY_POKEMON_CENTER
#define LOCALID_CHERRYGROVE_PC_NURSE 1
#define LOCALID_CHERRYGROVE_PC_LASS 3
#define LOCALID_CHERRYGROVE_PC_FISHER 4
#define LOCALID_CHERRYGROVE_PC_GENTLEMAN 5

// MAP_CHERRYGROVE_CITY_MART
#define LOCALID_CHERRYGROVE_MART_CLERK 1
#define LOCALID_CHERRYGROVE_MART_YOUNGSTER 2
#define LOCALID_CHERRYGROVE_MART_BUGCATCHER 3

// MAP_CIANWOOD_POKECENTER
#define LOCALID_CIANWOOD_PC_NURSE 1
#define LOCALID_CIANWOOD_PC_NERD 3
#define LOCALID_CIANWOOD_PC_GUIDE 4
#define LOCALID_CIANWOOD_PC_LASS 5
#define LOCALID_CIANWOOD_PC_FISHER 6

// MAP_CIANWOOD_SHOP
#define LOCALID_CIANWOOD_SHOP_CLERK 1

// MAP_ECRUTEAK_CITY_POKEMON_CENTER
#define LOCALID_ECRUTEAK_PC_NURSE 1
#define LOCALID_ECRUTEAK_PC_NERD 3
#define LOCALID_ECRUTEAK_PC_HIKER 4
#define LOCALID_ECRUTEAK_PC_WOMAN 5

// MAP_ECRUTEAK_CITY_MART
#define LOCALID_ECRUTEAK_MART_GRANNY 1
#define LOCALID_ECRUTEAK_MART_NERD 2
#define LOCALID_ECRUTEAK_MART_CLERK 3

// MAP_GOLDENROD_CITY_POKEMON_CENTER
#define LOCALID_GOLDENROD_PC_NURSE 1
#define LOCALID_GOLDENROD_PC_LASS 3
#define LOCALID_GOLDENROD_PC_KID1 4
#define LOCALID_GOLDENROD_PC_GRANNY 5
#define LOCALID_GOLDENROD_PC_KID2 6

// MAP_MAHOGANY_TOWN_POKEMON_CENTER
#define LOCALID_MAHOGANY_PC_NURSE 1
#define LOCALID_MAHOGANY_PC_HIKER 3
#define LOCALID_MAHOGANY_PC_BOY 4
#define LOCALID_MAHOGANY_PC_GIRL 5

// MAP_MAHOGANY_TOWN_SHOP
#define LOCALID_MAHOGANY_SHOP_CLERK 1

// MAP_OLIVINE_CITY_POKEMON_CENTER
#define LOCALID_OLIVINE_PC_NURSE 1
#define LOCALID_OLIVINE_PC_FISHER 3
#define LOCALID_OLIVINE_PC_TEACHER 4

// MAP_OLIVINE_CITY_MART
#define LOCALID_OLIVINE_MART_TRAINER 1
#define LOCALID_OLIVINE_MART_LASS 2
#define LOCALID_OLIVINE_MART_CLERK 3

// MAP_VIOLET_CITY_POKEMON_CENTER
#define LOCALID_VIOLET_PC_NURSE 1
#define LOCALID_VIOLET_PC_GENTLEMAN 3
#define LOCALID_VIOLET_PC_MAN 4
#define LOCALID_VIOLET_PC_KID 5
#define LOCALID_VIOLET_PC_BOOKWOMAN 7

// MAP_VIOLET_CITY_MART
#define LOCALID_VIOLET_MART_GRANNY 1
#define LOCALID_VIOLET_MART_ROCKER 2
#define LOCALID_VIOLET_MART_CLERK 3

#endif // GUARD_CONSTANTS_JOHTO_INTERIORES_H
