Route34_DayCare_MapScripts::
	.byte 0

@ Placas trazidas do hns por dev_scripts/importa_placas_johto.py

Route34_DayCare_Bookshelf1::
	msgbox Route34_DayCare_Text_Bookshelf1, MSGBOX_SIGN
	end

Route34_DayCare_Bookshelf2::
	msgbox Route34_DayCare_Text_Bookshelf2, MSGBOX_SIGN
	end

Route34_DayCare_Bookshelf3::
	msgbox Route34_DayCare_Text_Bookshelf3, MSGBOX_SIGN
	end

Route34_DayCare_Bookshelf4::
	msgbox Route34_DayCare_Text_Bookshelf4, MSGBOX_SIGN
	end

Route34_DayCare_Text_Bookshelf1::
	.string "A dictionary!\p"
	.string "{PLAYER} opened the dictionary to\n"
	.string "a random page.\p"
	.string "'BABE'\n"
	.string "A noun, meaning infant or baby.\p"
	.string "{PLAYER} put away the dictionary.$"

Route34_DayCare_Text_Bookshelf2::
	.string "A book about POKéMON!\p"
	.string "{PLAYER} flipped through\n"
	.string "the book.\p"
	.string "It must have the word\n"
	.string "POKéMON written on every page.\p"
	.string "{PLAYER} put away the book.$"

Route34_DayCare_Text_Bookshelf3::
	.string "A book of word assocations!\p"
	.string "{PLAYER} flipped through\n"
	.string "the book.\p"
	.string "PICHU -> CUTE\l"
	.string "CLEFFA -> CUTE\l"
	.string "IGGLYBUFF -> SONG\l"
	.string "TYROGUE -> FIGHTING\l"
	.string "SMOOCHUM -> ICE\l"
	.string "ELEKID -> ELECTRIC\l"
	.string "MAGBY -> FIRE\p"
	.string "{PLAYER} put away the book.$"

Route34_DayCare_Text_Bookshelf4::
	.string "A book of POKéMON abilities!\p"
	.string "{PLAYER} flipped through\n"
	.string "the book.\p"
	.string "PICHU -> STATIC\l"
	.string "CLEFFA -> CUTE CHARM\l"
	.string "IGGLYBUFF -> CUTE CHARM\l"
	.string "TYROGUE -> GUTS\l"
	.string "SMOOCHUM -> OBLIVIOUS\l"
	.string "ELEKID -> STATIC\l"
	.string "MAGBY -> FLAME BODY\p"
	.string "{PLAYER} put away the book.$"
