@ Rt19 do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt19_MapScripts::
	.byte 0

Unova_Rt19_EventScript_Npc7::
	msgbox Unova_Rt19_Text_PkmnBreederFR19SeenText, MSGBOX_NPC
	end

Unova_Rt19_EventScript_Npc8::
	msgbox Unova_Rt19_Text_PkmnBreederMR19SeenText, MSGBOX_NPC
	end

Unova_Rt19_EventScript_Npc9::
	msgbox Unova_Rt19_Text_LadyR19SeenText, MSGBOX_NPC
	end

Unova_Rt19_EventScript_Npc10::
	msgbox Unova_Rt19_Text_DepotAgent1R19SeenText, MSGBOX_NPC
	end

Unova_Rt19_EventScript_Npc11::
	msgbox Unova_Rt19_Text_DepotAgent2R19SeenText, MSGBOX_NPC
	end

Unova_Rt19_EventScript_Npc12::
	msgbox Unova_Rt19_Text_MaidR19SeenText, MSGBOX_NPC
	end

Unova_Rt19_EventScript_Npc13::
	msgbox Unova_Rt19_Text_BakerR19SeenText, MSGBOX_NPC
	end


Unova_Rt19_Text_PkmnBreederFR19SeenText::
	.string "We are totally in"
	.string "\nsync! I will teach"
	.string "\pyou all about"
	.string "\nPOKéMON breeders!$"

Unova_Rt19_Text_PkmnBreederMR19SeenText::
	.string "I'm always"
	.string "\npatrolling this"
	.string "\larea!$"

Unova_Rt19_Text_LadyR19SeenText::
	.string "Are you beautiful"
	.string "\nas a trainer?"
	.string "\lSurprise me!$"

Unova_Rt19_Text_DepotAgent1R19SeenText::
	.string "This is the battle"
	.string "\ntrain! All aboard!$"

Unova_Rt19_Text_DepotAgent2R19SeenText::
	.string "I want you to tell"
	.string "\nme something!$"

Unova_Rt19_Text_MaidR19SeenText::
	.string "You! Are you a fan"
	.string "\nof that person?"
	.string "\pBut that person is"
	.string "\nmine!$"

Unova_Rt19_Text_BakerR19SeenText::
	.string "I'm not satisfied"
	.string "\nwith my baking."
	.string "\pAre you satisfied"
	.string "\nwith your POKéMON"
	.string "\ltraining?$"
