@ HumilauTradeHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_HumilauTradeHouse_MapScripts::
	.byte 0

Unova_HumilauTradeHouse_EventScript_Npc0::
	msgbox Unova_HumilauTradeHouse_Text_HumilauTradeHouseNoPokeText, MSGBOX_NPC
	end


Unova_HumilauTradeHouse_Text_HumilauTradeHouseNoPokeText::
	.string "Hi, I'm looking to"
	.string "\ntrade POKéMON."
	.string "\pOh, you don't have"
	.string "\nany POKéMON?"
	.string "\lThat's too bad.$"
