@ Rt11 do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt11_MapScripts::
	.byte 0

Unova_Rt11_EventScript_Npc4::
	msgbox Unova_Rt11_Text_R11AmoongussText, MSGBOX_NPC
	end

Unova_Rt11_EventScript_Npc5::
	msgbox Unova_Rt11_Text_R11AmoongussText, MSGBOX_NPC
	end

Unova_Rt11_EventScript_Npc6::
	msgbox Unova_Rt11_Text_BackersMR11SeenText, MSGBOX_NPC
	end

Unova_Rt11_EventScript_Npc7::
	msgbox Unova_Rt11_Text_BackersMR11SeenText, MSGBOX_NPC
	end

Unova_Rt11_EventScript_Npc8::
	msgbox Unova_Rt11_Text_BackersFR11SeenText, MSGBOX_NPC
	end

Unova_Rt11_EventScript_Npc9::
	msgbox Unova_Rt11_Text_BackersFR11SeenText, MSGBOX_NPC
	end


Unova_Rt11_Text_R11AmoongussText::
	.string "Ooong!$"

Unova_Rt11_Text_BackersMR11SeenText::
	.string "Sports and POKé-"
	.string "\nMON battles are"
	.string "\pdramas that don't"
	.string "\nneed scripts!$"

Unova_Rt11_Text_BackersFR11SeenText::
	.string "Knowing what a"
	.string "\ntruly heated"
	.string "\pbattle is all"
	.string "\nabout is the key"
	.string "\pto truly passion-"
	.string "\nate cheering!$"
