@ DragonspiralTower2F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_DragonspiralTower2F_MapScripts::
	.byte 0

Unova_DragonspiralTower2F_EventScript_Npc3::
	msgbox Unova_DragonspiralTower2F_Text_DragonspiralTowerGialloSeenText, MSGBOX_NPC
	end


Unova_DragonspiralTower2F_Text_DragonspiralTowerGialloSeenText::
	.string "So, you've come."
	.string "\nWe, the SAGEs of"
	.string "\pTEAM PLASMA shall"
	.string "\ndefeat you here!$"
