Route209LostTower5F_MapScripts::
	.byte 0

Route209LostTower5F_EventScript_Npc1::
	msgbox Route209LostTower5F_Text_Npc1, MSGBOX_NPC
	end

Route209LostTower5F_Text_Npc1:
	.string "Oh! The fog is gone and, with it, all\ndoubt in my heart!\pThis is my thanks.\nDon't be shy! Take it!$"

Route209LostTower5F_EventScript_Npc2::
	msgbox Route209LostTower5F_Text_Npc2, MSGBOX_NPC
	end

Route209LostTower5F_Text_Npc2:
	.string "Let me make your journey out of this\nplace less frightening. Take this.$"
