HearthomeCityDpGymElevatorRoom1_MapScripts::
	.byte 0

HearthomeCityDpGymElevatorRoom1_EventScript_Placa1::
	msgbox HearthomeCityDpGymElevatorRoom1_Text_Placa1, MSGBOX_SIGN
	end

HearthomeCityDpGymElevatorRoom1_Text_Placa1:
	.string "Question: 3 times 13 is?\nAnswer: ←39 ↑93 →33$"

HearthomeCityDpGymElevatorRoom1_EventScript_Placa2::
	msgbox HearthomeCityDpGymElevatorRoom1_Text_Placa2, MSGBOX_SIGN
	end

HearthomeCityDpGymElevatorRoom1_Text_Placa2:
	.string "Correct!\nCongratulations!$"
