@ SeasideCave1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_SeasideCave1F_MapScripts::
	.byte 0

Unova_SeasideCave1F_EventScript_Npc6::
	msgbox Unova_SeasideCave1F_Text_SeasideCaveDoctorIntroText, MSGBOX_NPC
	end

Unova_SeasideCave1F_EventScript_Npc7::
	msgbox Unova_SeasideCave1F_Text_VeteranFSeasideCave1FSeenText, MSGBOX_NPC
	end

Unova_SeasideCave1F_EventScript_Npc8::
	msgbox Unova_SeasideCave1F_Text_BlackbeltSeasideCave1FSeenText, MSGBOX_NPC
	end

Unova_SeasideCave1F_EventScript_Npc9::
	msgbox Unova_SeasideCave1F_Text_BattleGirlSeasideCave1FSeenText, MSGBOX_NPC
	end


Unova_SeasideCave1F_Text_SeasideCaveDoctorIntroText::
	.string "I'm a doctor, but"
	.string "\nI'm also a POKé-"
	.string "\lMON trainer."
	.string "\pIf you can defeat"
	.string "\nme in a battle,"
	.string "\lI'll heal your"
	.string "\lPOKéMON.$"

Unova_SeasideCave1F_Text_VeteranFSeasideCave1FSeenText::
	.string "Let me show you"
	.string "\nthe POKéMON that I"
	.string "\lmet by fate!$"

Unova_SeasideCave1F_Text_BlackbeltSeasideCave1FSeenText::
	.string "The path of karate"
	.string "\nis the path of"
	.string "\phumanity… and the"
	.string "\npath of POKéMON!$"

Unova_SeasideCave1F_Text_BattleGirlSeasideCave1FSeenText::
	.string "Greetings! So…"
	.string "\nshall we do this?$"
