@ LavaridgeTown_Ex4_11: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 4.11) por dev_scripts/copia_planta_ex.py.

LavaridgeTown_Ex4_11_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 4.11), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
LavaridgeTown_Ex4_11_EventScript_ExNpc0::
	msgbox LavaridgeTown_Ex4_11_Text_ExNpc0, MSGBOX_NPC
	end

LavaridgeTown_Ex4_11_Text_ExNpc0:
	.string "...Grumble...\n"
	.string "...Grumble...\p"
	.string "FLANNERY shouldn’t of been made GYM\n"
	.string "LEADER...\p"
	.string "..Grumble...$"

