@ VictoryRoadCave2F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VictoryRoadCave2F_MapScripts::
	.byte 0

Unova_VictoryRoadCave2F_EventScript_Npc5::
	msgbox Unova_VictoryRoadCave2F_Text_AceTrainerMVictoryRoadCave2FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadCave2F_EventScript_Npc6::
	msgbox Unova_VictoryRoadCave2F_Text_AceTrainerFVictoryRoadCave2FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadCave2F_EventScript_Npc7::
	msgbox Unova_VictoryRoadCave2F_Text_PkmnRangerMVictoryRoadCave2FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadCave2F_EventScript_Npc8::
	msgbox Unova_VictoryRoadCave2F_Text_PkmnRangerFVictoryRoadCave2FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadCave2F_EventScript_Npc9::
	msgbox Unova_VictoryRoadCave2F_Text_VeteranMVictoryRoadCave2FSeenText, MSGBOX_NPC
	end

Unova_VictoryRoadCave2F_EventScript_Npc10::
	msgbox Unova_VictoryRoadCave2F_Text_BackpackerMVictoryRoadCave2FSeenText, MSGBOX_NPC
	end


Unova_VictoryRoadCave2F_Text_AceTrainerMVictoryRoadCave2FSeenText::
	.string "It's not enough for"
	.string "\nme just to be"
	.string "\ptogether with"
	.string "\nPOKéMON! I want to"
	.string "\lwin!$"

Unova_VictoryRoadCave2F_Text_AceTrainerFVictoryRoadCave2FSeenText::
	.string "Our unity won't be"
	.string "\nbested by anyone!$"

Unova_VictoryRoadCave2F_Text_PkmnRangerMVictoryRoadCave2FSeenText::
	.string "Behold the blind-"
	.string "\ning brilliance of"
	.string "\lmy many BADGEs!$"

Unova_VictoryRoadCave2F_Text_PkmnRangerFVictoryRoadCave2FSeenText::
	.string "Something about"
	.string "\nyou reminds me of"
	.string "\pthat trainer from"
	.string "\nyears ago…$"

Unova_VictoryRoadCave2F_Text_VeteranMVictoryRoadCave2FSeenText::
	.string "The endless cycle"
	.string "\nof wins and"
	.string "\plosses… Will it"
	.string "\nalways continue?$"

Unova_VictoryRoadCave2F_Text_BackpackerMVictoryRoadCave2FSeenText::
	.string "I'm gonna numb you"
	.string "\nand your POKéMON!$"
