@ VictoryRoadCave2F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_VictoryRoadCave2F_MapScripts::
	.byte 0

Unova_VictoryRoadCave2F_EventScript_Lider5::
	trainerbattle_single TRAINER_UNOVA_ACE_TRAINERM_VICTORY_ROAD_INT_2, Unova_VictoryRoadCave2F_Text_AceTrainerMVictoryRoadCave2FSeenText, Unova_VictoryRoadCave2F_Text_AceTrainerMVictoryRoadCave2FBeatenText
	end

Unova_VictoryRoadCave2F_EventScript_Lider6::
	trainerbattle_single TRAINER_UNOVA_ACE_TRAINERF_VICTORY_ROAD_INT_1, Unova_VictoryRoadCave2F_Text_AceTrainerFVictoryRoadCave2FSeenText, Unova_VictoryRoadCave2F_Text_AceTrainerFVictoryRoadCave2FBeatenText
	end

Unova_VictoryRoadCave2F_EventScript_Lider7::
	trainerbattle_single TRAINER_UNOVA_PKMN_RANGERM_VICTORY_ROAD_INT, Unova_VictoryRoadCave2F_Text_PkmnRangerMVictoryRoadCave2FSeenText, Unova_VictoryRoadCave2F_Text_PkmnRangerMVictoryRoadCave2FBeatenText
	end

Unova_VictoryRoadCave2F_EventScript_Lider8::
	trainerbattle_single TRAINER_UNOVA_PKMN_RANGERF_VICTORY_ROAD_INT, Unova_VictoryRoadCave2F_Text_PkmnRangerFVictoryRoadCave2FSeenText, Unova_VictoryRoadCave2F_Text_PkmnRangerFVictoryRoadCave2FBeatenText
	end

Unova_VictoryRoadCave2F_EventScript_Lider9::
	trainerbattle_single TRAINER_UNOVA_VETERANM_VICTORY_ROAD_INT_2, Unova_VictoryRoadCave2F_Text_VeteranMVictoryRoadCave2FSeenText, Unova_VictoryRoadCave2F_Text_VeteranMVictoryRoadCave2FBeatenText
	end

Unova_VictoryRoadCave2F_EventScript_Lider10::
	trainerbattle_single TRAINER_UNOVA_BACKPACKERM_VICTORY_ROAD_INT, Unova_VictoryRoadCave2F_Text_BackpackerMVictoryRoadCave2FSeenText, Unova_VictoryRoadCave2F_Text_BackpackerMVictoryRoadCave2FBeatenText
	end


Unova_VictoryRoadCave2F_Text_AceTrainerMVictoryRoadCave2FSeenText::
	.string "It's not enough for"
	.string "\nme just to be"
	.string "\ptogether with"
	.string "\nPOKéMON! I want to"
	.string "\lwin!$"

Unova_VictoryRoadCave2F_Text_AceTrainerMVictoryRoadCave2FBeatenText::
	.string "How… How could you"
	.string "\ndefeat me this"
	.string "\lutterly?$"

Unova_VictoryRoadCave2F_Text_AceTrainerFVictoryRoadCave2FSeenText::
	.string "Our unity won't be"
	.string "\nbested by anyone!$"

Unova_VictoryRoadCave2F_Text_AceTrainerFVictoryRoadCave2FBeatenText::
	.string "We couldn't win…"
	.string "\nbut that's alright.$"

Unova_VictoryRoadCave2F_Text_PkmnRangerMVictoryRoadCave2FSeenText::
	.string "Behold the blind-"
	.string "\ning brilliance of"
	.string "\lmy many BADGEs!$"

Unova_VictoryRoadCave2F_Text_PkmnRangerMVictoryRoadCave2FBeatenText::
	.string "Your skill is too"
	.string "\nbrilliant to"
	.string "\lbehold!$"

Unova_VictoryRoadCave2F_Text_PkmnRangerFVictoryRoadCave2FSeenText::
	.string "Something about"
	.string "\nyou reminds me of"
	.string "\pthat trainer from"
	.string "\nyears ago…$"

Unova_VictoryRoadCave2F_Text_PkmnRangerFVictoryRoadCave2FBeatenText::
	.string "Yes! That mix of"
	.string "\nkindness and power"
	.string "\pis just like that"
	.string "\ntrainer!$"

Unova_VictoryRoadCave2F_Text_VeteranMVictoryRoadCave2FSeenText::
	.string "The endless cycle"
	.string "\nof wins and"
	.string "\plosses… Will it"
	.string "\nalways continue?$"

Unova_VictoryRoadCave2F_Text_VeteranMVictoryRoadCave2FBeatenText::
	.string "Every win and loss"
	.string "\nis a precious"
	.string "\lmemory.$"

Unova_VictoryRoadCave2F_Text_BackpackerMVictoryRoadCave2FSeenText::
	.string "I'm gonna numb you"
	.string "\nand your POKéMON!$"

Unova_VictoryRoadCave2F_Text_BackpackerMVictoryRoadCave2FBeatenText::
	.string "Unbelievable! I"
	.string "\nwas the one struck"
	.string "\lnumb…$"
