@ NacreneCity do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_NacreneCity_MapScripts::
	.byte 0

Unova_NacreneCity_EventScript_Placa0::
	msgbox Unova_NacreneCity_Text_NacreneCitySignText, MSGBOX_SIGN
	end

Unova_NacreneCity_EventScript_Placa1::
	msgbox Unova_NacreneCity_Text_NacreneCafeSignText, MSGBOX_SIGN
	end

Unova_NacreneCity_EventScript_Placa2::
	msgbox Unova_NacreneCity_Text_NacreneMuseumSignText, MSGBOX_SIGN
	end

Unova_NacreneCity_EventScript_Placa3::
	msgbox Unova_NacreneCity_Text_NacreneR3SignText, MSGBOX_SIGN
	end

Unova_NacreneCity_EventScript_Npc1::
	msgbox Unova_NacreneCity_Text_NacreneCityLassText, MSGBOX_NPC
	end

Unova_NacreneCity_EventScript_Npc2::
	msgbox Unova_NacreneCity_Text_NacreneCityGentlemanText, MSGBOX_NPC
	end

Unova_NacreneCity_EventScript_Npc3::
	msgbox Unova_NacreneCity_Text_NacreneCityMusicianText, MSGBOX_NPC
	end


Unova_NacreneCity_Text_NacreneCitySignText::
	.string "NACRENE CITY"
	.string "\pA pearl of a"
	.string "\nplace!$"

Unova_NacreneCity_Text_NacreneCafeSignText::
	.string "NACRENE CITY Cafe."
	.string "\pRefresh your body"
	.string "\nand soul!$"

Unova_NacreneCity_Text_NacreneMuseumSignText::
	.string "NACRENE CITY"
	.string "\nMuseum."
	.string "\pWhere the past"
	.string "\ncomes to life!$"

Unova_NacreneCity_Text_NacreneR3SignText::
	.string "ROUTE 3 ahead."
	.string "\pPassage to"
	.string "\nSTRIATON CITY.$"

Unova_NacreneCity_Text_NacreneCityLassText::
	.string "The cafe in town"
	.string "\nserves specialty"
	.string "\pdrinks you can't"
	.string "\nget anywhere else!$"

Unova_NacreneCity_Text_NacreneCityGentlemanText::
	.string "We used to have a"
	.string "\nGYM in the museum,"
	.string "\pbut LENORA has"
	.string "\nretired to run"
	.string "\pthe museum full"
	.string "\ntime.$"

Unova_NacreneCity_Text_NacreneCityMusicianText::
	.string "NACRENE CITY may"
	.string "\nnot be the biggest"
	.string "\pcity in UNOVA, but"
	.string "\nit's got a"
	.string "\pthriving scene for"
	.string "\nyoung artists.$"
