@ DragonspiralTower4F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_DragonspiralTower4F_MapScripts::
	.byte 0

Unova_DragonspiralTower4F_EventScript_Npc1::
	msgbox Unova_DragonspiralTower4F_Text_DragonspiralTowerBroniusSeenText, MSGBOX_NPC
	end


Unova_DragonspiralTower4F_Text_DragonspiralTowerBroniusSeenText::
	.string "When I saw you in"
	.string "\nVIRBANK, I did not"
	.string "\pcare about your"
	.string "\nexistence. Now,"
	.string "\pI will put a stop"
	.string "\nto your little"
	.string "\pgame! You shall"
	.string "\nnot interfere with"
	.string "\lTEAM PLASMA!$"
