@ LilycoveCity_Ex13_28: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 13.28) por dev_scripts/copia_planta_ex.py.

LilycoveCity_Ex13_28_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 13.28), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
LilycoveCity_Ex13_28_EventScript_ExNpc0::
	msgbox LilycoveCity_Ex13_28_Text_ExNpc0, MSGBOX_NPC
	end

LilycoveCity_Ex13_28_Text_ExNpc0:
	.string "My bride is already making this house\n"
	.string "feel like a home.$"

LilycoveCity_Ex13_28_EventScript_ExNpc1::
	msgbox LilycoveCity_Ex13_28_Text_ExNpc1, MSGBOX_NPC
	end

LilycoveCity_Ex13_28_Text_ExNpc1:
	.string "We just moved here after our wedding!$"

LilycoveCity_Ex13_28_EventScript_ExNpc2::
	msgbox LilycoveCity_Ex13_28_Text_ExNpc2, MSGBOX_NPC
	end

LilycoveCity_Ex13_28_Text_ExNpc2:
	.string "Arf!$"

