@ DriftveilBridgeGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_DriftveilBridgeGate_MapScripts::
	.byte 0

Unova_DriftveilBridgeGate_EventScript_Npc0::
	msgbox Unova_DriftveilBridgeGate_Text_DriftveilBridgeGateOfficerText, MSGBOX_NPC
	end


Unova_DriftveilBridgeGate_Text_DriftveilBridgeGateOfficerText::
	.string "The BRIDGE takes"
	.string "\nyou straight to"
	.string "\lNIMBASA CITY.$"
