@ MistraltonCave2F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_MistraltonCave2F_MapScripts::
	.byte 0

Unova_MistraltonCave2F_EventScript_Npc7::
	msgbox Unova_MistraltonCave2F_Text_AceTrainerMMistraltonCaveSeenText, MSGBOX_NPC
	end

Unova_MistraltonCave2F_EventScript_Npc8::
	msgbox Unova_MistraltonCave2F_Text_AceTrainerFMistraltonCaveSeenText, MSGBOX_NPC
	end


Unova_MistraltonCave2F_Text_AceTrainerMMistraltonCaveSeenText::
	.string "Behold my"
	.string "\nimpressive"
	.string "\pphysique. It's"
	.string "\nfitting of an ACE"
	.string "\lTRAINER!$"

Unova_MistraltonCave2F_Text_AceTrainerFMistraltonCaveSeenText::
	.string "Why don't you prove"
	.string "\nto me how much you"
	.string "\pand your POKéMON"
	.string "\nare capable of!$"
