@ SeasideCaveB1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_SeasideCaveB1F_MapScripts::
	.byte 0

Unova_SeasideCaveB1F_EventScript_Npc5::
	msgbox Unova_SeasideCaveB1F_Text_BlackbeltSeasideCaveB1FSeenText, MSGBOX_NPC
	end

Unova_SeasideCaveB1F_EventScript_Npc6::
	msgbox Unova_SeasideCaveB1F_Text_BattleGirlSeasideCaveB1FSeenText, MSGBOX_NPC
	end


Unova_SeasideCaveB1F_Text_BlackbeltSeasideCaveB1FSeenText::
	.string "I will never turn"
	.string "\nmy back and run!$"

Unova_SeasideCaveB1F_Text_BattleGirlSeasideCaveB1FSeenText::
	.string "My training will"
	.string "\nnever betray me."
	.string "\pAfter training"
	.string "\nthis much, I am"
	.string "\lcertain to win!$"
