JubilifeCity_PoketchCompany_F2_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

JubilifeCity_PoketchCompany_F2_EventScript_Npc1::
	msgbox JubilifeCity_PoketchCompany_F2_Text_Npc1, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_Text_Npc1:
	.string "We'll try to think like a Trainer and find\nwhat Pokétch apps would be good.$"

JubilifeCity_PoketchCompany_F2_EventScript_Npc2::
	msgbox JubilifeCity_PoketchCompany_F2_Text_Npc2, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_Text_Npc2:
	.string "Pokémon Watch!\nThat's Pokétch for short.\pSay it the long way and...\nWhat does Pokémon stand for again?\pAnyway, I'm the father of the\npresident of the Pokétch Company!$"

JubilifeCity_PoketchCompany_F2_EventScript_Npc3::
	msgbox JubilifeCity_PoketchCompany_F2_Text_Npc3, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_Text_Npc3:
	.string "CLEFAIRY: Cleffy?$"
