JubilifeCity_PoketchCompany_F2_MapScripts::
	.byte 0

JubilifeCity_PoketchCompany_F2_EventScript_PokefanM::
	msgbox JubilifeCity_PoketchCompany_F2_Text_PokefanM, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_EventScript_OldMan::
	msgbox JubilifeCity_PoketchCompany_F2_Text_OldMan, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_EventScript_Clefairy::
	msgbox JubilifeCity_PoketchCompany_F2_Text_Clefairy, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_Text_PokefanM:
	.string "This place always smells like\n"
	.string "fresh paint and new ideas.$"

JubilifeCity_PoketchCompany_F2_Text_OldMan:
	.string "In my day, we didn't need a\n"
	.string "wrist gadget to tell time.\p"
	.string "We had the sun! ...And clocks.$"

JubilifeCity_PoketchCompany_F2_Text_Clefairy:
	.string "Clefairy!$"
