JubilifeCity_PoketchCompany_F2_MapScripts::
	.byte 0

JubilifeCity_PoketchCompany_F2_EventScript_PokefanM::
	msgbox JubilifeCity_PoketchCompany_F2_Text_PokefanM, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_EventScript_OldMan::
	msgbox JubilifeCity_PoketchCompany_F2_Text_OldMan, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_EventScript_Clefairy::
	msgbox JubilifeCity_PoketchCompany_F2_Text_Clefairy, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_Text_PokefanM:
	.string "This place always smells like\n"
	.string "fresh paint and new ideas.$"

JubilifeCity_PoketchCompany_F2_Text_OldMan:
	.string "In my day, we didn't need a\n"
	.string "wrist gadget to tell time.\p"
	.string "We had the sun! ...And clocks.$"

JubilifeCity_PoketchCompany_F2_Text_Clefairy:
	.string "Clefairy!$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

JubilifeCity_PoketchCompany_F2_EventScript_Npc1::
	msgbox JubilifeCity_PoketchCompany_F2_Text_Npc1, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_Text_Npc1:
	.string "We'll try to think like a Trainer and find\nwhat Pokétch apps would be good.$"

JubilifeCity_PoketchCompany_F2_EventScript_Npc2::
	msgbox JubilifeCity_PoketchCompany_F2_Text_Npc2, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_Text_Npc2:
	.string "Pokémon Watch!\nThat's Pokétch for short.\pSay it the long way and...\nWhat does Pokémon stand for again?\pAnyway, I'm the father of the\npresident of the Pokétch Company!$"

JubilifeCity_PoketchCompany_F2_EventScript_Npc3::
	msgbox JubilifeCity_PoketchCompany_F2_Text_Npc3, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_Text_Npc3:
	.string "CLEFAIRY: Cleffy?$"
