@ TimeCapsule do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_TimeCapsule_MapScripts::
	.byte 0

Unova_TimeCapsule_EventScript_Npc0::
	msgbox Unova_TimeCapsule_Text_TimeCapsuleFriendScript, MSGBOX_NPC
	end

Unova_TimeCapsule_EventScript_Npc1::
	msgbox Unova_TimeCapsule_Text_TimeCapsuleFriendScript, MSGBOX_NPC
	end


Unova_TimeCapsule_Text_TimeCapsuleFriendScript::
	.string "Your friend is"
	.string "\nready.$"
