@ Route125_Ex14_14: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 14.14) por dev_scripts/copia_planta_ex.py.

Route125_Ex14_14_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 14.14), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
Route125_Ex14_14_EventScript_ExNpc0::
	msgbox Route125_Ex14_14_Text_ExNpc0, MSGBOX_NPC
	end

Route125_Ex14_14_Text_ExNpc0:
	.string "I have a crush on the man next door.\p"
	.string "I wonder if he would ever ask me on a\n"
	.string "date…$"

