@ ReversalMountain1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_ReversalMountain1F_MapScripts::
	.byte 0

Unova_ReversalMountain1F_EventScript_Npc5::
	msgbox Unova_ReversalMountain1F_Text_SchoolKidFReversalSeenText, MSGBOX_NPC
	end

Unova_ReversalMountain1F_EventScript_Npc6::
	msgbox Unova_ReversalMountain1F_Text_Hiker2ReversalSeenText, MSGBOX_NPC
	end

Unova_ReversalMountain1F_EventScript_Npc7::
	msgbox Unova_ReversalMountain1F_Text_BackpackerFReversalSeenText, MSGBOX_NPC
	end

Unova_ReversalMountain1F_EventScript_Npc8::
	msgbox Unova_ReversalMountain1F_Text_BackpackerMReversalSeenText, MSGBOX_NPC
	end

Unova_ReversalMountain1F_EventScript_Npc9::
	msgbox Unova_ReversalMountain1F_Text_BlackbeltReversalSeenText, MSGBOX_NPC
	end

Unova_ReversalMountain1F_EventScript_Npc10::
	msgbox Unova_ReversalMountain1F_Text_LassReversalSeenText, MSGBOX_NPC
	end

Unova_ReversalMountain1F_EventScript_Npc11::
	msgbox Unova_ReversalMountain1F_Text_ReversalGruntIntroText, MSGBOX_NPC
	end


Unova_ReversalMountain1F_Text_SchoolKidFReversalSeenText::
	.string "Hi there! Look at"
	.string "\nmy awesome POKé-"
	.string "\lMON!$"

Unova_ReversalMountain1F_Text_Hiker2ReversalSeenText::
	.string "My POKéMON dig"
	.string "\ncause they believe"
	.string "\pthey're gonna find"
	.string "\nsomething, and"
	.string "\pthey battle cause"
	.string "\nthey believe"
	.string "\lthey're gonna win!$"

Unova_ReversalMountain1F_Text_BackpackerFReversalSeenText::
	.string "Hello, lo, lo!$"

Unova_ReversalMountain1F_Text_BackpackerMReversalSeenText::
	.string "You sure are"
	.string "\nunlucky to have"
	.string "\prun into someone"
	.string "\nas strong as me!$"

Unova_ReversalMountain1F_Text_BlackbeltReversalSeenText::
	.string "Oh! I haven't seen"
	.string "\nyou before! Would"
	.string "\pyou mind sparring"
	.string "\nwith me?$"

Unova_ReversalMountain1F_Text_LassReversalSeenText::
	.string "Sure, I'll be your"
	.string "\nopponent, right"
	.string "\palongside my"
	.string "\ntrusty MUNNA!$"

Unova_ReversalMountain1F_Text_ReversalGruntIntroText::
	.string "…"
	.string "\pI think this is"
	.string "\nthe way out…?$"
