@ MauvilleCity_Ex10_9: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 10.9) por dev_scripts/copia_planta_ex.py.

MauvilleCity_Ex10_9_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 10.9), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
MauvilleCity_Ex10_9_EventScript_ExNpc0::
	msgbox MauvilleCity_Ex10_9_Text_ExNpc0, MSGBOX_NPC
	end

MauvilleCity_Ex10_9_Text_ExNpc0:
	.string "LEADER WATTSON is great, but he’s a bit\n"
	.string "unreliable.\p"
	.string "Sometimes he’ll leave the gym for days\n"
	.string "just to look for new POKéMON!$"

