Route214_Access_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

Route214_Access_EventScript_Npc1::
	msgbox Route214_Access_Text_Npc1, MSGBOX_NPC
	end

Route214_Access_Text_Npc1:
	.string "Are you going to take Route 214?\nYou're serious, aren't you?\pIt's too badly chewed up, and\nthere's nothing to see there.\pWell, I guess there is that Ruin\nManiac guy you could check out.\pThat guy's been digging his way\nthrough the bedrock all by himself.$"
