@ GiantChasmB1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_GiantChasmB1F_MapScripts::
	.byte 0

Unova_GiantChasmB1F_EventScript_Npc6::
	msgbox Unova_GiantChasmB1F_Text_BackpackerMGiantChasmSeenText, MSGBOX_NPC
	end

Unova_GiantChasmB1F_EventScript_Npc7::
	msgbox Unova_GiantChasmB1F_Text_BackpackerFGiantChasmSeenText, MSGBOX_NPC
	end

Unova_GiantChasmB1F_EventScript_Npc8::
	msgbox Unova_GiantChasmB1F_Text_AceTrainerFGiantChasmSeenText, MSGBOX_NPC
	end

Unova_GiantChasmB1F_EventScript_Npc9::
	msgbox Unova_GiantChasmB1F_Text_AceTrainerMGiantChasmSeenText, MSGBOX_NPC
	end

Unova_GiantChasmB1F_EventScript_Npc10::
	msgbox Unova_GiantChasmB1F_Text_HikerGiantChasmSeenText, MSGBOX_NPC
	end


Unova_GiantChasmB1F_Text_BackpackerMGiantChasmSeenText::
	.string "What's this? A"
	.string "\nvisitor? Ooh, I'm"
	.string "\pso happy to meet"
	.string "\nsomeone else here!"
	.string "\pCould I ask you to"
	.string "\nbe my opponent?$"

Unova_GiantChasmB1F_Text_BackpackerFGiantChasmSeenText::
	.string "I may be a BACK-"
	.string "\nPACKER, but I'm"
	.string "\palso a treasure"
	.string "\nhunter!$"

Unova_GiantChasmB1F_Text_AceTrainerFGiantChasmSeenText::
	.string "Have you ever"
	.string "\nnoticed the stone"
	.string "\lcones in the cave?$"

Unova_GiantChasmB1F_Text_AceTrainerMGiantChasmSeenText::
	.string "Let's train! We'll"
	.string "\nget stronger with"
	.string "\lour POKéMON!$"

Unova_GiantChasmB1F_Text_HikerGiantChasmSeenText::
	.string "Hi-ho!$"
