@ GiantChasmB1F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_GiantChasmB1F_MapScripts::
	.byte 0

Unova_GiantChasmB1F_EventScript_Lider6::
	trainerbattle_single TRAINER_UNOVA_BACKPACKERM_GIANT_CHASM, Unova_GiantChasmB1F_Text_BackpackerMGiantChasmSeenText, Unova_GiantChasmB1F_Text_BackpackerMGiantChasmBeatenText
	end

Unova_GiantChasmB1F_EventScript_Lider7::
	trainerbattle_single TRAINER_UNOVA_BACKPACKERF_GIANT_CHASM, Unova_GiantChasmB1F_Text_BackpackerFGiantChasmSeenText, Unova_GiantChasmB1F_Text_BackpackerFGiantChasmBeatenText
	end

Unova_GiantChasmB1F_EventScript_Lider8::
	trainerbattle_single TRAINER_UNOVA_ACE_TRAINERF_GIANT_CHASM, Unova_GiantChasmB1F_Text_AceTrainerFGiantChasmSeenText, Unova_GiantChasmB1F_Text_AceTrainerFGiantChasmBeatenText
	end

Unova_GiantChasmB1F_EventScript_Lider9::
	trainerbattle_single TRAINER_UNOVA_ACE_TRAINERM_GIANT_CHASM, Unova_GiantChasmB1F_Text_AceTrainerMGiantChasmSeenText, Unova_GiantChasmB1F_Text_AceTrainerMGiantChasmBeatenText
	end

Unova_GiantChasmB1F_EventScript_Lider10::
	trainerbattle_single TRAINER_UNOVA_HIKER_GIANT_CHASM, Unova_GiantChasmB1F_Text_HikerGiantChasmSeenText, Unova_GiantChasmB1F_Text_HikerGiantChasmBeatenText
	end


Unova_GiantChasmB1F_Text_BackpackerMGiantChasmSeenText::
	.string "What's this? A"
	.string "\nvisitor? Ooh, I'm"
	.string "\pso happy to meet"
	.string "\nsomeone else here!"
	.string "\pCould I ask you to"
	.string "\nbe my opponent?$"

Unova_GiantChasmB1F_Text_BackpackerMGiantChasmBeatenText::
	.string "There is a certain"
	.string "\nthrill to battling"
	.string "\lanother trainer!$"

Unova_GiantChasmB1F_Text_BackpackerFGiantChasmSeenText::
	.string "I may be a BACK-"
	.string "\nPACKER, but I'm"
	.string "\palso a treasure"
	.string "\nhunter!$"

Unova_GiantChasmB1F_Text_BackpackerFGiantChasmBeatenText::
	.string "I missed that"
	.string "\nelusive treasure"
	.string "\lcalled victory.$"

Unova_GiantChasmB1F_Text_AceTrainerFGiantChasmSeenText::
	.string "Have you ever"
	.string "\nnoticed the stone"
	.string "\lcones in the cave?$"

Unova_GiantChasmB1F_Text_AceTrainerFGiantChasmBeatenText::
	.string "That marvelous"
	.string "\npower of yours! I"
	.string "\lwasn't aware!$"

Unova_GiantChasmB1F_Text_AceTrainerMGiantChasmSeenText::
	.string "Let's train! We'll"
	.string "\nget stronger with"
	.string "\lour POKéMON!$"

Unova_GiantChasmB1F_Text_AceTrainerMGiantChasmBeatenText::
	.string "Not yet! I still"
	.string "\nhaven't shared my"
	.string "\ltrue strength!$"

Unova_GiantChasmB1F_Text_HikerGiantChasmSeenText::
	.string "Hi-ho!$"

Unova_GiantChasmB1F_Text_HikerGiantChasmBeatenText::
	.string "Hi-ho…$"
