BattleTower_MapScripts::
	.byte 0

BattleTower_EventScript_Npc1::
	msgbox BattleTower_Text_Npc1, MSGBOX_NPC
	end

BattleTower_Text_Npc1:
	.string "Welcome to the Battle Tower!\pI am your guide to the Single\nand Double Battle Rooms.$"

BattleTower_EventScript_Npc2::
	msgbox BattleTower_Text_Npc2, MSGBOX_NPC
	end

BattleTower_Text_Npc2:
	.string "Welcome to the Battle Tower!\pI am your guide to the Multi\nBattle Rooms.$"

BattleTower_EventScript_Npc3::
	msgbox BattleTower_Text_Npc3, MSGBOX_NPC
	end

BattleTower_Text_Npc3:
	.string "Welcome to the Battle Tower!\pI am your guide to the Wi-Fi Battle\nRooms.$"
