@ StriatonLab do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_StriatonLab_MapScripts::
	.byte 0

Unova_StriatonLab_EventScript_Placa0::
	msgbox Unova_StriatonLab_Text_StriatonLabMachineText, MSGBOX_SIGN
	end

Unova_StriatonLab_EventScript_Placa1::
	msgbox Unova_StriatonLab_Text_StriatonLabMachineText, MSGBOX_SIGN
	end

Unova_StriatonLab_EventScript_Placa2::
	msgbox Unova_StriatonLab_Text_StriatonLabMachineText, MSGBOX_SIGN
	end

Unova_StriatonLab_EventScript_Placa3::
	msgbox Unova_StriatonLab_Text_StriatonLabMachineText, MSGBOX_SIGN
	end

Unova_StriatonLab_EventScript_Npc0::
	msgbox Unova_StriatonLab_Text_StriatonLabGiveMetalCoatText, MSGBOX_NPC
	end

Unova_StriatonLab_EventScript_Npc1::
	msgbox Unova_StriatonLab_Text_StriatonLabBlockerText, MSGBOX_NPC
	end


Unova_StriatonLab_Text_StriatonLabMachineText::
	.string "It's a complex"
	.string "\nmachine. Better"
	.string "\lnot touch it!$"

Unova_StriatonLab_Text_StriatonLabGiveMetalCoatText::
	.string "Hi, are you a"
	.string "\nPOKéMON trainer?"
	.string "\pI'm DR.FENNEL!"
	.string "\nI do research to"
	.string "\pdevelop products"
	.string "\nfor POKéMON"
	.string "\ltrainers."
	.string "\pHere, this might"
	.string "\nbe helpful to you.$"

Unova_StriatonLab_Text_StriatonLabBlockerText::
	.string "Sorry, there are"
	.string "\nimportant experi-"
	.string "\lments taking place"
	.string "\lupstairs.$"
