@ AspertiaCity do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_AspertiaCity_MapScripts::
	.byte 0

Unova_AspertiaCity_EventScript_Placa0::
	msgbox Unova_AspertiaCity_Text_AspertiaCitySignText, MSGBOX_SIGN
	end

Unova_AspertiaCity_EventScript_Placa1::
	msgbox Unova_AspertiaCity_Text_AspertiaSubwaySignText, MSGBOX_SIGN
	end

Unova_AspertiaCity_EventScript_Npc1::
	msgbox Unova_AspertiaCity_Text_AspertiaCityBlockerText, MSGBOX_NPC
	end

Unova_AspertiaCity_EventScript_Npc2::
	msgbox Unova_AspertiaCity_Text_AspertiaCityScopeGuyText, MSGBOX_NPC
	end

Unova_AspertiaCity_EventScript_Npc3::
	msgbox Unova_AspertiaCity_Text_AspertiaCityLassText, MSGBOX_NPC
	end

Unova_AspertiaCity_EventScript_Npc4::
	msgbox Unova_AspertiaCity_Text_AspertiaCityTeacherText, MSGBOX_NPC
	end

Unova_AspertiaCity_EventScript_Npc5::
	msgbox Unova_AspertiaCity_Text_AspertiaCityGrampsText, MSGBOX_NPC
	end

Unova_AspertiaCity_EventScript_Npc6::
	msgbox Unova_AspertiaCity_Text_AspertiaCityYoungsterText, MSGBOX_NPC
	end


Unova_AspertiaCity_Text_AspertiaCitySignText::
	.string "ASPERTIA CITY"
	.string "\pA city that"
	.string "\nreaches for the"
	.string "\lsky.$"

Unova_AspertiaCity_Text_AspertiaSubwaySignText::
	.string "ASPERTIA CITY"
	.string "\nSUBWAY station.$"

Unova_AspertiaCity_Text_AspertiaCityBlockerText::
	.string "Sorry, the GYM"
	.string "\nLEADER isn't here"
	.string "\lright now."
	.string "\pThe GYM's closed"
	.string "\nuntil he comes"
	.string "\lback.$"

Unova_AspertiaCity_Text_AspertiaCityScopeGuyText::
	.string "Boy, I sure do"
	.string "\nlove the view off"
	.string "\lthis platform.$"

Unova_AspertiaCity_Text_AspertiaCityLassText::
	.string "There's a man here"
	.string "\ncalled the MOVE"
	.string "\lDELETER."
	.string "\pHe can make your"
	.string "\nPOKéMON forget any"
	.string "\lmove, even an HM.$"

Unova_AspertiaCity_Text_AspertiaCityTeacherText::
	.string "I'm so glad they"
	.string "\nbuilt the SUBWAY"
	.string "\pstation here in"
	.string "\ntown. It's made"
	.string "\pshopping in"
	.string "\nNIMBASA so much"
	.string "\leasier!$"

Unova_AspertiaCity_Text_AspertiaCityGrampsText::
	.string "You know, I used"
	.string "\nto be quite the"
	.string "\ptrainer back in"
	.string "\nmy day. You young"
	.string "\luns could learn a"
	.string "\pthing or two from"
	.string "\nus elders!$"

Unova_AspertiaCity_Text_AspertiaCityYoungsterText::
	.string "You should always"
	.string "\nbe kind to your"
	.string "\lPOKéMON. Some"
	.string "\pPOKéMON can even"
	.string "\nevolve if you're"
	.string "\lkind to them."
	.string "\pAt least, that's"
	.string "\nwhat I've heard.$"
