JubilifeTv2FGallery_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

JubilifeTv2FGallery_EventScript_Npc1::
	msgbox JubilifeTv2FGallery_Text_Npc1, MSGBOX_NPC
	end

JubilifeTv2FGallery_Text_Npc1:
	.string "They display photos from Trainers\nyou been mixin' records with, right?\pI hope you collect yerself some good\nphotos of dressed-up Pokémon!$"

JubilifeTv2FGallery_EventScript_Npc2::
	msgbox JubilifeTv2FGallery_Text_Npc2, MSGBOX_NPC
	end

JubilifeTv2FGallery_Text_Npc2:
	.string "Someone gave me a new Backdrop when I\nwent to the Global Terminal.$"
