@ DesertResort do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_DesertResort_MapScripts::
	.byte 0

Unova_DesertResort_EventScript_Npc8::
	msgbox Unova_DesertResort_Text_RoughneckDesertSeenText, MSGBOX_NPC
	end

Unova_DesertResort_EventScript_Npc9::
	msgbox Unova_DesertResort_Text_HexManiacDesertSeenText, MSGBOX_NPC
	end

Unova_DesertResort_EventScript_Npc10::
	msgbox Unova_DesertResort_Text_YoungsterDesertSeenText, MSGBOX_NPC
	end

Unova_DesertResort_EventScript_Npc11::
	msgbox Unova_DesertResort_Text_BackpackerMDesertSeenText, MSGBOX_NPC
	end

Unova_DesertResort_EventScript_Npc12::
	msgbox Unova_DesertResort_Text_BackpackerFDesertSeenText, MSGBOX_NPC
	end

Unova_DesertResort_EventScript_Npc13::
	msgbox Unova_DesertResort_Text_PkmnRangerMDesertSeenText, MSGBOX_NPC
	end

Unova_DesertResort_EventScript_Npc14::
	msgbox Unova_DesertResort_Text_PkmnRangerFDesertSeenText, MSGBOX_NPC
	end

Unova_DesertResort_EventScript_Npc15::
	msgbox Unova_DesertResort_Text_LassDesertSeenText, MSGBOX_NPC
	end

Unova_DesertResort_EventScript_Npc16::
	msgbox Unova_DesertResort_Text_DesertNurseIntroText, MSGBOX_NPC
	end

Unova_DesertResort_EventScript_Npc17::
	msgbox Unova_DesertResort_Text_DesertSandManGiveText, MSGBOX_NPC
	end


Unova_DesertResort_Text_RoughneckDesertSeenText::
	.string "My shiny head is a"
	.string "\nreflection of my"
	.string "\lfighting spirit!$"

Unova_DesertResort_Text_HexManiacDesertSeenText::
	.string "Hm… You're strong,"
	.string "\naren't you?"
	.string "\pIt's tough when"
	.string "\nyou know that"
	.string "\pbefore you even"
	.string "\nstart the fight.$"

Unova_DesertResort_Text_YoungsterDesertSeenText::
	.string "Starting a day"
	.string "\nago, I decided to"
	.string "\lbecome a bad dude!$"

Unova_DesertResort_Text_BackpackerMDesertSeenText::
	.string "If you want to"
	.string "\nknow what I've got"
	.string "\pin my backpack,"
	.string "\nwhy don't you try"
	.string "\lto beat me!$"

Unova_DesertResort_Text_BackpackerFDesertSeenText::
	.string "A desert is like"
	.string "\none giant sandbox,"
	.string "\pright? So come on,"
	.string "\nlet's let our"
	.string "\lPOKéMON play!$"

Unova_DesertResort_Text_PkmnRangerMDesertSeenText::
	.string "I will show you"
	.string "\nthe harshness of"
	.string "\pthe desert through"
	.string "\na battle!$"

Unova_DesertResort_Text_PkmnRangerFDesertSeenText::
	.string "A scorching"
	.string "\ndesert! A passion"
	.string "\pfor adventure! And"
	.string "\na heated battle!$"

Unova_DesertResort_Text_LassDesertSeenText::
	.string "No matter how"
	.string "\ndesperately I try"
	.string "\pto scoop up the"
	.string "\nsand, it flows"
	.string "\lthrough my hands."
	.string "\pIt's kind of sad"
	.string "\nsomehow…$"

Unova_DesertResort_Text_DesertNurseIntroText::
	.string "I'm a nurse, but"
	.string "\nI'm also a POKé-"
	.string "\lMON trainer."
	.string "\pIf you can defeat"
	.string "\nme in a battle,"
	.string "\lI'll heal your"
	.string "\lPOKéMON.$"

Unova_DesertResort_Text_DesertSandManGiveText::
	.string "You're a POKéMON"
	.string "\ntrainer, right?"
	.string "\pHere, this may"
	.string "\nhelp you.$"
