RotomsRoom_MapScripts::
	.byte 0

RotomsRoom_EventScript_Placa1::
	msgbox RotomsRoom_Text_Placa1, MSGBOX_SIGN
	end

RotomsRoom_Text_Placa1:
	.string "Oh? ROTOM appears as if it wants to\nrevert to its original form.\pWould you like to recall it from\nthe motor?$"

RotomsRoom_EventScript_Placa2::
	msgbox RotomsRoom_Text_Placa2, MSGBOX_SIGN
	end

RotomsRoom_Text_Placa2:
	.string "Oh? ROTOM appears as if it wants to\nrevert to its original form.\pWould you like to recall it from\nthe motor?$"

RotomsRoom_EventScript_Placa3::
	msgbox RotomsRoom_Text_Placa3, MSGBOX_SIGN
	end

RotomsRoom_Text_Placa3:
	.string "Oh? ROTOM appears as if it wants to\nrevert to its original form.\pWould you like to recall it from\nthe motor?$"

RotomsRoom_EventScript_Placa4::
	msgbox RotomsRoom_Text_Placa4, MSGBOX_SIGN
	end

RotomsRoom_Text_Placa4:
	.string "Oh? ROTOM appears as if it wants to\nrevert to its original form.\pWould you like to recall it from\nthe motor?$"

RotomsRoom_EventScript_Placa5::
	msgbox RotomsRoom_Text_Placa5, MSGBOX_SIGN
	end

RotomsRoom_Text_Placa5:
	.string "Oh? ROTOM appears as if it wants to\nrevert to its original form.\pWould you like to recall it from\nthe motor?$"
