@ Rt5NimbasaGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt5NimbasaGate_MapScripts::
	.byte 0

Unova_Rt5NimbasaGate_EventScript_Npc0::
	msgbox Unova_Rt5NimbasaGate_Text_Rt5NimbasaGateOfficerText, MSGBOX_NPC
	end


Unova_Rt5NimbasaGate_Text_Rt5NimbasaGateOfficerText::
	.string "There are athletes"
	.string "\nand performers"
	.string "\pthat gather on"
	.string "\nROUTE 5.$"
