@ FloccesyRanchHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_FloccesyRanchHouse_MapScripts::
	.byte 0

Unova_FloccesyRanchHouse_EventScript_Npc0::
	msgbox Unova_FloccesyRanchHouse_Text_FarmerMText_BuyMilk, MSGBOX_NPC
	end

Unova_FloccesyRanchHouse_EventScript_Npc1::
	msgbox Unova_FloccesyRanchHouse_Text_FarmerFText, MSGBOX_NPC
	end


Unova_FloccesyRanchHouse_Text_FarmerMText_BuyMilk::
	.string "How'd you like my"
	.string "\nMOOMOO MILK?"
	.string "\pIt's my pride and"
	.string "\njoy, there."
	.string "\pGive it to POKéMON"
	.string "\nto restore HP!"
	.string "\pI'll give it to ya"
	.string "\nfer just ¥500."
	.string "\pYou want jus' one,"
	.string "\nor a case o' six?$"

Unova_FloccesyRanchHouse_Text_FarmerFText::
	.string "Our milk goes out"
	.string "\nall over UNOVA.$"
