@ PlayersNeighborsHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_PlayersNeighborsHouse_MapScripts::
	.byte 0

Unova_PlayersNeighborsHouse_EventScript_Npc0::
	msgbox Unova_PlayersNeighborsHouse_Text_PlayersNeighborsDaughter2Text, MSGBOX_NPC
	end

Unova_PlayersNeighborsHouse_EventScript_Npc1::
	msgbox Unova_PlayersNeighborsHouse_Text_PlayersNeighborText, MSGBOX_NPC
	end


Unova_PlayersNeighborsHouse_Text_PlayersNeighborsDaughter2Text::
	.string "Hey, {PLAYER}!"
	.string "\nAre you going on a"
	.string "\lPOKéMON journey?"
	.string "\pYou're so lucky!"
	.string "\pHey, hey! If your"
	.string "\nmom marries my"
	.string "\pmom, then I'll be"
	.string "\nyour little"
	.string "\lsister!"
	.string "\pThen you'll have"
	.string "\nto teach me to be"
	.string "\la POKéMON trainer!$"

Unova_PlayersNeighborsHouse_Text_PlayersNeighborText::
	.string "Oh, hello"
	.string "\n{PLAYER}."
	.string "\pIt's been so nice"
	.string "\nsince you and your"
	.string "\pmom moved out here"
	.string "\nto HUMILAU CITY."
	.string "\pShe really is a"
	.string "\nlovely woman!"
	.string "\pI think I'll take"
	.string "\nher out on a trip"
	.string "\pto the beach for"
	.string "\nour next date."
	.string "\pYou remember to"
	.string "\ncall your mother"
	.string "\lsometimes!$"
