JubilifeCity_Flat3_F2_MapScripts::
	.byte 0

JubilifeCity_Flat3_F2_EventScript_AceTrainerM::
	msgbox JubilifeCity_Flat3_F2_Text_AceTrainerM, MSGBOX_NPC
	end

JubilifeCity_Flat3_F2_EventScript_Beauty::
	msgbox JubilifeCity_Flat3_F2_Text_Beauty, MSGBOX_NPC
	end

JubilifeCity_Flat3_F2_EventScript_Lass::
	msgbox JubilifeCity_Flat3_F2_Text_Lass, MSGBOX_NPC
	end

JubilifeCity_Flat3_F2_Text_AceTrainerM:
	.string "I keep my POKéMON's training\n"
	.string "log pinned right there on the\l"
	.string "wall.$"

JubilifeCity_Flat3_F2_Text_Beauty:
	.string "A little perfume, a little\n"
	.string "polish, and my POKéMON and I\l"
	.string "are ready for the day.$"

JubilifeCity_Flat3_F2_Text_Lass:
	.string "I love this apartment.\p"
	.string "Small, but it's mine.$"
