JubilifeCity_Flat3_F2_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

JubilifeCity_Flat3_F2_EventScript_Npc1::
	msgbox JubilifeCity_Flat3_F2_Text_Npc1, MSGBOX_NPC
	end

JubilifeCity_Flat3_F2_Text_Npc1:
	.string "Wi: We come from faraway land.\nI come see the Pokémon I trade.\pI worry if it growing properly.$"

JubilifeCity_Flat3_F2_EventScript_Npc2::
	msgbox JubilifeCity_Flat3_F2_Text_Npc2, MSGBOX_NPC
	end

JubilifeCity_Flat3_F2_Text_Npc2:
	.string "Fi: I like look at Pokémon I get\nfrom friend in trade.\pIt make me remember my friend!$"

JubilifeCity_Flat3_F2_EventScript_Npc3::
	msgbox JubilifeCity_Flat3_F2_Text_Npc3, MSGBOX_NPC
	end

JubilifeCity_Flat3_F2_Text_Npc3:
	.string "You can trade Pokémon with people\naround the world on Nintendo WFC...\pJust hearing that gets my heart\nracing. Such exciting times!$"

JubilifeCity_Flat3_F2_EventScript_Npc4::
	msgbox JubilifeCity_Flat3_F2_Text_Npc4, MSGBOX_NPC
	end

JubilifeCity_Flat3_F2_Text_Npc4:
	.string "When you connect with people on\nNintendo WFC, it's hard to\ptell if the world's big or small.$"
