@ DewfordTown_Ex3_8: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 3.8) por dev_scripts/copia_planta_ex.py.

DewfordTown_Ex3_8_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 3.8), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
DewfordTown_Ex3_8_EventScript_ExNpc0::
	msgbox DewfordTown_Ex3_8_Text_ExNpc0, MSGBOX_NPC
	end

DewfordTown_Ex3_8_Text_ExNpc0:
	.string "DEWFORD TOWN was founded many years\n"
	.string "ago by a group of fishermen.\p"
	.string "My husband was one of them, but most of\n"
	.string "my generation is gone now.\p"
	.string "It’s good to see young people moving in\n"
	.string "to keep the town alive!$"

DewfordTown_Ex3_8_EventScript_ExNpc1::
	msgbox DewfordTown_Ex3_8_Text_ExNpc1, MSGBOX_NPC
	end

DewfordTown_Ex3_8_Text_ExNpc1:
	.string "I took on LEADER BRAWLY but he wiped\n"
	.string "the floor with me.\p"
	.string "He’s always surfing so I thought he\n"
	.string "used WATER TYPE POKéMON, but he used\l"
	.string "FIGHTING TYPES!$"

