@ Rt5BridgeGate do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Rt5BridgeGate_MapScripts::
	.byte 0

Unova_Rt5BridgeGate_EventScript_Npc0::
	msgbox Unova_Rt5BridgeGate_Text_Rt5BridgeGateOfficerText, MSGBOX_NPC
	end


Unova_Rt5BridgeGate_Text_Rt5BridgeGateOfficerText::
	.string "The BRIDGE has"
	.string "\nnow been lowered."
	.string "\pIt will take you"
	.string "\nto DRIFTVEIL CITY.$"
