@ LentimasHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_LentimasHouse_MapScripts::
	.byte 0

Unova_LentimasHouse_EventScript_Npc0::
	msgbox Unova_LentimasHouse_Text_LentimasHouseGrannyText, MSGBOX_NPC
	end


Unova_LentimasHouse_Text_LentimasHouseGrannyText::
	.string "The spirits are"
	.string "\nstrong in this"
	.string "\lplace…"
	.string "\pBeware the old"
	.string "\nhouse just outside"
	.string "\lof town, there"
	.string "\lare ghosts…$"
