@ ColresssRoom do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_ColresssRoom_MapScripts::
	.byte 0

Unova_ColresssRoom_EventScript_Lider0::
	trainerbattle_single TRAINER_UNOVA_E4_COLRESS, Unova_ColresssRoom_Text_EliteFourColressIntroText, Unova_ColresssRoom_Text_EliteFourColressWinText
	end


Unova_ColresssRoom_Text_EliteFourColressIntroText::
	.string "Greetings. I am"
	.string "\na scientist. My"
	.string "\lname is COLRESS."
	.string "\pAs a member of the"
	.string "\nELITE FOUR, I am"
	.string "\pable to carry out"
	.string "\nmy research on the"
	.string "\pmost powerful"
	.string "\ntrainers across"
	.string "\lthe region."
	.string "\pThe theme of my"
	.string "\nresearch is bring-"
	.string "\ling out the power"
	.string "\lof POKéMON."
	.string "\pIs it possible to"
	.string "\nbring out their"
	.string "\pmaximum power"
	.string "\nthrough the bond"
	.string "\pthey share with"
	.string "\ntheir trainers?"
	.string "\pOr is there some"
	.string "\nother different"
	.string "\pmethod? I'd like"
	.string "\nto test my theory"
	.string "\lby battling you."
	.string "\pDo you find this"
	.string "\nacceptable?$"

Unova_ColresssRoom_Text_EliteFourColressWinText::
	.string "Just as I"
	.string "\nexpected! Your"
	.string "\pPOKéMON must be"
	.string "\nhappy to be by"
	.string "\lyour side!"
	.string "\pYou bring out the"
	.string "\nbest in their"
	.string "\lpower!$"
