PastoriaCityNorthHouse_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

PastoriaCityNorthHouse_EventScript_Npc1::
	msgbox PastoriaCityNorthHouse_Text_Npc1, MSGBOX_NPC
	end

PastoriaCityNorthHouse_Text_Npc1:
	.string "In the Great Marsh, Quick Trams on\nrails are used for transportation.\pThey prevent damage to the Great\nMarsh's ecosystem.$"

PastoriaCityNorthHouse_EventScript_Npc2::
	msgbox PastoriaCityNorthHouse_Text_Npc2, MSGBOX_NPC
	end

PastoriaCityNorthHouse_Text_Npc2:
	.string "PSYDUCK: Gwah?!$"

PastoriaCityNorthHouse_EventScript_Npc3::
	msgbox PastoriaCityNorthHouse_Text_Npc3, MSGBOX_NPC
	end

PastoriaCityNorthHouse_Text_Npc3:
	.string "Though the name says 'Quick,' their\nmovements are anything but!\pThey're the Quick Trams that traverse\nthe Great Marsh.$"
