@ MarineTube do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_MarineTube_MapScripts::
	.byte 0

Unova_MarineTube_EventScript_Npc0::
	msgbox Unova_MarineTube_Text_MarineTubeCooltrainerFText, MSGBOX_NPC
	end

Unova_MarineTube_EventScript_Npc1::
	msgbox Unova_MarineTube_Text_MarineTubeCooltrainerMText, MSGBOX_NPC
	end

Unova_MarineTube_EventScript_Npc2::
	msgbox Unova_MarineTube_Text_MarineTubeLassText, MSGBOX_NPC
	end

Unova_MarineTube_EventScript_Npc3::
	msgbox Unova_MarineTube_Text_MarineTubePokefanMText, MSGBOX_NPC
	end

Unova_MarineTube_EventScript_Npc4::
	msgbox Unova_MarineTube_Text_NurseryAideMarineTubeSeenText, MSGBOX_NPC
	end

Unova_MarineTube_EventScript_Npc5::
	msgbox Unova_MarineTube_Text_TwinsMarineTubeSeenText, MSGBOX_NPC
	end

Unova_MarineTube_EventScript_Npc6::
	msgbox Unova_MarineTube_Text_TwinsMarineTubeSeenText, MSGBOX_NPC
	end

Unova_MarineTube_EventScript_Npc7::
	msgbox Unova_MarineTube_Text_PreschoolerMMarineTubeSeenText, MSGBOX_NPC
	end

Unova_MarineTube_EventScript_Npc8::
	msgbox Unova_MarineTube_Text_PreschoolerFMarineTubeSeenText, MSGBOX_NPC
	end


Unova_MarineTube_Text_MarineTubeCooltrainerFText::
	.string "Wow, look at all"
	.string "\nof the POKéMON"
	.string "\lunderwater!$"

Unova_MarineTube_Text_MarineTubeCooltrainerMText::
	.string "The MARINE TUBE"
	.string "\nis a great date"
	.string "\ldestination!$"

Unova_MarineTube_Text_MarineTubeLassText::
	.string "This tube serves"
	.string "\nas a shortcut to"
	.string "\pHUMILAU CITY, but"
	.string "\nthere are so many"
	.string "\ptourists that it's"
	.string "\nhard to get"
	.string "\lthrough!$"

Unova_MarineTube_Text_MarineTubePokefanMText::
	.string "Some people drop"
	.string "\ntheir valuables"
	.string "\pon the floor since"
	.string "\nit's so dark.$"

Unova_MarineTube_Text_NurseryAideMarineTubeSeenText::
	.string "You… are a rather"
	.string "\nadult looking kid…"
	.string "\pA kiddish adult…"
	.string "\nOh, jeez! I'll"
	.string "\pjust find out when"
	.string "\nwe battle!$"

Unova_MarineTube_Text_TwinsMarineTubeSeenText::
	.string "It's so fun to"
	.string "\nbattle along with"
	.string "\lmy sister!$"

Unova_MarineTube_Text_PreschoolerMMarineTubeSeenText::
	.string "Teacher?"
	.string "\pOh, you're not"
	.string "\nTeacher! You're a"
	.string "\ltrainer!$"

Unova_MarineTube_Text_PreschoolerFMarineTubeSeenText::
	.string "Roar!"
	.string "\pI'm a POKéMON!$"
