CanalaveLibrary3F_MapScripts::
	.byte 0

CanalaveLibrary3F_EventScript_Npc1::
	msgbox CanalaveLibrary3F_Text_Npc1, MSGBOX_NPC
	end

CanalaveLibrary3F_Text_Npc1:
	.string "Every book contains someone's\nmemories of various places and times.\pLibraries aren't just buildings where\nbooks are kept, you know.\pThey're where different places\nand times are gathered together.$"

CanalaveLibrary3F_EventScript_Npc2::
	msgbox CanalaveLibrary3F_Text_Npc2, MSGBOX_NPC
	end

CanalaveLibrary3F_Text_Npc2:
	.string "Someone's always checked out the\nbook I want to read...$"

CanalaveLibrary3F_EventScript_Placa1::
	msgbox CanalaveLibrary3F_Text_Placa1, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa1:
	.string "This book is titled 'Sinnoh\nMyth.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa2::
	msgbox CanalaveLibrary3F_Text_Placa2, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa2:
	.string "This book is titled 'Sinnoh\nMyth.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa3::
	msgbox CanalaveLibrary3F_Text_Placa3, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa3:
	.string "This book is titled 'Sinnoh Region's\nMythology.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa4::
	msgbox CanalaveLibrary3F_Text_Placa4, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa4:
	.string "This book is titled 'Sinnoh Region's\nMythology.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa5::
	msgbox CanalaveLibrary3F_Text_Placa5, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa5:
	.string "This book is titled 'Sinnoh's\nMyth.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa6::
	msgbox CanalaveLibrary3F_Text_Placa6, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa6:
	.string "This book is titled 'Sinnoh's\nMyth.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa7::
	msgbox CanalaveLibrary3F_Text_Placa7, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa7:
	.string "This book is titled 'Veilstone's\nMyth.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa8::
	msgbox CanalaveLibrary3F_Text_Placa8, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa8:
	.string "This book is titled 'Veilstone's\nMyth.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa9::
	msgbox CanalaveLibrary3F_Text_Placa9, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa9:
	.string "This ancient book is titled 'The\nOriginal Story.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa10::
	msgbox CanalaveLibrary3F_Text_Placa10, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa10:
	.string "This ancient book is titled 'The\nOriginal Story.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa11::
	msgbox CanalaveLibrary3F_Text_Placa11, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa11:
	.string "This book is titled 'A Horrific\nMyth.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa12::
	msgbox CanalaveLibrary3F_Text_Placa12, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa12:
	.string "This book is titled 'A Horrific\nMyth.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa13::
	msgbox CanalaveLibrary3F_Text_Placa13, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa13:
	.string "This book is titled 'Sinnoh Folk\nStories.'$"

CanalaveLibrary3F_EventScript_Placa14::
	msgbox CanalaveLibrary3F_Text_Placa14, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa14:
	.string "This book is titled 'Sinnoh Folk\nStories.'$"

CanalaveLibrary3F_EventScript_Placa15::
	msgbox CanalaveLibrary3F_Text_Placa15, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa15:
	.string "This ancient book is titled 'The\nOriginal Story.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa16::
	msgbox CanalaveLibrary3F_Text_Placa16, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa16:
	.string "This ancient book is titled 'The\nOriginal Story.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa17::
	msgbox CanalaveLibrary3F_Text_Placa17, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa17:
	.string "This ancient book is titled 'The\nOriginal Story.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa18::
	msgbox CanalaveLibrary3F_Text_Placa18, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa18:
	.string "This book is titled 'A Horrific\nMyth.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa19::
	msgbox CanalaveLibrary3F_Text_Placa19, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa19:
	.string "This book is titled 'A Horrific\nMyth.' Want to read it?$"

CanalaveLibrary3F_EventScript_Placa20::
	msgbox CanalaveLibrary3F_Text_Placa20, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa20:
	.string "This book is titled 'Sinnoh Folk\nStories.'$"

CanalaveLibrary3F_EventScript_Placa21::
	msgbox CanalaveLibrary3F_Text_Placa21, MSGBOX_SIGN
	end

CanalaveLibrary3F_Text_Placa21:
	.string "This book is titled 'Sinnoh Folk\nStories.'$"
