@ OpelucidBlackbeltHouse do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_OpelucidBlackbeltHouse_MapScripts::
	.byte 0

Unova_OpelucidBlackbeltHouse_EventScript_Npc0::
	msgbox Unova_OpelucidBlackbeltHouse_Text_OpelucidBlackbeltHouseGiveBeltText, MSGBOX_NPC
	end


Unova_OpelucidBlackbeltHouse_Text_OpelucidBlackbeltHouseGiveBeltText::
	.string "Hm, I can see that"
	.string "\nyour training has"
	.string "\lmade you strong."
	.string "\pBut you are not"
	.string "\nyet a master!"
	.string "\pGive your POKéMON"
	.string "\nthis belt to hone"
	.string "\lyour training.$"
