HearthomeCityNorthwestHouse_MapScripts::
	.byte 0

HearthomeCityNorthwestHouse_EventScript_Npc1::
	msgbox HearthomeCityNorthwestHouse_Text_Npc1, MSGBOX_NPC
	end

HearthomeCityNorthwestHouse_Text_Npc1:
	.string "Hiya!\nOh, you're a Trainer!\pThat means you're using Pokémon Boxes!\nI love meeting end users!\pOh, what's up?\nWhy that astonished look?\pOh, right, sorry!\nThere I go running my mouth again!\pMy name's Bebe!\pYou know the PC Pokémon Boxes?\nI'm the system administrator!\pI know this is out of the blue, but do\nyou want a Pokémon named EEVEE?$"
