@ FallarborTown_Ex5_12: planta copiada do Pokémon Emerald EX v1.0.4 (mapa 5.12) por dev_scripts/copia_planta_ex.py.

FallarborTown_Ex5_12_MapScripts::
	.byte 0

@ Eventos novos do Pokémon Emerald EX (mapa 5.12), reescritos a partir do texto da ROM
@ por dev_scripts/copia_planta_ex.py.
FallarborTown_Ex5_12_EventScript_ExNpc0::
	msgbox FallarborTown_Ex5_12_Text_ExNpc0, MSGBOX_NPC
	end

FallarborTown_Ex5_12_Text_ExNpc0:
	.string "Some POKéMON need certain items to\n"
	.string "EVOLVE.\p"
	.string "I wounder how that came about?$"

