@ TubelineBridge do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_TubelineBridge_MapScripts::
	.byte 0

Unova_TubelineBridge_EventScript_Npc0::
	msgbox Unova_TubelineBridge_Text_TubelineBridgeTeacherText, MSGBOX_NPC
	end

Unova_TubelineBridge_EventScript_Npc1::
	msgbox Unova_TubelineBridge_Text_TubelineBridgeSocialiteText, MSGBOX_NPC
	end


Unova_TubelineBridge_Text_TubelineBridgeTeacherText::
	.string "It's so loud in"
	.string "\nhere! If I were a"
	.string "\pPOKéMON, I'd want"
	.string "\nto have SOUNDPROOF"
	.string "\las my ability!$"

Unova_TubelineBridge_Text_TubelineBridgeSocialiteText::
	.string "This TUBELINE"
	.string "\nBRIDGE was No. 1"
	.string "\pin the bridge"
	.string "\nrankings in UNOVA."
	.string "\pThat means it's"
	.string "\nthe sturdiest!$"
