@ DragonspiralTower3F do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_DragonspiralTower3F_MapScripts::
	.byte 0

Unova_DragonspiralTower3F_EventScript_Lider3::
	trainerbattle_single TRAINER_UNOVA_RYOKU2, Unova_DragonspiralTower3F_Text_DragonspiralTowerRyokuSeenText, Unova_DragonspiralTower3F_Text_DragonspiralTowerRyokuBeatenText
	end


Unova_DragonspiralTower3F_Text_DragonspiralTowerRyokuSeenText::
	.string "I… I will once"
	.string "\nagain test how"
	.string "\pmuch power you"
	.string "\nhave. I will see"
	.string "\pif you can stand"
	.string "\nup to TEAM PLASMA!$"

Unova_DragonspiralTower3F_Text_DragonspiralTowerRyokuBeatenText::
	.string "I- I can't…$"
