@ LentimasOutskirts do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_LentimasOutskirts_MapScripts::
	.byte 0

Unova_LentimasOutskirts_EventScript_Placa0::
	msgbox Unova_LentimasOutskirts_Text_LentimasReversalSignText, MSGBOX_SIGN
	end

Unova_LentimasOutskirts_EventScript_Placa1::
	msgbox Unova_LentimasOutskirts_Text_LentimasLostlornSignText, MSGBOX_SIGN
	end

Unova_LentimasOutskirts_EventScript_Npc5::
	msgbox Unova_LentimasOutskirts_Text_SchoolKidMOutskirtsSeenText, MSGBOX_NPC
	end

Unova_LentimasOutskirts_EventScript_Npc6::
	msgbox Unova_LentimasOutskirts_Text_CyclistMOutskirtsSeenText, MSGBOX_NPC
	end

Unova_LentimasOutskirts_EventScript_Npc7::
	msgbox Unova_LentimasOutskirts_Text_CyclistFOutskirtsSeenText, MSGBOX_NPC
	end

Unova_LentimasOutskirts_EventScript_Npc8::
	msgbox Unova_LentimasOutskirts_Text_YoungsterOutskirtsSeenText, MSGBOX_NPC
	end

Unova_LentimasOutskirts_EventScript_Npc9::
	msgbox Unova_LentimasOutskirts_Text_PkmnRangerMOutskirtsSeenText, MSGBOX_NPC
	end

Unova_LentimasOutskirts_EventScript_Npc10::
	msgbox Unova_LentimasOutskirts_Text_PkmnRangerFOutskirtsSeenText, MSGBOX_NPC
	end

Unova_LentimasOutskirts_EventScript_Npc11::
	msgbox Unova_LentimasOutskirts_Text_OutskirtsDoctorIntroText, MSGBOX_NPC
	end


Unova_LentimasOutskirts_Text_LentimasReversalSignText::
	.string "REVERSAL MOUNTAIN."
	.string "\pEnter at your"
	.string "\nown risk!$"

Unova_LentimasOutskirts_Text_LentimasLostlornSignText::
	.string "South to"
	.string "\nLOSTLORN FOREST.$"

Unova_LentimasOutskirts_Text_SchoolKidMOutskirtsSeenText::
	.string "I've been training"
	.string "\nto take on the"
	.string "\pGYM. I won't give"
	.string "\nup easily!$"

Unova_LentimasOutskirts_Text_CyclistMOutskirtsSeenText::
	.string "Yahooo! If you"
	.string "\ncall, I'll come"
	.string "\lright away!$"

Unova_LentimasOutskirts_Text_CyclistFOutskirtsSeenText::
	.string "Shift gears and"
	.string "\nBob's your uncle!"
	.string "\pYou'll be going"
	.string "\nfull speed in no"
	.string "\ltime!$"

Unova_LentimasOutskirts_Text_YoungsterOutskirtsSeenText::
	.string "I'm going to over-"
	.string "\nwhelm you with my"
	.string "\lspeed!$"

Unova_LentimasOutskirts_Text_PkmnRangerMOutskirtsSeenText::
	.string "I'm wandering the"
	.string "\nworld trying to"
	.string "\pfind a place where"
	.string "\nI belong…"
	.string "\pHow about you?$"

Unova_LentimasOutskirts_Text_PkmnRangerFOutskirtsSeenText::
	.string "Every day is the"
	.string "\nsame. I get bored"
	.string "\pwhen things don't"
	.string "\nchange, so I don't"
	.string "\lmind battling you!$"

Unova_LentimasOutskirts_Text_OutskirtsDoctorIntroText::
	.string "I'm a doctor, but"
	.string "\nI'm also a POKé-"
	.string "\lMON trainer."
	.string "\pIf you can defeat"
	.string "\nme in a battle,"
	.string "\lI'll heal your"
	.string "\lPOKéMON.$"
