@ RelicPassageFront do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_RelicPassageFront_MapScripts::
	.byte 0

Unova_RelicPassageFront_EventScript_Npc3::
	msgbox Unova_RelicPassageFront_Text_RelicPassageNurseIntroText, MSGBOX_NPC
	end

Unova_RelicPassageFront_EventScript_Npc4::
	msgbox Unova_RelicPassageFront_Text_PsychicMRelicPassageSeenText, MSGBOX_NPC
	end

Unova_RelicPassageFront_EventScript_Npc5::
	msgbox Unova_RelicPassageFront_Text_Hiker1RelicPassageSeenText, MSGBOX_NPC
	end

Unova_RelicPassageFront_EventScript_Npc6::
	msgbox Unova_RelicPassageFront_Text_Hiker2RelicPassageSeenText, MSGBOX_NPC
	end

Unova_RelicPassageFront_EventScript_Npc7::
	msgbox Unova_RelicPassageFront_Text_BackpackerFRelicPassageSeenText, MSGBOX_NPC
	end


Unova_RelicPassageFront_Text_RelicPassageNurseIntroText::
	.string "I'm a nurse, but"
	.string "\nI'm also a POKé-"
	.string "\lMON trainer."
	.string "\pIf you can defeat"
	.string "\nme in a battle,"
	.string "\lI'll heal your"
	.string "\lPOKéMON.$"

Unova_RelicPassageFront_Text_PsychicMRelicPassageSeenText::
	.string "It's coming… It's"
	.string "\ncoming! The"
	.string "\pancient spiritual"
	.string "\npower!$"

Unova_RelicPassageFront_Text_Hiker1RelicPassageSeenText::
	.string "Hold up! Did you"
	.string "\nknow this path was"
	.string "\psupposedly made"
	.string "\nages and ages ago?$"

Unova_RelicPassageFront_Text_Hiker2RelicPassageSeenText::
	.string "Just because you"
	.string "\nwork hard doesn't"
	.string "\pmean you're gonna"
	.string "\nget what you want!"
	.string "\pBut if you don't"
	.string "\nwork hard, there"
	.string "\pare many things"
	.string "\nyou can't do!$"

Unova_RelicPassageFront_Text_BackpackerFRelicPassageSeenText::
	.string "My path and yours…"
	.string "\nThey cross here"
	.string "\land now…$"
