PastoriaCityNortheastHouse_MapScripts::
	.byte 0

PastoriaCityNortheastHouse_EventScript_Npc1::
	msgbox PastoriaCityNortheastHouse_Text_Npc1, MSGBOX_NPC
	end

PastoriaCityNortheastHouse_Text_Npc1:
	.string "I'm out of scarves to give you!\nI'm out of things to say, too!$"

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

PastoriaCityNortheastHouse_EventScript_Npc1::
	msgbox PastoriaCityNortheastHouse_Text_Npc1, MSGBOX_NPC
	end

PastoriaCityNortheastHouse_Text_Npc1:
	.string "My brother's girlfriend is the\nMassage Girl in Veilstone City.\pThey stay in touch by having Pokémon\nhold Mail for each other.$"
