@ ElesasRoom do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_ElesasRoom_MapScripts::
	.byte 0

Unova_ElesasRoom_EventScript_Lider0::
	trainerbattle_single TRAINER_UNOVA_E4_ELESA, Unova_ElesasRoom_Text_EliteFourElesaIntroText, Unova_ElesasRoom_Text_EliteFourElesaWinText
	end


Unova_ElesasRoom_Text_EliteFourElesaIntroText::
	.string "Welcome to the"
	.string "\nmain stage! I am"
	.string "\pELESA! World-"
	.string "\nrenowed model and"
	.string "\lPOKéMON master!"
	.string "\pFrom this grand"
	.string "\nstage in the sky,"
	.string "\pevery performance"
	.string "\nof battle from my"
	.string "\pPOKéMON are broad-"
	.string "\ncast across the"
	.string "\lworld!"
	.string "\pNow, my beloved"
	.string "\nPOKéMON and your"
	.string "\pPOKéMON shall"
	.string "\ncompete! We're"
	.string "\pgoing to see whose"
	.string "\nstar shines"
	.string "\lbrightest!$"

Unova_ElesasRoom_Text_EliteFourElesaWinText::
	.string "You've shocked me"
	.string "\nthrough and"
	.string "\pthrough! You've"
	.string "\nmelted my heart!"
	.string "\pYou're an even"
	.string "\nmore wonderful"
	.string "\ptrainer than I"
	.string "\nexpected. Your"
	.string "\psweet fighting"
	.string "\nstyle swept me off"
	.string "\lmy feet!$"
