SandgemTown_PokemonCenter_2F_MapScripts::
	.byte 0

SandgemTown_PokemonCenter_2F_EventScript_Teala1::
	msgbox SandgemTown_PokemonCenter_2F_Text_Teala1, MSGBOX_NPC
	end

SandgemTown_PokemonCenter_2F_EventScript_Teala2::
	msgbox SandgemTown_PokemonCenter_2F_Text_Teala2, MSGBOX_NPC
	end

SandgemTown_PokemonCenter_2F_EventScript_Lass::
	msgbox SandgemTown_PokemonCenter_2F_Text_Lass, MSGBOX_NPC
	end

SandgemTown_PokemonCenter_2F_Text_Teala1:
	.string "This terminal connects TRAINERS\n"
	.string "all over SINNOH.$"

SandgemTown_PokemonCenter_2F_Text_Teala2:
	.string "Feel free to use the terminal to\n"
	.string "trade with other TRAINERS.$"

SandgemTown_PokemonCenter_2F_Text_Lass:
	.string "I love coming up here to see who's\n"
	.string "online.$"
