@ Dreamyard do BW3G (Azure_Keys). Gerado por dev_scripts/importa_unova.py; nao editar a mao.

Unova_Dreamyard_MapScripts::
	.byte 0

Unova_Dreamyard_EventScript_Npc6::
	msgbox Unova_Dreamyard_Text_YoungsterDreamyardSeenText, MSGBOX_NPC
	end

Unova_Dreamyard_EventScript_Npc7::
	msgbox Unova_Dreamyard_Text_SchoolKidMDreamyardSeenText, MSGBOX_NPC
	end

Unova_Dreamyard_EventScript_Npc8::
	msgbox Unova_Dreamyard_Text_SchoolKidFDreamyardSeenText, MSGBOX_NPC
	end


Unova_Dreamyard_Text_YoungsterDreamyardSeenText::
	.string "Shorts and POKé-"
	.string "\nMON! This is the"
	.string "\pultimate"
	.string "\ncombination!$"

Unova_Dreamyard_Text_SchoolKidMDreamyardSeenText::
	.string "My POKéMON's"
	.string "\nstrong points!"
	.string "\pYou'll see them if"
	.string "\nyou fight!$"

Unova_Dreamyard_Text_SchoolKidFDreamyardSeenText::
	.string "See my extra-"
	.string "\nordinarily pretty"
	.string "\lPOKéMON!$"
