ForeignBuilding_MapScripts::
	.byte 0

@ Fala de NPC e de placa vinda do pokeplatinum (dev_scripts/texto_sinnoh.py)

ForeignBuilding_EventScript_Npc1::
	msgbox ForeignBuilding_Text_Npc1, MSGBOX_NPC
	end

ForeignBuilding_Text_Npc1:
	.string "And there do I see my father.\nMy son. My life.\pAnd there do I see nature.\nPokémon. The world.$"

ForeignBuilding_EventScript_Npc2::
	msgbox ForeignBuilding_Text_Npc2, MSGBOX_NPC
	end

ForeignBuilding_Text_Npc2:
	.string "The art of crafting things fatigues\none's spirit.\pWhen the spirit is healed, the desire\nto make something returns.\pIt is such a wondrous cycle.$"

ForeignBuilding_EventScript_Npc3::
	msgbox ForeignBuilding_Text_Npc3, MSGBOX_NPC
	end

ForeignBuilding_Text_Npc3:
	.string "When people and Pokémon join hands,\neveryone's happy.\pIt makes everyone come together.\nIt could even make the world one!$"

ForeignBuilding_EventScript_Npc4::
	msgbox ForeignBuilding_Text_Npc4, MSGBOX_NPC
	end

ForeignBuilding_Text_Npc4:
	.string "That people are lonely is only natural.\nIt gives me compassion for others.\pIt's what makes me look forward to\na better tomorrow.\pBut there are still moments of\nfondness for the past.\pThough, time can heal some sadness...$"

ForeignBuilding_EventScript_Npc5::
	msgbox ForeignBuilding_Text_Npc5, MSGBOX_NPC
	end

ForeignBuilding_Text_Npc5:
	.string "There are still words that not everyone\ncan describe...\pThe words are 'love' and 'joy.'$"

ForeignBuilding_EventScript_Npc6::
	msgbox ForeignBuilding_Text_Npc6, MSGBOX_NPC
	end

ForeignBuilding_Text_Npc6:
	.string "Pokémon... People... It's only natural\nthat we are all so very different.\pMake sure that you never judge\na Pokémon on if it's weak or strong.\pYou must always look for the good\ninside of them. That's what counts!$"

ForeignBuilding_EventScript_Npc7::
	msgbox ForeignBuilding_Text_Npc7, MSGBOX_NPC
	end

ForeignBuilding_Text_Npc7:
	.string "Mind and matter.\pIt's no good if one is stronger than\nthe other.\pBalance is what's needed.\nThat's the key.$"

ForeignBuilding_EventScript_Npc8::
	msgbox ForeignBuilding_Text_Npc8, MSGBOX_NPC
	end

ForeignBuilding_Text_Npc8:
	.string "We cannot read the minds of others,\nwhich causes us to feel fear and doubt.\pBut to control the aspects of the world\nbeyond our senses is an impossibility.$"

ForeignBuilding_EventScript_Npc9::
	msgbox ForeignBuilding_Text_Npc9, MSGBOX_NPC
	end

ForeignBuilding_Text_Npc9:
	.string "If the strong and able do too much,\nthey limit the contributions of others.\pThe strong must show restraint.\pThis enables everyone to live together\nand share responsibility.$"
